Proyecto Autos Seguros: BLL.UsuarioBLL Class Reference
BLL.UsuarioBLL Class Reference
Public Member Functions
void Eliminar (string id)
List< Usuario > GetUsuarioByFiltro (string filtro)
Usuario GetUsuarioById (string id)
void Guardar (Usuario user)
string ObtenerUsuarioIdByIdFac (int idFactura)
List< Usuario > ObtenerUsuarios ()
bool VerificarAcceso (string correo, string clave)
void Guardar (Usuario user)
void Eliminar (string id)
List< Usuario > ObtenerUsuarios ()
bool VerificarAcceso (string correo, string clave)
Usuario GetUsuarioById (string id)
List< Usuario > GetUsuarioByFiltro (string filtro)
string ObtenerUsuarioIdByIdFac (int idFactura)
Detailed Description
Definition at line 12 of file UsuarioBLL.cs.
Member Function Documentation
Eliminar()
void BLL.UsuarioBLL.Eliminar (string id)
Implements Interfaces.IUsuarioBLL.
Definition at line 14 of file UsuarioBLL.cs.
        {
            IUsuarioDAL datos = new UsuarioDAL ();
            if (datos.SeleccionarPorId(id) == null)
                throw new ApplicationException("El código no existe");
            datos.Eliminar(id);
        }
References Interfaces.IUsuarioDAL.Eliminar(), and Interfaces.IUsuarioDAL.SeleccionarPorId().
GetUsuarioByFiltro()
List< Usuario > BLL.UsuarioBLL.GetUsuarioByFiltro (string filtro)
Implements Interfaces.IUsuarioBLL.
Definition at line 23 of file UsuarioBLL.cs.
        {
            IUsuarioDAL datos = new UsuarioDAL();
            return datos.GetUsuarioByFiltro (filtro);
        }
References Interfaces.IUsuarioDAL.GetUsuarioByFiltro().
GetUsuarioById()
Usuario BLL.UsuarioBLL.GetUsuarioById (string id)
Implements Interfaces.IUsuarioBLL.
Definition at line 29 of file UsuarioBLL.cs.
        {
            IUsuarioDAL datos = new UsuarioDAL();
            return datos.SeleccionarPorId(id);
        }
References Interfaces.IUsuarioDAL.SeleccionarPorId().
Guardar()
void BLL.UsuarioBLL.Guardar (Usuario user)
Implements Interfaces.IUsuarioBLL.
Definition at line 35 of file UsuarioBLL.cs.
        {
            IUsuarioDAL datos = new UsuarioDAL();
            if (datos.SeleccionarPorId(user.Id) == null)
            {
                if (CacheUsuario.IdTipoUsuario == 4)
                {
                    throw new ApplicationException("Un usuario con rol de procesos no puede crear usuarios");
                }
                datos.Insertar(user);
            }
            else
            {
                datos.Actualizar(user);
            }
        }
References Interfaces.IUsuarioDAL.Actualizar(), Entities.Usuario.Id, Entities.CacheUsuario.IdTipoUsuario, Interfaces.IUsuarioDAL.Insertar(), and Interfaces.IUsuarioDAL.SeleccionarPorId().
ObtenerUsuarioIdByIdFac()
string BLL.UsuarioBLL.ObtenerUsuarioIdByIdFac (int idFactura)
Implements Interfaces.IUsuarioBLL.
Definition at line 53 of file UsuarioBLL.cs.
        {
            IUsuarioDAL datos = new UsuarioDAL();
            return datos.ObtenerUsuarioIdByIdFac(idFactura);
        }
References Interfaces.IUsuarioDAL.ObtenerUsuarioIdByIdFac().
ObtenerUsuarios()
List< Usuario > BLL.UsuarioBLL.ObtenerUsuarios ()
Implements Interfaces.IUsuarioBLL.
Definition at line 59 of file UsuarioBLL.cs.
        {
            IUsuarioDAL datos = new UsuarioDAL();
            return datos.SeleccionarTodas();
        }
References Interfaces.IUsuarioDAL.SeleccionarTodas().
VerificarAcceso()
bool BLL.UsuarioBLL.VerificarAcceso (string correo, string clave)
Implements Interfaces.IUsuarioBLL.
Definition at line 65 of file UsuarioBLL.cs.
        {
            IUsuarioDAL datos = new UsuarioDAL();
            return datos.VerificarLogin(correo, clave);
        }
References Interfaces.IUsuarioDAL.VerificarLogin().
The documentation for this class was generated from the following file:
BLL/UsuarioBLL.cs