Proyecto Autos Seguros: Capa.UI.Reporte.frmRptFactura Class Reference
Capa.UI.Reporte.frmRptFactura Class Reference
Public Member Functions
frmRptFactura (int idFactura)
Task< string > EnviarFacturaAsync ()
Método que ejecuta la lógica asincrónicamente para enviar el correo electrónico al destinatario. Al ser un método async tiene que devolver una Tarea(task) y no puede ser void
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void frmRptFactura_Load (object sender, EventArgs e)
Carga el reporte por medio del tableadapter
async void EnviarEmail_Click (object sender, EventArgs e)
Este método es el que invoca al método que yo quiero que sea asíncrono por lo tanto tiene que llevar la palabra reservada async para que pueda entender la máquina que lo tiene que ejecutar en "segundo plano". Cuando invoca el método, le tiene que poner la palabra await que significa "en espera". Quiere decir que va a ejecutar ese método paralelamente a los otros procesos por lo que es más agradable con el usuario ya que no se queda esperando a que termine de enviar el correo Si no fuese asíncrono, podríamos ver como se queda como "congelado" hasta que termine el proceso
void toolStripBtnSalir_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
int _IdFactura
System.ComponentModel.IContainer components = null
Required designer variable.
Microsoft.Reporting.WinForms.ReportViewer rptVisor
System.Windows.Forms.BindingSource uspObtenerFacturaReporteBindingSource
DataSetReportes dataSetReportes
DataSetReportesTableAdapters.usp_ObtenerFacturaReporteTableAdapter usp_ObtenerFacturaReporteTableAdapter
System.Windows.Forms.ToolStrip tspBarraSuperior
System.Windows.Forms.ToolStripButton EnviarEmail
System.Windows.Forms.ToolStripButton toolStripBtnSalir
Static Private Attributes
static readonly ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 21 of file frmRptFactura.cs.
Constructor & Destructor Documentation
frmRptFactura()
Capa.UI.Reporte.frmRptFactura.frmRptFactura (int idFactura)
Definition at line 25 of file frmRptFactura.cs.
        {
            _IdFactura = idFactura;
            InitializeComponent();
        }
References Capa.UI.Reporte.frmRptFactura._IdFactura, and Capa.UI.Reporte.frmRptFactura.InitializeComponent().
Member Function Documentation
Dispose()
override void Capa.UI.Reporte.frmRptFactura.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file frmRptFactura.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References Capa.UI.Reporte.frmRptFactura.components.
EnviarEmail_Click()
async void Capa.UI.Reporte.frmRptFactura.EnviarEmail_Click (object sender, EventArgs e) private
Este método es el que invoca al método que yo quiero que sea asíncrono por lo tanto tiene que llevar la palabra reservada async para que pueda entender la máquina que lo tiene que ejecutar en "segundo plano". Cuando invoca el método, le tiene que poner la palabra await que significa "en espera". Quiere decir que va a ejecutar ese método paralelamente a los otros procesos por lo que es más agradable con el usuario ya que no se queda esperando a que termine de enviar el correo Si no fuese asíncrono, podríamos ver como se queda como "congelado" hasta que termine el proceso
Parameters
sender
e
Definition at line 89 of file frmRptFactura.cs.
        {
            string ruta = @"c:\temp\reporteFactura.pdf";
            var deviceInfo = @"<DeviceInfo>
            <EmbedFonts>None</EmbedFonts>
           </DeviceInfo>";
            try
            {
                if (!Directory.Exists(@"c:\temp"))
                    Directory.CreateDirectory(@"c:\temp");
                byte[] Bytes = this.rptVisor.LocalReport.Render(format: "PDF", deviceInfo: deviceInfo);
                using (FileStream stream = new FileStream(ruta, FileMode.Create))
                {
                    stream.Write(Bytes, 0, Bytes.Length);
                }
                MessageBox.Show(await EnviarFacturaAsync());
            }
            catch (Exception ex)
            {
                MessageBox.Show("Se ha producido el siguiente error: \n" + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Reporte.frmRptFactura._MyLogControlEventos, Capa.UI.Reporte.frmRptFactura.EnviarFacturaAsync(), and Capa.UI.Reporte.frmRptFactura.rptVisor.
Referenced by Capa.UI.Reporte.frmRptFactura.InitializeComponent().
EnviarFacturaAsync()
Task< string > Capa.UI.Reporte.frmRptFactura.EnviarFacturaAsync ()
Método que ejecuta la lógica asincrónicamente para enviar el correo electrónico al destinatario. Al ser un método async tiene que devolver una Tarea(task) y no puede ser void
Returns
Definition at line 54 of file frmRptFactura.cs.
        {
            return Task.Run(() =>
            {
                Usuario user = null;
                IUsuarioBLL logica = new UsuarioBLL();
                user = logica.GetUsuarioById(logica.ObtenerUsuarioIdByIdFac(_IdFactura));
                MailMessage mensaje = new MailMessage();
                mensaje.IsBodyHtml = true;
                mensaje.Subject = "Seguros Pita";
                mensaje.Body = "¡Hola! Esperamos que se encuentre bien. Le adjuntamos su factura de compra";
                mensaje.From = new MailAddress("pipiticaseguros@hotmail.com");
                mensaje.To.Add(user.Correo);
                SmtpClient smtp = new SmtpClient("smtp.office365.com");
                smtp.Port = 587;
                smtp.Credentials = new NetworkCredential("pipiticaseguros@hotmail.com", "pipitica1234");
                smtp.EnableSsl = true;
                Attachment attachment = new Attachment(@"c:\temp\reporteFactura.pdf");
                mensaje.Attachments.Add(attachment);
                smtp.Send(mensaje);
                return "Factura enviada correctamente";
            });
        }
References Capa.UI.Reporte.frmRptFactura._IdFactura, Entities.Usuario.Correo, Interfaces.IUsuarioBLL.GetUsuarioById(), and Interfaces.IUsuarioBLL.ObtenerUsuarioIdByIdFac().
Referenced by Capa.UI.Reporte.frmRptFactura.EnviarEmail_Click().
frmRptFactura_Load()
void Capa.UI.Reporte.frmRptFactura.frmRptFactura_Load (object sender, EventArgs e) private
Carga el reporte por medio del tableadapter
Parameters
sender
e
Definition at line 36 of file frmRptFactura.cs.
        {
            // TODO: This line of code loads data into the 'DsReportes.Factura' table. You can move, or remove it, as needed.
            this.usp_ObtenerFacturaReporteTableAdapter.Fill(this.dataSetReportes.usp_ObtenerFacturaReporte, _IdFactura);
            string ruta = @"file:///" + @"C:/TEMP/qr.png";
            // Habilitar imagenes externas
            this.rptVisor.LocalReport.EnableExternalImages = true;
            ReportParameter param = new ReportParameter("quickresponse", ruta);
            this.rptVisor.LocalReport.SetParameters(param);
            this.rptVisor.RefreshReport();
        }
References Capa.UI.Reporte.frmRptFactura.dataSetReportes, Capa.UI.Reporte.frmRptFactura.rptVisor, Capa.UI.Reporte.DataSetReportes.usp_ObtenerFacturaReporte, and Capa.UI.Reporte.frmRptFactura.usp_ObtenerFacturaReporteTableAdapter.
Referenced by Capa.UI.Reporte.frmRptFactura.InitializeComponent().
InitializeComponent()
void Capa.UI.Reporte.frmRptFactura.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file frmRptFactura.Designer.cs.
        {
            this.components = new System.ComponentModel.Container();
            Microsoft.Reporting.WinForms.ReportDataSource reportDataSource1 = new Microsoft.Reporting.WinForms.ReportDataSource();
            this.uspObtenerFacturaReporteBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.dataSetReportes = new Capa.UI.Reporte.DataSetReportes();
            this.rptVisor = new Microsoft.Reporting.WinForms.ReportViewer();
            this.usp_ObtenerFacturaReporteTableAdapter = new Capa.UI.Reporte.DataSetReportesTableAdapters.usp_ObtenerFacturaReporteTableAdapter();
            this.tspBarraSuperior = new System.Windows.Forms.ToolStrip();
            this.EnviarEmail = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnSalir = new System.Windows.Forms.ToolStripButton();
            ((System.ComponentModel.ISupportInitialize)(this.uspObtenerFacturaReporteBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataSetReportes)).BeginInit();
            this.tspBarraSuperior.SuspendLayout();
            this.SuspendLayout();
            //
            // uspObtenerFacturaReporteBindingSource
            //
            this.uspObtenerFacturaReporteBindingSource.DataMember = "usp_ObtenerFacturaReporte";
            this.uspObtenerFacturaReporteBindingSource.DataSource = this.dataSetReportes;
            //
            // dataSetReportes
            //
            this.dataSetReportes.DataSetName = "DataSetReportes";
            this.dataSetReportes.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            //
            // rptVisor
            //
            reportDataSource1.Name = "dsFactura";
            reportDataSource1.Value = this.uspObtenerFacturaReporteBindingSource;
            this.rptVisor.LocalReport.DataSources.Add(reportDataSource1);
            this.rptVisor.LocalReport.ReportEmbeddedResource = "Capa.UI.Reporte.rptFactura.rdlc";
            this.rptVisor.Location = new System.Drawing.Point(0, 28);
            this.rptVisor.Name = "rptVisor";
            this.rptVisor.ServerReport.BearerToken = null;
            this.rptVisor.Size = new System.Drawing.Size(792, 515);
            this.rptVisor.TabIndex = 0;
            this.rptVisor.ZoomMode = Microsoft.Reporting.WinForms.ZoomMode.PageWidth;
            //
            // usp_ObtenerFacturaReporteTableAdapter
            //
            this.usp_ObtenerFacturaReporteTableAdapter.ClearBeforeFill = true;
            //
            // tspBarraSuperior
            //
            this.tspBarraSuperior.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.tspBarraSuperior.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.EnviarEmail,
            this.toolStripBtnSalir});
            this.tspBarraSuperior.Location = new System.Drawing.Point(0, 0);
            this.tspBarraSuperior.Name = "tspBarraSuperior";
            this.tspBarraSuperior.Size = new System.Drawing.Size(792, 25);
            this.tspBarraSuperior.TabIndex = 7;
            this.tspBarraSuperior.Text = "toolStrip1";
            //
            // EnviarEmail
            //
            this.EnviarEmail.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.EnviarEmail.ForeColor = System.Drawing.Color.White;
            this.EnviarEmail.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.EnviarEmail.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.EnviarEmail.Name = "EnviarEmail";
            this.EnviarEmail.Size = new System.Drawing.Size(88, 22);
            this.EnviarEmail.Text = "Enviar Email";
            this.EnviarEmail.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.EnviarEmail.ToolTipText = "Enviar Email";
            this.EnviarEmail.Click += new System.EventHandler(this.EnviarEmail_Click);
            //
            // toolStripBtnSalir
            //
            this.toolStripBtnSalir.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnSalir.ForeColor = System.Drawing.Color.White;
            this.toolStripBtnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnSalir.Name = "toolStripBtnSalir";
            this.toolStripBtnSalir.Size = new System.Drawing.Size(39, 22);
            this.toolStripBtnSalir.Text = "Salir";
            this.toolStripBtnSalir.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnSalir.Click += new System.EventHandler(this.toolStripBtnSalir_Click);
            //
            // frmRptFactura
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(792, 541);
            this.Controls.Add(this.tspBarraSuperior);
            this.Controls.Add(this.rptVisor);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmRptFactura";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmRptFactura";
            this.Load += new System.EventHandler(this.frmRptFactura_Load);
            ((System.ComponentModel.ISupportInitialize)(this.uspObtenerFacturaReporteBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataSetReportes)).EndInit();
            this.tspBarraSuperior.ResumeLayout(false);
            this.tspBarraSuperior.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References Capa.UI.Reporte.frmRptFactura.components, Capa.UI.Reporte.frmRptFactura.dataSetReportes, Capa.UI.Reporte.frmRptFactura.EnviarEmail, Capa.UI.Reporte.frmRptFactura.EnviarEmail_Click(), Capa.UI.Reporte.frmRptFactura.frmRptFactura_Load(), Capa.UI.Reporte.frmRptFactura.rptVisor, Capa.UI.Reporte.DataSetReportes.SchemaSerializationMode, Capa.UI.Reporte.frmRptFactura.toolStripBtnSalir, Capa.UI.Reporte.frmRptFactura.toolStripBtnSalir_Click(), Capa.UI.Reporte.frmRptFactura.tspBarraSuperior, Capa.UI.Reporte.frmRptFactura.usp_ObtenerFacturaReporteTableAdapter, and Capa.UI.Reporte.frmRptFactura.uspObtenerFacturaReporteBindingSource.
Referenced by Capa.UI.Reporte.frmRptFactura.frmRptFactura().
toolStripBtnSalir_Click()
void Capa.UI.Reporte.frmRptFactura.toolStripBtnSalir_Click (object sender, EventArgs e) private
Definition at line 118 of file frmRptFactura.cs.
        {
            this.Close();
        }
Referenced by Capa.UI.Reporte.frmRptFactura.InitializeComponent().
Member Data Documentation
_IdFactura
int Capa.UI.Reporte.frmRptFactura._IdFactura private
Definition at line 24 of file frmRptFactura.cs.
Referenced by Capa.UI.Reporte.frmRptFactura.EnviarFacturaAsync(), and Capa.UI.Reporte.frmRptFactura.frmRptFactura().
_MyLogControlEventos
readonly ILog Capa.UI.Reporte.frmRptFactura._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 23 of file frmRptFactura.cs.
Referenced by Capa.UI.Reporte.frmRptFactura.EnviarEmail_Click().
components
System.ComponentModel.IContainer Capa.UI.Reporte.frmRptFactura.components = null private
Required designer variable.
Definition at line 8 of file frmRptFactura.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptFactura.Dispose(), and Capa.UI.Reporte.frmRptFactura.InitializeComponent().
dataSetReportes
DataSetReportes Capa.UI.Reporte.frmRptFactura.dataSetReportes private
Definition at line 134 of file frmRptFactura.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptFactura.frmRptFactura_Load(), and Capa.UI.Reporte.frmRptFactura.InitializeComponent().
EnviarEmail
System.Windows.Forms.ToolStripButton Capa.UI.Reporte.frmRptFactura.EnviarEmail private
Definition at line 137 of file frmRptFactura.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptFactura.InitializeComponent().
rptVisor
Microsoft.Reporting.WinForms.ReportViewer Capa.UI.Reporte.frmRptFactura.rptVisor private
Definition at line 132 of file frmRptFactura.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptFactura.EnviarEmail_Click(), Capa.UI.Reporte.frmRptFactura.frmRptFactura_Load(), and Capa.UI.Reporte.frmRptFactura.InitializeComponent().
toolStripBtnSalir
System.Windows.Forms.ToolStripButton Capa.UI.Reporte.frmRptFactura.toolStripBtnSalir private
Definition at line 138 of file frmRptFactura.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptFactura.InitializeComponent().
tspBarraSuperior
System.Windows.Forms.ToolStrip Capa.UI.Reporte.frmRptFactura.tspBarraSuperior private
Definition at line 136 of file frmRptFactura.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptFactura.InitializeComponent().
usp_ObtenerFacturaReporteTableAdapter
DataSetReportesTableAdapters.usp_ObtenerFacturaReporteTableAdapter Capa.UI.Reporte.frmRptFactura.usp_ObtenerFacturaReporteTableAdapter private
Definition at line 135 of file frmRptFactura.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptFactura.frmRptFactura_Load(), and Capa.UI.Reporte.frmRptFactura.InitializeComponent().
uspObtenerFacturaReporteBindingSource
System.Windows.Forms.BindingSource Capa.UI.Reporte.frmRptFactura.uspObtenerFacturaReporteBindingSource private
Definition at line 133 of file frmRptFactura.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptFactura.InitializeComponent().
The documentation for this class was generated from the following files:
Capa.UI/Reporte/frmRptFactura.cs
Capa.UI/Reporte/frmRptFactura.Designer.cs