Proyecto Autos Seguros: Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager Class Reference
Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager Class Reference
TableAdapterManager is used to coordinate TableAdapters in the dataset to enable Hierarchical Update scenarios /summary>
Classes
class SelfReferenceComparer
Used to sort self-referenced table's rows /summary>
Public Types
enum UpdateOrderOption { InsertUpdateDelete = 0 , UpdateInsertDelete = 1 }
Update Order Option /summary>
Public Member Functions
virtual int UpdateAll (DataSetReportes dataSet)
Update all changes to the dataset. /summary>
Protected Member Functions
virtual void SortSelfReferenceRows (global::System.Data.DataRow[] rows, global::System.Data.DataRelation relation, bool childFirst)
virtual bool MatchTableAdapterConnection (global::System.Data.IDbConnection inputConnection)
Properties
UpdateOrderOption UpdateOrder [get, set]
bool BackupDataSetBeforeUpdate [get, set]
global::System.Data.IDbConnection Connection [get, set]
int TableAdapterInstanceCount [get]
Private Member Functions
int UpdateUpdatedRows (DataSetReportes dataSet, global::System.Collections.Generic.List< global::System.Data.DataRow > allChangedRows, global::System.Collections.Generic.List< global::System.Data.DataRow > allAddedRows)
Update rows in top-down order. /summary>
int UpdateInsertedRows (DataSetReportes dataSet, global::System.Collections.Generic.List< global::System.Data.DataRow > allAddedRows)
Insert rows in top-down order. /summary>
int UpdateDeletedRows (DataSetReportes dataSet, global::System.Collections.Generic.List< global::System.Data.DataRow > allChangedRows)
Delete rows in bottom-up order. /summary>
global::System.Data.DataRow[] GetRealUpdatedRows (global::System.Data.DataRow[] updatedRows, global::System.Collections.Generic.List< global::System.Data.DataRow > allAddedRows)
Remove inserted rows that become updated rows after calling TableAdapter.Update(inserted rows) first /summary>
Private Attributes
UpdateOrderOption _updateOrder
bool _backupDataSetBeforeUpdate
global::System.Data.IDbConnection _connection
Detailed Description
TableAdapterManager is used to coordinate TableAdapters in the dataset to enable Hierarchical Update scenarios /summary>
Definition at line 3708 of file DataSetReportes.Designer.cs.
Member Enumeration Documentation
UpdateOrderOption
enum Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.UpdateOrderOption
Update Order Option /summary>
Enumerator
InsertUpdateDelete
UpdateInsertDelete
Definition at line 3957 of file DataSetReportes.Designer.cs.
{
            InsertUpdateDelete = 0,
            UpdateInsertDelete = 1,
        }
Member Function Documentation
GetRealUpdatedRows()
global.System.Data.DataRow[] Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.GetRealUpdatedRows (global::System.Data.DataRow[] updatedRows, global::System.Collections.Generic.List< global::System.Data.DataRow > allAddedRows) private
Remove inserted rows that become updated rows after calling TableAdapter.Update(inserted rows) first /summary>
Definition at line 3798 of file DataSetReportes.Designer.cs.
{
            if (((updatedRows == null)
                        || (updatedRows.Length < 1))) {
                return updatedRows;
            }
            if (((allAddedRows == null)
                        || (allAddedRows.Count < 1))) {
                return updatedRows;
            }
            global::System.Collections.Generic.List<global::System.Data.DataRow> realUpdatedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow>();
            for (int i = 0; (i < updatedRows.Length); i = (i + 1)) {
                global::System.Data.DataRow row = updatedRows[i];
                if ((allAddedRows.Contains(row) == false)) {
                    realUpdatedRows.Add(row);
                }
            }
            return realUpdatedRows.ToArray();
        }
MatchTableAdapterConnection()
virtual bool Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.MatchTableAdapterConnection (global::System.Data.IDbConnection inputConnection) protected virtual
Definition at line 3939 of file DataSetReportes.Designer.cs.
{
            if ((this._connection != null)) {
                return true;
            }
            if (((this.Connection == null)
                        || (inputConnection == null))) {
                return true;
            }
            if (string.Equals(this.Connection.ConnectionString, inputConnection.ConnectionString, global::System.StringComparison.Ordinal)) {
                return true;
            }
            return false;
        }
References Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager._connection, and Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.Connection.
SortSelfReferenceRows()
virtual void Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.SortSelfReferenceRows (global::System.Data.DataRow[] rows, global::System.Data.DataRelation relation, bool childFirst) protected virtual
Definition at line 3933 of file DataSetReportes.Designer.cs.
{
            global::System.Array.Sort<global::System.Data.DataRow>(rows, new SelfReferenceComparer(relation, childFirst));
        }
UpdateAll()
virtual int Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.UpdateAll (DataSetReportes dataSet) virtual
Update all changes to the dataset. /summary>
Definition at line 3822 of file DataSetReportes.Designer.cs.
{
            if ((dataSet == null)) {
                throw new global::System.ArgumentNullException("dataSet");
            }
            if ((dataSet.HasChanges() == false)) {
                return 0;
            }
            global::System.Data.IDbConnection workConnection = this.Connection;
            if ((workConnection == null)) {
                throw new global::System.ApplicationException("TableAdapterManager contains no connection information. Set each TableAdapterMana" +
                        "ger TableAdapter property to a valid TableAdapter instance.");
            }
            bool workConnOpened = false;
            if (((workConnection.State & global::System.Data.ConnectionState.Broken)
                        == global::System.Data.ConnectionState.Broken)) {
                workConnection.Close();
            }
            if ((workConnection.State == global::System.Data.ConnectionState.Closed)) {
                workConnection.Open();
                workConnOpened = true;
            }
            global::System.Data.IDbTransaction workTransaction = workConnection.BeginTransaction();
            if ((workTransaction == null)) {
                throw new global::System.ApplicationException("The transaction cannot begin. The current data connection does not support transa" +
                        "ctions or the current state is not allowing the transaction to begin.");
            }
            global::System.Collections.Generic.List<global::System.Data.DataRow> allChangedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow>();
            global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow>();
            global::System.Collections.Generic.List<global::System.Data.Common.DataAdapter> adaptersWithAcceptChangesDuringUpdate = new global::System.Collections.Generic.List<global::System.Data.Common.DataAdapter>();
            global::System.Collections.Generic.Dictionary<object, global::System.Data.IDbConnection> revertConnections = new global::System.Collections.Generic.Dictionary<object, global::System.Data.IDbConnection>();
            int result = 0;
            global::System.Data.DataSet backupDataSet = null;
            if (this.BackupDataSetBeforeUpdate) {
                backupDataSet = new global::System.Data.DataSet();
                backupDataSet.Merge(dataSet);
            }
            try {
                // ---- Prepare for update -----------
                //
                //
                //---- Perform updates -----------
                //
                if ((this.UpdateOrder == UpdateOrderOption.UpdateInsertDelete)) {
                    result = (result + this.UpdateUpdatedRows(dataSet, allChangedRows, allAddedRows));
                    result = (result + this.UpdateInsertedRows(dataSet, allAddedRows));
                }
                else {
                    result = (result + this.UpdateInsertedRows(dataSet, allAddedRows));
                    result = (result + this.UpdateUpdatedRows(dataSet, allChangedRows, allAddedRows));
                }
                result = (result + this.UpdateDeletedRows(dataSet, allChangedRows));
                //
                //---- Commit updates -----------
                //
                workTransaction.Commit();
                if ((0 < allAddedRows.Count)) {
                    global::System.Data.DataRow[] rows = new System.Data.DataRow[allAddedRows.Count];
                    allAddedRows.CopyTo(rows);
                    for (int i = 0; (i < rows.Length); i = (i + 1)) {
                        global::System.Data.DataRow row = rows[i];
                        row.AcceptChanges();
                    }
                }
                if ((0 < allChangedRows.Count)) {
                    global::System.Data.DataRow[] rows = new System.Data.DataRow[allChangedRows.Count];
                    allChangedRows.CopyTo(rows);
                    for (int i = 0; (i < rows.Length); i = (i + 1)) {
                        global::System.Data.DataRow row = rows[i];
                        row.AcceptChanges();
                    }
                }
            }
            catch (global::System.Exception ex) {
                workTransaction.Rollback();
                // ---- Restore the dataset -----------
                if (this.BackupDataSetBeforeUpdate) {
                    global::System.Diagnostics.Debug.Assert((backupDataSet != null));
                    dataSet.Clear();
                    dataSet.Merge(backupDataSet);
                }
                else {
                    if ((0 < allAddedRows.Count)) {
                        global::System.Data.DataRow[] rows = new System.Data.DataRow[allAddedRows.Count];
                        allAddedRows.CopyTo(rows);
                        for (int i = 0; (i < rows.Length); i = (i + 1)) {
                            global::System.Data.DataRow row = rows[i];
                            row.AcceptChanges();
                            row.SetAdded();
                        }
                    }
                }
                throw ex;
            }
            finally {
                if (workConnOpened) {
                    workConnection.Close();
                }
                if ((0 < adaptersWithAcceptChangesDuringUpdate.Count)) {
                    global::System.Data.Common.DataAdapter[] adapters = new System.Data.Common.DataAdapter[adaptersWithAcceptChangesDuringUpdate.Count];
                    adaptersWithAcceptChangesDuringUpdate.CopyTo(adapters);
                    for (int i = 0; (i < adapters.Length); i = (i + 1)) {
                        global::System.Data.Common.DataAdapter adapter = adapters[i];
                        adapter.AcceptChangesDuringUpdate = true;
                    }
                }
            }
            return result;
        }
References Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.BackupDataSetBeforeUpdate, Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.Connection, Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.UpdateDeletedRows(), Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.UpdateInsertedRows(), Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.UpdateOrder, and Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.UpdateUpdatedRows().
UpdateDeletedRows()
int Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.UpdateDeletedRows (DataSetReportes dataSet, global::System.Collections.Generic.List< global::System.Data.DataRow > allChangedRows) private
Delete rows in bottom-up order. /summary>
Definition at line 3788 of file DataSetReportes.Designer.cs.
{
            int result = 0;
            return result;
        }
Referenced by Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.UpdateAll().
UpdateInsertedRows()
int Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.UpdateInsertedRows (DataSetReportes dataSet, global::System.Collections.Generic.List< global::System.Data.DataRow > allAddedRows) private
Insert rows in top-down order. /summary>
Definition at line 3778 of file DataSetReportes.Designer.cs.
{
            int result = 0;
            return result;
        }
Referenced by Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.UpdateAll().
UpdateUpdatedRows()
int Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.UpdateUpdatedRows (DataSetReportes dataSet, global::System.Collections.Generic.List< global::System.Data.DataRow > allChangedRows, global::System.Collections.Generic.List< global::System.Data.DataRow > allAddedRows) private
Update rows in top-down order. /summary>
Definition at line 3768 of file DataSetReportes.Designer.cs.
{
            int result = 0;
            return result;
        }
Referenced by Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.UpdateAll().
Member Data Documentation
_backupDataSetBeforeUpdate
bool Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager._backupDataSetBeforeUpdate private
Definition at line 3712 of file DataSetReportes.Designer.cs.
_connection
global.System.Data.IDbConnection Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager._connection private
Definition at line 3714 of file DataSetReportes.Designer.cs.
Referenced by Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.MatchTableAdapterConnection().
_updateOrder
UpdateOrderOption Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager._updateOrder private
Definition at line 3710 of file DataSetReportes.Designer.cs.
Property Documentation
BackupDataSetBeforeUpdate
bool Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.BackupDataSetBeforeUpdate get set
Definition at line 3729 of file DataSetReportes.Designer.cs.
{
            get {
                return this._backupDataSetBeforeUpdate;
            }
            set {
                this._backupDataSetBeforeUpdate = value;
            }
        }
Referenced by Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.UpdateAll().
Connection
global.System.Data.IDbConnection Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.Connection get set
Definition at line 3741 of file DataSetReportes.Designer.cs.
{
            get {
                if ((this._connection != null)) {
                    return this._connection;
                }
                return null;
            }
            set {
                this._connection = value;
            }
        }
Referenced by Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.MatchTableAdapterConnection(), and Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.UpdateAll().
TableAdapterInstanceCount
int Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.TableAdapterInstanceCount get
Definition at line 3756 of file DataSetReportes.Designer.cs.
{
            get {
                int count = 0;
                return count;
            }
        }
UpdateOrder
UpdateOrderOption Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.UpdateOrder get set
Definition at line 3718 of file DataSetReportes.Designer.cs.
{
            get {
                return this._updateOrder;
            }
            set {
                this._updateOrder = value;
            }
        }
Referenced by Capa.UI.Reporte.DataSetReportesTableAdapters.TableAdapterManager.UpdateAll().
The documentation for this class was generated from the following file:
Capa.UI/Reporte/DataSetReportes.Designer.cs