Proyecto Autos Seguros: DataBase Class Reference
DataBase Class Reference
Public Member Functions
IDataReader ExecuteReader (IDbCommand pCommand)
DataSet ExecuteDataSet (IDbCommand pCommand)
DataSet ExecuteDataSet (IDbCommand pCommand, String pTabla)
double ExecuteNonQuery (IDbCommand pCommand, IsolationLevel pIsolationLevel)
int ExecuteNonQuery (IDbCommand pCommand)
object ExecuteScalar (IDbCommand pCommand)
void ExecuteNonQuery (ref IDbCommand pCommand, IsolationLevel pIsolationLevel)
void ExecuteNonQuery (List< IDbCommand > pCommands, IsolationLevel pIsolationLevel)
void Dispose ()
Public Member Functions inherited from IDataBase
double ExecuteNonQuery (IDbCommand pCommand, IsolationLevel pIsolationLevel)
void ExecuteNonQuery (ref IDbCommand pCommand, IsolationLevel pIsolationLevel)
void ExecuteNonQuery (List< IDbCommand > pCommands, IsolationLevel pIsolationLevel)
int ExecuteNonQuery (IDbCommand pCommand)
IDataReader ExecuteReader (IDbCommand pSqlCommand)
DataSet ExecuteDataSet (IDbCommand pSqlCommand, string pTabla)
DataSet ExecuteDataSet (IDbCommand pCommand)
object ExecuteScalar (IDbCommand pSQLCommand)
Properties
IDbConnection _Conexion = new SqlConnection() [get, set]
IDbConnection Conexion [get, set]
Properties inherited from IDataBase
IDbConnection _Conexion [get, set]
Detailed Description
Definition at line 7 of file DataBase.cs.
Member Function Documentation
Dispose()
void DataBase.Dispose ()
Definition at line 222 of file DataBase.cs.
    {
        if (_Conexion != null)
            _Conexion.Close();
    }
References _Conexion.
ExecuteDataSet() [1/2]
DataSet DataBase.ExecuteDataSet (IDbCommand pCommand)
Implements IDataBase.
Definition at line 36 of file DataBase.cs.
    {
        DataSet dsTabla = new DataSet();
        try
        {
            using (SqlDataAdapter adaptador = new SqlDataAdapter(pCommand as SqlCommand))
            {
                pCommand.Connection = _Conexion;
                dsTabla = new DataSet();
                adaptador.Fill(dsTabla);
            }
            return dsTabla;
        }
        catch (Exception)
        {
            // lanzar excepción
            throw;
        }
        finally
        {
            if (dsTabla != null)
                dsTabla.Dispose();
        }
    }
References _Conexion.
ExecuteDataSet() [2/2]
DataSet DataBase.ExecuteDataSet (IDbCommand pCommand, String pTabla)
Definition at line 65 of file DataBase.cs.
    {
        DataSet dsTabla = new DataSet();
        try
        {
            using (SqlDataAdapter adaptador = new SqlDataAdapter(pCommand as SqlCommand))
            {
                pCommand.Connection = _Conexion;
                dsTabla = new DataSet();
                adaptador.Fill(dsTabla, pTabla);
            }
            return dsTabla;
        }
        catch (Exception)
        {
            // lanzar excepción
            throw;
        }
        finally
        {
            if (dsTabla != null)
                dsTabla.Dispose();
        }
    }
References _Conexion.
ExecuteNonQuery() [1/4]
int DataBase.ExecuteNonQuery (IDbCommand pCommand)
Implements IDataBase.
Definition at line 122 of file DataBase.cs.
    {
        int registrosafectados = 0;
        try
        {
            pCommand.Connection = _Conexion;
            registrosafectados = pCommand.ExecuteNonQuery();
            return registrosafectados;
        }
        catch (Exception)
        {
            throw;
        }
    }
References _Conexion.
ExecuteNonQuery() [2/4]
double DataBase.ExecuteNonQuery (IDbCommand pCommand, IsolationLevel pIsolationLevel)
Implements IDataBase.
Definition at line 94 of file DataBase.cs.
    {
        using (IDbTransaction transaccion =  _Conexion.BeginTransaction(pIsolationLevel))
        {
            double registrosafectados = 0;
            try
            {
                pCommand.Connection = _Conexion;
                pCommand.Transaction = transaccion;
                registrosafectados = pCommand.ExecuteNonQuery();
                // Commit a la transacción
                transaccion.Commit();
                return registrosafectados;
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
References _Conexion.
ExecuteNonQuery() [3/4]
void DataBase.ExecuteNonQuery (List< IDbCommand > pCommands, IsolationLevel pIsolationLevel)
Implements IDataBase.
Definition at line 193 of file DataBase.cs.
    {
        try
        {
            using (IDbTransaction transaccion = _Conexion.BeginTransaction(pIsolationLevel))
            {
                foreach (IDbCommand command in pCommands)
                {
                    command.Connection = (_Conexion as SqlConnection);
                    command.Transaction = transaccion;
                    // command.CommandTimeout = int.Parse(System.Configuration.ConfigurationManager.AppSettings["ConnectionTimeOut"].ToString());
                    command.ExecuteNonQuery();
                }
                // Commit a la transacción
                transaccion.Commit();
            }
        }
        catch (Exception)
        {
            throw;
        }
        finally
        {
        }
    }
References _Conexion.
ExecuteNonQuery() [4/4]
void DataBase.ExecuteNonQuery (ref IDbCommand pCommand, IsolationLevel pIsolationLevel)
Implements IDataBase.
Definition at line 164 of file DataBase.cs.
    {
        using (IDbTransaction transaccion = _Conexion.BeginTransaction(pIsolationLevel))
        {
            try
            {
                pCommand.Connection = _Conexion;
                pCommand.Transaction = transaccion;
                pCommand.ExecuteNonQuery();
                // Commit a la transacción
                transaccion.Commit();
            }
            catch (Exception error)
            {
                throw error;
            }
        }
    }
References _Conexion.
ExecuteReader()
IDataReader DataBase.ExecuteReader (IDbCommand pCommand)
Implements IDataBase.
Definition at line 16 of file DataBase.cs.
    {
        IDataReader lector = null;
        try
        {
            pCommand.Connection = _Conexion;
            lector = pCommand.ExecuteReader(CommandBehavior.CloseConnection);
            return lector;
        }
        catch (Exception)
        {
            throw;
        }
    }
References _Conexion.
ExecuteScalar()
object DataBase.ExecuteScalar (IDbCommand pCommand)
Implements IDataBase.
Definition at line 143 of file DataBase.cs.
    {
        object respuesta = null;
        try
        {
            pCommand.Connection = _Conexion;
            respuesta = pCommand.ExecuteScalar();
            return respuesta;
        }
        catch (Exception)
        {
            throw;
        }
    }
References _Conexion.
Property Documentation
_Conexion
IDbConnection DataBase._Conexion = new SqlConnection() get set
Implements IDataBase.
Definition at line 9 of file DataBase.cs.
{ get; set; } = new SqlConnection();
Referenced by Dispose(), ExecuteDataSet(), ExecuteNonQuery(), ExecuteReader(), and ExecuteScalar().
Conexion
IDbConnection DataBase.Conexion get set
Definition at line 10 of file DataBase.cs.
    {
        get;
        set;
    }
The documentation for this class was generated from the following file:
DAL/Persistencia/DataBase.cs