Proyecto Autos Seguros: BLL.DetallePolizaBLL Class Reference
BLL.DetallePolizaBLL Class Reference
Public Member Functions
void Actualizar (DetallePoliza detallePoliza)
void EliminarByIdTipoPoliza (int idTipoPoliza)
void EliminarByPolCob (int idTipoPoliza, int idCobertura)
void Insertar (DetallePoliza detallePoliza)
DetallePoliza SeleccionarPorId (int idTipoPoliza, int idCobertura)
List< DetallePoliza > SeleccionarTodas ()
void Insertar (DetallePoliza detallePoliza)
void Actualizar (DetallePoliza detallePoliza)
void EliminarByIdTipoPoliza (int idTipoPoliza)
void EliminarByPolCob (int idTipoPoliza, int idCobertura)
List< DetallePoliza > SeleccionarTodas ()
DetallePoliza SeleccionarPorId (int idTipoPoliza, int idCobertura)
Detailed Description
Definition at line 12 of file DetallePolizaBLL.cs.
Member Function Documentation
Actualizar()
void BLL.DetallePolizaBLL.Actualizar (DetallePoliza detallePoliza)
Implements Interfaces.IDetallePolizaBLL.
Definition at line 14 of file DetallePolizaBLL.cs.
        {
            IDetallePolizaDAL detallePolizaDAL = new DetallePolizaDAL();
            detallePolizaDAL.Actualizar(detallePoliza);
        }
References Interfaces.IDetallePolizaDAL.Actualizar().
EliminarByIdTipoPoliza()
void BLL.DetallePolizaBLL.EliminarByIdTipoPoliza (int idTipoPoliza)
Implements Interfaces.IDetallePolizaBLL.
Definition at line 20 of file DetallePolizaBLL.cs.
        {
            IDetallePolizaDAL detallePolizaDAL = new DetallePolizaDAL();
            detallePolizaDAL.Eliminar(idTipoPoliza);
        }
References Interfaces.IDetallePolizaDAL.Eliminar().
EliminarByPolCob()
void BLL.DetallePolizaBLL.EliminarByPolCob (int idTipoPoliza, int idCobertura)
Implements Interfaces.IDetallePolizaBLL.
Definition at line 26 of file DetallePolizaBLL.cs.
        {
            IDetallePolizaDAL detallePolizaDAL = new DetallePolizaDAL();
            detallePolizaDAL.EliminarByPolCob(idTipoPoliza, idCobertura);
        }
References Interfaces.IDetallePolizaDAL.EliminarByPolCob().
Insertar()
void BLL.DetallePolizaBLL.Insertar (DetallePoliza detallePoliza)
Implements Interfaces.IDetallePolizaBLL.
Definition at line 32 of file DetallePolizaBLL.cs.
        {
            IDetallePolizaDAL detallePolizaDAL = new DetallePolizaDAL();
            detallePolizaDAL.Insertar(detallePoliza);
        }
References Interfaces.IDetallePolizaDAL.Insertar().
SeleccionarPorId()
DetallePoliza BLL.DetallePolizaBLL.SeleccionarPorId (int idTipoPoliza, int idCobertura)
Implements Interfaces.IDetallePolizaBLL.
Definition at line 38 of file DetallePolizaBLL.cs.
        {
            IDetallePolizaDAL detallePolizaDAL = new DetallePolizaDAL();
            return detallePolizaDAL.SeleccionarPorId(idTipoPoliza, idCobertura);
        }
References Interfaces.IDetallePolizaDAL.SeleccionarPorId().
SeleccionarTodas()
List< DetallePoliza > BLL.DetallePolizaBLL.SeleccionarTodas ()
Implements Interfaces.IDetallePolizaBLL.
Definition at line 44 of file DetallePolizaBLL.cs.
        {
            IDetallePolizaDAL detallePolizaDAL = new DetallePolizaDAL();
            return detallePolizaDAL.SeleccionarTodas();
        }
References Interfaces.IDetallePolizaDAL.SeleccionarTodas().
The documentation for this class was generated from the following file:
BLL/DetallePolizaBLL.cs