Proyecto Autos Seguros: SqlServerTypes.Utilities Class Reference
SqlServerTypes.Utilities Class Reference
Utility methods related to CLR Types for SQL Server
Static Public Member Functions
static void LoadNativeAssemblies (string rootApplicationPath)
Loads the required native assemblies for the current architecture (x86 or x64)
static void LoadNativeAssemblies (string rootApplicationPath)
Loads the required native assemblies for the current architecture (x86 or x64)
Private Member Functions
static IntPtr LoadLibrary (string libname)
static IntPtr LoadLibrary (string libname)
Static Private Member Functions
static void LoadNativeAssembly (string nativeBinaryPath, string assemblyName)
static void LoadNativeAssembly (string nativeBinaryPath, string assemblyName)
Detailed Description
Utility methods related to CLR Types for SQL Server
Definition at line 10 of file Loader.cs.
Member Function Documentation
LoadLibrary() [1/2]
static IntPtr SqlServerTypes.Utilities.LoadLibrary (string libname) private
Referenced by SqlServerTypes.Utilities.LoadNativeAssembly().
LoadLibrary() [2/2]
static IntPtr SqlServerTypes.Utilities.LoadLibrary (string libname) private
LoadNativeAssemblies() [1/2]
static void SqlServerTypes.Utilities.LoadNativeAssemblies (string rootApplicationPath) static
Loads the required native assemblies for the current architecture (x86 or x64)
Parameters
rootApplicationPath Root path of the current application. Use Server.MapPath(".") for ASP.NET applications and AppDomain.CurrentDomain.BaseDirectory for desktop applications.
Definition at line 22 of file Loader.cs.
        {
            var nativeBinaryPath = IntPtr.Size > 4
                ? Path.Combine(rootApplicationPath, @"SqlServerTypes\x64\")
                : Path.Combine(rootApplicationPath, @"SqlServerTypes\x86\");
            LoadNativeAssembly(nativeBinaryPath, "msvcr120.dll");
            LoadNativeAssembly(nativeBinaryPath, "SqlServerSpatial140.dll");
        }
References SqlServerTypes.Utilities.LoadNativeAssembly().
LoadNativeAssemblies() [2/2]
static void SqlServerTypes.Utilities.LoadNativeAssemblies (string rootApplicationPath) static
Loads the required native assemblies for the current architecture (x86 or x64)
Parameters
rootApplicationPath Root path of the current application. Use Server.MapPath(".") for ASP.NET applications and AppDomain.CurrentDomain.BaseDirectory for desktop applications.
Definition at line 22 of file Loader.cs.
        {
            var nativeBinaryPath = IntPtr.Size > 4
                ? Path.Combine(rootApplicationPath, @"SqlServerTypes\x64\")
                : Path.Combine(rootApplicationPath, @"SqlServerTypes\x86\");
            LoadNativeAssembly(nativeBinaryPath, "msvcr120.dll");
            LoadNativeAssembly(nativeBinaryPath, "SqlServerSpatial140.dll");
        }
References SqlServerTypes.Utilities.LoadNativeAssembly().
LoadNativeAssembly() [1/2]
static void SqlServerTypes.Utilities.LoadNativeAssembly (string nativeBinaryPath, string assemblyName) static private
Definition at line 32 of file Loader.cs.
        {
            var path = Path.Combine(nativeBinaryPath, assemblyName);
            var ptr = LoadLibrary(path);
            if (ptr == IntPtr.Zero)
            {
                throw new Exception(string.Format(
                    "Error loading {0} (ErrorCode: {1})",
                    assemblyName,
                    Marshal.GetLastWin32Error()));
            }
        }
References SqlServerTypes.Utilities.LoadLibrary().
Referenced by SqlServerTypes.Utilities.LoadNativeAssemblies().
LoadNativeAssembly() [2/2]
static void SqlServerTypes.Utilities.LoadNativeAssembly (string nativeBinaryPath, string assemblyName) static private
Definition at line 32 of file Loader.cs.
        {
            var path = Path.Combine(nativeBinaryPath, assemblyName);
            var ptr = LoadLibrary(path);
            if (ptr == IntPtr.Zero)
            {
                throw new Exception(string.Format(
                    "Error loading {0} (ErrorCode: {1})",
                    assemblyName,
                    Marshal.GetLastWin32Error()));
            }
        }
References SqlServerTypes.Utilities.LoadLibrary().
The documentation for this class was generated from the following files:
Capa.UI/SqlServerTypes/Loader.cs
packages/Microsoft.SqlServer.Types.14.0.314.76/content/SqlServerTypes/Loader.cs