Proyecto Autos Seguros: Capa.UI.Util.Utilitarios Class Reference
Capa.UI.Util.Utilitarios Class Reference
Static Public Member Functions
static void CultureInfo ()
Colocar Cultura Estandar para Costa Rica
static decimal ConsumoDolar (decimal valor)
Método que calcula el total en colones por medio del valor obtenido de la página de indicadores económicos
Detailed Description
Definition at line 13 of file Utilitarios.cs.
Member Function Documentation
ConsumoDolar()
static decimal Capa.UI.Util.Utilitarios.ConsumoDolar (decimal valor) static
Método que calcula el total en colones por medio del valor obtenido de la página de indicadores económicos
Parameters
valor
Returns
Definition at line 42 of file Utilitarios.cs.
        {
            string correoRegistrado = "pipiticaseguros@hotmail.com";
            string token = "EMIIOAPI1R";
            string nombreRegistrado = "Seguros Pipitica";
            try
            {
                // Habilitar TLS12
                System.Net.ServicePointManager.SecurityProtocol =
                                              SecurityProtocolType.Tls12;
                // wsindicadoreseconomicosSoap12 Binding tomado del app.Config
                Agente.wsindicadoreseconomicosSoapClient cliente =
                     new Agente.wsindicadoreseconomicosSoapClient("wsindicadoreseconomicosSoap12");
                DataSet dolar = cliente.ObtenerIndicadoresEconomicos("317",    /* 317 Compra / 318 Venta */
                                                                  "06/01/2020",      /* Fecha Inicial */
                                                                  "08/01/2020",      /* Fecha Final */
                                                                  nombreRegistrado,  /* Su Nombre Registrado   BCCR */
                                                                  "N",
                                                                  correoRegistrado, /* Correo Registrado BCCR */
                                                                  token             /* Token enviado por el BCCR */
                                                                 );
                decimal cambio = (decimal)dolar.Tables[0].Rows[2].Field<decimal>("NUM_VALOR");
                return valor*cambio;
            }
            catch (Exception)
            {
                throw;
            }
            return 0;
        }
Referenced by Capa.UI.Facturacion.frmFacturacion.cmbTipoPago_SelectionChangeCommitted().
CultureInfo()
static void Capa.UI.Util.Utilitarios.CultureInfo () static
Colocar Cultura Estandar para Costa Rica
Definition at line 18 of file Utilitarios.cs.
        {
            // Colocar Cultura Estandar para Costa Rica
            // esto me permite no tener problemas con (.) de los decimales
            CultureInfo Micultura = new CultureInfo("es-CR", false);
            Micultura.NumberFormat.CurrencySymbol = "¢";
            Micultura.NumberFormat.CurrencyDecimalDigits = 2;
            Micultura.NumberFormat.CurrencyDecimalSeparator = ".";
            Micultura.NumberFormat.CurrencyGroupSeparator = ",";
            int[] grupo = new int[] { 3, 3, 3 };
            Micultura.NumberFormat.CurrencyGroupSizes = grupo;
            Micultura.NumberFormat.NumberDecimalDigits = 2;
            Micultura.NumberFormat.NumberGroupSeparator = ",";
            Micultura.NumberFormat.NumberDecimalSeparator = ".";
            Micultura.NumberFormat.NumberGroupSizes = grupo;
            //Micultura.DateTimeFormat.
            Thread.CurrentThread.CurrentCulture = Micultura;
        }
References Capa.UI.Util.Utilitarios.CultureInfo().
Referenced by Capa.UI.Util.Utilitarios.CultureInfo(), and Capa.UI.Facturacion.frmFacturacion.frmFacturacion_Load().
The documentation for this class was generated from the following file:
Capa.UI/Util/Utilitarios.cs