Proyecto Autos Seguros: Capa.UI.Filtro.frmCoberturasAgregadas Class Reference
Capa.UI.Filtro.frmCoberturasAgregadas Class Reference
Public Member Functions
frmCoberturasAgregadas (int idTipoPoliza)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void toolStripBtnSalir_Click (object sender, EventArgs e)
void frmCoberturasAgregadas_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
int idTipoPoliza
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.ToolStrip tspBarraSuperior
System.Windows.Forms.ToolStripButton toolStripBtnSalir
System.Windows.Forms.DataGridView dgvCoberturasAgregadas
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn2
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn3
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn4
Detailed Description
Definition at line 15 of file frmCoberturasAgregadas.cs.
Constructor & Destructor Documentation
frmCoberturasAgregadas()
Capa.UI.Filtro.frmCoberturasAgregadas.frmCoberturasAgregadas (int idTipoPoliza)
Definition at line 18 of file frmCoberturasAgregadas.cs.
        {
            InitializeComponent();
            this.idTipoPoliza = idTipoPoliza;
        }
References Capa.UI.Filtro.frmCoberturasAgregadas.idTipoPoliza, and Capa.UI.Filtro.frmCoberturasAgregadas.InitializeComponent().
Member Function Documentation
Dispose()
override void Capa.UI.Filtro.frmCoberturasAgregadas.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file frmCoberturasAgregadas.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References Capa.UI.Filtro.frmCoberturasAgregadas.components.
frmCoberturasAgregadas_Load()
void Capa.UI.Filtro.frmCoberturasAgregadas.frmCoberturasAgregadas_Load (object sender, EventArgs e) private
Definition at line 29 of file frmCoberturasAgregadas.cs.
        {
            ICoberturaBLL logica = new CoberturaBLL();
            dgvCoberturasAgregadas.DataSource = logica.CoberturasAgregadas(idTipoPoliza);
        }
References Interfaces.ICoberturaBLL.CoberturasAgregadas(), Capa.UI.Filtro.frmCoberturasAgregadas.dgvCoberturasAgregadas, and Capa.UI.Filtro.frmCoberturasAgregadas.idTipoPoliza.
Referenced by Capa.UI.Filtro.frmCoberturasAgregadas.InitializeComponent().
InitializeComponent()
void Capa.UI.Filtro.frmCoberturasAgregadas.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file frmCoberturasAgregadas.Designer.cs.
        {
            this.tspBarraSuperior = new System.Windows.Forms.ToolStrip();
            this.toolStripBtnSalir = new System.Windows.Forms.ToolStripButton();
            this.dgvCoberturasAgregadas = new System.Windows.Forms.DataGridView();
            this.dataGridViewTextBoxColumn2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn3 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn4 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.tspBarraSuperior.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvCoberturasAgregadas)).BeginInit();
            this.SuspendLayout();
            //
            // tspBarraSuperior
            //
            this.tspBarraSuperior.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.tspBarraSuperior.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.tspBarraSuperior.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripBtnSalir});
            this.tspBarraSuperior.Location = new System.Drawing.Point(0, 0);
            this.tspBarraSuperior.Name = "tspBarraSuperior";
            this.tspBarraSuperior.Size = new System.Drawing.Size(572, 25);
            this.tspBarraSuperior.TabIndex = 18;
            this.tspBarraSuperior.Text = "toolStrip1";
            //
            // toolStripBtnSalir
            //
            this.toolStripBtnSalir.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnSalir.ForeColor = System.Drawing.Color.LightGray;
            this.toolStripBtnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnSalir.Name = "toolStripBtnSalir";
            this.toolStripBtnSalir.Size = new System.Drawing.Size(39, 22);
            this.toolStripBtnSalir.Text = "Salir";
            this.toolStripBtnSalir.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnSalir.Click += new System.EventHandler(this.toolStripBtnSalir_Click);
            //
            // dgvCoberturasAgregadas
            //
            this.dgvCoberturasAgregadas.AllowUserToAddRows = false;
            this.dgvCoberturasAgregadas.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvCoberturasAgregadas.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.dataGridViewTextBoxColumn2,
            this.dataGridViewTextBoxColumn3,
            this.dataGridViewTextBoxColumn4});
            this.dgvCoberturasAgregadas.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvCoberturasAgregadas.Location = new System.Drawing.Point(0, 25);
            this.dgvCoberturasAgregadas.Name = "dgvCoberturasAgregadas";
            this.dgvCoberturasAgregadas.ReadOnly = true;
            this.dgvCoberturasAgregadas.Size = new System.Drawing.Size(572, 313);
            this.dgvCoberturasAgregadas.TabIndex = 154;
            //
            // dataGridViewTextBoxColumn2
            //
            this.dataGridViewTextBoxColumn2.DataPropertyName = "Id";
            this.dataGridViewTextBoxColumn2.HeaderText = "Id";
            this.dataGridViewTextBoxColumn2.Name = "dataGridViewTextBoxColumn2";
            this.dataGridViewTextBoxColumn2.ReadOnly = true;
            //
            // dataGridViewTextBoxColumn3
            //
            this.dataGridViewTextBoxColumn3.DataPropertyName = "Precio";
            this.dataGridViewTextBoxColumn3.HeaderText = "Precio";
            this.dataGridViewTextBoxColumn3.Name = "dataGridViewTextBoxColumn3";
            this.dataGridViewTextBoxColumn3.ReadOnly = true;
            //
            // dataGridViewTextBoxColumn4
            //
            this.dataGridViewTextBoxColumn4.DataPropertyName = "Descripcion";
            this.dataGridViewTextBoxColumn4.HeaderText = "Descripcion";
            this.dataGridViewTextBoxColumn4.Name = "dataGridViewTextBoxColumn4";
            this.dataGridViewTextBoxColumn4.ReadOnly = true;
            //
            // frmCoberturasAgregadas
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(572, 338);
            this.Controls.Add(this.dgvCoberturasAgregadas);
            this.Controls.Add(this.tspBarraSuperior);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmCoberturasAgregadas";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "frmCoberturasAgregadas";
            this.Load += new System.EventHandler(this.frmCoberturasAgregadas_Load);
            this.tspBarraSuperior.ResumeLayout(false);
            this.tspBarraSuperior.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvCoberturasAgregadas)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References Capa.UI.Filtro.frmCoberturasAgregadas.dataGridViewTextBoxColumn2, Capa.UI.Filtro.frmCoberturasAgregadas.dataGridViewTextBoxColumn3, Capa.UI.Filtro.frmCoberturasAgregadas.dataGridViewTextBoxColumn4, Capa.UI.Filtro.frmCoberturasAgregadas.dgvCoberturasAgregadas, Capa.UI.Filtro.frmCoberturasAgregadas.frmCoberturasAgregadas_Load(), Capa.UI.Filtro.frmCoberturasAgregadas.toolStripBtnSalir, Capa.UI.Filtro.frmCoberturasAgregadas.toolStripBtnSalir_Click(), and Capa.UI.Filtro.frmCoberturasAgregadas.tspBarraSuperior.
Referenced by Capa.UI.Filtro.frmCoberturasAgregadas.frmCoberturasAgregadas().
toolStripBtnSalir_Click()
void Capa.UI.Filtro.frmCoberturasAgregadas.toolStripBtnSalir_Click (object sender, EventArgs e) private
Definition at line 24 of file frmCoberturasAgregadas.cs.
        {
            this.Close();
        }
Referenced by Capa.UI.Filtro.frmCoberturasAgregadas.InitializeComponent().
Member Data Documentation
components
System.ComponentModel.IContainer Capa.UI.Filtro.frmCoberturasAgregadas.components = null private
Required designer variable.
Definition at line 8 of file frmCoberturasAgregadas.Designer.cs.
Referenced by Capa.UI.Filtro.frmCoberturasAgregadas.Dispose().
dataGridViewTextBoxColumn2
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Filtro.frmCoberturasAgregadas.dataGridViewTextBoxColumn2 private
Definition at line 126 of file frmCoberturasAgregadas.Designer.cs.
Referenced by Capa.UI.Filtro.frmCoberturasAgregadas.InitializeComponent().
dataGridViewTextBoxColumn3
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Filtro.frmCoberturasAgregadas.dataGridViewTextBoxColumn3 private
Definition at line 127 of file frmCoberturasAgregadas.Designer.cs.
Referenced by Capa.UI.Filtro.frmCoberturasAgregadas.InitializeComponent().
dataGridViewTextBoxColumn4
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Filtro.frmCoberturasAgregadas.dataGridViewTextBoxColumn4 private
Definition at line 128 of file frmCoberturasAgregadas.Designer.cs.
Referenced by Capa.UI.Filtro.frmCoberturasAgregadas.InitializeComponent().
dgvCoberturasAgregadas
System.Windows.Forms.DataGridView Capa.UI.Filtro.frmCoberturasAgregadas.dgvCoberturasAgregadas private
Definition at line 125 of file frmCoberturasAgregadas.Designer.cs.
Referenced by Capa.UI.Filtro.frmCoberturasAgregadas.frmCoberturasAgregadas_Load(), and Capa.UI.Filtro.frmCoberturasAgregadas.InitializeComponent().
idTipoPoliza
int Capa.UI.Filtro.frmCoberturasAgregadas.idTipoPoliza private
Definition at line 17 of file frmCoberturasAgregadas.cs.
Referenced by Capa.UI.Filtro.frmCoberturasAgregadas.frmCoberturasAgregadas(), and Capa.UI.Filtro.frmCoberturasAgregadas.frmCoberturasAgregadas_Load().
toolStripBtnSalir
System.Windows.Forms.ToolStripButton Capa.UI.Filtro.frmCoberturasAgregadas.toolStripBtnSalir private
Definition at line 124 of file frmCoberturasAgregadas.Designer.cs.
Referenced by Capa.UI.Filtro.frmCoberturasAgregadas.InitializeComponent().
tspBarraSuperior
System.Windows.Forms.ToolStrip Capa.UI.Filtro.frmCoberturasAgregadas.tspBarraSuperior private
Definition at line 123 of file frmCoberturasAgregadas.Designer.cs.
Referenced by Capa.UI.Filtro.frmCoberturasAgregadas.InitializeComponent().
The documentation for this class was generated from the following files:
Capa.UI/Filtro/frmCoberturasAgregadas.cs
Capa.UI/Filtro/frmCoberturasAgregadas.Designer.cs