Proyecto Autos Seguros: DAL.FacturaDAL Class Reference
DAL.FacturaDAL Class Reference
Public Member Functions
void AnularFactura (int idFactura)
void Eliminar (int idFactura)
void Insertar (Factura factura)
List< Factura > SeleccionarFacturaHoy ()
List< Factura > SeleccionarFacturasAnuladas ()
Factura SeleccionarPorId (int idFactura)
List< Factura > SeleccionarTodas ()
void Insertar (Factura factura)
void Eliminar (int idFactura)
List< Factura > SeleccionarTodas ()
Factura SeleccionarPorId (int idFactura)
List< Factura > SeleccionarFacturaHoy ()
void AnularFactura (int idFactura)
List< Factura > SeleccionarFacturasAnuladas ()
Detailed Description
Definition at line 14 of file FacturaDAL.cs.
Member Function Documentation
AnularFactura()
void DAL.FacturaDAL.AnularFactura (int idFactura)
Implements Interfaces.IFacturaDAL.
Definition at line 16 of file FacturaDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_UPDATE_ActivoFactura";
                comando.Parameters.AddWithValue("@IdFactura", idFactura);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), and IDataBase.ExecuteNonQuery().
Eliminar()
void DAL.FacturaDAL.Eliminar (int idFactura)
Implements Interfaces.IFacturaDAL.
Definition at line 29 of file FacturaDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_DELETE_Factura_ByID";
                comando.Parameters.AddWithValue("@Id", idFactura);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), and IDataBase.ExecuteNonQuery().
Insertar()
void DAL.FacturaDAL.Insertar (Factura factura)
Implements Interfaces.IFacturaDAL.
Definition at line 43 of file FacturaDAL.cs.
        {
            List<IDbCommand> listaCommands = new List<IDbCommand>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comandoPoliza = new SqlCommand();
                SqlCommand comando = new SqlCommand();
                comandoPoliza.CommandType = System.Data.CommandType.StoredProcedure;
                comandoPoliza.CommandText = "usp_INSERT_Poliza";
                comandoPoliza.Parameters.AddWithValue("@Id", factura._Poliza.Id);
                comandoPoliza.Parameters.AddWithValue("@Descripcion", factura._Poliza.Descripcion);
                comandoPoliza.Parameters.AddWithValue("@FechaVencimiento", factura._Poliza.FechaVencimiento);
                comandoPoliza.Parameters.AddWithValue("@IdTipoPoliza", factura._Poliza.IdTipoPoliza);
                listaCommands.Add(comandoPoliza);
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_INSERT_Factura";
                comando.Parameters.AddWithValue("@Id", factura.IdFactura);
                comando.Parameters.AddWithValue("@IdTarjeta", factura.IdTarjeta);
                comando.Parameters.AddWithValue("@IdUsuario", factura.IdUsuario);
                comando.Parameters.AddWithValue("@FechaFacturacion", factura.FechaFacturacion);
                comando.Parameters.AddWithValue("@NumeroTarjeta", factura.NumeroTarjeta);
                comando.Parameters.AddWithValue("@IdTipoPago", factura.IdTipoPago);
                comando.Parameters.AddWithValue("@TotalDolares", factura.TotalDolares);
                comando.Parameters.AddWithValue("@TotalColones", factura.TotalColones);
                comando.Parameters.AddWithValue("@Activo", factura.Activo);
                comando.Parameters.AddWithValue("@IdPoliza", factura._Poliza.Id);
                listaCommands.Add(comando);
               db.ExecuteNonQuery(listaCommands,IsolationLevel.ReadCommitted);
            }
        }
References capa.Entidades.Factura._Poliza, capa.Entidades.Factura.Activo, FactoryDatabase.CreateDefaultDataBase(), Entities.Poliza.Descripcion, IDataBase.ExecuteNonQuery(), capa.Entidades.Factura.FechaFacturacion, Entities.Poliza.FechaVencimiento, Entities.Poliza.Id, capa.Entidades.Factura.IdFactura, capa.Entidades.Factura.IdTarjeta, capa.Entidades.Factura.IdTipoPago, Entities.Poliza.IdTipoPoliza, capa.Entidades.Factura.IdUsuario, capa.Entidades.Factura.NumeroTarjeta, capa.Entidades.Factura.TotalColones, and capa.Entidades.Factura.TotalDolares.
SeleccionarFacturaHoy()
List< Factura > DAL.FacturaDAL.SeleccionarFacturaHoy ()
Implements Interfaces.IFacturaDAL.
Definition at line 87 of file FacturaDAL.cs.
        {
            List<Factura> lista = new List<Factura>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_ObtenerFacturaHoy";
                comando.Parameters.AddWithValue("@Desde", new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 0, 0, 0));
                comando.Parameters.AddWithValue("@Hasta", new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 23, 59, 59));
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Factura factura = new Factura();
                    factura.IdFactura = (int)dr["Id"];
                    factura.IdUsuario = dr["IdUsuario"].ToString();
                    factura.FechaFacturacion = DateTime.Parse(dr["FechaFacturacion"].ToString());
                    factura.IdTipoPago = (int)dr["IdTipoPago"];
                    factura.IdTarjeta = (int)dr["IdTarjeta"];
                    factura.NumeroTarjeta = (int)dr["NumeroTarjeta"];
                    factura.TotalDolares = decimal.Parse(dr["TotalDolares"].ToString());
                    factura.TotalColones = decimal.Parse(dr["TotalColones"].ToString());
                    factura.Activo = (bool)dr["Activo"];
                    factura.IdPoliza = (int)dr["IdPoliza"];
                    lista.Add(factura);
                }
            }
            return lista;
        }
References capa.Entidades.Factura.Activo, FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteDataSet(), capa.Entidades.Factura.FechaFacturacion, capa.Entidades.Factura.IdFactura, capa.Entidades.Factura.IdPoliza, capa.Entidades.Factura.IdTarjeta, capa.Entidades.Factura.IdTipoPago, capa.Entidades.Factura.IdUsuario, capa.Entidades.Factura.NumeroTarjeta, capa.Entidades.Factura.TotalColones, and capa.Entidades.Factura.TotalDolares.
SeleccionarFacturasAnuladas()
List< Factura > DAL.FacturaDAL.SeleccionarFacturasAnuladas ()
Implements Interfaces.IFacturaDAL.
Definition at line 121 of file FacturaDAL.cs.
        {
            List<Factura> lista = new List<Factura>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_FacturasAnuladas";
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Factura factura = new Factura();
                    factura.IdFactura = (int)dr["Id"];
                    factura.IdUsuario = dr["IdUsuario"].ToString();
                    factura.FechaFacturacion = DateTime.Parse(dr["FechaFacturacion"].ToString());
                    factura.IdTipoPago = (int)dr["IdTipoPago"];
                    factura.IdTarjeta = (int)dr["IdTarjeta"];
                    factura.NumeroTarjeta = (int)dr["NumeroTarjeta"];
                    factura.TotalDolares = decimal.Parse(dr["TotalDolares"].ToString());
                    factura.TotalColones = decimal.Parse(dr["TotalColones"].ToString());
                    factura.Activo = (bool)dr["Activo"];
                    factura.IdPoliza = (int)dr["IdPoliza"];
                    lista.Add(factura);
                }
            }
            return lista;
        }
References capa.Entidades.Factura.Activo, FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteDataSet(), capa.Entidades.Factura.FechaFacturacion, capa.Entidades.Factura.IdFactura, capa.Entidades.Factura.IdPoliza, capa.Entidades.Factura.IdTarjeta, capa.Entidades.Factura.IdTipoPago, capa.Entidades.Factura.IdUsuario, capa.Entidades.Factura.NumeroTarjeta, capa.Entidades.Factura.TotalColones, and capa.Entidades.Factura.TotalDolares.
SeleccionarPorId()
Factura DAL.FacturaDAL.SeleccionarPorId (int idFactura)
Implements Interfaces.IFacturaDAL.
Definition at line 152 of file FacturaDAL.cs.
        {
            Factura oEncFactura = new Factura();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_";
                comando.Parameters.AddWithValue("@Id", idFactura);
                DataSet ds = db.ExecuteDataSet(comando);
                if (ds.Tables[0].Rows.Count > 0)
                {
                    DataRow dr = ds.Tables[0].Rows[0];
                    oEncFactura = new Factura()
                    {
                        IdFactura = (int)dr["Id"],
                        IdUsuario = dr["IdUsuario"].ToString(),
                        FechaFacturacion = DateTime.Parse(dr["FechaFacturacion"].ToString()),
                        IdTipoPago = (int)dr["IdTipoPago"],
                        TotalDolares = decimal.Parse(dr["TotalDolares"].ToString()),
                        TotalColones = decimal.Parse(dr["TotalColones"].ToString()),
                        Activo = (bool)dr["Activo"],
                        IdPoliza =(int) dr["IdPoliza"]
                    };
                    IUsuarioDAL datosUsuario = new UsuarioDAL();
                    oEncFactura._Usuario = datosUsuario.SeleccionarPorId(oEncFactura.IdUsuario);
                }
            }
            return oEncFactura;
        }
References capa.Entidades.Factura._Usuario, FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteDataSet(), capa.Entidades.Factura.IdUsuario, and Interfaces.IUsuarioDAL.SeleccionarPorId().
SeleccionarTodas()
List< Factura > DAL.FacturaDAL.SeleccionarTodas ()
Implements Interfaces.IFacturaDAL.
Definition at line 187 of file FacturaDAL.cs.
        {
            List<Factura> lista = new List<Factura>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_ObtenerFacturaHoy";
                comando.Parameters.AddWithValue("@Desde", new DateTime(DateTime.Now.Year,DateTime.Now.Month,DateTime.Now.Day,0,0,0));
                comando.Parameters.AddWithValue("@Hasta", new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 23, 59, 59));
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Factura factura = new Factura();
                    factura.IdFactura = (int)dr["Id"];
                    factura.IdUsuario = dr["IdUsuario"].ToString();
                        factura.FechaFacturacion = DateTime.Parse(dr["FechaFacturacion"].ToString());
                    factura.IdTipoPago = (int)dr["IdTipoPago"];
                    factura.TotalDolares = decimal.Parse(dr["TotalDolares"].ToString());
                    factura.TotalColones = decimal.Parse(dr["TotalColones"].ToString());
                    factura.Activo = (bool)dr["Activo"];
                        factura.IdPoliza = (int)dr["IdPoliza"];
                    lista.Add(factura);
                }
            }
            return lista;
        }
References capa.Entidades.Factura.Activo, FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteDataSet(), capa.Entidades.Factura.FechaFacturacion, capa.Entidades.Factura.IdFactura, capa.Entidades.Factura.IdPoliza, capa.Entidades.Factura.IdTipoPago, capa.Entidades.Factura.IdUsuario, capa.Entidades.Factura.TotalColones, and capa.Entidades.Factura.TotalDolares.
The documentation for this class was generated from the following file:
DAL/FacturaDAL.cs