Proyecto Autos Seguros: DAL.CoberturaDAL Class Reference
DAL.CoberturaDAL Class Reference
Public Member Functions
void Actualizar (Cobertura cobertura)
List< Cobertura > CoberturasAgregadas (int idTipoPoliza)
void Eliminar (int id)
void Insertar (Cobertura cobertura)
Cobertura SeleccionarPorId (int id)
List< Cobertura > SeleccionarTodas ()
void Insertar (Cobertura cobertura)
void Actualizar (Cobertura cobertura)
void Eliminar (int id)
List< Cobertura > SeleccionarTodas ()
Cobertura SeleccionarPorId (int id)
List< Cobertura > CoberturasAgregadas (int idTipoPoliza)
Detailed Description
Definition at line 13 of file CoberturaDAL.cs.
Member Function Documentation
Actualizar()
void DAL.CoberturaDAL.Actualizar (Cobertura cobertura)
Implements Interfaces.ICoberturaDAL.
Definition at line 15 of file CoberturaDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_UPDATE_Cobertura";
                comando.Parameters.AddWithValue("@Id", cobertura.Id);
                comando.Parameters.AddWithValue("@Descripcion", cobertura.Descripcion);
                comando.Parameters.AddWithValue("@Precio", cobertura.Precio);
                comando.Parameters.AddWithValue("@Total", cobertura.Total);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), Entities.Cobertura.Descripcion, IDataBase.ExecuteNonQuery(), Entities.Cobertura.Id, Entities.Cobertura.Precio, and Entities.Cobertura.Total.
CoberturasAgregadas()
List< Cobertura > DAL.CoberturaDAL.CoberturasAgregadas (int idTipoPoliza)
Implements Interfaces.ICoberturaDAL.
Definition at line 32 of file CoberturaDAL.cs.
        {
            List<Cobertura> lista = new List<Cobertura>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_coberturasAgregadas";
                comando.Parameters.AddWithValue("@IdTipoPoliza", idTipoPoliza);
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Cobertura cobertura = new Cobertura();
                    cobertura.Id = (int)dr["IdCobertura"];
                    cobertura.Descripcion = dr["Descripcion"].ToString();
                    cobertura.Precio = (decimal)dr["Precio"];
                    cobertura.Total = (decimal)dr["Total"];
                    lista.Add(cobertura);
                }
            }
            return lista;
        }
References FactoryDatabase.CreateDefaultDataBase(), Entities.Cobertura.Descripcion, IDataBase.ExecuteDataSet(), Entities.Cobertura.Id, Entities.Cobertura.Precio, and Entities.Cobertura.Total.
Eliminar()
void DAL.CoberturaDAL.Eliminar (int id)
Implements Interfaces.ICoberturaDAL.
Definition at line 60 of file CoberturaDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_DELETE_Cobertura_ByID";
                comando.Parameters.AddWithValue("@Id", id);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), and IDataBase.ExecuteNonQuery().
Insertar()
void DAL.CoberturaDAL.Insertar (Cobertura cobertura)
Implements Interfaces.ICoberturaDAL.
Definition at line 73 of file CoberturaDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_INSERT_Cobertura";
                comando.Parameters.AddWithValue("@Descripcion", cobertura.Descripcion);
                comando.Parameters.AddWithValue("@Precio", cobertura.Precio);
                comando.Parameters.AddWithValue("@Total", cobertura.Total);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), Entities.Cobertura.Descripcion, IDataBase.ExecuteNonQuery(), Entities.Cobertura.Precio, and Entities.Cobertura.Total.
SeleccionarPorId()
Cobertura DAL.CoberturaDAL.SeleccionarPorId (int id)
Implements Interfaces.ICoberturaDAL.
Definition at line 88 of file CoberturaDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_Cobertura_ByID";
                comando.Parameters.AddWithValue("@Id", id);
                IDataReader dr = db.ExecuteReader(comando);
                while (dr.Read())
                {
                    Cobertura cobertura = new Cobertura();
                    cobertura.Id =(int) dr["Id"];
                    cobertura.Descripcion = dr["Descripcion"].ToString();
                    cobertura.Precio =(decimal) dr["Precio"];
                    cobertura.Total = (decimal)dr["Total"];
                    return cobertura;
                }
            }
            return null;
        }
References FactoryDatabase.CreateDefaultDataBase(), Entities.Cobertura.Descripcion, IDataBase.ExecuteReader(), Entities.Cobertura.Id, Entities.Cobertura.Precio, and Entities.Cobertura.Total.
SeleccionarTodas()
List< Cobertura > DAL.CoberturaDAL.SeleccionarTodas ()
Implements Interfaces.ICoberturaDAL.
Definition at line 114 of file CoberturaDAL.cs.
        {
            List<Cobertura> lista = new List<Cobertura>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_Cobertura_All";
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Cobertura cobertura = new Cobertura();
                    cobertura.Id = (int)dr["Id"];
                    cobertura.Descripcion = dr["Descripcion"].ToString();
                    cobertura.Precio = (decimal)dr["Precio"];
                    cobertura.Total = (decimal)dr["Total"];
                    lista.Add(cobertura);
                }
            }
            return lista;
        }
References FactoryDatabase.CreateDefaultDataBase(), Entities.Cobertura.Descripcion, IDataBase.ExecuteDataSet(), Entities.Cobertura.Id, Entities.Cobertura.Precio, and Entities.Cobertura.Total.
The documentation for this class was generated from the following file:
DAL/CoberturaDAL.cs