Proyecto Autos Seguros: Capa.UI.Filtro.frmFiltroUsuario Class Reference
Capa.UI.Filtro.frmFiltroUsuario Class Reference
Public Member Functions
frmFiltroUsuario ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
Usuario _User = null [get, private set]
Private Member Functions
void toolStripBtnNuevo_Click (object sender, EventArgs e)
Limpia los campos
void toolStripBtnBuscar_Click (object sender, EventArgs e)
Ejecuta el método que busca el usuario por filtración
void toolStripBtnSalir_Click (object sender, EventArgs e)
void dgvDatos_CellClick (object sender, DataGridViewCellEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.TextBox txtFiltro
System.Windows.Forms.DataGridView dgvDatos
System.Windows.Forms.ToolStrip tspBarraSuperior
System.Windows.Forms.ToolStripButton toolStripBtnNuevo
System.Windows.Forms.ToolStripButton toolStripBtnBuscar
System.Windows.Forms.ToolStripButton toolStripBtnSalir
System.Windows.Forms.DataGridViewTextBoxColumn Column1
System.Windows.Forms.DataGridViewTextBoxColumn Nombre
Static Private Attributes
static readonly ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 18 of file frmFiltroUsuario.cs.
Constructor & Destructor Documentation
frmFiltroUsuario()
Capa.UI.Filtro.frmFiltroUsuario.frmFiltroUsuario ()
Definition at line 23 of file frmFiltroUsuario.cs.
        {
            InitializeComponent();
        }
References Capa.UI.Filtro.frmFiltroUsuario.InitializeComponent().
Member Function Documentation
dgvDatos_CellClick()
void Capa.UI.Filtro.frmFiltroUsuario.dgvDatos_CellClick (object sender, DataGridViewCellEventArgs e) private
Definition at line 72 of file frmFiltroUsuario.cs.
        {
            try
            {
                if (dgvDatos.RowCount > 0 && dgvDatos.SelectedRows.Count > 0)
                {
                    if (dgvDatos.CurrentCell.Selected)
                    {
                        _User = dgvDatos.SelectedRows[0].DataBoundItem as Usuario;
                        this.DialogResult = DialogResult.OK;
                    }
                }
            }
            catch (Exception er)
            {
                MessageBox.Show("Se ha producido el siguiente error " + er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error(er.Message);
            }
        }
References Capa.UI.Filtro.frmFiltroUsuario._MyLogControlEventos, Capa.UI.Filtro.frmFiltroUsuario._User, and Capa.UI.Filtro.frmFiltroUsuario.dgvDatos.
Referenced by Capa.UI.Filtro.frmFiltroUsuario.InitializeComponent().
Dispose()
override void Capa.UI.Filtro.frmFiltroUsuario.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 15 of file frmFiltroUsuario.designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References Capa.UI.Filtro.frmFiltroUsuario.components.
InitializeComponent()
void Capa.UI.Filtro.frmFiltroUsuario.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 30 of file frmFiltroUsuario.designer.cs.
        {
            this.txtFiltro = new System.Windows.Forms.TextBox();
            this.dgvDatos = new System.Windows.Forms.DataGridView();
            this.Column1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Nombre = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.tspBarraSuperior = new System.Windows.Forms.ToolStrip();
            this.toolStripBtnNuevo = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnBuscar = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnSalir = new System.Windows.Forms.ToolStripButton();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDatos)).BeginInit();
            this.tspBarraSuperior.SuspendLayout();
            this.SuspendLayout();
            //
            // txtFiltro
            //
            this.txtFiltro.Location = new System.Drawing.Point(12, 65);
            this.txtFiltro.Name = "txtFiltro";
            this.txtFiltro.Size = new System.Drawing.Size(554, 20);
            this.txtFiltro.TabIndex = 19;
            //
            // dgvDatos
            //
            this.dgvDatos.AllowUserToAddRows = false;
            this.dgvDatos.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvDatos.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Column1,
            this.Nombre});
            this.dgvDatos.Location = new System.Drawing.Point(12, 91);
            this.dgvDatos.Name = "dgvDatos";
            this.dgvDatos.Size = new System.Drawing.Size(554, 189);
            this.dgvDatos.TabIndex = 18;
            this.dgvDatos.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvDatos_CellClick);
            //
            // Column1
            //
            this.Column1.DataPropertyName = "Id";
            this.Column1.HeaderText = "Id";
            this.Column1.Name = "Column1";
            //
            // Nombre
            //
            this.Nombre.DataPropertyName = "Nombre";
            this.Nombre.HeaderText = "Nombre";
            this.Nombre.Name = "Nombre";
            //
            // tspBarraSuperior
            //
            this.tspBarraSuperior.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.tspBarraSuperior.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.tspBarraSuperior.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripBtnNuevo,
            this.toolStripBtnBuscar,
            this.toolStripBtnSalir});
            this.tspBarraSuperior.Location = new System.Drawing.Point(0, 0);
            this.tspBarraSuperior.Name = "tspBarraSuperior";
            this.tspBarraSuperior.Size = new System.Drawing.Size(578, 25);
            this.tspBarraSuperior.TabIndex = 17;
            this.tspBarraSuperior.Text = "toolStrip1";
            //
            // toolStripBtnNuevo
            //
            this.toolStripBtnNuevo.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnNuevo.ForeColor = System.Drawing.Color.LightGray;
            this.toolStripBtnNuevo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnNuevo.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnNuevo.Name = "toolStripBtnNuevo";
            this.toolStripBtnNuevo.Size = new System.Drawing.Size(52, 22);
            this.toolStripBtnNuevo.Text = "Nuevo";
            this.toolStripBtnNuevo.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnNuevo.Click += new System.EventHandler(this.toolStripBtnNuevo_Click);
            //
            // toolStripBtnBuscar
            //
            this.toolStripBtnBuscar.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnBuscar.ForeColor = System.Drawing.Color.LightGray;
            this.toolStripBtnBuscar.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnBuscar.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnBuscar.Name = "toolStripBtnBuscar";
            this.toolStripBtnBuscar.Size = new System.Drawing.Size(52, 22);
            this.toolStripBtnBuscar.Text = "Buscar";
            this.toolStripBtnBuscar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnBuscar.Click += new System.EventHandler(this.toolStripBtnBuscar_Click);
            //
            // toolStripBtnSalir
            //
            this.toolStripBtnSalir.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnSalir.ForeColor = System.Drawing.Color.LightGray;
            this.toolStripBtnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnSalir.Name = "toolStripBtnSalir";
            this.toolStripBtnSalir.Size = new System.Drawing.Size(39, 22);
            this.toolStripBtnSalir.Text = "Salir";
            this.toolStripBtnSalir.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnSalir.Click += new System.EventHandler(this.toolStripBtnSalir_Click);
            //
            // frmFiltroUsuario
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.ClientSize = new System.Drawing.Size(578, 289);
            this.Controls.Add(this.txtFiltro);
            this.Controls.Add(this.dgvDatos);
            this.Controls.Add(this.tspBarraSuperior);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmFiltroUsuario";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmFiltroUsuario";
            ((System.ComponentModel.ISupportInitialize)(this.dgvDatos)).EndInit();
            this.tspBarraSuperior.ResumeLayout(false);
            this.tspBarraSuperior.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References Capa.UI.Filtro.frmFiltroUsuario.Column1, Capa.UI.Filtro.frmFiltroUsuario.dgvDatos, Capa.UI.Filtro.frmFiltroUsuario.dgvDatos_CellClick(), Capa.UI.Filtro.frmFiltroUsuario.Nombre, Capa.UI.Filtro.frmFiltroUsuario.toolStripBtnBuscar, Capa.UI.Filtro.frmFiltroUsuario.toolStripBtnBuscar_Click(), Capa.UI.Filtro.frmFiltroUsuario.toolStripBtnNuevo, Capa.UI.Filtro.frmFiltroUsuario.toolStripBtnNuevo_Click(), Capa.UI.Filtro.frmFiltroUsuario.toolStripBtnSalir, Capa.UI.Filtro.frmFiltroUsuario.toolStripBtnSalir_Click(), Capa.UI.Filtro.frmFiltroUsuario.tspBarraSuperior, and Capa.UI.Filtro.frmFiltroUsuario.txtFiltro.
Referenced by Capa.UI.Filtro.frmFiltroUsuario.frmFiltroUsuario().
toolStripBtnBuscar_Click()
void Capa.UI.Filtro.frmFiltroUsuario.toolStripBtnBuscar_Click (object sender, EventArgs e) private
Ejecuta el método que busca el usuario por filtración
Parameters
sender
e
Definition at line 45 of file frmFiltroUsuario.cs.
        {
            IUsuarioBLL datos = new UsuarioBLL();
            string filtro = string.Empty;
            try
            {
                filtro = this.txtFiltro.Text;
                filtro = filtro.Replace(' ', '%');
                filtro = "%" + filtro + "%";
                this.dgvDatos.AutoGenerateColumns = false;
                this.dgvDatos.DataSource = datos.GetUsuarioByFiltro(filtro);
            }
            catch (Exception er)
            {
                MessageBox.Show("Se ha producido el siguiente error " + er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error(er.Message);
            }
        }
References Capa.UI.Filtro.frmFiltroUsuario._MyLogControlEventos, Capa.UI.Filtro.frmFiltroUsuario.dgvDatos, Interfaces.IUsuarioBLL.GetUsuarioByFiltro(), and Capa.UI.Filtro.frmFiltroUsuario.txtFiltro.
Referenced by Capa.UI.Filtro.frmFiltroUsuario.InitializeComponent().
toolStripBtnNuevo_Click()
void Capa.UI.Filtro.frmFiltroUsuario.toolStripBtnNuevo_Click (object sender, EventArgs e) private
Limpia los campos
Parameters
sender
e
Definition at line 34 of file frmFiltroUsuario.cs.
        {
            this.txtFiltro.Clear();
            this.dgvDatos.DataSource = null;
            txtFiltro.Focus();
        }
References Capa.UI.Filtro.frmFiltroUsuario.dgvDatos, and Capa.UI.Filtro.frmFiltroUsuario.txtFiltro.
Referenced by Capa.UI.Filtro.frmFiltroUsuario.InitializeComponent().
toolStripBtnSalir_Click()
void Capa.UI.Filtro.frmFiltroUsuario.toolStripBtnSalir_Click (object sender, EventArgs e) private
Definition at line 66 of file frmFiltroUsuario.cs.
        {
            this.DialogResult = DialogResult.Cancel;
            Close();
        }
Referenced by Capa.UI.Filtro.frmFiltroUsuario.InitializeComponent().
Member Data Documentation
_MyLogControlEventos
readonly ILog Capa.UI.Filtro.frmFiltroUsuario._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 20 of file frmFiltroUsuario.cs.
Referenced by Capa.UI.Filtro.frmFiltroUsuario.dgvDatos_CellClick(), and Capa.UI.Filtro.frmFiltroUsuario.toolStripBtnBuscar_Click().
Column1
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Filtro.frmFiltroUsuario.Column1 private
Definition at line 155 of file frmFiltroUsuario.designer.cs.
Referenced by Capa.UI.Filtro.frmFiltroUsuario.InitializeComponent().
components
System.ComponentModel.IContainer Capa.UI.Filtro.frmFiltroUsuario.components = null private
Required designer variable.
Definition at line 9 of file frmFiltroUsuario.designer.cs.
Referenced by Capa.UI.Filtro.frmFiltroUsuario.Dispose().
dgvDatos
System.Windows.Forms.DataGridView Capa.UI.Filtro.frmFiltroUsuario.dgvDatos private
Definition at line 150 of file frmFiltroUsuario.designer.cs.
Referenced by Capa.UI.Filtro.frmFiltroUsuario.dgvDatos_CellClick(), Capa.UI.Filtro.frmFiltroUsuario.InitializeComponent(), Capa.UI.Filtro.frmFiltroUsuario.toolStripBtnBuscar_Click(), and Capa.UI.Filtro.frmFiltroUsuario.toolStripBtnNuevo_Click().
Nombre
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Filtro.frmFiltroUsuario.Nombre private
Definition at line 156 of file frmFiltroUsuario.designer.cs.
Referenced by Capa.UI.Filtro.frmFiltroUsuario.InitializeComponent().
toolStripBtnBuscar
System.Windows.Forms.ToolStripButton Capa.UI.Filtro.frmFiltroUsuario.toolStripBtnBuscar private
Definition at line 153 of file frmFiltroUsuario.designer.cs.
Referenced by Capa.UI.Filtro.frmFiltroUsuario.InitializeComponent().
toolStripBtnNuevo
System.Windows.Forms.ToolStripButton Capa.UI.Filtro.frmFiltroUsuario.toolStripBtnNuevo private
Definition at line 152 of file frmFiltroUsuario.designer.cs.
Referenced by Capa.UI.Filtro.frmFiltroUsuario.InitializeComponent().
toolStripBtnSalir
System.Windows.Forms.ToolStripButton Capa.UI.Filtro.frmFiltroUsuario.toolStripBtnSalir private
Definition at line 154 of file frmFiltroUsuario.designer.cs.
Referenced by Capa.UI.Filtro.frmFiltroUsuario.InitializeComponent().
tspBarraSuperior
System.Windows.Forms.ToolStrip Capa.UI.Filtro.frmFiltroUsuario.tspBarraSuperior private
Definition at line 151 of file frmFiltroUsuario.designer.cs.
Referenced by Capa.UI.Filtro.frmFiltroUsuario.InitializeComponent().
txtFiltro
System.Windows.Forms.TextBox Capa.UI.Filtro.frmFiltroUsuario.txtFiltro private
Definition at line 149 of file frmFiltroUsuario.designer.cs.
Referenced by Capa.UI.Filtro.frmFiltroUsuario.InitializeComponent(), Capa.UI.Filtro.frmFiltroUsuario.toolStripBtnBuscar_Click(), and Capa.UI.Filtro.frmFiltroUsuario.toolStripBtnNuevo_Click().
Property Documentation
_User
Usuario Capa.UI.Filtro.frmFiltroUsuario._User = null get private set
Definition at line 21 of file frmFiltroUsuario.cs.
{ get; private set; } = null;
Referenced by Capa.UI.Facturacion.frmFacturacion.btnBuscar_Click(), and Capa.UI.Filtro.frmFiltroUsuario.dgvDatos_CellClick().
The documentation for this class was generated from the following files:
Capa.UI/Filtro/frmFiltroUsuario.cs
Capa.UI/Filtro/frmFiltroUsuario.designer.cs