Proyecto Autos Seguros: FactoryDatabase Class Reference
FactoryDatabase Class Reference
Static Public Member Functions
static IDataBase CreateDefaultDataBase ()
static IDataBase CreateDataBase (string pStringConnection)
Detailed Description
Definition at line 6 of file FactoryDataBase.cs.
Member Function Documentation
CreateDataBase()
static IDataBase FactoryDatabase.CreateDataBase (string pStringConnection) static
Definition at line 38 of file FactoryDataBase.cs.
    {
        IDbConnection conexion = null;
        try
        {
            IDataBase db = new DataBase();
            conexion = new SqlConnection(pStringConnection);
            conexion.Open();
            db._Conexion = conexion;
            if (conexion.State != ConnectionState.Open)
            {
                throw new Exception("No se pudo abrir la Base de Datos, revise los parámetros de conexión! ");
            }
            return db;
        }
        catch (Exception)
        {
            throw;
        }
    }
References IDataBase._Conexion.
CreateDefaultDataBase()
static IDataBase FactoryDatabase.CreateDefaultDataBase () static
Definition at line 8 of file FactoryDataBase.cs.
    {
        IDbConnection conexion = null;
        try
        {
            string pStringConnection = FactoryConexion.CreateConnection();
            IDataBase db = new DataBase();
            conexion = new SqlConnection(pStringConnection);
            conexion.Open();
            db._Conexion = conexion;
            if (conexion.State != ConnectionState.Open)
            {
                throw new Exception("No se pudo abrir la Base de Datos, revise los parámetros de conexión! ");
            }
            return db;
        }
        catch (Exception)
        {
            throw;
        }
    }
References IDataBase._Conexion, and FactoryConexion.CreateConnection().
Referenced by DAL.CoberturaDAL.Actualizar(), DAL.DetallePolizaDAL.Actualizar(), DAL.IVADAL.Actualizar(), DAL.PolizaDAL.Actualizar(), DAL.TipoPolizaDAL.Actualizar(), DAL.UsuarioDAL.Actualizar(), DAL.FacturaDAL.AnularFactura(), DAL.CoberturaDAL.CoberturasAgregadas(), DAL.CoberturaDAL.Eliminar(), DAL.IVADAL.Eliminar(), DAL.PolizaDAL.Eliminar(), DAL.TipoPolizaDAL.Eliminar(), DAL.FacturaDAL.Eliminar(), DAL.DetallePolizaDAL.Eliminar(), DAL.UsuarioDAL.Eliminar(), DAL.DetallePolizaDAL.EliminarByPolCob(), DAL.PolizaDAL.GetCurrentNumeroPoliza(), DAL.PolizaDAL.GetNextNumeroPoliza(), DAL.UsuarioDAL.GetUsuarioByFiltro(), DAL.CoberturaDAL.Insertar(), DAL.DetallePolizaDAL.Insertar(), DAL.FacturaDAL.Insertar(), DAL.IVADAL.Insertar(), DAL.PolizaDAL.Insertar(), DAL.TipoPolizaDAL.Insertar(), DAL.UsuarioDAL.Insertar(), DAL.GeneroDAL.ObtenerGenero(), DAL.PaisDAL.ObtenerPaises(), DAL.GeneroDAL.ObtenerPorId(), DAL.PaisDAL.ObtenerPorId(), DAL.TarjetaDAL.ObtenerPorId(), DAL.TipoPagoDAL.ObtenerPorId(), DAL.TipoPolizaDAL.ObtenerPorId(), DAL.TipoUsuarioDAL.ObtenerPorId(), DAL.TarjetaDAL.ObtenerTarjeta(), DAL.TipoPagoDAL.ObtenerTipoPago(), DAL.TipoPolizaDAL.ObtenerTipoPolizas(), DAL.TipoUsuarioDAL.ObtenerTiposUsuarios(), DAL.UsuarioDAL.ObtenerUsuarioIdByIdFac(), DAL.FacturaDAL.SeleccionarFacturaHoy(), DAL.FacturaDAL.SeleccionarFacturasAnuladas(), DAL.CoberturaDAL.SeleccionarPorId(), DAL.IVADAL.SeleccionarPorId(), DAL.PolizaDAL.SeleccionarPorId(), DAL.FacturaDAL.SeleccionarPorId(), DAL.DetallePolizaDAL.SeleccionarPorId(), DAL.UsuarioDAL.SeleccionarPorId(), DAL.IVADAL.SeleccionarReciente(), DAL.CoberturaDAL.SeleccionarTodas(), DAL.DetallePolizaDAL.SeleccionarTodas(), DAL.FacturaDAL.SeleccionarTodas(), DAL.IVADAL.SeleccionarTodas(), DAL.PolizaDAL.SeleccionarTodas(), DAL.UsuarioDAL.SeleccionarTodas(), and DAL.UsuarioDAL.VerificarLogin().
The documentation for this class was generated from the following file:
DAL/Persistencia/FactoryDataBase.cs