Proyecto Autos Seguros: BLL.PolizaBLL Class Reference
BLL.PolizaBLL Class Reference
Public Member Functions
void Actualizar (Poliza poliza)
void Eliminar (int id)
int GetCurrentNumeroPoliza ()
int GetNextNumeroPoliza ()
void Insertar (Poliza poliza)
Poliza SeleccionarPorId (int id)
List< Poliza > SeleccionarTodas ()
void Insertar (Poliza poliza)
void Actualizar (Poliza poliza)
void Eliminar (int id)
List< Poliza > SeleccionarTodas ()
Poliza SeleccionarPorId (int id)
int GetNextNumeroPoliza ()
int GetCurrentNumeroPoliza ()
Detailed Description
Definition at line 12 of file PolizaBLL.cs.
Member Function Documentation
Actualizar()
void BLL.PolizaBLL.Actualizar (Poliza poliza)
Implements Interfaces.IPolizaBLL.
Definition at line 14 of file PolizaBLL.cs.
        {
            IPolizaDAL polizaDAL = new PolizaDAL();
            polizaDAL.Actualizar(poliza);
        }
References Interfaces.IPolizaDAL.Actualizar().
Eliminar()
void BLL.PolizaBLL.Eliminar (int id)
Implements Interfaces.IPolizaBLL.
Definition at line 20 of file PolizaBLL.cs.
        {
            IPolizaDAL polizaDAL = new PolizaDAL();
            polizaDAL.Eliminar(id);
        }
References Interfaces.IPolizaDAL.Eliminar().
GetCurrentNumeroPoliza()
int BLL.PolizaBLL.GetCurrentNumeroPoliza ()
Implements Interfaces.IPolizaBLL.
Definition at line 26 of file PolizaBLL.cs.
        {
            IPolizaDAL polizaDAL = new PolizaDAL();
          return  polizaDAL.GetCurrentNumeroPoliza();
        }
References Interfaces.IPolizaDAL.GetCurrentNumeroPoliza().
GetNextNumeroPoliza()
int BLL.PolizaBLL.GetNextNumeroPoliza ()
Implements Interfaces.IPolizaBLL.
Definition at line 32 of file PolizaBLL.cs.
        {
            IPolizaDAL polizaDAL = new PolizaDAL();
            return polizaDAL.GetNextNumeroPoliza();
        }
References Interfaces.IPolizaDAL.GetNextNumeroPoliza().
Insertar()
void BLL.PolizaBLL.Insertar (Poliza poliza)
Implements Interfaces.IPolizaBLL.
Definition at line 38 of file PolizaBLL.cs.
        {
            IPolizaDAL logica = new PolizaDAL();
            if (logica.SeleccionarPorId(poliza.Id) == null)
            {
                logica.Insertar(poliza);
            }
            else
            {
                logica.Actualizar(poliza);
            }
        }
References Interfaces.IPolizaDAL.Actualizar(), Entities.Poliza.Id, Interfaces.IPolizaDAL.Insertar(), and Interfaces.IPolizaDAL.SeleccionarPorId().
SeleccionarPorId()
Poliza BLL.PolizaBLL.SeleccionarPorId (int id)
Implements Interfaces.IPolizaBLL.
Definition at line 52 of file PolizaBLL.cs.
        {
            IPolizaDAL polizaDAL = new PolizaDAL();
            return polizaDAL.SeleccionarPorId(id);
        }
References Interfaces.IPolizaDAL.SeleccionarPorId().
SeleccionarTodas()
List< Poliza > BLL.PolizaBLL.SeleccionarTodas ()
Implements Interfaces.IPolizaBLL.
Definition at line 58 of file PolizaBLL.cs.
        {
            IPolizaDAL polizaDAL = new PolizaDAL();
            return polizaDAL.SeleccionarTodas();
        }
References Interfaces.IPolizaDAL.SeleccionarTodas().
The documentation for this class was generated from the following file:
BLL/PolizaBLL.cs