Proyecto Autos Seguros: DAL.TipoPagoDAL Class Reference
DAL.TipoPagoDAL Class Reference
Public Member Functions
TipoPago ObtenerPorId (int id)
List< TipoPago > ObtenerTipoPago ()
List< TipoPago > ObtenerTipoPago ()
TipoPago ObtenerPorId (int id)
Detailed Description
Definition at line 13 of file TipoPagoDAL.cs.
Member Function Documentation
ObtenerPorId()
TipoPago DAL.TipoPagoDAL.ObtenerPorId (int id)
Implements Interfaces.ITipoPagoDAL.
Definition at line 15 of file TipoPagoDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_TipoPago_ByID";
                comando.Parameters.AddWithValue("@Id", id);
                IDataReader reader = db.ExecuteReader(comando);
                while (reader.Read())
                {
                    TipoPago tipoPago = new TipoPago();
                    tipoPago.Id = (int)reader["Id"];
                    tipoPago.Descripcion = reader["Descripcion"].ToString();
                    tipoPago.Porcentaje = (Decimal)reader["Porcentaje"];
                    return tipoPago;
                }
            }
            return null;
        }
References FactoryDatabase.CreateDefaultDataBase(), Entities.TipoPago.Descripcion, IDataBase.ExecuteReader(), Entities.TipoPago.Id, and Entities.TipoPago.Porcentaje.
ObtenerTipoPago()
List< TipoPago > DAL.TipoPagoDAL.ObtenerTipoPago ()
Implements Interfaces.ITipoPagoDAL.
Definition at line 39 of file TipoPagoDAL.cs.
        {
            List<TipoPago> lista = new List<TipoPago>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_TipoPago_All";
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    TipoPago tipoPago = new TipoPago();
                    tipoPago.Id = (int)dr["Id"];
                    tipoPago.Descripcion = dr["Descripcion"].ToString();
                    tipoPago.Porcentaje = (Decimal) dr["Porcentaje"];
                    lista.Add(tipoPago);
                }
            }
            return lista;
        }
References FactoryDatabase.CreateDefaultDataBase(), Entities.TipoPago.Descripcion, IDataBase.ExecuteDataSet(), Entities.TipoPago.Id, and Entities.TipoPago.Porcentaje.
The documentation for this class was generated from the following file:
DAL/TipoPagoDAL.cs