Proyecto Autos Seguros: Capa.UI.Reporte.DataSetReportes Class Reference
Capa.UI.Reporte.DataSetReportes Class Reference
Represents a strongly typed in-memory cache of data. /summary>
Classes
class usp_ObtenerFacturaReporteDataTable
Represents the strongly named DataTable class. /summary>
class usp_ObtenerFacturaReporteRow
Represents strongly named DataRow class. /summary>
class usp_ObtenerFacturaReporteRowChangeEvent
Row event argument class /summary>
class usp_PolizaByIdUsuarioDataTable
Represents the strongly named DataTable class. /summary>
class usp_PolizaByIdUsuarioRow
Represents strongly named DataRow class. /summary>
class usp_PolizaByIdUsuarioRowChangeEvent
Row event argument class /summary>
class usp_PolizaTotalByFechasDataTable
Represents the strongly named DataTable class. /summary>
class usp_PolizaTotalByFechasRow
Represents strongly named DataRow class. /summary>
class usp_PolizaTotalByFechasRowChangeEvent
Row event argument class /summary>
class usp_SELECT_VentasByDiaDataTable
Represents the strongly named DataTable class. /summary>
class usp_SELECT_VentasByDiaRow
Represents strongly named DataRow class. /summary>
class usp_SELECT_VentasByDiaRowChangeEvent
Row event argument class /summary>
Public Member Functions
DataSetReportes ()
override global::System.Data.DataSet Clone ()
delegate void usp_PolizaTotalByFechasRowChangeEventHandler (object sender, usp_PolizaTotalByFechasRowChangeEvent e)
delegate void usp_PolizaByIdUsuarioRowChangeEventHandler (object sender, usp_PolizaByIdUsuarioRowChangeEvent e)
delegate void usp_SELECT_VentasByDiaRowChangeEventHandler (object sender, usp_SELECT_VentasByDiaRowChangeEvent e)
delegate void usp_ObtenerFacturaReporteRowChangeEventHandler (object sender, usp_ObtenerFacturaReporteRowChangeEvent e)
Static Public Member Functions
static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema (global::System.Xml.Schema.XmlSchemaSet xs)
Protected Member Functions
DataSetReportes (global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context)
override void InitializeDerivedDataSet ()
override bool ShouldSerializeTables ()
override bool ShouldSerializeRelations ()
override void ReadXmlSerializable (global::System.Xml.XmlReader reader)
override global::System.Xml.Schema.XmlSchema GetSchemaSerializable ()
Package Functions
void InitVars ()
void InitVars (bool initTable)
Properties
usp_PolizaTotalByFechasDataTable usp_PolizaTotalByFechas [get]
usp_PolizaByIdUsuarioDataTable usp_PolizaByIdUsuario [get]
usp_SELECT_VentasByDiaDataTable usp_SELECT_VentasByDia [get]
usp_ObtenerFacturaReporteDataTable usp_ObtenerFacturaReporte [get]
override global::System.Data.SchemaSerializationMode SchemaSerializationMode [get, set]
new global::System.Data.DataTableCollection Tables [get]
new global::System.Data.DataRelationCollection Relations [get]
Private Member Functions
void InitClass ()
bool ShouldSerializeusp_PolizaTotalByFechas ()
bool ShouldSerializeusp_PolizaByIdUsuario ()
bool ShouldSerializeusp_SELECT_VentasByDia ()
bool ShouldSerializeusp_ObtenerFacturaReporte ()
void SchemaChanged (object sender, global::System.ComponentModel.CollectionChangeEventArgs e)
Private Attributes
usp_PolizaTotalByFechasDataTable tableusp_PolizaTotalByFechas
usp_PolizaByIdUsuarioDataTable tableusp_PolizaByIdUsuario
usp_SELECT_VentasByDiaDataTable tableusp_SELECT_VentasByDia
usp_ObtenerFacturaReporteDataTable tableusp_ObtenerFacturaReporte
global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema
Detailed Description
Represents a strongly typed in-memory cache of data. /summary>
Definition at line 5 of file DataSetReportes.cs.
Constructor & Destructor Documentation
DataSetReportes() [1/2]
Capa.UI.Reporte.DataSetReportes.DataSetReportes ()
Definition at line 39 of file DataSetReportes.Designer.cs.
{
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
References Capa.UI.Reporte.DataSetReportes.InitClass(), and Capa.UI.Reporte.DataSetReportes.SchemaChanged().
Referenced by Capa.UI.Reporte.DataSetReportes.Clone(), Capa.UI.Reporte.DataSetReportes.GetTypedDataSetSchema(), Capa.UI.Reporte.DataSetReportes.usp_PolizaTotalByFechasDataTable.GetTypedTableSchema(), Capa.UI.Reporte.DataSetReportes.usp_PolizaByIdUsuarioDataTable.GetTypedTableSchema(), Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.GetTypedTableSchema(), and Capa.UI.Reporte.DataSetReportes.usp_ObtenerFacturaReporteDataTable.GetTypedTableSchema().
DataSetReportes() [2/2]
Capa.UI.Reporte.DataSetReportes.DataSetReportes (global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) protected
Definition at line 50 of file DataSetReportes.Designer.cs.
                                                                                                                                                          :
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["usp_PolizaTotalByFechas"] != null)) {
                    base.Tables.Add(new usp_PolizaTotalByFechasDataTable(ds.Tables["usp_PolizaTotalByFechas"]));
                }
                if ((ds.Tables["usp_PolizaByIdUsuario"] != null)) {
                    base.Tables.Add(new usp_PolizaByIdUsuarioDataTable(ds.Tables["usp_PolizaByIdUsuario"]));
                }
                if ((ds.Tables["usp_SELECT_VentasByDia"] != null)) {
                    base.Tables.Add(new usp_SELECT_VentasByDiaDataTable(ds.Tables["usp_SELECT_VentasByDia"]));
                }
                if ((ds.Tables["usp_ObtenerFacturaReporte"] != null)) {
                    base.Tables.Add(new usp_ObtenerFacturaReporteDataTable(ds.Tables["usp_ObtenerFacturaReporte"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
References Capa.UI.Reporte.DataSetReportes.InitVars(), Capa.UI.Reporte.DataSetReportes.Relations, Capa.UI.Reporte.DataSetReportes.SchemaChanged(), and Capa.UI.Reporte.DataSetReportes.Tables.
Member Function Documentation
Clone()
override global.System.Data.DataSet Capa.UI.Reporte.DataSetReportes.Clone ()
Definition at line 174 of file DataSetReportes.Designer.cs.
{
            DataSetReportes cln = ((DataSetReportes)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
References Capa.UI.Reporte.DataSetReportes.DataSetReportes(), and Capa.UI.Reporte.DataSetReportes.SchemaSerializationMode.
GetSchemaSerializable()
override global.System.Xml.Schema.XmlSchema Capa.UI.Reporte.DataSetReportes.GetSchemaSerializable () protected
Definition at line 229 of file DataSetReportes.Designer.cs.
{
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
GetTypedDataSetSchema()
static global.System.Xml.Schema.XmlSchemaComplexType Capa.UI.Reporte.DataSetReportes.GetTypedDataSetSchema (global::System.Xml.Schema.XmlSchemaSet xs) static
Definition at line 323 of file DataSetReportes.Designer.cs.
{
            DataSetReportes ds = new DataSetReportes();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length)
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
References Capa.UI.Reporte.DataSetReportes.DataSetReportes().
InitClass()
void Capa.UI.Reporte.DataSetReportes.InitClass () private
Definition at line 273 of file DataSetReportes.Designer.cs.
{
            this.DataSetName = "DataSetReportes";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DataSetReportes.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableusp_PolizaTotalByFechas = new usp_PolizaTotalByFechasDataTable();
            base.Tables.Add(this.tableusp_PolizaTotalByFechas);
            this.tableusp_PolizaByIdUsuario = new usp_PolizaByIdUsuarioDataTable();
            base.Tables.Add(this.tableusp_PolizaByIdUsuario);
            this.tableusp_SELECT_VentasByDia = new usp_SELECT_VentasByDiaDataTable();
            base.Tables.Add(this.tableusp_SELECT_VentasByDia);
            this.tableusp_ObtenerFacturaReporte = new usp_ObtenerFacturaReporteDataTable();
            base.Tables.Add(this.tableusp_ObtenerFacturaReporte);
        }
References Capa.UI.Reporte.DataSetReportes.SchemaSerializationMode.
Referenced by Capa.UI.Reporte.DataSetReportes.DataSetReportes(), and Capa.UI.Reporte.DataSetReportes.InitializeDerivedDataSet().
InitializeDerivedDataSet()
override void Capa.UI.Reporte.DataSetReportes.InitializeDerivedDataSet () protected
Definition at line 166 of file DataSetReportes.Designer.cs.
{
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
References Capa.UI.Reporte.DataSetReportes.InitClass().
InitVars() [1/2]
void Capa.UI.Reporte.DataSetReportes.InitVars () package
Definition at line 238 of file DataSetReportes.Designer.cs.
{
            this.InitVars(true);
        }
References Capa.UI.Reporte.DataSetReportes.InitVars().
Referenced by Capa.UI.Reporte.DataSetReportes.DataSetReportes(), Capa.UI.Reporte.DataSetReportes.InitVars(), Capa.UI.Reporte.DataSetReportes.ReadXmlSerializable(), and Capa.UI.Reporte.DataSetReportes.SchemaChanged().
InitVars() [2/2]
void Capa.UI.Reporte.DataSetReportes.InitVars (bool initTable) package
Definition at line 244 of file DataSetReportes.Designer.cs.
{
            this.tableusp_PolizaTotalByFechas = ((usp_PolizaTotalByFechasDataTable)(base.Tables["usp_PolizaTotalByFechas"]));
            if ((initTable == true)) {
                if ((this.tableusp_PolizaTotalByFechas != null)) {
                    this.tableusp_PolizaTotalByFechas.InitVars();
                }
            }
            this.tableusp_PolizaByIdUsuario = ((usp_PolizaByIdUsuarioDataTable)(base.Tables["usp_PolizaByIdUsuario"]));
            if ((initTable == true)) {
                if ((this.tableusp_PolizaByIdUsuario != null)) {
                    this.tableusp_PolizaByIdUsuario.InitVars();
                }
            }
            this.tableusp_SELECT_VentasByDia = ((usp_SELECT_VentasByDiaDataTable)(base.Tables["usp_SELECT_VentasByDia"]));
            if ((initTable == true)) {
                if ((this.tableusp_SELECT_VentasByDia != null)) {
                    this.tableusp_SELECT_VentasByDia.InitVars();
                }
            }
            this.tableusp_ObtenerFacturaReporte = ((usp_ObtenerFacturaReporteDataTable)(base.Tables["usp_ObtenerFacturaReporte"]));
            if ((initTable == true)) {
                if ((this.tableusp_ObtenerFacturaReporte != null)) {
                    this.tableusp_ObtenerFacturaReporte.InitVars();
                }
            }
        }
References Capa.UI.Reporte.DataSetReportes.usp_PolizaTotalByFechasDataTable.InitVars(), Capa.UI.Reporte.DataSetReportes.usp_PolizaByIdUsuarioDataTable.InitVars(), Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.InitVars(), and Capa.UI.Reporte.DataSetReportes.usp_ObtenerFacturaReporteDataTable.InitVars().
ReadXmlSerializable()
override void Capa.UI.Reporte.DataSetReportes.ReadXmlSerializable (global::System.Xml.XmlReader reader) protected
Definition at line 195 of file DataSetReportes.Designer.cs.
{
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["usp_PolizaTotalByFechas"] != null)) {
                    base.Tables.Add(new usp_PolizaTotalByFechasDataTable(ds.Tables["usp_PolizaTotalByFechas"]));
                }
                if ((ds.Tables["usp_PolizaByIdUsuario"] != null)) {
                    base.Tables.Add(new usp_PolizaByIdUsuarioDataTable(ds.Tables["usp_PolizaByIdUsuario"]));
                }
                if ((ds.Tables["usp_SELECT_VentasByDia"] != null)) {
                    base.Tables.Add(new usp_SELECT_VentasByDiaDataTable(ds.Tables["usp_SELECT_VentasByDia"]));
                }
                if ((ds.Tables["usp_ObtenerFacturaReporte"] != null)) {
                    base.Tables.Add(new usp_ObtenerFacturaReporteDataTable(ds.Tables["usp_ObtenerFacturaReporte"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
References Capa.UI.Reporte.DataSetReportes.InitVars().
SchemaChanged()
void Capa.UI.Reporte.DataSetReportes.SchemaChanged (object sender, global::System.ComponentModel.CollectionChangeEventArgs e) private
Definition at line 315 of file DataSetReportes.Designer.cs.
{
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
References Capa.UI.Reporte.DataSetReportes.InitVars().
Referenced by Capa.UI.Reporte.DataSetReportes.DataSetReportes().
ShouldSerializeRelations()
override bool Capa.UI.Reporte.DataSetReportes.ShouldSerializeRelations () protected
Definition at line 189 of file DataSetReportes.Designer.cs.
{
            return false;
        }
ShouldSerializeTables()
override bool Capa.UI.Reporte.DataSetReportes.ShouldSerializeTables () protected
Definition at line 183 of file DataSetReportes.Designer.cs.
{
            return false;
        }
ShouldSerializeusp_ObtenerFacturaReporte()
bool Capa.UI.Reporte.DataSetReportes.ShouldSerializeusp_ObtenerFacturaReporte () private
Definition at line 309 of file DataSetReportes.Designer.cs.
{
            return false;
        }
ShouldSerializeusp_PolizaByIdUsuario()
bool Capa.UI.Reporte.DataSetReportes.ShouldSerializeusp_PolizaByIdUsuario () private
Definition at line 297 of file DataSetReportes.Designer.cs.
{
            return false;
        }
ShouldSerializeusp_PolizaTotalByFechas()
bool Capa.UI.Reporte.DataSetReportes.ShouldSerializeusp_PolizaTotalByFechas () private
Definition at line 291 of file DataSetReportes.Designer.cs.
{
            return false;
        }
ShouldSerializeusp_SELECT_VentasByDia()
bool Capa.UI.Reporte.DataSetReportes.ShouldSerializeusp_SELECT_VentasByDia () private
Definition at line 303 of file DataSetReportes.Designer.cs.
{
            return false;
        }
usp_ObtenerFacturaReporteRowChangeEventHandler()
delegate void Capa.UI.Reporte.DataSetReportes.usp_ObtenerFacturaReporteRowChangeEventHandler (object sender, usp_ObtenerFacturaReporteRowChangeEvent e)
usp_PolizaByIdUsuarioRowChangeEventHandler()
delegate void Capa.UI.Reporte.DataSetReportes.usp_PolizaByIdUsuarioRowChangeEventHandler (object sender, usp_PolizaByIdUsuarioRowChangeEvent e)
usp_PolizaTotalByFechasRowChangeEventHandler()
delegate void Capa.UI.Reporte.DataSetReportes.usp_PolizaTotalByFechasRowChangeEventHandler (object sender, usp_PolizaTotalByFechasRowChangeEvent e)
usp_SELECT_VentasByDiaRowChangeEventHandler()
delegate void Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaRowChangeEventHandler (object sender, usp_SELECT_VentasByDiaRowChangeEvent e)
Member Data Documentation
_schemaSerializationMode
global.System.Data.SchemaSerializationMode Capa.UI.Reporte.DataSetReportes._schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema private
Definition at line 35 of file DataSetReportes.Designer.cs.
tableusp_ObtenerFacturaReporte
usp_ObtenerFacturaReporteDataTable Capa.UI.Reporte.DataSetReportes.tableusp_ObtenerFacturaReporte private
Definition at line 33 of file DataSetReportes.Designer.cs.
tableusp_PolizaByIdUsuario
usp_PolizaByIdUsuarioDataTable Capa.UI.Reporte.DataSetReportes.tableusp_PolizaByIdUsuario private
Definition at line 29 of file DataSetReportes.Designer.cs.
tableusp_PolizaTotalByFechas
usp_PolizaTotalByFechasDataTable Capa.UI.Reporte.DataSetReportes.tableusp_PolizaTotalByFechas private
Definition at line 27 of file DataSetReportes.Designer.cs.
tableusp_SELECT_VentasByDia
usp_SELECT_VentasByDiaDataTable Capa.UI.Reporte.DataSetReportes.tableusp_SELECT_VentasByDia private
Definition at line 31 of file DataSetReportes.Designer.cs.
Property Documentation
Relations
new global.System.Data.DataRelationCollection Capa.UI.Reporte.DataSetReportes.Relations get
Definition at line 158 of file DataSetReportes.Designer.cs.
{
            get {
                return base.Relations;
            }
        }
Referenced by Capa.UI.Reporte.DataSetReportes.DataSetReportes().
SchemaSerializationMode
override global.System.Data.SchemaSerializationMode Capa.UI.Reporte.DataSetReportes.SchemaSerializationMode get set
Definition at line 137 of file DataSetReportes.Designer.cs.
{
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
Referenced by Capa.UI.Reporte.DataSetReportes.Clone(), Capa.UI.Reporte.DataSetReportes.InitClass(), Capa.UI.Reporte.frmRptFactura.InitializeComponent(), Capa.UI.Reporte.frmRptPolizaByIdUsuario.InitializeComponent(), and Capa.UI.Reporte.frmRptVentasByDia.InitializeComponent().
Tables
new global.System.Data.DataTableCollection Capa.UI.Reporte.DataSetReportes.Tables get
Definition at line 149 of file DataSetReportes.Designer.cs.
{
            get {
                return base.Tables;
            }
        }
Referenced by Capa.UI.Reporte.DataSetReportes.DataSetReportes().
usp_ObtenerFacturaReporte
usp_ObtenerFacturaReporteDataTable Capa.UI.Reporte.DataSetReportes.usp_ObtenerFacturaReporte get
Definition at line 127 of file DataSetReportes.Designer.cs.
{
            get {
                return this.tableusp_ObtenerFacturaReporte;
            }
        }
Referenced by Capa.UI.Reporte.frmRptFactura.frmRptFactura_Load().
usp_PolizaByIdUsuario
usp_PolizaByIdUsuarioDataTable Capa.UI.Reporte.DataSetReportes.usp_PolizaByIdUsuario get
Definition at line 107 of file DataSetReportes.Designer.cs.
{
            get {
                return this.tableusp_PolizaByIdUsuario;
            }
        }
Referenced by Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripBtnBuscar_Click().
usp_PolizaTotalByFechas
usp_PolizaTotalByFechasDataTable Capa.UI.Reporte.DataSetReportes.usp_PolizaTotalByFechas get
Definition at line 97 of file DataSetReportes.Designer.cs.
{
            get {
                return this.tableusp_PolizaTotalByFechas;
            }
        }
usp_SELECT_VentasByDia
usp_SELECT_VentasByDiaDataTable Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDia get
Definition at line 117 of file DataSetReportes.Designer.cs.
{
            get {
                return this.tableusp_SELECT_VentasByDia;
            }
        }
Referenced by Capa.UI.Reporte.frmRptVentasByDia.frmRptVentasByDia_Load().
The documentation for this class was generated from the following files:
Capa.UI/Reporte/DataSetReportes.cs
Capa.UI/Reporte/DataSetReportes.Designer.cs