Proyecto Autos Seguros: DAL.PaisDAL Class Reference
DAL.PaisDAL Class Reference
Public Member Functions
List< Pais > ObtenerPaises ()
Pais ObtenerPorId (int id)
Pais ObtenerPorId (int id)
List< Pais > ObtenerPaises ()
Detailed Description
Definition at line 13 of file PaisDAL.cs.
Member Function Documentation
ObtenerPaises()
List< Pais > DAL.PaisDAL.ObtenerPaises ()
Implements Interfaces.IPaisDAL.
Definition at line 15 of file PaisDAL.cs.
        {
            List<Pais> lista = new List<Pais>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_Pais_All";
                IDataReader reader = db.ExecuteReader(comando);
                while (reader.Read())
                {
                    Pais pais = new Pais();
                    pais.Id = (int)reader["Id"];
                    pais.Nombre = reader["Nombre"].ToString();
                    lista.Add(pais);
                }
            }
            return lista;
        }
References FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteReader(), Entities.Pais.Id, and Entities.Pais.Nombre.
ObtenerPorId()
Pais DAL.PaisDAL.ObtenerPorId (int id)
Implements Interfaces.IPaisDAL.
Definition at line 39 of file PaisDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_Pais_ByID";
                comando.Parameters.AddWithValue("@Id", id);
                IDataReader reader = db.ExecuteReader(comando);
                while (reader.Read())
                {
                    Pais pais = new Pais();
                    pais.Id = (int)reader["Id"];
                    pais.Nombre = reader["Nombre"].ToString();
                    return pais;
                }
            }
            return null;
        }
References FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteReader(), Entities.Pais.Id, and Entities.Pais.Nombre.
The documentation for this class was generated from the following file:
DAL/PaisDAL.cs