Proyecto Autos Seguros: DAL.TipoUsuarioDAL Class Reference
DAL.TipoUsuarioDAL Class Reference
Public Member Functions
TipoUsuario ObtenerPorId (int id)
List< TipoUsuario > ObtenerTiposUsuarios ()
TipoUsuario ObtenerPorId (int id)
List< TipoUsuario > ObtenerTiposUsuarios ()
Detailed Description
Definition at line 13 of file TipoUsuarioDAL.cs.
Member Function Documentation
ObtenerPorId()
TipoUsuario DAL.TipoUsuarioDAL.ObtenerPorId (int id)
Implements Interfaces.ITipoUsuarioDAL.
Definition at line 15 of file TipoUsuarioDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_TipoUsuario_ByID";
                comando.Parameters.AddWithValue("@Id", id);
                IDataReader reader = db.ExecuteReader(comando);
                while (reader.Read())
                {
                    TipoUsuario tipoUsuario = new TipoUsuario();
                    tipoUsuario.Id = (int)reader["Id"];
                    tipoUsuario.Descripcion = reader["Descripcion"].ToString();
                    return tipoUsuario;
                }
            }
            return null;
        }
References FactoryDatabase.CreateDefaultDataBase(), Entities.TipoUsuario.Descripcion, IDataBase.ExecuteReader(), and Entities.TipoUsuario.Id.
ObtenerTiposUsuarios()
List< TipoUsuario > DAL.TipoUsuarioDAL.ObtenerTiposUsuarios ()
Implements Interfaces.ITipoUsuarioDAL.
Definition at line 39 of file TipoUsuarioDAL.cs.
        {
            List<TipoUsuario> lista = new List<TipoUsuario>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_TipoUsuario_All";
                IDataReader reader = db.ExecuteReader(comando);
                while (reader.Read())
                {
                    TipoUsuario tipoUsuario = new TipoUsuario();
                    tipoUsuario.Id = (int)reader["Id"];
                    tipoUsuario.Descripcion = reader["Descripcion"].ToString();
                    lista.Add(tipoUsuario);
                }
            }
            return lista;
        }
References FactoryDatabase.CreateDefaultDataBase(), Entities.TipoUsuario.Descripcion, IDataBase.ExecuteReader(), and Entities.TipoUsuario.Id.
The documentation for this class was generated from the following file:
DAL/TipoUsuarioDAL.cs