Proyecto Autos Seguros: BLL.TipoPolizaBLL Class Reference
BLL.TipoPolizaBLL Class Reference
Public Member Functions
void Eliminar (int id)
void Insertar (TipoPoliza tipoPoliza)
TipoPoliza ObtenerPorId (int id)
List< TipoPoliza > ObtenerTipoPolizas ()
void Insertar (TipoPoliza tipoPoliza)
void Eliminar (int id)
List< TipoPoliza > ObtenerTipoPolizas ()
TipoPoliza ObtenerPorId (int id)
Detailed Description
Definition at line 12 of file TipoPolizaBLL.cs.
Member Function Documentation
Eliminar()
void BLL.TipoPolizaBLL.Eliminar (int id)
Implements Interfaces.ITipoPolizaBLL.
Definition at line 16 of file TipoPolizaBLL.cs.
        {
            ITipoPolizaDAL logica = new TipoPolizaDAL();
            logica.Eliminar(id);
        }
References Interfaces.ITipoPolizaDAL.Eliminar().
Insertar()
void BLL.TipoPolizaBLL.Insertar (TipoPoliza tipoPoliza)
Implements Interfaces.ITipoPolizaBLL.
Definition at line 22 of file TipoPolizaBLL.cs.
        {
            ITipoPolizaDAL logica = new TipoPolizaDAL();
            if (logica.ObtenerPorId(tipoPoliza.Id) == null)
            {
                logica.Insertar(tipoPoliza);
            }
            else
            {
                logica.Actualizar(tipoPoliza);
            }
        }
References Interfaces.ITipoPolizaDAL.Actualizar(), Entities.TipoPoliza.Id, Interfaces.ITipoPolizaDAL.Insertar(), and Interfaces.ITipoPolizaDAL.ObtenerPorId().
ObtenerPorId()
TipoPoliza BLL.TipoPolizaBLL.ObtenerPorId (int id)
Implements Interfaces.ITipoPolizaBLL.
Definition at line 36 of file TipoPolizaBLL.cs.
        {
            ITipoPolizaDAL logica = new TipoPolizaDAL();
            return logica.ObtenerPorId(id);
        }
References Interfaces.ITipoPolizaDAL.ObtenerPorId().
ObtenerTipoPolizas()
List< TipoPoliza > BLL.TipoPolizaBLL.ObtenerTipoPolizas ()
Implements Interfaces.ITipoPolizaBLL.
Definition at line 42 of file TipoPolizaBLL.cs.
        {
            ITipoPolizaDAL logica = new TipoPolizaDAL();
            return logica.ObtenerTipoPolizas();
        }
References Interfaces.ITipoPolizaDAL.ObtenerTipoPolizas().
The documentation for this class was generated from the following file:
BLL/TipoPolizaBLL.cs