Proyecto Autos Seguros: DAL.TipoPolizaDAL Class Reference
DAL.TipoPolizaDAL Class Reference
Public Member Functions
List< TipoPoliza > ObtenerTipoPolizas ()
TipoPoliza ObtenerPorId (int id)
void Insertar (TipoPoliza tipoPoliza)
void Actualizar (TipoPoliza tipoPoliza)
void Eliminar (int id)
void Insertar (TipoPoliza tipoPoliza)
void Actualizar (TipoPoliza tipoPoliza)
void Eliminar (int id)
List< TipoPoliza > ObtenerTipoPolizas ()
TipoPoliza ObtenerPorId (int id)
Detailed Description
Definition at line 13 of file TipoPolizaDAL.cs.
Member Function Documentation
Actualizar()
void DAL.TipoPolizaDAL.Actualizar (TipoPoliza tipoPoliza)
Implements Interfaces.ITipoPolizaDAL.
Definition at line 78 of file TipoPolizaDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_UPDATE_TipoPoliza";
                comando.Parameters.AddWithValue("@Id", tipoPoliza.Id);
                comando.Parameters.AddWithValue("@Descripcion", tipoPoliza.Descripcion);
                comando.Parameters.AddWithValue("@Costo", tipoPoliza.Costo);
                db.ExecuteNonQuery(comando);
            }
        }
References Entities.TipoPoliza.Costo, FactoryDatabase.CreateDefaultDataBase(), Entities.TipoPoliza.Descripcion, IDataBase.ExecuteNonQuery(), and Entities.TipoPoliza.Id.
Eliminar()
void DAL.TipoPolizaDAL.Eliminar (int id)
Implements Interfaces.ITipoPolizaDAL.
Definition at line 93 of file TipoPolizaDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_DELETE_TipoPoliza_ByID";
                comando.Parameters.AddWithValue("@Id", id);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), and IDataBase.ExecuteNonQuery().
Insertar()
void DAL.TipoPolizaDAL.Insertar (TipoPoliza tipoPoliza)
Implements Interfaces.ITipoPolizaDAL.
Definition at line 63 of file TipoPolizaDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_INSERT_TipoPoliza";
                comando.Parameters.AddWithValue("@Id", tipoPoliza.Id);
                comando.Parameters.AddWithValue("@Descripcion", tipoPoliza.Descripcion);
                comando.Parameters.AddWithValue("@Costo", tipoPoliza.Costo);
                db.ExecuteNonQuery(comando);
            }
        }
References Entities.TipoPoliza.Costo, FactoryDatabase.CreateDefaultDataBase(), Entities.TipoPoliza.Descripcion, IDataBase.ExecuteNonQuery(), and Entities.TipoPoliza.Id.
ObtenerPorId()
TipoPoliza DAL.TipoPolizaDAL.ObtenerPorId (int id)
Implements Interfaces.ITipoPolizaDAL.
Definition at line 39 of file TipoPolizaDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_TipoPoliza_ByID";
                comando.Parameters.AddWithValue("@Id", id);
                IDataReader reader = db.ExecuteReader(comando);
                while (reader.Read())
                {
                    TipoPoliza tipoPoliza = new TipoPoliza();
                    tipoPoliza.Id = (int)reader["Id"];
                    tipoPoliza.Descripcion = reader["Descripcion"].ToString();
                    tipoPoliza.Costo = (decimal)reader["Costo"];
                    return tipoPoliza;
                }
            }
            return null;
        }
References Entities.TipoPoliza.Costo, FactoryDatabase.CreateDefaultDataBase(), Entities.TipoPoliza.Descripcion, IDataBase.ExecuteReader(), and Entities.TipoPoliza.Id.
ObtenerTipoPolizas()
List< TipoPoliza > DAL.TipoPolizaDAL.ObtenerTipoPolizas ()
Implements Interfaces.ITipoPolizaDAL.
Definition at line 15 of file TipoPolizaDAL.cs.
        {
            List<TipoPoliza> lista = new List<TipoPoliza>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_TipoPoliza_All";
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    TipoPoliza tipoPoliza = new TipoPoliza();
                    tipoPoliza.Id = (int)dr["Id"];
                    tipoPoliza.Descripcion = dr["Descripcion"].ToString();
                    tipoPoliza.Costo =(decimal) dr["Costo"];
                    lista.Add(tipoPoliza);
                }
            }
            return lista;
        }
References Entities.TipoPoliza.Costo, FactoryDatabase.CreateDefaultDataBase(), Entities.TipoPoliza.Descripcion, IDataBase.ExecuteDataSet(), and Entities.TipoPoliza.Id.
The documentation for this class was generated from the following file:
DAL/TipoPolizaDAL.cs