Proyecto Autos Seguros: DAL.DetallePolizaDAL Class Reference
DAL.DetallePolizaDAL Class Reference
Public Member Functions
void Actualizar (DetallePoliza detallePoliza)
void Eliminar (int idTipoPoliza)
void EliminarByPolCob (int idTipoPoliza, int idCobertura)
void Insertar (DetallePoliza detallePoliza)
DetallePoliza SeleccionarPorId (int idTipoPoliza, int idCobertura)
List< DetallePoliza > SeleccionarTodas ()
void Insertar (DetallePoliza detallePoliza)
void Actualizar (DetallePoliza detallePoliza)
void Eliminar (int idTipoPoliza)
void EliminarByPolCob (int idTipoPoliza, int idCobertura)
List< DetallePoliza > SeleccionarTodas ()
DetallePoliza SeleccionarPorId (int idTipoPoliza, int idCobertura)
Detailed Description
Definition at line 13 of file DetallePolizaDAL.cs.
Member Function Documentation
Actualizar()
void DAL.DetallePolizaDAL.Actualizar (DetallePoliza detallePoliza)
Implements Interfaces.IDetallePolizaDAL.
Definition at line 15 of file DetallePolizaDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_UPDATE_DetallePoliza";
                comando.Parameters.AddWithValue("@IdPoliza", detallePoliza.IdTipoPoliza);
                comando.Parameters.AddWithValue("@IdCobertura", detallePoliza.IdCobertura);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteNonQuery(), Entities.DetallePoliza.IdCobertura, and Entities.DetallePoliza.IdTipoPoliza.
Eliminar()
void DAL.DetallePolizaDAL.Eliminar (int idTipoPoliza)
Implements Interfaces.IDetallePolizaDAL.
Definition at line 30 of file DetallePolizaDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_DELETE_DetallePolizaByIdTipoPoliza";
                comando.Parameters.AddWithValue("@IdTipoPoliza", idTipoPoliza);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), and IDataBase.ExecuteNonQuery().
EliminarByPolCob()
void DAL.DetallePolizaDAL.EliminarByPolCob (int idTipoPoliza, int idCobertura)
Implements Interfaces.IDetallePolizaDAL.
Definition at line 43 of file DetallePolizaDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_DELETE_DetallePoliza_ByIDCobPol";
                comando.Parameters.AddWithValue("@IdTipoPoliza", idTipoPoliza);
                comando.Parameters.AddWithValue("@IdCobertura", idCobertura);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), and IDataBase.ExecuteNonQuery().
Insertar()
void DAL.DetallePolizaDAL.Insertar (DetallePoliza detallePoliza)
Implements Interfaces.IDetallePolizaDAL.
Definition at line 56 of file DetallePolizaDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_INSERT_DetallePoliza";
                comando.Parameters.AddWithValue("@IdTipoPoliza", detallePoliza.IdTipoPoliza);
                comando.Parameters.AddWithValue("@IdCobertura", detallePoliza.IdCobertura);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteNonQuery(), Entities.DetallePoliza.IdCobertura, and Entities.DetallePoliza.IdTipoPoliza.
SeleccionarPorId()
DetallePoliza DAL.DetallePolizaDAL.SeleccionarPorId (int idTipoPoliza, int idCobertura)
Implements Interfaces.IDetallePolizaDAL.
Definition at line 71 of file DetallePolizaDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_DetallePoliza_ByID";
                comando.Parameters.AddWithValue("@IdTipoPoliza", idTipoPoliza);
                comando.Parameters.AddWithValue("@IdCobertura", idCobertura);
                IDataReader reader = db.ExecuteReader(comando);
                while (reader.Read())
                {
                    DetallePoliza detallePoliza = new DetallePoliza();
                    detallePoliza.IdTipoPoliza = (int)reader["IdTipoPoliza"];
                    detallePoliza.IdCobertura = (int)reader["IdCobertura"];
                    return detallePoliza;
                }
            }
            return null;
        }
References FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteReader(), Entities.DetallePoliza.IdCobertura, and Entities.DetallePoliza.IdTipoPoliza.
SeleccionarTodas()
List< DetallePoliza > DAL.DetallePolizaDAL.SeleccionarTodas ()
Implements Interfaces.IDetallePolizaDAL.
Definition at line 97 of file DetallePolizaDAL.cs.
        {
            List<DetallePoliza> lista = new List<DetallePoliza>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_DetallePoliza_All";
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    DetallePoliza detallePoliza = new DetallePoliza();
                    detallePoliza.IdTipoPoliza = (int)dr["IdTipoPoliza"];
                    detallePoliza.IdCobertura = (int)dr["IdCobertura"];
                    lista.Add(detallePoliza);
                }
            }
            return lista;
        }
References FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteDataSet(), Entities.DetallePoliza.IdCobertura, and Entities.DetallePoliza.IdTipoPoliza.
The documentation for this class was generated from the following file:
DAL/DetallePolizaDAL.cs