Proyecto Autos Seguros: BLL.IVABLL Class Reference
BLL.IVABLL Class Reference
Public Member Functions
void Actualizar (IVA iva)
void Eliminar (int id)
void Insertar (IVA iva)
IVA SeleccionarPorId (int id)
IVA SeleccionarReciente ()
List< IVA > SeleccionarTodas ()
void Actualizar (IVA iva)
void Eliminar (int id)
void Insertar (IVA iva)
List< IVA > SeleccionarTodas ()
IVA SeleccionarPorId (int id)
IVA SeleccionarReciente ()
Detailed Description
Definition at line 12 of file IVABLL.cs.
Member Function Documentation
Actualizar()
void BLL.IVABLL.Actualizar (IVA iva)
Implements Interfaces.I_IVA_BLL.
Definition at line 14 of file IVABLL.cs.
        {
            I_IVA_DAL logica = new IVADAL();
            logica.Actualizar(iva);
        }
References Interfaces.I_IVA_DAL.Actualizar().
Eliminar()
void BLL.IVABLL.Eliminar (int id)
Implements Interfaces.I_IVA_BLL.
Definition at line 20 of file IVABLL.cs.
        {
            I_IVA_DAL logica = new IVADAL();
            logica.Eliminar(id);
        }
References Interfaces.I_IVA_DAL.Eliminar().
Insertar()
void BLL.IVABLL.Insertar (IVA iva)
Implements Interfaces.I_IVA_BLL.
Definition at line 26 of file IVABLL.cs.
        {
            I_IVA_DAL logica = new IVADAL();
            if (logica.SeleccionarPorId(iva.Id) == null)
            {
                logica.Insertar(iva);
            }
            else
            {
                logica.Actualizar(iva);
            }
        }
References Interfaces.I_IVA_DAL.Actualizar(), Entities.IVA.Id, Interfaces.I_IVA_DAL.Insertar(), and Interfaces.I_IVA_DAL.SeleccionarPorId().
SeleccionarPorId()
IVA BLL.IVABLL.SeleccionarPorId (int id)
Implements Interfaces.I_IVA_BLL.
Definition at line 40 of file IVABLL.cs.
        {
            I_IVA_DAL logica = new IVADAL();
            return logica.SeleccionarPorId(id);
        }
References Interfaces.I_IVA_DAL.SeleccionarPorId().
SeleccionarReciente()
IVA BLL.IVABLL.SeleccionarReciente ()
Implements Interfaces.I_IVA_BLL.
Definition at line 46 of file IVABLL.cs.
        {
            I_IVA_DAL logica = new IVADAL();
            return logica.SeleccionarReciente();
        }
References Interfaces.I_IVA_DAL.SeleccionarReciente().
SeleccionarTodas()
List< IVA > BLL.IVABLL.SeleccionarTodas ()
Implements Interfaces.I_IVA_BLL.
Definition at line 52 of file IVABLL.cs.
        {
            I_IVA_DAL logica = new IVADAL();
            return logica.SeleccionarTodas();
        }
References Interfaces.I_IVA_DAL.SeleccionarTodas().
The documentation for this class was generated from the following file:
BLL/IVABLL.cs