Proyecto Autos Seguros: Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable Class Reference
Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable Class Reference
Represents the strongly named DataTable class. /summary>
Public Member Functions
usp_SELECT_VentasByDiaDataTable ()
void Addusp_SELECT_VentasByDiaRow (usp_SELECT_VentasByDiaRow row)
usp_SELECT_VentasByDiaRow Addusp_SELECT_VentasByDiaRow (System.DateTime fecha, decimal Total)
override global::System.Data.DataTable Clone ()
usp_SELECT_VentasByDiaRow Newusp_SELECT_VentasByDiaRow ()
void Removeusp_SELECT_VentasByDiaRow (usp_SELECT_VentasByDiaRow row)
Static Public Member Functions
static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema (global::System.Xml.Schema.XmlSchemaSet xs)
Protected Member Functions
usp_SELECT_VentasByDiaDataTable (global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context)
override global::System.Data.DataTable CreateInstance ()
override global::System.Data.DataRow NewRowFromBuilder (global::System.Data.DataRowBuilder builder)
override global::System.Type GetRowType ()
override void OnRowChanged (global::System.Data.DataRowChangeEventArgs e)
override void OnRowChanging (global::System.Data.DataRowChangeEventArgs e)
override void OnRowDeleted (global::System.Data.DataRowChangeEventArgs e)
override void OnRowDeleting (global::System.Data.DataRowChangeEventArgs e)
Package Functions
usp_SELECT_VentasByDiaDataTable (global::System.Data.DataTable table)
void InitVars ()
Properties
global::System.Data.DataColumn fechaColumn [get]
global::System.Data.DataColumn TotalColumn [get]
int Count [get]
usp_SELECT_VentasByDiaRow this[int index] [get]
Events
usp_SELECT_VentasByDiaRowChangeEventHandler usp_SELECT_VentasByDiaRowChanging
usp_SELECT_VentasByDiaRowChangeEventHandler usp_SELECT_VentasByDiaRowChanged
usp_SELECT_VentasByDiaRowChangeEventHandler usp_SELECT_VentasByDiaRowDeleting
usp_SELECT_VentasByDiaRowChangeEventHandler usp_SELECT_VentasByDiaRowDeleted
Private Member Functions
void InitClass ()
Private Attributes
global::System.Data.DataColumn columnfecha
global::System.Data.DataColumn columnTotal
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 1095 of file DataSetReportes.Designer.cs.
Constructor & Destructor Documentation
usp_SELECT_VentasByDiaDataTable() [1/3]
Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.usp_SELECT_VentasByDiaDataTable ()
Definition at line 1103 of file DataSetReportes.Designer.cs.
{
                this.TableName = "usp_SELECT_VentasByDia";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
References Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.InitClass().
Referenced by Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.Clone(), and Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.CreateInstance().
usp_SELECT_VentasByDiaDataTable() [2/3]
Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.usp_SELECT_VentasByDiaDataTable (global::System.Data.DataTable table) package
Definition at line 1112 of file DataSetReportes.Designer.cs.
{
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
usp_SELECT_VentasByDiaDataTable() [3/3]
Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.usp_SELECT_VentasByDiaDataTable (global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) protected
Definition at line 1129 of file DataSetReportes.Designer.cs.
                                                                                                                                                                              :
                    base(info, context) {
                this.InitVars();
            }
References Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.InitVars().
Member Function Documentation
Addusp_SELECT_VentasByDiaRow() [1/2]
usp_SELECT_VentasByDiaRow Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.Addusp_SELECT_VentasByDiaRow (System.DateTime fecha, decimal Total)
Definition at line 1187 of file DataSetReportes.Designer.cs.
{
                usp_SELECT_VentasByDiaRow rowusp_SELECT_VentasByDiaRow = ((usp_SELECT_VentasByDiaRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        fecha,
                        Total};
                rowusp_SELECT_VentasByDiaRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowusp_SELECT_VentasByDiaRow);
                return rowusp_SELECT_VentasByDiaRow;
            }
Addusp_SELECT_VentasByDiaRow() [2/2]
void Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.Addusp_SELECT_VentasByDiaRow (usp_SELECT_VentasByDiaRow row)
Definition at line 1181 of file DataSetReportes.Designer.cs.
{
                this.Rows.Add(row);
            }
Clone()
override global.System.Data.DataTable Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.Clone ()
Definition at line 1199 of file DataSetReportes.Designer.cs.
{
                usp_SELECT_VentasByDiaDataTable cln = ((usp_SELECT_VentasByDiaDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
References Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.InitVars(), and Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.usp_SELECT_VentasByDiaDataTable().
CreateInstance()
override global.System.Data.DataTable Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.CreateInstance () protected
Definition at line 1207 of file DataSetReportes.Designer.cs.
{
                return new usp_SELECT_VentasByDiaDataTable();
            }
References Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.usp_SELECT_VentasByDiaDataTable().
GetRowType()
override global.System.Type Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.GetRowType () protected
Definition at line 1242 of file DataSetReportes.Designer.cs.
{
                return typeof(usp_SELECT_VentasByDiaRow);
            }
GetTypedTableSchema()
static global.System.Xml.Schema.XmlSchemaComplexType Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.GetTypedTableSchema (global::System.Xml.Schema.XmlSchemaSet xs) static
Definition at line 1290 of file DataSetReportes.Designer.cs.
{
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DataSetReportes ds = new DataSetReportes();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "usp_SELECT_VentasByDiaDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length)
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
References Capa.UI.Reporte.DataSetReportes.DataSetReportes().
InitClass()
void Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.InitClass () private
Definition at line 1220 of file DataSetReportes.Designer.cs.
{
                this.columnfecha = new global::System.Data.DataColumn("fecha", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfecha);
                this.columnTotal = new global::System.Data.DataColumn("Total", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTotal);
                this.columnTotal.ReadOnly = true;
            }
References Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.columnfecha, and Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.columnTotal.
Referenced by Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.usp_SELECT_VentasByDiaDataTable().
InitVars()
void Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.InitVars () package
Definition at line 1213 of file DataSetReportes.Designer.cs.
{
                this.columnfecha = base.Columns["fecha"];
                this.columnTotal = base.Columns["Total"];
            }
References Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.columnfecha, and Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.columnTotal.
Referenced by Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.Clone(), Capa.UI.Reporte.DataSetReportes.InitVars(), and Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.usp_SELECT_VentasByDiaDataTable().
NewRowFromBuilder()
override global.System.Data.DataRow Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.NewRowFromBuilder (global::System.Data.DataRowBuilder builder) protected
Definition at line 1236 of file DataSetReportes.Designer.cs.
{
                return new usp_SELECT_VentasByDiaRow(builder);
            }
Newusp_SELECT_VentasByDiaRow()
usp_SELECT_VentasByDiaRow Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.Newusp_SELECT_VentasByDiaRow ()
Definition at line 1230 of file DataSetReportes.Designer.cs.
{
                return ((usp_SELECT_VentasByDiaRow)(this.NewRow()));
            }
OnRowChanged()
override void Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.OnRowChanged (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 1248 of file DataSetReportes.Designer.cs.
{
                base.OnRowChanged(e);
                if ((this.usp_SELECT_VentasByDiaRowChanged != null)) {
                    this.usp_SELECT_VentasByDiaRowChanged(this, new usp_SELECT_VentasByDiaRowChangeEvent(((usp_SELECT_VentasByDiaRow)(e.Row)), e.Action));
                }
            }
References Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.usp_SELECT_VentasByDiaRowChanged.
OnRowChanging()
override void Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.OnRowChanging (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 1257 of file DataSetReportes.Designer.cs.
{
                base.OnRowChanging(e);
                if ((this.usp_SELECT_VentasByDiaRowChanging != null)) {
                    this.usp_SELECT_VentasByDiaRowChanging(this, new usp_SELECT_VentasByDiaRowChangeEvent(((usp_SELECT_VentasByDiaRow)(e.Row)), e.Action));
                }
            }
References Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.usp_SELECT_VentasByDiaRowChanging.
OnRowDeleted()
override void Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.OnRowDeleted (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 1266 of file DataSetReportes.Designer.cs.
{
                base.OnRowDeleted(e);
                if ((this.usp_SELECT_VentasByDiaRowDeleted != null)) {
                    this.usp_SELECT_VentasByDiaRowDeleted(this, new usp_SELECT_VentasByDiaRowChangeEvent(((usp_SELECT_VentasByDiaRow)(e.Row)), e.Action));
                }
            }
References Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.usp_SELECT_VentasByDiaRowDeleted.
OnRowDeleting()
override void Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.OnRowDeleting (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 1275 of file DataSetReportes.Designer.cs.
{
                base.OnRowDeleting(e);
                if ((this.usp_SELECT_VentasByDiaRowDeleting != null)) {
                    this.usp_SELECT_VentasByDiaRowDeleting(this, new usp_SELECT_VentasByDiaRowChangeEvent(((usp_SELECT_VentasByDiaRow)(e.Row)), e.Action));
                }
            }
References Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.usp_SELECT_VentasByDiaRowDeleting.
Removeusp_SELECT_VentasByDiaRow()
void Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.Removeusp_SELECT_VentasByDiaRow (usp_SELECT_VentasByDiaRow row)
Definition at line 1284 of file DataSetReportes.Designer.cs.
{
                this.Rows.Remove(row);
            }
Member Data Documentation
columnfecha
global.System.Data.DataColumn Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.columnfecha private
Definition at line 1097 of file DataSetReportes.Designer.cs.
Referenced by Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.InitClass(), and Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.InitVars().
columnTotal
global.System.Data.DataColumn Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.columnTotal private
Definition at line 1099 of file DataSetReportes.Designer.cs.
Referenced by Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.InitClass(), and Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.InitVars().
Property Documentation
Count
int Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.Count get
Definition at line 1153 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.Rows.Count;
                }
            }
fechaColumn
global.System.Data.DataColumn Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.fechaColumn get
Definition at line 1136 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnfecha;
                }
            }
Referenced by Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaRow.IsfechaNull(), and Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaRow.SetfechaNull().
this[int index]
usp_SELECT_VentasByDiaRow Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.this[int index] get
Definition at line 1161 of file DataSetReportes.Designer.cs.
{
                get {
                    return ((usp_SELECT_VentasByDiaRow)(this.Rows[index]));
                }
            }
TotalColumn
global.System.Data.DataColumn Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.TotalColumn get
Definition at line 1144 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnTotal;
                }
            }
Referenced by Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaRow.IsTotalNull(), and Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaRow.SetTotalNull().
Event Documentation
usp_SELECT_VentasByDiaRowChanged
usp_SELECT_VentasByDiaRowChangeEventHandler Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.usp_SELECT_VentasByDiaRowChanged
Definition at line 1171 of file DataSetReportes.Designer.cs.
Referenced by Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.OnRowChanged().
usp_SELECT_VentasByDiaRowChanging
usp_SELECT_VentasByDiaRowChangeEventHandler Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.usp_SELECT_VentasByDiaRowChanging
Definition at line 1168 of file DataSetReportes.Designer.cs.
Referenced by Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.OnRowChanging().
usp_SELECT_VentasByDiaRowDeleted
usp_SELECT_VentasByDiaRowChangeEventHandler Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.usp_SELECT_VentasByDiaRowDeleted
Definition at line 1177 of file DataSetReportes.Designer.cs.
Referenced by Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.OnRowDeleted().
usp_SELECT_VentasByDiaRowDeleting
usp_SELECT_VentasByDiaRowChangeEventHandler Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.usp_SELECT_VentasByDiaRowDeleting
Definition at line 1174 of file DataSetReportes.Designer.cs.
Referenced by Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDiaDataTable.OnRowDeleting().
The documentation for this class was generated from the following file:
Capa.UI/Reporte/DataSetReportes.Designer.cs