Proyecto Autos Seguros: BLL.CoberturaBLL Class Reference
BLL.CoberturaBLL Class Reference
Public Member Functions
void Actualizar (Cobertura cobertura)
List< Cobertura > CoberturasAgregadas (int idTipoPoliza)
void Eliminar (int id)
void Insertar (Cobertura cobertura)
Cobertura SeleccionarPorId (int id)
List< Cobertura > SeleccionarTodas ()
void Insertar (Cobertura cobertura)
void Actualizar (Cobertura cobertur)
void Eliminar (int id)
List< Cobertura > SeleccionarTodas ()
Cobertura SeleccionarPorId (int id)
List< Cobertura > CoberturasAgregadas (int idTipoPoliza)
Detailed Description
Definition at line 12 of file CoberturaBLL.cs.
Member Function Documentation
Actualizar()
void BLL.CoberturaBLL.Actualizar (Cobertura cobertura)
Implements Interfaces.ICoberturaBLL.
Definition at line 14 of file CoberturaBLL.cs.
        {
            ICoberturaDAL logica = new CoberturaDAL();
            logica.Actualizar(cobertura);
        }
References Interfaces.ICoberturaDAL.Actualizar().
CoberturasAgregadas()
List< Cobertura > BLL.CoberturaBLL.CoberturasAgregadas (int idTipoPoliza)
Implements Interfaces.ICoberturaBLL.
Definition at line 20 of file CoberturaBLL.cs.
        {
            ICoberturaDAL logica = new CoberturaDAL();
            return logica.CoberturasAgregadas(idTipoPoliza);
        }
References Interfaces.ICoberturaDAL.CoberturasAgregadas().
Eliminar()
void BLL.CoberturaBLL.Eliminar (int id)
Implements Interfaces.ICoberturaBLL.
Definition at line 26 of file CoberturaBLL.cs.
        {
            ICoberturaDAL logica = new CoberturaDAL();
            logica.Eliminar(id);
        }
References Interfaces.ICoberturaDAL.Eliminar().
Insertar()
void BLL.CoberturaBLL.Insertar (Cobertura cobertura)
Implements Interfaces.ICoberturaBLL.
Definition at line 32 of file CoberturaBLL.cs.
        {
            I_IVA_BLL logicaIva = new IVABLL();
            Decimal porcIva = logicaIva.SeleccionarReciente().Porcentaje;
            cobertura.Total = cobertura.Precio * porcIva + cobertura.Precio;
            ICoberturaDAL logica = new CoberturaDAL();
            if (logica.SeleccionarPorId(cobertura.Id) == null)
            {
                logica.Insertar(cobertura);
            }
            else
            {
                logica.Actualizar(cobertura);
            }
        }
References Interfaces.ICoberturaDAL.Actualizar(), Entities.Cobertura.Id, Interfaces.ICoberturaDAL.Insertar(), Entities.IVA.Porcentaje, Entities.Cobertura.Precio, Interfaces.ICoberturaDAL.SeleccionarPorId(), Interfaces.I_IVA_BLL.SeleccionarReciente(), and Entities.Cobertura.Total.
SeleccionarPorId()
Cobertura BLL.CoberturaBLL.SeleccionarPorId (int id)
Implements Interfaces.ICoberturaBLL.
Definition at line 49 of file CoberturaBLL.cs.
        {
            ICoberturaDAL logica = new CoberturaDAL();
            return logica.SeleccionarPorId(id);
        }
References Interfaces.ICoberturaDAL.SeleccionarPorId().
SeleccionarTodas()
List< Cobertura > BLL.CoberturaBLL.SeleccionarTodas ()
Implements Interfaces.ICoberturaBLL.
Definition at line 55 of file CoberturaBLL.cs.
        {
            ICoberturaDAL logica = new CoberturaDAL();
            return logica.SeleccionarTodas();
        }
References Interfaces.ICoberturaDAL.SeleccionarTodas().
The documentation for this class was generated from the following file:
BLL/CoberturaBLL.cs