Proyecto Autos Seguros: DAL.IVADAL Class Reference
DAL.IVADAL Class Reference
Public Member Functions
void Actualizar (IVA iva)
void Eliminar (int id)
void Insertar (IVA iva)
IVA SeleccionarPorId (int id)
IVA SeleccionarReciente ()
List< IVA > SeleccionarTodas ()
void Actualizar (IVA iva)
void Eliminar (int id)
void Insertar (IVA iva)
List< IVA > SeleccionarTodas ()
IVA SeleccionarPorId (int id)
IVA SeleccionarReciente ()
Detailed Description
Definition at line 13 of file IVADAL.cs.
Member Function Documentation
Actualizar()
void DAL.IVADAL.Actualizar (IVA iva)
Implements Interfaces.I_IVA_DAL.
Definition at line 15 of file IVADAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_UPDATE_IVA";
                comando.Parameters.AddWithValue("@Id", iva.Id);
                comando.Parameters.AddWithValue("@Porcentaje", iva.Porcentaje);
                comando.Parameters.AddWithValue("@Fecha", iva.Fecha);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteNonQuery(), Entities.IVA.Fecha, Entities.IVA.Id, and Entities.IVA.Porcentaje.
Eliminar()
void DAL.IVADAL.Eliminar (int id)
Implements Interfaces.I_IVA_DAL.
Definition at line 31 of file IVADAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_DELETE_IVA_ByID";
                comando.Parameters.AddWithValue("@Id", id);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), and IDataBase.ExecuteNonQuery().
Insertar()
void DAL.IVADAL.Insertar (IVA iva)
Implements Interfaces.I_IVA_DAL.
Definition at line 44 of file IVADAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_INSERT_IVA";
                comando.Parameters.AddWithValue("@Porcentaje", iva.Porcentaje);
                comando.Parameters.AddWithValue("@Fecha", iva.Fecha);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteNonQuery(), Entities.IVA.Fecha, and Entities.IVA.Porcentaje.
SeleccionarPorId()
IVA DAL.IVADAL.SeleccionarPorId (int id)
Implements Interfaces.I_IVA_DAL.
Definition at line 59 of file IVADAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_IVA_ByID";
                comando.Parameters.AddWithValue("@Id", id);
                IDataReader dr = db.ExecuteReader(comando);
                while (dr.Read())
                {
                    IVA iva = new IVA();
                    iva.Id = (int)dr["Id"];
                    iva.Fecha = DateTime.Parse(dr["Fecha"].ToString());
                    iva.Porcentaje = (decimal)dr["Porcentaje"];
                    return iva;
                }
            }
            return null;
        }
References FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteReader(), Entities.IVA.Fecha, Entities.IVA.Id, and Entities.IVA.Porcentaje.
SeleccionarReciente()
IVA DAL.IVADAL.SeleccionarReciente ()
Implements Interfaces.I_IVA_DAL.
Definition at line 84 of file IVADAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_IVA_Reciente";
                IDataReader dr = db.ExecuteReader(comando);
                while (dr.Read())
                {
                    IVA iva = new IVA();
                    iva.Id = (int)dr["Id"];
                    iva.Fecha = DateTime.Parse(dr["Fecha"].ToString());
                    iva.Porcentaje = (decimal)dr["Porcentaje"];
                    return iva;
                }
            }
            return null;
        }
References FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteReader(), Entities.IVA.Fecha, Entities.IVA.Id, and Entities.IVA.Porcentaje.
SeleccionarTodas()
List< IVA > DAL.IVADAL.SeleccionarTodas ()
Implements Interfaces.I_IVA_DAL.
Definition at line 109 of file IVADAL.cs.
        {
            List<IVA> lista = new List<IVA>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_IVA_All";
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    IVA iva = new IVA();
                    iva.Id = (int)dr["Id"];
                    iva.Fecha = DateTime.Parse(dr["Fecha"].ToString());
                    iva.Porcentaje = (decimal)dr["Porcentaje"];
                    lista.Add(iva);
                }
            }
            return lista;
        }
References FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteDataSet(), Entities.IVA.Fecha, Entities.IVA.Id, and Entities.IVA.Porcentaje.
The documentation for this class was generated from the following file:
DAL/IVADAL.cs