Proyecto Autos Seguros: DAL.PolizaDAL Class Reference
DAL.PolizaDAL Class Reference
Public Member Functions
void Actualizar (Poliza poliza)
void Eliminar (int id)
int GetCurrentNumeroPoliza ()
int GetNextNumeroPoliza ()
void Insertar (Poliza poliza)
Poliza SeleccionarPorId (int id)
List< Poliza > SeleccionarTodas ()
void Insertar (Poliza poliza)
void Actualizar (Poliza poliza)
void Eliminar (int id)
List< Poliza > SeleccionarTodas ()
Poliza SeleccionarPorId (int id)
int GetNextNumeroPoliza ()
int GetCurrentNumeroPoliza ()
Detailed Description
Definition at line 13 of file PolizaDAL.cs.
Member Function Documentation
Actualizar()
void DAL.PolizaDAL.Actualizar (Poliza poliza)
Implements Interfaces.IPolizaDAL.
Definition at line 15 of file PolizaDAL.cs.
        {
                using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
                {
                    SqlCommand comando = new SqlCommand();
                    comando.CommandType = System.Data.CommandType.StoredProcedure;
                    comando.CommandText = "usp_UPDATE_Poliza";
                    comando.Parameters.AddWithValue("@Id", poliza.Id);
                    comando.Parameters.AddWithValue("@Descripcion",poliza.Descripcion);
                    comando.Parameters.AddWithValue("@FechaVencimiento", poliza.FechaVencimiento);
                    comando.Parameters.AddWithValue("@IdTipoPoliza", poliza.IdTipoPoliza);
                comando.Parameters.AddWithValue("@IdUsuario", poliza.IdUsuario);
                db.ExecuteNonQuery(comando);
                }
            }
References FactoryDatabase.CreateDefaultDataBase(), Entities.Poliza.Descripcion, IDataBase.ExecuteNonQuery(), Entities.Poliza.FechaVencimiento, Entities.Poliza.Id, Entities.Poliza.IdTipoPoliza, and Entities.Poliza.IdUsuario.
Eliminar()
void DAL.PolizaDAL.Eliminar (int id)
Implements Interfaces.IPolizaDAL.
Definition at line 34 of file PolizaDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_DELETE_Poliza_ByID";
                comando.Parameters.AddWithValue("@Id", id);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), and IDataBase.ExecuteNonQuery().
GetCurrentNumeroPoliza()
int DAL.PolizaDAL.GetCurrentNumeroPoliza ()
Implements Interfaces.IPolizaDAL.
Definition at line 47 of file PolizaDAL.cs.
        {
            DataSet ds = null;
            IDbCommand command = new SqlCommand();
            int numeroFactura = 0;
            string sql = @"SELECT current_value FROM sys.sequences WHERE name = 'secuenciaPoliza'  ";
            DataTable dt = null;
            try
            {
                command.CommandText = sql;
                command.CommandType = CommandType.Text;
                using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
                {
                    ds = db.ExecuteDataSet(command);
                }
                // Extraer la tabla
                dt = ds.Tables[0];
                //Extraer el valor que viene en el DataTable
                numeroFactura = int.Parse(dt.Rows[0][0].ToString());
                return numeroFactura;
            }
            catch (Exception er)
            {
                throw;
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), and IDataBase.ExecuteDataSet().
GetNextNumeroPoliza()
int DAL.PolizaDAL.GetNextNumeroPoliza ()
Implements Interfaces.IPolizaDAL.
Definition at line 76 of file PolizaDAL.cs.
        {
            DataSet ds = null;
            IDbCommand command = new SqlCommand();
            int numeroFactura = 0;
            string sql = @"SELECT NEXT VALUE FOR secuenciaPoliza";
            DataTable dt = null;
            try
            {
                command.CommandText = sql;
                command.CommandType = CommandType.Text;
                using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
                {
                    ds = db.ExecuteDataSet(command);
                }
                // Extraer la tabla
                dt = ds.Tables[0];
                //Extraer el valor que viene en el DataTable
                numeroFactura = int.Parse(dt.Rows[0][0].ToString());
                return numeroFactura;
            }
            catch (Exception er)
            {
                throw;
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), and IDataBase.ExecuteDataSet().
Insertar()
void DAL.PolizaDAL.Insertar (Poliza poliza)
Implements Interfaces.IPolizaDAL.
Definition at line 106 of file PolizaDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_INSERT_Poliza";
                comando.Parameters.AddWithValue("@Id", poliza.Id);
                comando.Parameters.AddWithValue("@Descripcion", poliza.Descripcion);
                comando.Parameters.AddWithValue("@FechaVencimiento", poliza.FechaVencimiento);
                comando.Parameters.AddWithValue("@IdTipoPoliza", poliza.IdTipoPoliza);
                comando.Parameters.AddWithValue("@IdUsuario", poliza.IdUsuario);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), Entities.Poliza.Descripcion, IDataBase.ExecuteNonQuery(), Entities.Poliza.FechaVencimiento, Entities.Poliza.Id, Entities.Poliza.IdTipoPoliza, and Entities.Poliza.IdUsuario.
SeleccionarPorId()
Poliza DAL.PolizaDAL.SeleccionarPorId (int id)
Implements Interfaces.IPolizaDAL.
Definition at line 123 of file PolizaDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_Poliza_ByID";
                comando.Parameters.AddWithValue("@Id", id);
                IDataReader dr = db.ExecuteReader(comando);
                while (dr.Read())
                {
                    Poliza poliza = new Poliza();
                    poliza.Id =(int) dr["Id"];
                    poliza.Descripcion = dr["Descripcion"].ToString();
                    poliza.FechaVencimiento = DateTime.Parse( dr["FechaVencimiento"].ToString());
                    poliza.IdUsuario = (int)dr["IdUsuario"];
                    ITipoPolizaDAL datosTipoPoliza = new TipoPolizaDAL();
                    poliza._TipoPoliza = datosTipoPoliza.ObtenerPorId(poliza.IdTipoPoliza);
                    return poliza;
                }
            }
            return null;
        }
References Entities.Poliza._TipoPoliza, FactoryDatabase.CreateDefaultDataBase(), Entities.Poliza.Descripcion, IDataBase.ExecuteReader(), Entities.Poliza.FechaVencimiento, Entities.Poliza.Id, Entities.Poliza.IdTipoPoliza, Entities.Poliza.IdUsuario, and Interfaces.ITipoPolizaDAL.ObtenerPorId().
SeleccionarTodas()
List< Poliza > DAL.PolizaDAL.SeleccionarTodas ()
Implements Interfaces.IPolizaDAL.
Definition at line 152 of file PolizaDAL.cs.
        {
            List<Poliza> lista = new List<Poliza>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_Poliza_All";
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Poliza poliza = new Poliza();
                    poliza.Id = (int)dr["Id"];
                    poliza.Descripcion = dr["Descripcion"].ToString();
                    poliza.FechaVencimiento = DateTime.Parse(dr["FechaVencimiento"].ToString());
                    poliza.IdTipoPoliza = (int)dr["IdTipoPoliza"];
                    poliza.IdUsuario = (int)dr["IdUsuario"];
                    //ITipoPolizaDAL datosTipoPoliza = new TipoPolizaDAL();
                    //poliza._TipoPoliza = datosTipoPoliza.ObtenerPorId(poliza.IdTipoPoliza);
                    lista.Add(poliza);
                }
            }
            return lista;
        }
References FactoryDatabase.CreateDefaultDataBase(), Entities.Poliza.Descripcion, IDataBase.ExecuteDataSet(), Entities.Poliza.FechaVencimiento, Entities.Poliza.Id, Entities.Poliza.IdTipoPoliza, and Entities.Poliza.IdUsuario.
The documentation for this class was generated from the following file:
DAL/PolizaDAL.cs