Proyecto Autos Seguros: Capa.UI.frmPrincipal Class Reference
Capa.UI.frmPrincipal Class Reference
Public Member Functions
frmPrincipal ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void VerificarTipoUsuario ()
void cerrarSesiónToolStripMenuItem_Click (object sender, EventArgs e)
void salirToolStripMenuItem_Click (object sender, EventArgs e)
void TsMenuItemUsuarios_Click (object sender, EventArgs e)
void TsMenuItemCoberturas_Click (object sender, EventArgs e)
void toolStripMenuItem1_Click (object sender, EventArgs e)
void TsMenuItemPolizas_Click (object sender, EventArgs e)
void tipoPolizaToolStripMenuItem_Click (object sender, EventArgs e)
void TsMenuItemFacturacion_Click (object sender, EventArgs e)
void toolStripMenuItem2_Click (object sender, EventArgs e)
void PolizasPorUsuarioToolStripMenuItem_Click (object sender, EventArgs e)
void anularFacturaToolStripMenuItem_Click (object sender, EventArgs e)
void ventasPorDíaToolStripMenuItem_Click (object sender, EventArgs e)
void frmPrincipal_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.MenuStrip mspMenuPrincipal
System.Windows.Forms.ToolStripMenuItem toolStripMenuItemArchivo
System.Windows.Forms.ToolStripMenuItem cerrarSesiónToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem salirToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem toolStripMenuItemMantenimientos
System.Windows.Forms.ToolStripMenuItem TsMenuItemUsuarios
System.Windows.Forms.ToolStripMenuItem TsMenuItemCoberturas
System.Windows.Forms.ToolStripMenuItem toolStripMenuItemProcesos
System.Windows.Forms.ToolStripMenuItem TsMenuItemFacturacion
System.Windows.Forms.ToolStripMenuItem ToolStripMenuItemReportes
System.Windows.Forms.ToolStripMenuItem PolizasPorUsuarioToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem toolStripMenuItemAcercaDe
System.Windows.Forms.ToolStripMenuItem toolStripMenuItem1
System.Windows.Forms.ToolStripMenuItem tipoPolizaToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem toolStripMenuItem2
System.Windows.Forms.ToolStripMenuItem anularFacturaToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem ventasPorDíaToolStripMenuItem
Static Private Attributes
static readonly ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 18 of file frmPrincipal.cs.
Constructor & Destructor Documentation
frmPrincipal()
Capa.UI.frmPrincipal.frmPrincipal ()
Definition at line 21 of file frmPrincipal.cs.
        {
            InitializeComponent();
        }
References Capa.UI.frmPrincipal.InitializeComponent().
Member Function Documentation
anularFacturaToolStripMenuItem_Click()
void Capa.UI.frmPrincipal.anularFacturaToolStripMenuItem_Click (object sender, EventArgs e) private
Definition at line 202 of file frmPrincipal.cs.
        {
            frmMantenimientoAnulaFac frmAnulaFacturas;
            try
            {
                frmAnulaFacturas = new frmMantenimientoAnulaFac();
                frmAnulaFacturas.MdiParent = this;
                frmAnulaFacturas.Show();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Se ha producido el siguiente error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.frmPrincipal._MyLogControlEventos.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
cerrarSesiónToolStripMenuItem_Click()
void Capa.UI.frmPrincipal.cerrarSesiónToolStripMenuItem_Click (object sender, EventArgs e) private
Definition at line 37 of file frmPrincipal.cs.
        {
            try
            {
                var r = MessageBox.Show("¿Desea Cerrar Sesión?", "Atención", MessageBoxButtons.YesNo);
                    if (r == DialogResult.Yes)
                    {
                        this.Close();
                    }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.frmPrincipal._MyLogControlEventos.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
Dispose()
override void Capa.UI.frmPrincipal.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file frmPrincipal.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References Capa.UI.frmPrincipal.components.
frmPrincipal_Load()
void Capa.UI.frmPrincipal.frmPrincipal_Load (object sender, EventArgs e) private
Definition at line 238 of file frmPrincipal.cs.
        {
            VerificarTipoUsuario();
        }
References Capa.UI.frmPrincipal.VerificarTipoUsuario().
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
InitializeComponent()
void Capa.UI.frmPrincipal.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file frmPrincipal.Designer.cs.
        {
            this.mspMenuPrincipal = new System.Windows.Forms.MenuStrip();
            this.toolStripMenuItemArchivo = new System.Windows.Forms.ToolStripMenuItem();
            this.cerrarSesiónToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.salirToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItemMantenimientos = new System.Windows.Forms.ToolStripMenuItem();
            this.TsMenuItemUsuarios = new System.Windows.Forms.ToolStripMenuItem();
            this.TsMenuItemCoberturas = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItem1 = new System.Windows.Forms.ToolStripMenuItem();
            this.tipoPolizaToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItemProcesos = new System.Windows.Forms.ToolStripMenuItem();
            this.TsMenuItemFacturacion = new System.Windows.Forms.ToolStripMenuItem();
            this.anularFacturaToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ToolStripMenuItemReportes = new System.Windows.Forms.ToolStripMenuItem();
            this.PolizasPorUsuarioToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItem2 = new System.Windows.Forms.ToolStripMenuItem();
            this.ventasPorDíaToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItemAcercaDe = new System.Windows.Forms.ToolStripMenuItem();
            this.mspMenuPrincipal.SuspendLayout();
            this.SuspendLayout();
            //
            // mspMenuPrincipal
            //
            this.mspMenuPrincipal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.mspMenuPrincipal.Dock = System.Windows.Forms.DockStyle.Left;
            this.mspMenuPrincipal.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripMenuItemArchivo,
            this.toolStripMenuItemMantenimientos,
            this.toolStripMenuItemProcesos,
            this.ToolStripMenuItemReportes,
            this.toolStripMenuItemAcercaDe});
            this.mspMenuPrincipal.Location = new System.Drawing.Point(0, 0);
            this.mspMenuPrincipal.Name = "mspMenuPrincipal";
            this.mspMenuPrincipal.RenderMode = System.Windows.Forms.ToolStripRenderMode.Professional;
            this.mspMenuPrincipal.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.mspMenuPrincipal.Size = new System.Drawing.Size(126, 619);
            this.mspMenuPrincipal.TabIndex = 3;
            this.mspMenuPrincipal.Text = "menuStrip1";
            //
            // toolStripMenuItemArchivo
            //
            this.toolStripMenuItemArchivo.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.cerrarSesiónToolStripMenuItem,
            this.salirToolStripMenuItem});
            this.toolStripMenuItemArchivo.ForeColor = System.Drawing.Color.White;
            this.toolStripMenuItemArchivo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripMenuItemArchivo.Name = "toolStripMenuItemArchivo";
            this.toolStripMenuItemArchivo.Size = new System.Drawing.Size(99, 19);
            this.toolStripMenuItemArchivo.Text = "Archivo";
            this.toolStripMenuItemArchivo.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            //
            // cerrarSesiónToolStripMenuItem
            //
            this.cerrarSesiónToolStripMenuItem.Name = "cerrarSesiónToolStripMenuItem";
            this.cerrarSesiónToolStripMenuItem.Size = new System.Drawing.Size(143, 22);
            this.cerrarSesiónToolStripMenuItem.Text = "Cerrar Sesión";
            this.cerrarSesiónToolStripMenuItem.Click += new System.EventHandler(this.cerrarSesiónToolStripMenuItem_Click);
            //
            // salirToolStripMenuItem
            //
            this.salirToolStripMenuItem.Name = "salirToolStripMenuItem";
            this.salirToolStripMenuItem.Size = new System.Drawing.Size(143, 22);
            this.salirToolStripMenuItem.Text = "Salir";
            this.salirToolStripMenuItem.Click += new System.EventHandler(this.salirToolStripMenuItem_Click);
            //
            // toolStripMenuItemMantenimientos
            //
            this.toolStripMenuItemMantenimientos.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.TsMenuItemUsuarios,
            this.TsMenuItemCoberturas,
            this.toolStripMenuItem1,
            this.tipoPolizaToolStripMenuItem});
            this.toolStripMenuItemMantenimientos.ForeColor = System.Drawing.Color.White;
            this.toolStripMenuItemMantenimientos.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripMenuItemMantenimientos.Name = "toolStripMenuItemMantenimientos";
            this.toolStripMenuItemMantenimientos.Size = new System.Drawing.Size(99, 19);
            this.toolStripMenuItemMantenimientos.Text = "Mantenimientos";
            this.toolStripMenuItemMantenimientos.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            //
            // TsMenuItemUsuarios
            //
            this.TsMenuItemUsuarios.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.TsMenuItemUsuarios.Name = "TsMenuItemUsuarios";
            this.TsMenuItemUsuarios.Size = new System.Drawing.Size(180, 22);
            this.TsMenuItemUsuarios.Text = "Usuarios";
            this.TsMenuItemUsuarios.Click += new System.EventHandler(this.TsMenuItemUsuarios_Click);
            //
            // TsMenuItemCoberturas
            //
            this.TsMenuItemCoberturas.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.TsMenuItemCoberturas.Name = "TsMenuItemCoberturas";
            this.TsMenuItemCoberturas.Size = new System.Drawing.Size(180, 22);
            this.TsMenuItemCoberturas.Text = "Coberturas";
            this.TsMenuItemCoberturas.Click += new System.EventHandler(this.TsMenuItemCoberturas_Click);
            //
            // toolStripMenuItem1
            //
            this.toolStripMenuItem1.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripMenuItem1.Name = "toolStripMenuItem1";
            this.toolStripMenuItem1.Size = new System.Drawing.Size(180, 22);
            this.toolStripMenuItem1.Text = "IVA";
            this.toolStripMenuItem1.Click += new System.EventHandler(this.toolStripMenuItem1_Click);
            //
            // tipoPolizaToolStripMenuItem
            //
            this.tipoPolizaToolStripMenuItem.Name = "tipoPolizaToolStripMenuItem";
            this.tipoPolizaToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
            this.tipoPolizaToolStripMenuItem.Text = "TipoPoliza";
            this.tipoPolizaToolStripMenuItem.Click += new System.EventHandler(this.tipoPolizaToolStripMenuItem_Click);
            //
            // toolStripMenuItemProcesos
            //
            this.toolStripMenuItemProcesos.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.TsMenuItemFacturacion,
            this.anularFacturaToolStripMenuItem});
            this.toolStripMenuItemProcesos.ForeColor = System.Drawing.Color.White;
            this.toolStripMenuItemProcesos.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripMenuItemProcesos.Name = "toolStripMenuItemProcesos";
            this.toolStripMenuItemProcesos.Size = new System.Drawing.Size(99, 19);
            this.toolStripMenuItemProcesos.Text = "Procesos";
            this.toolStripMenuItemProcesos.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            //
            // TsMenuItemFacturacion
            //
            this.TsMenuItemFacturacion.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.TsMenuItemFacturacion.Name = "TsMenuItemFacturacion";
            this.TsMenuItemFacturacion.Size = new System.Drawing.Size(151, 22);
            this.TsMenuItemFacturacion.Text = "Facturación";
            this.TsMenuItemFacturacion.Click += new System.EventHandler(this.TsMenuItemFacturacion_Click);
            //
            // anularFacturaToolStripMenuItem
            //
            this.anularFacturaToolStripMenuItem.Name = "anularFacturaToolStripMenuItem";
            this.anularFacturaToolStripMenuItem.Size = new System.Drawing.Size(151, 22);
            this.anularFacturaToolStripMenuItem.Text = "Anular Factura";
            this.anularFacturaToolStripMenuItem.Click += new System.EventHandler(this.anularFacturaToolStripMenuItem_Click);
            //
            // ToolStripMenuItemReportes
            //
            this.ToolStripMenuItemReportes.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.PolizasPorUsuarioToolStripMenuItem,
            this.toolStripMenuItem2,
            this.ventasPorDíaToolStripMenuItem});
            this.ToolStripMenuItemReportes.ForeColor = System.Drawing.Color.White;
            this.ToolStripMenuItemReportes.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.ToolStripMenuItemReportes.Name = "ToolStripMenuItemReportes";
            this.ToolStripMenuItemReportes.Size = new System.Drawing.Size(99, 19);
            this.ToolStripMenuItemReportes.Text = "Reportes";
            this.ToolStripMenuItemReportes.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            //
            // PolizasPorUsuarioToolStripMenuItem
            //
            this.PolizasPorUsuarioToolStripMenuItem.Name = "PolizasPorUsuarioToolStripMenuItem";
            this.PolizasPorUsuarioToolStripMenuItem.Size = new System.Drawing.Size(174, 22);
            this.PolizasPorUsuarioToolStripMenuItem.Text = "Polizas por Usuario";
            this.PolizasPorUsuarioToolStripMenuItem.Click += new System.EventHandler(this.PolizasPorUsuarioToolStripMenuItem_Click);
            //
            // toolStripMenuItem2
            //
            this.toolStripMenuItem2.Name = "toolStripMenuItem2";
            this.toolStripMenuItem2.Size = new System.Drawing.Size(174, 22);
            this.toolStripMenuItem2.Text = "Polizas Vendidas";
            this.toolStripMenuItem2.Click += new System.EventHandler(this.toolStripMenuItem2_Click);
            //
            // ventasPorDíaToolStripMenuItem
            //
            this.ventasPorDíaToolStripMenuItem.Name = "ventasPorDíaToolStripMenuItem";
            this.ventasPorDíaToolStripMenuItem.Size = new System.Drawing.Size(174, 22);
            this.ventasPorDíaToolStripMenuItem.Text = "Ventas por Día";
            this.ventasPorDíaToolStripMenuItem.Click += new System.EventHandler(this.ventasPorDíaToolStripMenuItem_Click);
            //
            // toolStripMenuItemAcercaDe
            //
            this.toolStripMenuItemAcercaDe.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripMenuItemAcercaDe.Name = "toolStripMenuItemAcercaDe";
            this.toolStripMenuItemAcercaDe.Size = new System.Drawing.Size(99, 4);
            //
            // frmPrincipal
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1398, 619);
            this.Controls.Add(this.mspMenuPrincipal);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.IsMdiContainer = true;
            this.MainMenuStrip = this.mspMenuPrincipal;
            this.Name = "frmPrincipal";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmPrincipal";
            this.Load += new System.EventHandler(this.frmPrincipal_Load);
            this.mspMenuPrincipal.ResumeLayout(false);
            this.mspMenuPrincipal.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References Capa.UI.frmPrincipal.anularFacturaToolStripMenuItem, Capa.UI.frmPrincipal.anularFacturaToolStripMenuItem_Click(), Capa.UI.frmPrincipal.cerrarSesiónToolStripMenuItem, Capa.UI.frmPrincipal.cerrarSesiónToolStripMenuItem_Click(), Capa.UI.frmPrincipal.frmPrincipal_Load(), Capa.UI.frmPrincipal.mspMenuPrincipal, Capa.UI.frmPrincipal.PolizasPorUsuarioToolStripMenuItem, Capa.UI.frmPrincipal.PolizasPorUsuarioToolStripMenuItem_Click(), Capa.UI.frmPrincipal.salirToolStripMenuItem, Capa.UI.frmPrincipal.salirToolStripMenuItem_Click(), Capa.UI.frmPrincipal.tipoPolizaToolStripMenuItem, Capa.UI.frmPrincipal.tipoPolizaToolStripMenuItem_Click(), Capa.UI.frmPrincipal.toolStripMenuItem1, Capa.UI.frmPrincipal.toolStripMenuItem1_Click(), Capa.UI.frmPrincipal.toolStripMenuItem2, Capa.UI.frmPrincipal.toolStripMenuItem2_Click(), Capa.UI.frmPrincipal.toolStripMenuItemAcercaDe, Capa.UI.frmPrincipal.toolStripMenuItemArchivo, Capa.UI.frmPrincipal.toolStripMenuItemMantenimientos, Capa.UI.frmPrincipal.toolStripMenuItemProcesos, Capa.UI.frmPrincipal.ToolStripMenuItemReportes, Capa.UI.frmPrincipal.TsMenuItemCoberturas, Capa.UI.frmPrincipal.TsMenuItemCoberturas_Click(), Capa.UI.frmPrincipal.TsMenuItemFacturacion, Capa.UI.frmPrincipal.TsMenuItemFacturacion_Click(), Capa.UI.frmPrincipal.TsMenuItemUsuarios, Capa.UI.frmPrincipal.TsMenuItemUsuarios_Click(), Capa.UI.frmPrincipal.ventasPorDíaToolStripMenuItem, and Capa.UI.frmPrincipal.ventasPorDíaToolStripMenuItem_Click().
Referenced by Capa.UI.frmPrincipal.frmPrincipal().
PolizasPorUsuarioToolStripMenuItem_Click()
void Capa.UI.frmPrincipal.PolizasPorUsuarioToolStripMenuItem_Click (object sender, EventArgs e) private
Definition at line 184 of file frmPrincipal.cs.
        {
            frmRptPolizaByIdUsuario frmRptPolizasByIdUsuario;
            try
            {
                frmRptPolizasByIdUsuario = new frmRptPolizaByIdUsuario();
                frmRptPolizasByIdUsuario.MdiParent = this;
                frmRptPolizasByIdUsuario.Show();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Se ha producido el siguiente error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.frmPrincipal._MyLogControlEventos.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
salirToolStripMenuItem_Click()
void Capa.UI.frmPrincipal.salirToolStripMenuItem_Click (object sender, EventArgs e) private
Definition at line 57 of file frmPrincipal.cs.
        {
            var response = MessageBox.Show("¿Desea Salir?", "Atención", MessageBoxButtons.YesNo);
            if (response == DialogResult.Yes)
            {
                System.Windows.Forms.Application.Exit();
                 _MyLogControlEventos.Error("Se cierra la aplicación");
            }
        }
References Capa.UI.frmPrincipal._MyLogControlEventos.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
tipoPolizaToolStripMenuItem_Click()
void Capa.UI.frmPrincipal.tipoPolizaToolStripMenuItem_Click (object sender, EventArgs e) private
Definition at line 128 of file frmPrincipal.cs.
        {
            frmMantenimientoTipoPoliza ofrmMantenimientoTipoPolizas;
            try
            {
                ofrmMantenimientoTipoPolizas = new frmMantenimientoTipoPoliza();
                ofrmMantenimientoTipoPolizas.MdiParent = this;
                ofrmMantenimientoTipoPolizas.Show();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Se ha producido el siguiente error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.frmPrincipal._MyLogControlEventos.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
toolStripMenuItem1_Click()
void Capa.UI.frmPrincipal.toolStripMenuItem1_Click (object sender, EventArgs e) private
Definition at line 105 of file frmPrincipal.cs.
        {
            frmMantenimientoIVA ofrmMantenimientoIva;
            try
            {
                ofrmMantenimientoIva = new frmMantenimientoIVA();
                ofrmMantenimientoIva.MdiParent = this;
                ofrmMantenimientoIva.Show();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Se ha producido el siguiente error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.frmPrincipal._MyLogControlEventos.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
toolStripMenuItem2_Click()
void Capa.UI.frmPrincipal.toolStripMenuItem2_Click (object sender, EventArgs e) private
Definition at line 166 of file frmPrincipal.cs.
        {
            frmRptPolizasByFecha frmPolizasVendidas;
            try
            {
                frmPolizasVendidas = new frmRptPolizasByFecha();
                frmPolizasVendidas.MdiParent = this;
                frmPolizasVendidas.Show();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Se ha producido el siguiente error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.frmPrincipal._MyLogControlEventos.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
TsMenuItemCoberturas_Click()
void Capa.UI.frmPrincipal.TsMenuItemCoberturas_Click (object sender, EventArgs e) private
Definition at line 87 of file frmPrincipal.cs.
        {
            frmMantenimientoCoberturas ofrmMantenimientoCoberturas;
            try
            {
                ofrmMantenimientoCoberturas = new frmMantenimientoCoberturas();
                ofrmMantenimientoCoberturas.MdiParent = this;
                ofrmMantenimientoCoberturas.Show();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Se ha producido el siguiente error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.frmPrincipal._MyLogControlEventos.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
TsMenuItemFacturacion_Click()
void Capa.UI.frmPrincipal.TsMenuItemFacturacion_Click (object sender, EventArgs e) private
Definition at line 146 of file frmPrincipal.cs.
        {
            frmFacturacion ofrmFacturacion;
            try
            {
                ofrmFacturacion = new frmFacturacion();
                ofrmFacturacion.MdiParent = this;
                ofrmFacturacion.Show();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Se ha producido el siguiente error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.frmPrincipal._MyLogControlEventos.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
TsMenuItemPolizas_Click()
void Capa.UI.frmPrincipal.TsMenuItemPolizas_Click (object sender, EventArgs e) private
Definition at line 123 of file frmPrincipal.cs.
        {
        }
TsMenuItemUsuarios_Click()
void Capa.UI.frmPrincipal.TsMenuItemUsuarios_Click (object sender, EventArgs e) private
Definition at line 68 of file frmPrincipal.cs.
        {
            frmMantenimientoUsuarios ofrmMantenimientoUsuarios;
            try
            {
                ofrmMantenimientoUsuarios = new frmMantenimientoUsuarios();
                ofrmMantenimientoUsuarios.MdiParent = this;
                ofrmMantenimientoUsuarios.Show();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Se ha producido el siguiente error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.frmPrincipal._MyLogControlEventos.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
ventasPorDíaToolStripMenuItem_Click()
void Capa.UI.frmPrincipal.ventasPorDíaToolStripMenuItem_Click (object sender, EventArgs e) private
Definition at line 220 of file frmPrincipal.cs.
        {
            frmRptVentasByDia frmVentas;
            try
            {
                frmVentas = new frmRptVentasByDia();
                frmVentas.MdiParent = this;
                frmVentas.Show();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Se ha producido el siguiente error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.frmPrincipal._MyLogControlEventos.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
VerificarTipoUsuario()
void Capa.UI.frmPrincipal.VerificarTipoUsuario () private
Definition at line 26 of file frmPrincipal.cs.
        {
            if (CacheUsuario.IdTipoUsuario == 3)
            {
                toolStripMenuItemMantenimientos.Visible = false;
                toolStripMenuItemProcesos.Visible = false;
            }
        }
References Entities.CacheUsuario.IdTipoUsuario, Capa.UI.frmPrincipal.toolStripMenuItemMantenimientos, and Capa.UI.frmPrincipal.toolStripMenuItemProcesos.
Referenced by Capa.UI.frmPrincipal.frmPrincipal_Load().
Member Data Documentation
_MyLogControlEventos
readonly ILog Capa.UI.frmPrincipal._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 20 of file frmPrincipal.cs.
Referenced by Capa.UI.frmPrincipal.anularFacturaToolStripMenuItem_Click(), Capa.UI.frmPrincipal.cerrarSesiónToolStripMenuItem_Click(), Capa.UI.frmPrincipal.PolizasPorUsuarioToolStripMenuItem_Click(), Capa.UI.frmPrincipal.salirToolStripMenuItem_Click(), Capa.UI.frmPrincipal.tipoPolizaToolStripMenuItem_Click(), Capa.UI.frmPrincipal.toolStripMenuItem1_Click(), Capa.UI.frmPrincipal.toolStripMenuItem2_Click(), Capa.UI.frmPrincipal.TsMenuItemCoberturas_Click(), Capa.UI.frmPrincipal.TsMenuItemFacturacion_Click(), Capa.UI.frmPrincipal.TsMenuItemUsuarios_Click(), and Capa.UI.frmPrincipal.ventasPorDíaToolStripMenuItem_Click().
anularFacturaToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem Capa.UI.frmPrincipal.anularFacturaToolStripMenuItem private
Definition at line 244 of file frmPrincipal.Designer.cs.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
cerrarSesiónToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem Capa.UI.frmPrincipal.cerrarSesiónToolStripMenuItem private
Definition at line 231 of file frmPrincipal.Designer.cs.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
components
System.ComponentModel.IContainer Capa.UI.frmPrincipal.components = null private
Required designer variable.
Definition at line 8 of file frmPrincipal.Designer.cs.
Referenced by Capa.UI.frmPrincipal.Dispose().
mspMenuPrincipal
System.Windows.Forms.MenuStrip Capa.UI.frmPrincipal.mspMenuPrincipal private
Definition at line 229 of file frmPrincipal.Designer.cs.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
PolizasPorUsuarioToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem Capa.UI.frmPrincipal.PolizasPorUsuarioToolStripMenuItem private
Definition at line 239 of file frmPrincipal.Designer.cs.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
salirToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem Capa.UI.frmPrincipal.salirToolStripMenuItem private
Definition at line 232 of file frmPrincipal.Designer.cs.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
tipoPolizaToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem Capa.UI.frmPrincipal.tipoPolizaToolStripMenuItem private
Definition at line 242 of file frmPrincipal.Designer.cs.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
toolStripMenuItem1
System.Windows.Forms.ToolStripMenuItem Capa.UI.frmPrincipal.toolStripMenuItem1 private
Definition at line 241 of file frmPrincipal.Designer.cs.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
toolStripMenuItem2
System.Windows.Forms.ToolStripMenuItem Capa.UI.frmPrincipal.toolStripMenuItem2 private
Definition at line 243 of file frmPrincipal.Designer.cs.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
toolStripMenuItemAcercaDe
System.Windows.Forms.ToolStripMenuItem Capa.UI.frmPrincipal.toolStripMenuItemAcercaDe private
Definition at line 240 of file frmPrincipal.Designer.cs.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
toolStripMenuItemArchivo
System.Windows.Forms.ToolStripMenuItem Capa.UI.frmPrincipal.toolStripMenuItemArchivo private
Definition at line 230 of file frmPrincipal.Designer.cs.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
toolStripMenuItemMantenimientos
System.Windows.Forms.ToolStripMenuItem Capa.UI.frmPrincipal.toolStripMenuItemMantenimientos private
Definition at line 233 of file frmPrincipal.Designer.cs.
Referenced by Capa.UI.frmPrincipal.InitializeComponent(), and Capa.UI.frmPrincipal.VerificarTipoUsuario().
toolStripMenuItemProcesos
System.Windows.Forms.ToolStripMenuItem Capa.UI.frmPrincipal.toolStripMenuItemProcesos private
Definition at line 236 of file frmPrincipal.Designer.cs.
Referenced by Capa.UI.frmPrincipal.InitializeComponent(), and Capa.UI.frmPrincipal.VerificarTipoUsuario().
ToolStripMenuItemReportes
System.Windows.Forms.ToolStripMenuItem Capa.UI.frmPrincipal.ToolStripMenuItemReportes private
Definition at line 238 of file frmPrincipal.Designer.cs.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
TsMenuItemCoberturas
System.Windows.Forms.ToolStripMenuItem Capa.UI.frmPrincipal.TsMenuItemCoberturas private
Definition at line 235 of file frmPrincipal.Designer.cs.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
TsMenuItemFacturacion
System.Windows.Forms.ToolStripMenuItem Capa.UI.frmPrincipal.TsMenuItemFacturacion private
Definition at line 237 of file frmPrincipal.Designer.cs.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
TsMenuItemUsuarios
System.Windows.Forms.ToolStripMenuItem Capa.UI.frmPrincipal.TsMenuItemUsuarios private
Definition at line 234 of file frmPrincipal.Designer.cs.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
ventasPorDíaToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem Capa.UI.frmPrincipal.ventasPorDíaToolStripMenuItem private
Definition at line 245 of file frmPrincipal.Designer.cs.
Referenced by Capa.UI.frmPrincipal.InitializeComponent().
The documentation for this class was generated from the following files:
Capa.UI/frmPrincipal.cs
Capa.UI/frmPrincipal.Designer.cs