Proyecto Autos Seguros: Capa.UI.Reporte.frmRptPolizaByIdUsuario Class Reference
Capa.UI.Reporte.frmRptPolizaByIdUsuario Class Reference
Public Member Functions
frmRptPolizaByIdUsuario ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void toolStripTxtId_Enter (object sender, EventArgs e)
void toolStripTxtId_Leave (object sender, EventArgs e)
void toolStripBtnBuscar_Click (object sender, EventArgs e)
void frmRptPolizaByIdUsuario_Load (object sender, EventArgs e)
void toolStripBtnSalir_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.ToolStrip tspBarraSuperior
System.Windows.Forms.ToolStripButton toolStripBtnSalir
System.Windows.Forms.ToolStripTextBox toolStripTxtId
System.Windows.Forms.ToolStripButton toolStripBtnBuscar
Microsoft.Reporting.WinForms.ReportViewer rptVisor
System.Windows.Forms.BindingSource uspPolizaByIdUsuarioBindingSource
DataSetReportes dataSetReportes
DataSetReportesTableAdapters.usp_PolizaByIdUsuarioTableAdapter usp_PolizaByIdUsuarioTableAdapter
Static Private Attributes
static readonly ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 14 of file frmRptPolizaByIdUsuario.cs.
Constructor & Destructor Documentation
frmRptPolizaByIdUsuario()
Capa.UI.Reporte.frmRptPolizaByIdUsuario.frmRptPolizaByIdUsuario ()
Definition at line 17 of file frmRptPolizaByIdUsuario.cs.
        {
            InitializeComponent();
        }
References Capa.UI.Reporte.frmRptPolizaByIdUsuario.InitializeComponent().
Member Function Documentation
Dispose()
override void Capa.UI.Reporte.frmRptPolizaByIdUsuario.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file frmRptPolizaByIdUsuario.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References Capa.UI.Reporte.frmRptPolizaByIdUsuario.components.
frmRptPolizaByIdUsuario_Load()
void Capa.UI.Reporte.frmRptPolizaByIdUsuario.frmRptPolizaByIdUsuario_Load (object sender, EventArgs e) private
Definition at line 60 of file frmRptPolizaByIdUsuario.cs.
        {
            this.rptVisor.RefreshReport();
        }
References Capa.UI.Reporte.frmRptPolizaByIdUsuario.rptVisor.
Referenced by Capa.UI.Reporte.frmRptPolizaByIdUsuario.InitializeComponent().
InitializeComponent()
void Capa.UI.Reporte.frmRptPolizaByIdUsuario.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file frmRptPolizaByIdUsuario.Designer.cs.
        {
            this.components = new System.ComponentModel.Container();
            Microsoft.Reporting.WinForms.ReportDataSource reportDataSource1 = new Microsoft.Reporting.WinForms.ReportDataSource();
            this.uspPolizaByIdUsuarioBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.dataSetReportes = new Capa.UI.Reporte.DataSetReportes();
            this.tspBarraSuperior = new System.Windows.Forms.ToolStrip();
            this.toolStripBtnSalir = new System.Windows.Forms.ToolStripButton();
            this.toolStripTxtId = new System.Windows.Forms.ToolStripTextBox();
            this.toolStripBtnBuscar = new System.Windows.Forms.ToolStripButton();
            this.rptVisor = new Microsoft.Reporting.WinForms.ReportViewer();
            this.usp_PolizaByIdUsuarioTableAdapter = new Capa.UI.Reporte.DataSetReportesTableAdapters.usp_PolizaByIdUsuarioTableAdapter();
            ((System.ComponentModel.ISupportInitialize)(this.uspPolizaByIdUsuarioBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataSetReportes)).BeginInit();
            this.tspBarraSuperior.SuspendLayout();
            this.SuspendLayout();
            //
            // uspPolizaByIdUsuarioBindingSource
            //
            this.uspPolizaByIdUsuarioBindingSource.DataMember = "usp_PolizaByIdUsuario";
            this.uspPolizaByIdUsuarioBindingSource.DataSource = this.dataSetReportes;
            //
            // dataSetReportes
            //
            this.dataSetReportes.DataSetName = "DataSetReportes";
            this.dataSetReportes.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            //
            // tspBarraSuperior
            //
            this.tspBarraSuperior.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.tspBarraSuperior.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripBtnSalir,
            this.toolStripTxtId,
            this.toolStripBtnBuscar});
            this.tspBarraSuperior.Location = new System.Drawing.Point(0, 0);
            this.tspBarraSuperior.Name = "tspBarraSuperior";
            this.tspBarraSuperior.Size = new System.Drawing.Size(800, 25);
            this.tspBarraSuperior.TabIndex = 8;
            this.tspBarraSuperior.Text = "toolStrip1";
            //
            // toolStripBtnSalir
            //
            this.toolStripBtnSalir.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnSalir.ForeColor = System.Drawing.Color.White;
            this.toolStripBtnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnSalir.Name = "toolStripBtnSalir";
            this.toolStripBtnSalir.Size = new System.Drawing.Size(39, 22);
            this.toolStripBtnSalir.Text = "Salir";
            this.toolStripBtnSalir.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnSalir.Click += new System.EventHandler(this.toolStripBtnSalir_Click);
            //
            // toolStripTxtId
            //
            this.toolStripTxtId.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.toolStripTxtId.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripTxtId.ForeColor = System.Drawing.Color.White;
            this.toolStripTxtId.Name = "toolStripTxtId";
            this.toolStripTxtId.Size = new System.Drawing.Size(100, 25);
            this.toolStripTxtId.Text = "Identificación";
            this.toolStripTxtId.Enter += new System.EventHandler(this.toolStripTxtId_Enter);
            this.toolStripTxtId.Leave += new System.EventHandler(this.toolStripTxtId_Leave);
            //
            // toolStripBtnBuscar
            //
            this.toolStripBtnBuscar.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnBuscar.ForeColor = System.Drawing.Color.White;
            this.toolStripBtnBuscar.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnBuscar.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnBuscar.Name = "toolStripBtnBuscar";
            this.toolStripBtnBuscar.Size = new System.Drawing.Size(52, 22);
            this.toolStripBtnBuscar.Text = "Buscar";
            this.toolStripBtnBuscar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnBuscar.Click += new System.EventHandler(this.toolStripBtnBuscar_Click);
            //
            // rptVisor
            //
            reportDataSource1.Name = "dsPolizaByIdUsuario";
            reportDataSource1.Value = this.uspPolizaByIdUsuarioBindingSource;
            this.rptVisor.LocalReport.DataSources.Add(reportDataSource1);
            this.rptVisor.LocalReport.ReportEmbeddedResource = "Capa.UI.Reporte.rptPolizaByIdUsuario.rdlc";
            this.rptVisor.Location = new System.Drawing.Point(0, 28);
            this.rptVisor.Name = "rptVisor";
            this.rptVisor.ServerReport.BearerToken = null;
            this.rptVisor.Size = new System.Drawing.Size(800, 427);
            this.rptVisor.TabIndex = 9;
            this.rptVisor.ZoomMode = Microsoft.Reporting.WinForms.ZoomMode.PageWidth;
            //
            // usp_PolizaByIdUsuarioTableAdapter
            //
            this.usp_PolizaByIdUsuarioTableAdapter.ClearBeforeFill = true;
            //
            // frmRptPolizaByIdUsuario
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.rptVisor);
            this.Controls.Add(this.tspBarraSuperior);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmRptPolizaByIdUsuario";
            this.Text = "frmRptPolizaByIdUsuario";
            this.Load += new System.EventHandler(this.frmRptPolizaByIdUsuario_Load);
            ((System.ComponentModel.ISupportInitialize)(this.uspPolizaByIdUsuarioBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataSetReportes)).EndInit();
            this.tspBarraSuperior.ResumeLayout(false);
            this.tspBarraSuperior.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References Capa.UI.Reporte.frmRptPolizaByIdUsuario.components, Capa.UI.Reporte.frmRptPolizaByIdUsuario.dataSetReportes, Capa.UI.Reporte.frmRptPolizaByIdUsuario.frmRptPolizaByIdUsuario_Load(), Capa.UI.Reporte.frmRptPolizaByIdUsuario.rptVisor, Capa.UI.Reporte.DataSetReportes.SchemaSerializationMode, Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripBtnBuscar, Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripBtnBuscar_Click(), Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripBtnSalir, Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripBtnSalir_Click(), Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripTxtId, Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripTxtId_Enter(), Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripTxtId_Leave(), Capa.UI.Reporte.frmRptPolizaByIdUsuario.tspBarraSuperior, Capa.UI.Reporte.frmRptPolizaByIdUsuario.usp_PolizaByIdUsuarioTableAdapter, and Capa.UI.Reporte.frmRptPolizaByIdUsuario.uspPolizaByIdUsuarioBindingSource.
Referenced by Capa.UI.Reporte.frmRptPolizaByIdUsuario.frmRptPolizaByIdUsuario().
toolStripBtnBuscar_Click()
void Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripBtnBuscar_Click (object sender, EventArgs e) private
Definition at line 40 of file frmRptPolizaByIdUsuario.cs.
        {
            if (toolStripTxtId.Text == "" || toolStripTxtId.Text == "Identificación")
            {
                MessageBox.Show("Debe digitar la identificación");
                return;
            }
            try
            {
                this.usp_PolizaByIdUsuarioTableAdapter.Fill(this.dataSetReportes.usp_PolizaByIdUsuario, toolStripTxtId.Text.Trim());
                this.rptVisor.RefreshReport();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Reporte.frmRptPolizaByIdUsuario._MyLogControlEventos, Capa.UI.Reporte.frmRptPolizaByIdUsuario.dataSetReportes, Capa.UI.Reporte.frmRptPolizaByIdUsuario.rptVisor, Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripTxtId, Capa.UI.Reporte.DataSetReportes.usp_PolizaByIdUsuario, and Capa.UI.Reporte.frmRptPolizaByIdUsuario.usp_PolizaByIdUsuarioTableAdapter.
Referenced by Capa.UI.Reporte.frmRptPolizaByIdUsuario.InitializeComponent().
toolStripBtnSalir_Click()
void Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripBtnSalir_Click (object sender, EventArgs e) private
Definition at line 66 of file frmRptPolizaByIdUsuario.cs.
        {
            this.Close();
        }
Referenced by Capa.UI.Reporte.frmRptPolizaByIdUsuario.InitializeComponent().
toolStripTxtId_Enter()
void Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripTxtId_Enter (object sender, EventArgs e) private
Definition at line 22 of file frmRptPolizaByIdUsuario.cs.
        {
            if (toolStripTxtId.Text.Equals("Identificación"))
            {
                toolStripTxtId.Text = "";
                toolStripTxtId.ForeColor = Color.White;
            }
        }
References Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripTxtId.
Referenced by Capa.UI.Reporte.frmRptPolizaByIdUsuario.InitializeComponent().
toolStripTxtId_Leave()
void Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripTxtId_Leave (object sender, EventArgs e) private
Definition at line 31 of file frmRptPolizaByIdUsuario.cs.
        {
            if (toolStripTxtId.Text == "")
            {
                toolStripTxtId.Text = "Identificación";
                toolStripTxtId.ForeColor = Color.White;
            }
        }
References Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripTxtId.
Referenced by Capa.UI.Reporte.frmRptPolizaByIdUsuario.InitializeComponent().
Member Data Documentation
_MyLogControlEventos
readonly ILog Capa.UI.Reporte.frmRptPolizaByIdUsuario._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 16 of file frmRptPolizaByIdUsuario.cs.
Referenced by Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripBtnBuscar_Click().
components
System.ComponentModel.IContainer Capa.UI.Reporte.frmRptPolizaByIdUsuario.components = null private
Required designer variable.
Definition at line 8 of file frmRptPolizaByIdUsuario.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptPolizaByIdUsuario.Dispose(), and Capa.UI.Reporte.frmRptPolizaByIdUsuario.InitializeComponent().
dataSetReportes
DataSetReportes Capa.UI.Reporte.frmRptPolizaByIdUsuario.dataSetReportes private
Definition at line 149 of file frmRptPolizaByIdUsuario.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptPolizaByIdUsuario.InitializeComponent(), and Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripBtnBuscar_Click().
rptVisor
Microsoft.Reporting.WinForms.ReportViewer Capa.UI.Reporte.frmRptPolizaByIdUsuario.rptVisor private
Definition at line 147 of file frmRptPolizaByIdUsuario.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptPolizaByIdUsuario.frmRptPolizaByIdUsuario_Load(), Capa.UI.Reporte.frmRptPolizaByIdUsuario.InitializeComponent(), and Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripBtnBuscar_Click().
toolStripBtnBuscar
System.Windows.Forms.ToolStripButton Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripBtnBuscar private
Definition at line 146 of file frmRptPolizaByIdUsuario.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptPolizaByIdUsuario.InitializeComponent().
toolStripBtnSalir
System.Windows.Forms.ToolStripButton Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripBtnSalir private
Definition at line 144 of file frmRptPolizaByIdUsuario.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptPolizaByIdUsuario.InitializeComponent().
toolStripTxtId
System.Windows.Forms.ToolStripTextBox Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripTxtId private
Definition at line 145 of file frmRptPolizaByIdUsuario.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptPolizaByIdUsuario.InitializeComponent(), Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripBtnBuscar_Click(), Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripTxtId_Enter(), and Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripTxtId_Leave().
tspBarraSuperior
System.Windows.Forms.ToolStrip Capa.UI.Reporte.frmRptPolizaByIdUsuario.tspBarraSuperior private
Definition at line 143 of file frmRptPolizaByIdUsuario.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptPolizaByIdUsuario.InitializeComponent().
usp_PolizaByIdUsuarioTableAdapter
DataSetReportesTableAdapters.usp_PolizaByIdUsuarioTableAdapter Capa.UI.Reporte.frmRptPolizaByIdUsuario.usp_PolizaByIdUsuarioTableAdapter private
Definition at line 150 of file frmRptPolizaByIdUsuario.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptPolizaByIdUsuario.InitializeComponent(), and Capa.UI.Reporte.frmRptPolizaByIdUsuario.toolStripBtnBuscar_Click().
uspPolizaByIdUsuarioBindingSource
System.Windows.Forms.BindingSource Capa.UI.Reporte.frmRptPolizaByIdUsuario.uspPolizaByIdUsuarioBindingSource private
Definition at line 148 of file frmRptPolizaByIdUsuario.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptPolizaByIdUsuario.InitializeComponent().
The documentation for this class was generated from the following files:
Capa.UI/Reporte/frmRptPolizaByIdUsuario.cs
Capa.UI/Reporte/frmRptPolizaByIdUsuario.Designer.cs