Proyecto Autos Seguros: Capa.UI.Reporte.frmRptVentasByDia Class Reference
Capa.UI.Reporte.frmRptVentasByDia Class Reference
Public Member Functions
frmRptVentasByDia ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void frmRptVentasByDia_Load (object sender, EventArgs e)
void toolStripBtnSalir_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
Microsoft.Reporting.WinForms.ReportViewer reportViewer1
DataSetReportes dataSetReportes
System.Windows.Forms.BindingSource uspSELECTVentasByDiaBindingSource
DataSetReportesTableAdapters.usp_SELECT_VentasByDiaTableAdapter usp_SELECT_VentasByDiaTableAdapter
System.Windows.Forms.ToolStrip tspBarraSuperior
System.Windows.Forms.ToolStripButton toolStripBtnSalir
Detailed Description
Definition at line 13 of file frmRptVentasByDia.cs.
Constructor & Destructor Documentation
frmRptVentasByDia()
Capa.UI.Reporte.frmRptVentasByDia.frmRptVentasByDia ()
Definition at line 15 of file frmRptVentasByDia.cs.
        {
            InitializeComponent();
        }
References Capa.UI.Reporte.frmRptVentasByDia.InitializeComponent().
Member Function Documentation
Dispose()
override void Capa.UI.Reporte.frmRptVentasByDia.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file frmRptVentasByDia.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References Capa.UI.Reporte.frmRptVentasByDia.components.
frmRptVentasByDia_Load()
void Capa.UI.Reporte.frmRptVentasByDia.frmRptVentasByDia_Load (object sender, EventArgs e) private
Definition at line 20 of file frmRptVentasByDia.cs.
        {
            // TODO: This line of code loads data into the 'dataSetReportes.usp_SELECT_VentasByDia' table. You can move, or remove it, as needed.
            this.usp_SELECT_VentasByDiaTableAdapter.Fill(this.dataSetReportes.usp_SELECT_VentasByDia);
            this.reportViewer1.RefreshReport();
        }
References Capa.UI.Reporte.frmRptVentasByDia.dataSetReportes, Capa.UI.Reporte.frmRptVentasByDia.reportViewer1, Capa.UI.Reporte.DataSetReportes.usp_SELECT_VentasByDia, and Capa.UI.Reporte.frmRptVentasByDia.usp_SELECT_VentasByDiaTableAdapter.
Referenced by Capa.UI.Reporte.frmRptVentasByDia.InitializeComponent().
InitializeComponent()
void Capa.UI.Reporte.frmRptVentasByDia.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file frmRptVentasByDia.Designer.cs.
        {
            this.components = new System.ComponentModel.Container();
            Microsoft.Reporting.WinForms.ReportDataSource reportDataSource1 = new Microsoft.Reporting.WinForms.ReportDataSource();
            this.uspSELECTVentasByDiaBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.dataSetReportes = new Capa.UI.Reporte.DataSetReportes();
            this.reportViewer1 = new Microsoft.Reporting.WinForms.ReportViewer();
            this.usp_SELECT_VentasByDiaTableAdapter = new Capa.UI.Reporte.DataSetReportesTableAdapters.usp_SELECT_VentasByDiaTableAdapter();
            this.tspBarraSuperior = new System.Windows.Forms.ToolStrip();
            this.toolStripBtnSalir = new System.Windows.Forms.ToolStripButton();
            ((System.ComponentModel.ISupportInitialize)(this.uspSELECTVentasByDiaBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataSetReportes)).BeginInit();
            this.tspBarraSuperior.SuspendLayout();
            this.SuspendLayout();
            //
            // uspSELECTVentasByDiaBindingSource
            //
            this.uspSELECTVentasByDiaBindingSource.DataMember = "usp_SELECT_VentasByDia";
            this.uspSELECTVentasByDiaBindingSource.DataSource = this.dataSetReportes;
            //
            // dataSetReportes
            //
            this.dataSetReportes.DataSetName = "DataSetReportes";
            this.dataSetReportes.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            //
            // reportViewer1
            //
            reportDataSource1.Name = "DataSet1";
            reportDataSource1.Value = this.uspSELECTVentasByDiaBindingSource;
            this.reportViewer1.LocalReport.DataSources.Add(reportDataSource1);
            this.reportViewer1.LocalReport.ReportEmbeddedResource = "Capa.UI.Reporte.rptVentasByDia.rdlc";
            this.reportViewer1.Location = new System.Drawing.Point(0, 28);
            this.reportViewer1.Name = "reportViewer1";
            this.reportViewer1.ServerReport.BearerToken = null;
            this.reportViewer1.Size = new System.Drawing.Size(800, 424);
            this.reportViewer1.TabIndex = 0;
            this.reportViewer1.ZoomMode = Microsoft.Reporting.WinForms.ZoomMode.PageWidth;
            //
            // usp_SELECT_VentasByDiaTableAdapter
            //
            this.usp_SELECT_VentasByDiaTableAdapter.ClearBeforeFill = true;
            //
            // tspBarraSuperior
            //
            this.tspBarraSuperior.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.tspBarraSuperior.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripBtnSalir});
            this.tspBarraSuperior.Location = new System.Drawing.Point(0, 0);
            this.tspBarraSuperior.Name = "tspBarraSuperior";
            this.tspBarraSuperior.Size = new System.Drawing.Size(800, 25);
            this.tspBarraSuperior.TabIndex = 6;
            this.tspBarraSuperior.Text = "toolStrip1";
            //
            // toolStripBtnSalir
            //
            this.toolStripBtnSalir.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnSalir.ForeColor = System.Drawing.Color.White;
            this.toolStripBtnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnSalir.Name = "toolStripBtnSalir";
            this.toolStripBtnSalir.Size = new System.Drawing.Size(39, 22);
            this.toolStripBtnSalir.Text = "Salir";
            this.toolStripBtnSalir.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnSalir.Click += new System.EventHandler(this.toolStripBtnSalir_Click);
            //
            // frmRptVentasByDia
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.tspBarraSuperior);
            this.Controls.Add(this.reportViewer1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmRptVentasByDia";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmRptVentasByDia";
            this.Load += new System.EventHandler(this.frmRptVentasByDia_Load);
            ((System.ComponentModel.ISupportInitialize)(this.uspSELECTVentasByDiaBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataSetReportes)).EndInit();
            this.tspBarraSuperior.ResumeLayout(false);
            this.tspBarraSuperior.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References Capa.UI.Reporte.frmRptVentasByDia.components, Capa.UI.Reporte.frmRptVentasByDia.dataSetReportes, Capa.UI.Reporte.frmRptVentasByDia.frmRptVentasByDia_Load(), Capa.UI.Reporte.frmRptVentasByDia.reportViewer1, Capa.UI.Reporte.DataSetReportes.SchemaSerializationMode, Capa.UI.Reporte.frmRptVentasByDia.toolStripBtnSalir, Capa.UI.Reporte.frmRptVentasByDia.toolStripBtnSalir_Click(), Capa.UI.Reporte.frmRptVentasByDia.tspBarraSuperior, Capa.UI.Reporte.frmRptVentasByDia.usp_SELECT_VentasByDiaTableAdapter, and Capa.UI.Reporte.frmRptVentasByDia.uspSELECTVentasByDiaBindingSource.
Referenced by Capa.UI.Reporte.frmRptVentasByDia.frmRptVentasByDia().
toolStripBtnSalir_Click()
void Capa.UI.Reporte.frmRptVentasByDia.toolStripBtnSalir_Click (object sender, EventArgs e) private
Definition at line 28 of file frmRptVentasByDia.cs.
        {
            this.Close();
        }
Referenced by Capa.UI.Reporte.frmRptVentasByDia.InitializeComponent().
Member Data Documentation
components
System.ComponentModel.IContainer Capa.UI.Reporte.frmRptVentasByDia.components = null private
Required designer variable.
Definition at line 8 of file frmRptVentasByDia.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptVentasByDia.Dispose(), and Capa.UI.Reporte.frmRptVentasByDia.InitializeComponent().
dataSetReportes
DataSetReportes Capa.UI.Reporte.frmRptVentasByDia.dataSetReportes private
Definition at line 118 of file frmRptVentasByDia.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptVentasByDia.frmRptVentasByDia_Load(), and Capa.UI.Reporte.frmRptVentasByDia.InitializeComponent().
reportViewer1
Microsoft.Reporting.WinForms.ReportViewer Capa.UI.Reporte.frmRptVentasByDia.reportViewer1 private
Definition at line 117 of file frmRptVentasByDia.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptVentasByDia.frmRptVentasByDia_Load(), and Capa.UI.Reporte.frmRptVentasByDia.InitializeComponent().
toolStripBtnSalir
System.Windows.Forms.ToolStripButton Capa.UI.Reporte.frmRptVentasByDia.toolStripBtnSalir private
Definition at line 122 of file frmRptVentasByDia.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptVentasByDia.InitializeComponent().
tspBarraSuperior
System.Windows.Forms.ToolStrip Capa.UI.Reporte.frmRptVentasByDia.tspBarraSuperior private
Definition at line 121 of file frmRptVentasByDia.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptVentasByDia.InitializeComponent().
usp_SELECT_VentasByDiaTableAdapter
DataSetReportesTableAdapters.usp_SELECT_VentasByDiaTableAdapter Capa.UI.Reporte.frmRptVentasByDia.usp_SELECT_VentasByDiaTableAdapter private
Definition at line 120 of file frmRptVentasByDia.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptVentasByDia.frmRptVentasByDia_Load(), and Capa.UI.Reporte.frmRptVentasByDia.InitializeComponent().
uspSELECTVentasByDiaBindingSource
System.Windows.Forms.BindingSource Capa.UI.Reporte.frmRptVentasByDia.uspSELECTVentasByDiaBindingSource private
Definition at line 119 of file frmRptVentasByDia.Designer.cs.
Referenced by Capa.UI.Reporte.frmRptVentasByDia.InitializeComponent().
The documentation for this class was generated from the following files:
Capa.UI/Reporte/frmRptVentasByDia.cs
Capa.UI/Reporte/frmRptVentasByDia.Designer.cs