Proyecto Autos Seguros: BLL.FacturaBLL Class Reference
BLL.FacturaBLL Class Reference
Public Member Functions
void AnularFactura (int idFactura)
void Eliminar (int idFactura)
void Insertar (Factura factura)
Validaciones para ver si el usuario cumple con los requisitos mínimos para obtener una poliza
List< Factura > SeleccionarFacturaHoy ()
List< Factura > SeleccionarFacturasAnuladas ()
Factura SeleccionarPorId (int idFactura)
List< Factura > SeleccionarTodas ()
void Insertar (Factura encFactura)
void Eliminar (int idFactura)
List< Factura > SeleccionarTodas ()
Factura SeleccionarPorId (int idFactura)
List< Factura > SeleccionarFacturaHoy ()
void AnularFactura (int idFactura)
List< Factura > SeleccionarFacturasAnuladas ()
Detailed Description
Definition at line 13 of file FacturaBLL.cs.
Member Function Documentation
AnularFactura()
void BLL.FacturaBLL.AnularFactura (int idFactura)
Implements Interfaces.IFacturaBLL.
Definition at line 15 of file FacturaBLL.cs.
        {
            IFacturaDAL logica = new FacturaDAL();
            logica.AnularFactura(idFactura);
        }
References Interfaces.IFacturaDAL.AnularFactura().
Eliminar()
void BLL.FacturaBLL.Eliminar (int idFactura)
Implements Interfaces.IFacturaBLL.
Definition at line 21 of file FacturaBLL.cs.
        {
            IFacturaDAL logica = new FacturaDAL();
            logica.Eliminar(idFactura);
        }
References Interfaces.IFacturaDAL.Eliminar().
Insertar()
void BLL.FacturaBLL.Insertar (Factura factura)
Validaciones para ver si el usuario cumple con los requisitos mínimos para obtener una poliza
Parameters
factura
Exceptions
ApplicationException
Implements Interfaces.IFacturaBLL.
Definition at line 31 of file FacturaBLL.cs.
        {
            IFacturaDAL logica = new FacturaDAL();
            IUsuarioBLL logicaUsuario = new UsuarioBLL();
            Usuario usuario = logicaUsuario.GetUsuarioById(factura.IdUsuario);
            if ((DateTime.Now.Year - usuario.FechaNacimiento.Year) < 18) {
                throw new ApplicationException("Debe ser mayor de 18 años");
            }
            if (usuario.PuntosLicencia <= 1) {
                throw new ApplicationException("Cantidad de puntos por debajo de lo permitido ");
            }
            if (usuario.PuntosLicencia > 6)
            {
                throw new ApplicationException("Cantidad de puntos inválida. Máximo 6");
            }
            logica.Insertar(factura);
        }
References Entities.Usuario.FechaNacimiento, Interfaces.IUsuarioBLL.GetUsuarioById(), capa.Entidades.Factura.IdUsuario, Interfaces.IFacturaDAL.Insertar(), and Entities.Usuario.PuntosLicencia.
SeleccionarFacturaHoy()
List< Factura > BLL.FacturaBLL.SeleccionarFacturaHoy ()
Implements Interfaces.IFacturaBLL.
Definition at line 52 of file FacturaBLL.cs.
        {
            IFacturaDAL logica = new FacturaDAL();
            return (List<Factura>)logica.SeleccionarFacturaHoy();
        }
References Interfaces.IFacturaDAL.SeleccionarFacturaHoy().
SeleccionarFacturasAnuladas()
List< Factura > BLL.FacturaBLL.SeleccionarFacturasAnuladas ()
Implements Interfaces.IFacturaBLL.
Definition at line 58 of file FacturaBLL.cs.
        {
            IFacturaDAL logica = new FacturaDAL();
            return (List<Factura>)logica.SeleccionarFacturasAnuladas();
        }
References Interfaces.IFacturaDAL.SeleccionarFacturasAnuladas().
SeleccionarPorId()
Factura BLL.FacturaBLL.SeleccionarPorId (int idFactura)
Implements Interfaces.IFacturaBLL.
Definition at line 64 of file FacturaBLL.cs.
        {
            IFacturaDAL logica = new FacturaDAL();
            return logica.SeleccionarPorId(idFactura);
        }
References Interfaces.IFacturaDAL.SeleccionarPorId().
SeleccionarTodas()
List< Factura > BLL.FacturaBLL.SeleccionarTodas ()
Implements Interfaces.IFacturaBLL.
Definition at line 70 of file FacturaBLL.cs.
        {
            IFacturaDAL logica = new FacturaDAL();
            return (List<Factura>)logica.SeleccionarTodas();
        }
References Interfaces.IFacturaDAL.SeleccionarTodas().
The documentation for this class was generated from the following file:
BLL/FacturaBLL.cs