Proyecto Autos Seguros: Capa.UI.Mantenimientos.frmMantenimientoCoberturas Class Reference
Capa.UI.Mantenimientos.frmMantenimientoCoberturas Class Reference
Public Member Functions
frmMantenimientoCoberturas ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void CargarDatos ()
void CambiarEstadoMantenimiento (EstadoMantenimiento estado)
Cambia el estado matenimiento según el enum
void toolStripBtnNuevo_Click (object sender, EventArgs e)
Limpia los campos
void toolStripBtnEditar_Click (object sender, EventArgs e)
Selecciona el registro del dgv para editarlo
void toolStripBtnEliminar_Click (object sender, EventArgs e)
Selecciona el registro para eliminarlo
void toolStripBtnSalir_Click (object sender, EventArgs e)
void btnAceptar_Click (object sender, EventArgs e)
Valida los campos, crea el objeto tipo cobertura y lo guarda en la base de datos
void frmMantenimientoCoberturas_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
EstadoMantenimiento estadoMantenimiento
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.ToolStrip tspMantenimientos
System.Windows.Forms.ToolStripButton toolStripBtnNuevo
System.Windows.Forms.ToolStripButton toolStripBtnEditar
System.Windows.Forms.ToolStripButton toolStripBtnEliminar
System.Windows.Forms.ToolStripButton toolStripBtnSalir
System.Windows.Forms.SplitContainer splitContainer1
System.Windows.Forms.DataGridView dgvDatos
System.Windows.Forms.Label lblPrecio
System.Windows.Forms.TextBox txtPrecio
System.Windows.Forms.Label lblDescripcion
System.Windows.Forms.TextBox txtDescripcion
System.Windows.Forms.TextBox txtId
System.Windows.Forms.Button btnCancelar
System.Windows.Forms.Button btnAceptar
System.Windows.Forms.DataGridViewTextBoxColumn Id
System.Windows.Forms.DataGridViewTextBoxColumn Descripcion
System.Windows.Forms.DataGridViewTextBoxColumn Precio
System.Windows.Forms.DataGridViewTextBoxColumn Total
Static Private Attributes
static readonly ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 18 of file frmMantenimientoCoberturas.cs.
Constructor & Destructor Documentation
frmMantenimientoCoberturas()
Capa.UI.Mantenimientos.frmMantenimientoCoberturas.frmMantenimientoCoberturas ()
Definition at line 22 of file frmMantenimientoCoberturas.cs.
        {
            InitializeComponent();
        }
References Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
Member Function Documentation
btnAceptar_Click()
void Capa.UI.Mantenimientos.frmMantenimientoCoberturas.btnAceptar_Click (object sender, EventArgs e) private
Valida los campos, crea el objeto tipo cobertura y lo guarda en la base de datos
Parameters
sender
e
Definition at line 185 of file frmMantenimientoCoberturas.cs.
        {
            int resultado = 0;
            ErrorProvider oErrorProvider = new ErrorProvider();
            if (txtPrecio.Text == "") {
                oErrorProvider.SetError(txtPrecio, "Digite un precio");
                return;
            }
            if (txtDescripcion.Text == "")
            {
                oErrorProvider.SetError(txtDescripcion, "Digite una descripción");
                return;
            }
            try
            {
                Cobertura cobertura = new Cobertura();
                if (estadoMantenimiento == EstadoMantenimiento.Editar)
                {
                    cobertura.Id = Int32.Parse(txtId.Text);
                }
                cobertura.Descripcion = txtDescripcion.Text;
                cobertura.Precio = Decimal.Parse(txtPrecio.Text);
                ICoberturaBLL logica = new CoberturaBLL();
                logica.Insertar(cobertura);
                CargarDatos();
                CambiarEstadoMantenimiento(EstadoMantenimiento.Ninguno);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Mantenimientos.frmMantenimientoCoberturas._MyLogControlEventos, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.CambiarEstadoMantenimiento(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.CargarDatos(), Entities.Cobertura.Descripcion, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.estadoMantenimiento, Entities.Cobertura.Id, Interfaces.ICoberturaBLL.Insertar(), Entities.Cobertura.Precio, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.txtDescripcion, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.txtId, and Capa.UI.Mantenimientos.frmMantenimientoCoberturas.txtPrecio.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
CambiarEstadoMantenimiento()
void Capa.UI.Mantenimientos.frmMantenimientoCoberturas.CambiarEstadoMantenimiento (EstadoMantenimiento estado) private
Cambia el estado matenimiento según el enum
Parameters
estado
Definition at line 49 of file frmMantenimientoCoberturas.cs.
        {
            txtDescripcion.Clear();
            txtId.Clear();
            txtPrecio.Clear();
            txtDescripcion.Enabled = false;
            txtId.Enabled = false;
            txtPrecio.Enabled = false;
            switch (estado)
            {
                case EstadoMantenimiento.Nuevo:
                    txtDescripcion.Enabled = true;
                    txtId.Enabled = true;
                    txtPrecio.Enabled = true;
                    txtDescripcion.Focus();
                    estadoMantenimiento = EstadoMantenimiento.Nuevo;
                    break;
                case EstadoMantenimiento.Editar:
                    txtDescripcion.Enabled = true;
                    txtId.Enabled = true;
                    txtPrecio.Enabled = true;
                    txtDescripcion.Focus();
                    estadoMantenimiento = EstadoMantenimiento.Editar;
                    break;
                case EstadoMantenimiento.Borrar:
                    estadoMantenimiento = EstadoMantenimiento.Borrar;
                    break;
                case EstadoMantenimiento.Ninguno:
                    estadoMantenimiento = EstadoMantenimiento.Ninguno;
                    break;
            }
        }
References Capa.UI.Mantenimientos.frmMantenimientoCoberturas.estadoMantenimiento, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.txtDescripcion, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.txtId, and Capa.UI.Mantenimientos.frmMantenimientoCoberturas.txtPrecio.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnEditar_Click(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnEliminar_Click(), and Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnNuevo_Click().
CargarDatos()
void Capa.UI.Mantenimientos.frmMantenimientoCoberturas.CargarDatos () private
Definition at line 26 of file frmMantenimientoCoberturas.cs.
        {
            try
            {
                dgvDatos.AutoGenerateColumns = false;
                dgvDatos.RowTemplate.Height = 100;
                dgvDatos.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
                ICoberturaBLL logica = new CoberturaBLL();
                dgvDatos.DataSource = logica.SeleccionarTodas();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Mantenimientos.frmMantenimientoCoberturas._MyLogControlEventos, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.dgvDatos, and Interfaces.ICoberturaBLL.SeleccionarTodas().
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.frmMantenimientoCoberturas_Load(), and Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnEliminar_Click().
Dispose()
override void Capa.UI.Mantenimientos.frmMantenimientoCoberturas.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file frmMantenimientoCoberturas.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References Capa.UI.Mantenimientos.frmMantenimientoCoberturas.components.
frmMantenimientoCoberturas_Load()
void Capa.UI.Mantenimientos.frmMantenimientoCoberturas.frmMantenimientoCoberturas_Load (object sender, EventArgs e) private
Definition at line 226 of file frmMantenimientoCoberturas.cs.
        {
            CargarDatos();
        }
References Capa.UI.Mantenimientos.frmMantenimientoCoberturas.CargarDatos().
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
InitializeComponent()
void Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file frmMantenimientoCoberturas.Designer.cs.
        {
            this.tspMantenimientos = new System.Windows.Forms.ToolStrip();
            this.toolStripBtnNuevo = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnEditar = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnEliminar = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnSalir = new System.Windows.Forms.ToolStripButton();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.dgvDatos = new System.Windows.Forms.DataGridView();
            this.Id = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Descripcion = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Precio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Total = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.txtId = new System.Windows.Forms.TextBox();
            this.btnCancelar = new System.Windows.Forms.Button();
            this.btnAceptar = new System.Windows.Forms.Button();
            this.lblPrecio = new System.Windows.Forms.Label();
            this.txtPrecio = new System.Windows.Forms.TextBox();
            this.lblDescripcion = new System.Windows.Forms.Label();
            this.txtDescripcion = new System.Windows.Forms.TextBox();
            this.tspMantenimientos.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDatos)).BeginInit();
            this.SuspendLayout();
            //
            // tspMantenimientos
            //
            this.tspMantenimientos.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.tspMantenimientos.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripBtnNuevo,
            this.toolStripBtnEditar,
            this.toolStripBtnEliminar,
            this.toolStripBtnSalir});
            this.tspMantenimientos.Location = new System.Drawing.Point(0, 0);
            this.tspMantenimientos.Name = "tspMantenimientos";
            this.tspMantenimientos.Size = new System.Drawing.Size(792, 25);
            this.tspMantenimientos.TabIndex = 52;
            this.tspMantenimientos.Text = "toolStrip1";
            //
            // toolStripBtnNuevo
            //
            this.toolStripBtnNuevo.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.toolStripBtnNuevo.ForeColor = System.Drawing.Color.White;
            this.toolStripBtnNuevo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnNuevo.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnNuevo.Name = "toolStripBtnNuevo";
            this.toolStripBtnNuevo.Size = new System.Drawing.Size(52, 22);
            this.toolStripBtnNuevo.Text = "Nuevo";
            this.toolStripBtnNuevo.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnNuevo.Click += new System.EventHandler(this.toolStripBtnNuevo_Click);
            //
            // toolStripBtnEditar
            //
            this.toolStripBtnEditar.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnEditar.ForeColor = System.Drawing.Color.White;
            this.toolStripBtnEditar.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnEditar.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnEditar.Name = "toolStripBtnEditar";
            this.toolStripBtnEditar.Size = new System.Drawing.Size(48, 22);
            this.toolStripBtnEditar.Text = "Editar";
            this.toolStripBtnEditar.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.toolStripBtnEditar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnEditar.Click += new System.EventHandler(this.toolStripBtnEditar_Click);
            //
            // toolStripBtnEliminar
            //
            this.toolStripBtnEliminar.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnEliminar.ForeColor = System.Drawing.Color.White;
            this.toolStripBtnEliminar.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnEliminar.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnEliminar.Name = "toolStripBtnEliminar";
            this.toolStripBtnEliminar.Size = new System.Drawing.Size(63, 22);
            this.toolStripBtnEliminar.Text = "Eliminar";
            this.toolStripBtnEliminar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnEliminar.Click += new System.EventHandler(this.toolStripBtnEliminar_Click);
            //
            // toolStripBtnSalir
            //
            this.toolStripBtnSalir.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnSalir.ForeColor = System.Drawing.Color.White;
            this.toolStripBtnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnSalir.Name = "toolStripBtnSalir";
            this.toolStripBtnSalir.Size = new System.Drawing.Size(39, 22);
            this.toolStripBtnSalir.Text = "Salir";
            this.toolStripBtnSalir.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnSalir.Click += new System.EventHandler(this.toolStripBtnSalir_Click);
            //
            // splitContainer1
            //
            this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer1.Location = new System.Drawing.Point(0, 25);
            this.splitContainer1.Name = "splitContainer1";
            //
            // splitContainer1.Panel1
            //
            this.splitContainer1.Panel1.Controls.Add(this.dgvDatos);
            //
            // splitContainer1.Panel2
            //
            this.splitContainer1.Panel2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.splitContainer1.Panel2.Controls.Add(this.txtId);
            this.splitContainer1.Panel2.Controls.Add(this.btnCancelar);
            this.splitContainer1.Panel2.Controls.Add(this.btnAceptar);
            this.splitContainer1.Panel2.Controls.Add(this.lblPrecio);
            this.splitContainer1.Panel2.Controls.Add(this.txtPrecio);
            this.splitContainer1.Panel2.Controls.Add(this.lblDescripcion);
            this.splitContainer1.Panel2.Controls.Add(this.txtDescripcion);
            this.splitContainer1.Size = new System.Drawing.Size(792, 516);
            this.splitContainer1.SplitterDistance = 342;
            this.splitContainer1.TabIndex = 53;
            //
            // dgvDatos
            //
            this.dgvDatos.AllowUserToAddRows = false;
            this.dgvDatos.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvDatos.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Id,
            this.Descripcion,
            this.Precio,
            this.Total});
            this.dgvDatos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvDatos.Location = new System.Drawing.Point(0, 0);
            this.dgvDatos.Name = "dgvDatos";
            this.dgvDatos.ReadOnly = true;
            this.dgvDatos.Size = new System.Drawing.Size(342, 516);
            this.dgvDatos.TabIndex = 24;
            //
            // Id
            //
            this.Id.DataPropertyName = "Id";
            this.Id.HeaderText = "Id";
            this.Id.Name = "Id";
            this.Id.ReadOnly = true;
            //
            // Descripcion
            //
            this.Descripcion.DataPropertyName = "Descripcion";
            this.Descripcion.HeaderText = "Descripcion";
            this.Descripcion.Name = "Descripcion";
            this.Descripcion.ReadOnly = true;
            //
            // Precio
            //
            this.Precio.DataPropertyName = "Precio";
            this.Precio.HeaderText = "Precio";
            this.Precio.Name = "Precio";
            this.Precio.ReadOnly = true;
            //
            // Total
            //
            this.Total.DataPropertyName = "Total";
            this.Total.HeaderText = "Precio+IVA";
            this.Total.Name = "Total";
            this.Total.ReadOnly = true;
            //
            // txtId
            //
            this.txtId.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(138)))), ((int)(((byte)(181)))));
            this.txtId.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtId.Enabled = false;
            this.txtId.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtId.ForeColor = System.Drawing.Color.White;
            this.txtId.Location = new System.Drawing.Point(136, 30);
            this.txtId.Name = "txtId";
            this.txtId.Size = new System.Drawing.Size(167, 27);
            this.txtId.TabIndex = 143;
            this.txtId.Visible = false;
            //
            // btnCancelar
            //
            this.btnCancelar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(138)))), ((int)(((byte)(181)))));
            this.btnCancelar.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnCancelar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCancelar.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancelar.ForeColor = System.Drawing.Color.White;
            this.btnCancelar.Location = new System.Drawing.Point(457, 443);
            this.btnCancelar.Name = "btnCancelar";
            this.btnCancelar.Size = new System.Drawing.Size(167, 45);
            this.btnCancelar.TabIndex = 142;
            this.btnCancelar.Text = "Cancelar";
            this.btnCancelar.UseVisualStyleBackColor = false;
            //
            // btnAceptar
            //
            this.btnAceptar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(138)))), ((int)(((byte)(181)))));
            this.btnAceptar.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnAceptar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAceptar.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAceptar.ForeColor = System.Drawing.Color.White;
            this.btnAceptar.Location = new System.Drawing.Point(136, 443);
            this.btnAceptar.Name = "btnAceptar";
            this.btnAceptar.Size = new System.Drawing.Size(167, 45);
            this.btnAceptar.TabIndex = 141;
            this.btnAceptar.Text = "Aceptar";
            this.btnAceptar.UseVisualStyleBackColor = false;
            this.btnAceptar.Click += new System.EventHandler(this.btnAceptar_Click);
            //
            // lblPrecio
            //
            this.lblPrecio.AutoSize = true;
            this.lblPrecio.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPrecio.ForeColor = System.Drawing.Color.White;
            this.lblPrecio.Location = new System.Drawing.Point(276, 89);
            this.lblPrecio.Name = "lblPrecio";
            this.lblPrecio.Size = new System.Drawing.Size(47, 16);
            this.lblPrecio.TabIndex = 139;
            this.lblPrecio.Text = "Precio";
            this.lblPrecio.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            //
            // txtPrecio
            //
            this.txtPrecio.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(138)))), ((int)(((byte)(181)))));
            this.txtPrecio.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtPrecio.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPrecio.ForeColor = System.Drawing.Color.White;
            this.txtPrecio.Location = new System.Drawing.Point(279, 108);
            this.txtPrecio.Name = "txtPrecio";
            this.txtPrecio.Size = new System.Drawing.Size(140, 27);
            this.txtPrecio.TabIndex = 140;
            //
            // lblDescripcion
            //
            this.lblDescripcion.AutoSize = true;
            this.lblDescripcion.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblDescripcion.ForeColor = System.Drawing.Color.White;
            this.lblDescripcion.Location = new System.Drawing.Point(14, 85);
            this.lblDescripcion.Name = "lblDescripcion";
            this.lblDescripcion.Size = new System.Drawing.Size(84, 16);
            this.lblDescripcion.TabIndex = 135;
            this.lblDescripcion.Text = "Descripción";
            this.lblDescripcion.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            //
            // txtDescripcion
            //
            this.txtDescripcion.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(138)))), ((int)(((byte)(181)))));
            this.txtDescripcion.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtDescripcion.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtDescripcion.ForeColor = System.Drawing.Color.White;
            this.txtDescripcion.Location = new System.Drawing.Point(17, 108);
            this.txtDescripcion.Name = "txtDescripcion";
            this.txtDescripcion.Size = new System.Drawing.Size(136, 27);
            this.txtDescripcion.TabIndex = 136;
            //
            // frmMantenimientoCoberturas
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(792, 541);
            this.Controls.Add(this.splitContainer1);
            this.Controls.Add(this.tspMantenimientos);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmMantenimientoCoberturas";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmMantenimientoCoberturas";
            this.Load += new System.EventHandler(this.frmMantenimientoCoberturas_Load);
            this.tspMantenimientos.ResumeLayout(false);
            this.tspMantenimientos.PerformLayout();
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            this.splitContainer1.Panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvDatos)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References Capa.UI.Mantenimientos.frmMantenimientoCoberturas.btnAceptar, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.btnCancelar, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.Descripcion, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.dgvDatos, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.frmMantenimientoCoberturas_Load(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.Id, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.lblDescripcion, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.lblPrecio, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.Precio, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.splitContainer1, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnEditar, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnEditar_Click(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnEliminar, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnEliminar_Click(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnNuevo, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnNuevo_Click(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnSalir, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnSalir_Click(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.Total, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.tspMantenimientos, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.txtDescripcion, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.txtId, and Capa.UI.Mantenimientos.frmMantenimientoCoberturas.txtPrecio.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.frmMantenimientoCoberturas().
toolStripBtnEditar_Click()
void Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnEditar_Click (object sender, EventArgs e) private
Selecciona el registro del dgv para editarlo
Parameters
sender
e
Definition at line 112 of file frmMantenimientoCoberturas.cs.
        {
            Cobertura oCobertura = null;
            try
            {
                if (this.dgvDatos.SelectedRows.Count > 0)
                {
                    // Cambiar de estado
                    this.CambiarEstadoMantenimiento(EstadoMantenimiento.Editar);
                    //Extraer el DTO seleccionado
                    oCobertura = this.dgvDatos.SelectedRows[0].DataBoundItem as Cobertura;
                    this.txtId.Text = oCobertura.Id.ToString();
                    this.txtDescripcion.Text = oCobertura.Descripcion.ToString();
                    this.txtPrecio.Text = oCobertura.Precio.ToString();
                }
                else
                {
                    MessageBox.Show("Seleccione el registro !", "", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Mantenimientos.frmMantenimientoCoberturas._MyLogControlEventos, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.CambiarEstadoMantenimiento(), Entities.Cobertura.Descripcion, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.dgvDatos, Entities.Cobertura.Id, Entities.Cobertura.Precio, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.txtDescripcion, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.txtId, and Capa.UI.Mantenimientos.frmMantenimientoCoberturas.txtPrecio.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
toolStripBtnEliminar_Click()
void Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnEliminar_Click (object sender, EventArgs e) private
Selecciona el registro para eliminarlo
Parameters
sender
e
Definition at line 147 of file frmMantenimientoCoberturas.cs.
        {
            ICoberturaBLL logica = new CoberturaBLL();
            try
            {
                if (this.dgvDatos.SelectedRows.Count > 0)
                {
                    this.CambiarEstadoMantenimiento(EstadoMantenimiento.Borrar);
                    Cobertura oCObertura = this.dgvDatos.SelectedRows[0].DataBoundItem as Cobertura;
                    if (MessageBox.Show($"¿Seguro que desea borrar el registro {oCObertura.Id} {oCObertura.Descripcion}?", "Confirmación", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
                    {
                        logica.Eliminar(oCObertura.Id);
                        this.CargarDatos();
                    }
                }
                else
                {
                    MessageBox.Show("Seleccione el registro !", "Atención", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Mantenimientos.frmMantenimientoCoberturas._MyLogControlEventos, Capa.UI.Mantenimientos.frmMantenimientoCoberturas.CambiarEstadoMantenimiento(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.CargarDatos(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.dgvDatos, Interfaces.ICoberturaBLL.Eliminar(), and Entities.Cobertura.Id.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
toolStripBtnNuevo_Click()
void Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnNuevo_Click (object sender, EventArgs e) private
Limpia los campos
Parameters
sender
e
Definition at line 94 of file frmMantenimientoCoberturas.cs.
        {
            try
            {
                this.CambiarEstadoMantenimiento(EstadoMantenimiento.Nuevo);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Mantenimientos.frmMantenimientoCoberturas._MyLogControlEventos, and Capa.UI.Mantenimientos.frmMantenimientoCoberturas.CambiarEstadoMantenimiento().
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
toolStripBtnSalir_Click()
void Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnSalir_Click (object sender, EventArgs e) private
Definition at line 176 of file frmMantenimientoCoberturas.cs.
        {
            this.Close();
        }
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
Member Data Documentation
_MyLogControlEventos
readonly ILog Capa.UI.Mantenimientos.frmMantenimientoCoberturas._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 21 of file frmMantenimientoCoberturas.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.CargarDatos(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnEditar_Click(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnEliminar_Click(), and Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnNuevo_Click().
btnAceptar
System.Windows.Forms.Button Capa.UI.Mantenimientos.frmMantenimientoCoberturas.btnAceptar private
Definition at line 316 of file frmMantenimientoCoberturas.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
btnCancelar
System.Windows.Forms.Button Capa.UI.Mantenimientos.frmMantenimientoCoberturas.btnCancelar private
Definition at line 315 of file frmMantenimientoCoberturas.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
components
System.ComponentModel.IContainer Capa.UI.Mantenimientos.frmMantenimientoCoberturas.components = null private
Required designer variable.
Definition at line 8 of file frmMantenimientoCoberturas.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.Dispose().
Descripcion
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoCoberturas.Descripcion private
Definition at line 318 of file frmMantenimientoCoberturas.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
dgvDatos
System.Windows.Forms.DataGridView Capa.UI.Mantenimientos.frmMantenimientoCoberturas.dgvDatos private
Definition at line 309 of file frmMantenimientoCoberturas.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.CargarDatos(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnEditar_Click(), and Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnEliminar_Click().
estadoMantenimiento
EstadoMantenimiento Capa.UI.Mantenimientos.frmMantenimientoCoberturas.estadoMantenimiento private
Definition at line 20 of file frmMantenimientoCoberturas.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.btnAceptar_Click(), and Capa.UI.Mantenimientos.frmMantenimientoCoberturas.CambiarEstadoMantenimiento().
Id
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoCoberturas.Id private
Definition at line 317 of file frmMantenimientoCoberturas.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
lblDescripcion
System.Windows.Forms.Label Capa.UI.Mantenimientos.frmMantenimientoCoberturas.lblDescripcion private
Definition at line 312 of file frmMantenimientoCoberturas.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
lblPrecio
System.Windows.Forms.Label Capa.UI.Mantenimientos.frmMantenimientoCoberturas.lblPrecio private
Definition at line 310 of file frmMantenimientoCoberturas.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
Precio
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoCoberturas.Precio private
Definition at line 319 of file frmMantenimientoCoberturas.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
splitContainer1
System.Windows.Forms.SplitContainer Capa.UI.Mantenimientos.frmMantenimientoCoberturas.splitContainer1 private
Definition at line 308 of file frmMantenimientoCoberturas.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
toolStripBtnEditar
System.Windows.Forms.ToolStripButton Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnEditar private
Definition at line 305 of file frmMantenimientoCoberturas.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
toolStripBtnEliminar
System.Windows.Forms.ToolStripButton Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnEliminar private
Definition at line 306 of file frmMantenimientoCoberturas.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
toolStripBtnNuevo
System.Windows.Forms.ToolStripButton Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnNuevo private
Definition at line 304 of file frmMantenimientoCoberturas.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
toolStripBtnSalir
System.Windows.Forms.ToolStripButton Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnSalir private
Definition at line 307 of file frmMantenimientoCoberturas.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
Total
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoCoberturas.Total private
Definition at line 320 of file frmMantenimientoCoberturas.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
tspMantenimientos
System.Windows.Forms.ToolStrip Capa.UI.Mantenimientos.frmMantenimientoCoberturas.tspMantenimientos private
Definition at line 303 of file frmMantenimientoCoberturas.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent().
txtDescripcion
System.Windows.Forms.TextBox Capa.UI.Mantenimientos.frmMantenimientoCoberturas.txtDescripcion private
Definition at line 313 of file frmMantenimientoCoberturas.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.CambiarEstadoMantenimiento(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent(), and Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnEditar_Click().
txtId
System.Windows.Forms.TextBox Capa.UI.Mantenimientos.frmMantenimientoCoberturas.txtId private
Definition at line 314 of file frmMantenimientoCoberturas.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.CambiarEstadoMantenimiento(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent(), and Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnEditar_Click().
txtPrecio
System.Windows.Forms.TextBox Capa.UI.Mantenimientos.frmMantenimientoCoberturas.txtPrecio private
Definition at line 311 of file frmMantenimientoCoberturas.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.CambiarEstadoMantenimiento(), Capa.UI.Mantenimientos.frmMantenimientoCoberturas.InitializeComponent(), and Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnEditar_Click().
The documentation for this class was generated from the following files:
Capa.UI/Mantenimientos/frmMantenimientoCoberturas.cs
Capa.UI/Mantenimientos/frmMantenimientoCoberturas.Designer.cs