Proyecto Autos Seguros: Capa.UI.Mantenimientos.frmMantenimientoAnulaFac Class Reference
Capa.UI.Mantenimientos.frmMantenimientoAnulaFac Class Reference
Public Member Functions
frmMantenimientoAnulaFac ()
void CargarDatos ()
Carga los datos en las tablas
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void frmMantenimientoAnulaFac_Load (object sender, EventArgs e)
void toolStripBtnEliminar_Click (object sender, EventArgs e)
Selecciona el registro y anula la factura
void toolStripBtnSalir_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.ToolStrip tspMantenimientos
System.Windows.Forms.ToolStripButton toolStripBtnEliminar
System.Windows.Forms.ToolStripButton toolStripBtnSalir
System.Windows.Forms.DataGridView dgvDatos
System.Windows.Forms.DataGridViewTextBoxColumn Id
System.Windows.Forms.DataGridViewTextBoxColumn Precio
System.Windows.Forms.DataGridViewTextBoxColumn Total
System.Windows.Forms.DataGridViewTextBoxColumn TotalDolares
System.Windows.Forms.DataGridViewTextBoxColumn TotalColones
System.Windows.Forms.DataGridView dgvFacturasAnuladas
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn1
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn2
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn3
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn4
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn5
System.Windows.Forms.Label lblDescripcion
System.Windows.Forms.Label label1
Detailed Description
Definition at line 17 of file frmMantenimientoAnulaFac.cs.
Constructor & Destructor Documentation
frmMantenimientoAnulaFac()
Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.frmMantenimientoAnulaFac ()
Definition at line 19 of file frmMantenimientoAnulaFac.cs.
        {
            InitializeComponent();
        }
References Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
Member Function Documentation
CargarDatos()
void Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.CargarDatos ()
Carga los datos en las tablas
Definition at line 26 of file frmMantenimientoAnulaFac.cs.
{
            IFacturaBLL logicaFactura = new FacturaBLL();
            dgvDatos.DataSource = logicaFactura.SeleccionarFacturaHoy();
            dgvFacturasAnuladas.DataSource = logicaFactura.SeleccionarFacturasAnuladas();
        }
References Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.dgvDatos, Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.dgvFacturasAnuladas, Interfaces.IFacturaBLL.SeleccionarFacturaHoy(), and Interfaces.IFacturaBLL.SeleccionarFacturasAnuladas().
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.frmMantenimientoAnulaFac_Load(), and Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.toolStripBtnEliminar_Click().
Dispose()
override void Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file frmMantenimientoAnulaFac.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.components.
frmMantenimientoAnulaFac_Load()
void Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.frmMantenimientoAnulaFac_Load (object sender, EventArgs e) private
Definition at line 32 of file frmMantenimientoAnulaFac.cs.
        {
            CargarDatos();
        }
References Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.CargarDatos().
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
InitializeComponent()
void Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file frmMantenimientoAnulaFac.Designer.cs.
        {
            this.tspMantenimientos = new System.Windows.Forms.ToolStrip();
            this.toolStripBtnEliminar = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnSalir = new System.Windows.Forms.ToolStripButton();
            this.dgvDatos = new System.Windows.Forms.DataGridView();
            this.Id = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Precio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Total = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.TotalDolares = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.TotalColones = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvFacturasAnuladas = new System.Windows.Forms.DataGridView();
            this.dataGridViewTextBoxColumn1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn3 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn4 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn5 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.lblDescripcion = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.tspMantenimientos.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDatos)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvFacturasAnuladas)).BeginInit();
            this.SuspendLayout();
            //
            // tspMantenimientos
            //
            this.tspMantenimientos.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.tspMantenimientos.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripBtnEliminar,
            this.toolStripBtnSalir});
            this.tspMantenimientos.Location = new System.Drawing.Point(0, 0);
            this.tspMantenimientos.Name = "tspMantenimientos";
            this.tspMantenimientos.Size = new System.Drawing.Size(792, 25);
            this.tspMantenimientos.TabIndex = 53;
            this.tspMantenimientos.Text = "toolStrip1";
            //
            // toolStripBtnEliminar
            //
            this.toolStripBtnEliminar.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnEliminar.ForeColor = System.Drawing.Color.White;
            this.toolStripBtnEliminar.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnEliminar.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnEliminar.Name = "toolStripBtnEliminar";
            this.toolStripBtnEliminar.Size = new System.Drawing.Size(63, 22);
            this.toolStripBtnEliminar.Text = "Eliminar";
            this.toolStripBtnEliminar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnEliminar.Click += new System.EventHandler(this.toolStripBtnEliminar_Click);
            //
            // toolStripBtnSalir
            //
            this.toolStripBtnSalir.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnSalir.ForeColor = System.Drawing.Color.White;
            this.toolStripBtnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnSalir.Name = "toolStripBtnSalir";
            this.toolStripBtnSalir.Size = new System.Drawing.Size(39, 22);
            this.toolStripBtnSalir.Text = "Salir";
            this.toolStripBtnSalir.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnSalir.Click += new System.EventHandler(this.toolStripBtnSalir_Click);
            //
            // dgvDatos
            //
            this.dgvDatos.AllowUserToAddRows = false;
            this.dgvDatos.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvDatos.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Id,
            this.Precio,
            this.Total,
            this.TotalDolares,
            this.TotalColones});
            this.dgvDatos.Location = new System.Drawing.Point(0, 50);
            this.dgvDatos.Name = "dgvDatos";
            this.dgvDatos.ReadOnly = true;
            this.dgvDatos.Size = new System.Drawing.Size(398, 493);
            this.dgvDatos.TabIndex = 54;
            //
            // Id
            //
            this.Id.DataPropertyName = "IdFactura";
            this.Id.HeaderText = "Id";
            this.Id.Name = "Id";
            this.Id.ReadOnly = true;
            //
            // Precio
            //
            this.Precio.DataPropertyName = "IdUsuario";
            this.Precio.HeaderText = "IdUsuario";
            this.Precio.Name = "Precio";
            this.Precio.ReadOnly = true;
            //
            // Total
            //
            this.Total.DataPropertyName = "FechaFacturacion";
            this.Total.HeaderText = " Fecha de Facturacion";
            this.Total.Name = "Total";
            this.Total.ReadOnly = true;
            //
            // TotalDolares
            //
            this.TotalDolares.DataPropertyName = "TotalDolares";
            this.TotalDolares.HeaderText = "TotalDolares";
            this.TotalDolares.Name = "TotalDolares";
            this.TotalDolares.ReadOnly = true;
            //
            // TotalColones
            //
            this.TotalColones.DataPropertyName = "TotalColones";
            this.TotalColones.HeaderText = "TotalColones";
            this.TotalColones.Name = "TotalColones";
            this.TotalColones.ReadOnly = true;
            //
            // dgvFacturasAnuladas
            //
            this.dgvFacturasAnuladas.AllowUserToAddRows = false;
            this.dgvFacturasAnuladas.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvFacturasAnuladas.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.dataGridViewTextBoxColumn1,
            this.dataGridViewTextBoxColumn2,
            this.dataGridViewTextBoxColumn3,
            this.dataGridViewTextBoxColumn4,
            this.dataGridViewTextBoxColumn5});
            this.dgvFacturasAnuladas.Location = new System.Drawing.Point(404, 50);
            this.dgvFacturasAnuladas.Name = "dgvFacturasAnuladas";
            this.dgvFacturasAnuladas.ReadOnly = true;
            this.dgvFacturasAnuladas.Size = new System.Drawing.Size(388, 493);
            this.dgvFacturasAnuladas.TabIndex = 55;
            //
            // dataGridViewTextBoxColumn1
            //
            this.dataGridViewTextBoxColumn1.DataPropertyName = "IdFactura";
            this.dataGridViewTextBoxColumn1.HeaderText = "Id";
            this.dataGridViewTextBoxColumn1.Name = "dataGridViewTextBoxColumn1";
            this.dataGridViewTextBoxColumn1.ReadOnly = true;
            //
            // dataGridViewTextBoxColumn2
            //
            this.dataGridViewTextBoxColumn2.DataPropertyName = "IdUsuario";
            this.dataGridViewTextBoxColumn2.HeaderText = "IdUsuario";
            this.dataGridViewTextBoxColumn2.Name = "dataGridViewTextBoxColumn2";
            this.dataGridViewTextBoxColumn2.ReadOnly = true;
            //
            // dataGridViewTextBoxColumn3
            //
            this.dataGridViewTextBoxColumn3.DataPropertyName = "FechaFacturacion";
            this.dataGridViewTextBoxColumn3.HeaderText = " Fecha de Facturacion";
            this.dataGridViewTextBoxColumn3.Name = "dataGridViewTextBoxColumn3";
            this.dataGridViewTextBoxColumn3.ReadOnly = true;
            //
            // dataGridViewTextBoxColumn4
            //
            this.dataGridViewTextBoxColumn4.DataPropertyName = "TotalDolares";
            this.dataGridViewTextBoxColumn4.HeaderText = "TotalDolares";
            this.dataGridViewTextBoxColumn4.Name = "dataGridViewTextBoxColumn4";
            this.dataGridViewTextBoxColumn4.ReadOnly = true;
            //
            // dataGridViewTextBoxColumn5
            //
            this.dataGridViewTextBoxColumn5.DataPropertyName = "TotalColones";
            this.dataGridViewTextBoxColumn5.HeaderText = "TotalColones";
            this.dataGridViewTextBoxColumn5.Name = "dataGridViewTextBoxColumn5";
            this.dataGridViewTextBoxColumn5.ReadOnly = true;
            //
            // lblDescripcion
            //
            this.lblDescripcion.AutoSize = true;
            this.lblDescripcion.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblDescripcion.ForeColor = System.Drawing.Color.White;
            this.lblDescripcion.Location = new System.Drawing.Point(12, 31);
            this.lblDescripcion.Name = "lblDescripcion";
            this.lblDescripcion.Size = new System.Drawing.Size(114, 16);
            this.lblDescripcion.TabIndex = 152;
            this.lblDescripcion.Text = "Facturas Activas";
            this.lblDescripcion.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            //
            // label1
            //
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(445, 31);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(129, 16);
            this.label1.TabIndex = 153;
            this.label1.Text = "Facturas Anuladas";
            this.label1.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            //
            // frmMantenimientoAnulaFac
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.ClientSize = new System.Drawing.Size(792, 541);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.lblDescripcion);
            this.Controls.Add(this.dgvFacturasAnuladas);
            this.Controls.Add(this.dgvDatos);
            this.Controls.Add(this.tspMantenimientos);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmMantenimientoAnulaFac";
            this.Text = "frmMantenimientoAnulaFac";
            this.Load += new System.EventHandler(this.frmMantenimientoAnulaFac_Load);
            this.tspMantenimientos.ResumeLayout(false);
            this.tspMantenimientos.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDatos)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvFacturasAnuladas)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.dataGridViewTextBoxColumn1, Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.dataGridViewTextBoxColumn2, Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.dataGridViewTextBoxColumn3, Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.dataGridViewTextBoxColumn4, Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.dataGridViewTextBoxColumn5, Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.dgvDatos, Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.dgvFacturasAnuladas, Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.frmMantenimientoAnulaFac_Load(), Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.Id, Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.label1, Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.lblDescripcion, Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.Precio, Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.toolStripBtnEliminar, Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.toolStripBtnEliminar_Click(), Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.toolStripBtnSalir, Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.toolStripBtnSalir_Click(), Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.Total, Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.TotalColones, Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.TotalDolares, and Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.tspMantenimientos.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.frmMantenimientoAnulaFac().
toolStripBtnEliminar_Click()
void Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.toolStripBtnEliminar_Click (object sender, EventArgs e) private
Selecciona el registro y anula la factura
Parameters
sender
e
Definition at line 42 of file frmMantenimientoAnulaFac.cs.
        {
            IFacturaBLL logicaFactura = new FacturaBLL();
            // logicaFactura.AnularFactura()
            if (this.dgvDatos.SelectedRows.Count > 0)
            {
                Factura factura = this.dgvDatos.SelectedRows[0].DataBoundItem as Factura;
                logicaFactura.AnularFactura(factura.IdFactura);
                CargarDatos();
            }
            else
            {
                MessageBox.Show("Seleccione el registro !", "", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
References Interfaces.IFacturaBLL.AnularFactura(), Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.CargarDatos(), Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.dgvDatos, and capa.Entidades.Factura.IdFactura.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
toolStripBtnSalir_Click()
void Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.toolStripBtnSalir_Click (object sender, EventArgs e) private
Definition at line 58 of file frmMantenimientoAnulaFac.cs.
        {
            this.Close();
        }
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
Member Data Documentation
components
System.ComponentModel.IContainer Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.components = null private
Required designer variable.
Definition at line 8 of file frmMantenimientoAnulaFac.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.Dispose().
dataGridViewTextBoxColumn1
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.dataGridViewTextBoxColumn1 private
Definition at line 251 of file frmMantenimientoAnulaFac.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
dataGridViewTextBoxColumn2
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.dataGridViewTextBoxColumn2 private
Definition at line 252 of file frmMantenimientoAnulaFac.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
dataGridViewTextBoxColumn3
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.dataGridViewTextBoxColumn3 private
Definition at line 253 of file frmMantenimientoAnulaFac.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
dataGridViewTextBoxColumn4
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.dataGridViewTextBoxColumn4 private
Definition at line 254 of file frmMantenimientoAnulaFac.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
dataGridViewTextBoxColumn5
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.dataGridViewTextBoxColumn5 private
Definition at line 255 of file frmMantenimientoAnulaFac.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
dgvDatos
System.Windows.Forms.DataGridView Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.dgvDatos private
Definition at line 244 of file frmMantenimientoAnulaFac.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.CargarDatos(), Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent(), and Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.toolStripBtnEliminar_Click().
dgvFacturasAnuladas
System.Windows.Forms.DataGridView Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.dgvFacturasAnuladas private
Definition at line 250 of file frmMantenimientoAnulaFac.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.CargarDatos(), and Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
Id
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.Id private
Definition at line 245 of file frmMantenimientoAnulaFac.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
label1
System.Windows.Forms.Label Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.label1 private
Definition at line 257 of file frmMantenimientoAnulaFac.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
lblDescripcion
System.Windows.Forms.Label Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.lblDescripcion private
Definition at line 256 of file frmMantenimientoAnulaFac.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
Precio
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.Precio private
Definition at line 246 of file frmMantenimientoAnulaFac.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
toolStripBtnEliminar
System.Windows.Forms.ToolStripButton Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.toolStripBtnEliminar private
Definition at line 242 of file frmMantenimientoAnulaFac.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
toolStripBtnSalir
System.Windows.Forms.ToolStripButton Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.toolStripBtnSalir private
Definition at line 243 of file frmMantenimientoAnulaFac.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
Total
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.Total private
Definition at line 247 of file frmMantenimientoAnulaFac.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
TotalColones
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.TotalColones private
Definition at line 249 of file frmMantenimientoAnulaFac.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
TotalDolares
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.TotalDolares private
Definition at line 248 of file frmMantenimientoAnulaFac.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
tspMantenimientos
System.Windows.Forms.ToolStrip Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.tspMantenimientos private
Definition at line 241 of file frmMantenimientoAnulaFac.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.InitializeComponent().
The documentation for this class was generated from the following files:
Capa.UI/Mantenimientos/frmMantenimientoAnulaFac.cs
Capa.UI/Mantenimientos/frmMantenimientoAnulaFac.Designer.cs