Proyecto Autos Seguros: DAL.TarjetaDAL Class Reference
DAL.TarjetaDAL Class Reference
Public Member Functions
Tarjeta ObtenerPorId (int id)
List< Tarjeta > ObtenerTarjeta ()
List< Tarjeta > ObtenerTarjeta ()
Tarjeta ObtenerPorId (int id)
Detailed Description
Definition at line 13 of file TarjetaDAL.cs.
Member Function Documentation
ObtenerPorId()
Tarjeta DAL.TarjetaDAL.ObtenerPorId (int id)
Implements Interfaces.ITarjetaDAL.
Definition at line 15 of file TarjetaDAL.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_Tarjeta_ByID";
                comando.Parameters.AddWithValue("@Id", id);
                IDataReader reader = db.ExecuteReader(comando);
                while (reader.Read())
                {
                    Tarjeta tarjeta = new Tarjeta();
                    tarjeta.Id = (int)reader["Id"];
                    tarjeta.Nombre = reader["Descripcion"].ToString();
                    return tarjeta;
                }
            }
            return null;
        }
References FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteReader(), Entities.Tarjeta.Id, and Entities.Tarjeta.Nombre.
ObtenerTarjeta()
List< Tarjeta > DAL.TarjetaDAL.ObtenerTarjeta ()
Implements Interfaces.ITarjetaDAL.
Definition at line 38 of file TarjetaDAL.cs.
        {
            List<Tarjeta> lista = new List<Tarjeta>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "usp_SELECT_Tarjeta_All";
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Tarjeta tarjeta = new Tarjeta();
                    tarjeta.Id = (int)dr["Id"];
                    tarjeta.Nombre = dr["Descripcion"].ToString();
                    lista.Add(tarjeta);
                }
            }
            return lista;
        }
References FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteDataSet(), Entities.Tarjeta.Id, and Entities.Tarjeta.Nombre.
The documentation for this class was generated from the following file:
DAL/TarjetaDAL.cs