Proyecto Autos Seguros: Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza Class Reference
Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza Class Reference
Public Member Functions
frmMantenimientoTipoPoliza ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void CargarDatos ()
Cargar los datos de las tablas y combos
void CambiarEstadoMantenimiento (EstadoMantenimiento estado)
void btnCancelar_Click (object sender, EventArgs e)
Cancela la ejecución y limpia los campos
void splitContainer1_Panel2_Paint (object sender, PaintEventArgs e)
void frmMantenimientoTipoPoliza_Load (object sender, EventArgs e)
eveneto que se ejecuta al abrir el form
void btnAgregarCobertura_Click (object sender, EventArgs e)
Verifica que no haya añadido la cobertura anteriormente y lo guarda en una lista tipo cobertura. Además llena el txtcosto con la suma del total de las coberturas que es el mismo
void btnAceptar_Click (object sender, EventArgs e)
Valida los campos y actualiza los registros
void dgvDatos_CellClick (object sender, DataGridViewCellEventArgs e)
void toolStripBtnEditar_Click (object sender, EventArgs e)
Selecciona el tipo de poliza y lo elimina
void dgvDatos_CellMouseClick (object sender, DataGridViewCellMouseEventArgs e)
Crea un tipo de poliza y muestra las coberturas que tiene agregadas
void toolStripBtnNuevo_Click (object sender, EventArgs e)
void btnEliminarCobAgregada_Click (object sender, EventArgs e)
Elimina la cobertura del tipo de poliza
void toolStripBtnEliminar_Click (object sender, EventArgs e)
Elimina el tipo de poliza seleccionado
void toolStripBtnSalir_Click (object sender, EventArgs e)
Sale del form
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
EstadoMantenimiento estadoMantenimiento
List< Cobertura > listaCobertura
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.ToolStrip tspMantenimientos
System.Windows.Forms.ToolStripButton toolStripBtnNuevo
System.Windows.Forms.ToolStripButton toolStripBtnEditar
System.Windows.Forms.ToolStripButton toolStripBtnEliminar
System.Windows.Forms.ToolStripButton toolStripBtnSalir
System.Windows.Forms.SplitContainer splitContainer1
System.Windows.Forms.DataGridView dgvDatos
System.Windows.Forms.TextBox txtId
System.Windows.Forms.Button btnCancelar
System.Windows.Forms.Button btnAceptar
System.Windows.Forms.Label lblDescripcion
System.Windows.Forms.TextBox txtDescripcion
System.Windows.Forms.Panel panel1
System.Windows.Forms.Label lblCobertura
System.Windows.Forms.ComboBox cmbCobertura
System.Windows.Forms.Button btnAgregarCobertura
System.Windows.Forms.DataGridView dgvDatosCobertura
System.Windows.Forms.Label lblId
System.Windows.Forms.Label lblCoberturaAgregadas
System.Windows.Forms.DataGridView dgvCoberturasAgregadas
System.Windows.Forms.Label lblTipoPoliza
System.Windows.Forms.Button btnEliminarCobAgregada
System.Windows.Forms.Panel panel2
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn2
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn4
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn3
System.Windows.Forms.DataGridViewTextBoxColumn Total
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn1
System.Windows.Forms.DataGridViewTextBoxColumn Descripcion
System.Windows.Forms.DataGridViewTextBoxColumn Precio
System.Windows.Forms.DataGridViewTextBoxColumn Totall
System.Windows.Forms.DataGridViewTextBoxColumn Id
System.Windows.Forms.DataGridViewTextBoxColumn DescripcionTipoPlan
System.Windows.Forms.DataGridViewTextBoxColumn Costo
System.Windows.Forms.TextBox txtCosto
System.Windows.Forms.Label lblCosto
Static Private Attributes
static readonly ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 17 of file frmMantenimientoTipoPoliza.cs.
Constructor & Destructor Documentation
frmMantenimientoTipoPoliza()
Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.frmMantenimientoTipoPoliza ()
Definition at line 23 of file frmMantenimientoTipoPoliza.cs.
        {
            InitializeComponent();
            listaCobertura = new List<Cobertura>();
        }
References Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent(), and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.listaCobertura.
Member Function Documentation
btnAceptar_Click()
void Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAceptar_Click (object sender, EventArgs e) private
Valida los campos y actualiza los registros
Parameters
sender
e
Definition at line 151 of file frmMantenimientoTipoPoliza.cs.
        {
            ErrorProvider oErrorProvider = new ErrorProvider();
            if (txtId.Text == "")
            {
                oErrorProvider.SetError(txtDescripcion, "Digite un Id");
                return;
            }
            if (txtDescripcion.Text == "")
            {
                oErrorProvider.SetError(txtDescripcion, "Digite una descripción");
                return;
            }
            if (dgvDatosCobertura.DataSource == null) {
                oErrorProvider.SetError(cmbCobertura, "Debe agregar al menos una cobertura");
                return;
            }
            try
            {
                TipoPoliza tipoPoliza = new TipoPoliza();
                tipoPoliza.Descripcion = txtDescripcion.Text;
                tipoPoliza.Id = int.Parse( txtId.Text);
                if (listaCobertura.Count == 0) {
                    MessageBox.Show("Debe agregar coberturas");
                    return;
                }
                foreach (var item in listaCobertura)
                {
                    tipoPoliza.Costo += item.Total;
                }
                ITipoPolizaBLL logica = new TipoPolizaBLL();
                logica.Insertar(tipoPoliza);
                    IDetallePolizaBLL logicaDetallePoliza = new DetallePolizaBLL();
                    foreach (var item in listaCobertura)
                    {
                        DetallePoliza detallePoliza = new DetallePoliza();
                        detallePoliza.IdTipoPoliza = tipoPoliza.Id;
                        detallePoliza.IdCobertura = item.Id;
                        logicaDetallePoliza.Insertar(detallePoliza);
                    }
                CargarDatos();
                CambiarEstadoMantenimiento(EstadoMantenimiento.Ninguno);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza._MyLogControlEventos, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CambiarEstadoMantenimiento(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CargarDatos(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.cmbCobertura, Entities.TipoPoliza.Descripcion, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvDatosCobertura, Entities.TipoPoliza.Id, Entities.DetallePoliza.IdCobertura, Entities.DetallePoliza.IdTipoPoliza, Interfaces.ITipoPolizaBLL.Insertar(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.listaCobertura, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.txtDescripcion, and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.txtId.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
btnAgregarCobertura_Click()
void Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAgregarCobertura_Click (object sender, EventArgs e) private
Verifica que no haya añadido la cobertura anteriormente y lo guarda en una lista tipo cobertura. Además llena el txtcosto con la suma del total de las coberturas que es el mismo
Parameters
sender
e
Definition at line 127 of file frmMantenimientoTipoPoliza.cs.
        {
            ICoberturaBLL logicaCobertura = new CoberturaBLL();
            Cobertura cobertura = logicaCobertura.SeleccionarPorId((int)cmbCobertura.SelectedValue);
            if (listaCobertura.FindAll(p => p.Id == cobertura.Id).Count > 0)
            {
                MessageBox.Show("La cobertura ya fue agregada", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }
            listaCobertura.Add(cobertura);
            decimal costo = 0;
            foreach (var item in listaCobertura)
            {
                costo += item.Total;
            }
            txtCosto.Text = costo.ToString();
            dgvDatosCobertura.DataSource = null;
            dgvDatosCobertura.DataSource =listaCobertura;
        }
References Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.cmbCobertura, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvDatosCobertura, Entities.Cobertura.Id, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.listaCobertura, Interfaces.ICoberturaBLL.SeleccionarPorId(), and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.txtCosto.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
btnCancelar_Click()
void Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnCancelar_Click (object sender, EventArgs e) private
Cancela la ejecución y limpia los campos
Parameters
sender
e
Definition at line 101 of file frmMantenimientoTipoPoliza.cs.
        {
            CambiarEstadoMantenimiento(EstadoMantenimiento.Ninguno);
        }
References Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CambiarEstadoMantenimiento().
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
btnEliminarCobAgregada_Click()
void Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnEliminarCobAgregada_Click (object sender, EventArgs e) private
Elimina la cobertura del tipo de poliza
Parameters
sender
e
Definition at line 288 of file frmMantenimientoTipoPoliza.cs.
        {
            if (this.dgvDatosCobertura.SelectedRows.Count > 0)
            {
                Cobertura cobertura = this.dgvDatosCobertura.SelectedRows[0].DataBoundItem as Cobertura;
                IDetallePolizaBLL detallePolizaBLL = new DetallePolizaBLL();
                detallePolizaBLL.EliminarByPolCob(int.Parse(txtId.Text), cobertura.Id);
                ICoberturaBLL logicaCobertura = new CoberturaBLL();
                listaCobertura = logicaCobertura.CoberturasAgregadas(int.Parse(txtId.Text));
                dgvDatosCobertura.DataSource = listaCobertura;
                decimal costo = 0;
                foreach (var item in listaCobertura)
                {
                    costo += item.Total;
                }
            }
            else
            {
                MessageBox.Show("Seleccione el registro de la tabla!", "", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
References Interfaces.ICoberturaBLL.CoberturasAgregadas(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvDatosCobertura, Interfaces.IDetallePolizaBLL.EliminarByPolCob(), Entities.Cobertura.Id, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.listaCobertura, and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.txtId.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
CambiarEstadoMantenimiento()
void Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CambiarEstadoMantenimiento (EstadoMantenimiento estado) private
Definition at line 56 of file frmMantenimientoTipoPoliza.cs.
        {
            txtDescripcion.Clear();
            txtId.Clear();
            txtCosto.Clear();
            dgvDatosCobertura.DataSource = null;
            cmbCobertura.SelectedIndex = -1;
            dgvCoberturasAgregadas.DataSource = null;
            txtDescripcion.Enabled = false;
            txtId.Enabled = false;
            listaCobertura = new List<Cobertura>();
            switch (estado)
            {
                case EstadoMantenimiento.Nuevo:
                    txtDescripcion.Enabled = true;
                    txtId.Enabled = true;
                  //  listaCobertura = new List<Cobertura>();
                    estadoMantenimiento = EstadoMantenimiento.Nuevo;
                    break;
                case EstadoMantenimiento.Editar:
                    txtDescripcion.Enabled = true;
                    txtId.Enabled = false;
                    estadoMantenimiento = EstadoMantenimiento.Editar;
                    break;
                case EstadoMantenimiento.Borrar:
                    estadoMantenimiento = EstadoMantenimiento.Borrar;
                    break;
                case EstadoMantenimiento.Ninguno:
                    estadoMantenimiento = EstadoMantenimiento.Ninguno;
                    break;
            }
        }
References Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.cmbCobertura, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvCoberturasAgregadas, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvDatosCobertura, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.estadoMantenimiento, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.listaCobertura, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.txtCosto, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.txtDescripcion, and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.txtId.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnCancelar_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEditar_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEliminar_Click(), and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnNuevo_Click().
CargarDatos()
void Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CargarDatos () private
Cargar los datos de las tablas y combos
Definition at line 33 of file frmMantenimientoTipoPoliza.cs.
        {
            try
            {
                ITipoPolizaBLL logica = new TipoPolizaBLL();
                dgvDatos.DataSource = logica.ObtenerTipoPolizas();
                ICoberturaBLL logicaCobertura = new CoberturaBLL();
                cmbCobertura.DataSource = logicaCobertura.SeleccionarTodas();
                cmbCobertura.DisplayMember = "Descripcion";
                cmbCobertura.ValueMember = "Id";
                cmbCobertura.SelectedIndex = -1;
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza._MyLogControlEventos, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.cmbCobertura, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvDatos, Interfaces.ITipoPolizaBLL.ObtenerTipoPolizas(), and Interfaces.ICoberturaBLL.SeleccionarTodas().
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.frmMantenimientoTipoPoliza_Load(), and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEliminar_Click().
dgvDatos_CellClick()
void Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvDatos_CellClick (object sender, DataGridViewCellEventArgs e) private
Definition at line 215 of file frmMantenimientoTipoPoliza.cs.
        {
        }
dgvDatos_CellMouseClick()
void Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvDatos_CellMouseClick (object sender, DataGridViewCellMouseEventArgs e) private
Crea un tipo de poliza y muestra las coberturas que tiene agregadas
Parameters
sender
e
Definition at line 263 of file frmMantenimientoTipoPoliza.cs.
        {
            if (this.dgvDatos.SelectedRows.Count > 0)
            {
                ICoberturaBLL logicaCobertura = new CoberturaBLL();
                TipoPoliza tipoPoliza = new TipoPoliza();
                tipoPoliza = this.dgvDatos.SelectedRows[0].DataBoundItem as TipoPoliza;
                dgvCoberturasAgregadas.DataSource = logicaCobertura.CoberturasAgregadas(tipoPoliza.Id);
            }
            else
            {
                MessageBox.Show("Seleccione el registro !", "", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
References Interfaces.ICoberturaBLL.CoberturasAgregadas(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvCoberturasAgregadas, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvDatos, and Entities.TipoPoliza.Id.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
Dispose()
override void Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file frmMantenimientoTipoPoliza.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.components.
frmMantenimientoTipoPoliza_Load()
void Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.frmMantenimientoTipoPoliza_Load (object sender, EventArgs e) private
eveneto que se ejecuta al abrir el form
Parameters
sender
e
Definition at line 116 of file frmMantenimientoTipoPoliza.cs.
        {
            CargarDatos();
        }
References Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CargarDatos().
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
InitializeComponent()
void Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file frmMantenimientoTipoPoliza.Designer.cs.
        {
            this.tspMantenimientos = new System.Windows.Forms.ToolStrip();
            this.toolStripBtnNuevo = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnEditar = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnEliminar = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnSalir = new System.Windows.Forms.ToolStripButton();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.lblTipoPoliza = new System.Windows.Forms.Label();
            this.lblCoberturaAgregadas = new System.Windows.Forms.Label();
            this.dgvCoberturasAgregadas = new System.Windows.Forms.DataGridView();
            this.dataGridViewTextBoxColumn2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn4 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn3 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Total = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDatos = new System.Windows.Forms.DataGridView();
            this.Id = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.DescripcionTipoPlan = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Costo = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.panel2 = new System.Windows.Forms.Panel();
            this.txtCosto = new System.Windows.Forms.TextBox();
            this.lblCosto = new System.Windows.Forms.Label();
            this.txtDescripcion = new System.Windows.Forms.TextBox();
            this.lblId = new System.Windows.Forms.Label();
            this.lblDescripcion = new System.Windows.Forms.Label();
            this.txtId = new System.Windows.Forms.TextBox();
            this.panel1 = new System.Windows.Forms.Panel();
            this.btnEliminarCobAgregada = new System.Windows.Forms.Button();
            this.dgvDatosCobertura = new System.Windows.Forms.DataGridView();
            this.dataGridViewTextBoxColumn1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Descripcion = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Precio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Totall = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.lblCobertura = new System.Windows.Forms.Label();
            this.cmbCobertura = new System.Windows.Forms.ComboBox();
            this.btnAgregarCobertura = new System.Windows.Forms.Button();
            this.btnCancelar = new System.Windows.Forms.Button();
            this.btnAceptar = new System.Windows.Forms.Button();
            this.tspMantenimientos.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvCoberturasAgregadas)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDatos)).BeginInit();
            this.panel2.SuspendLayout();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDatosCobertura)).BeginInit();
            this.SuspendLayout();
            //
            // tspMantenimientos
            //
            this.tspMantenimientos.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.tspMantenimientos.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripBtnNuevo,
            this.toolStripBtnEditar,
            this.toolStripBtnEliminar,
            this.toolStripBtnSalir});
            this.tspMantenimientos.Location = new System.Drawing.Point(0, 0);
            this.tspMantenimientos.Name = "tspMantenimientos";
            this.tspMantenimientos.Size = new System.Drawing.Size(1287, 25);
            this.tspMantenimientos.TabIndex = 54;
            this.tspMantenimientos.Text = "toolStrip1";
            //
            // toolStripBtnNuevo
            //
            this.toolStripBtnNuevo.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.toolStripBtnNuevo.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.toolStripBtnNuevo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnNuevo.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnNuevo.Name = "toolStripBtnNuevo";
            this.toolStripBtnNuevo.Size = new System.Drawing.Size(52, 22);
            this.toolStripBtnNuevo.Text = "Nuevo";
            this.toolStripBtnNuevo.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnNuevo.Click += new System.EventHandler(this.toolStripBtnNuevo_Click);
            //
            // toolStripBtnEditar
            //
            this.toolStripBtnEditar.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnEditar.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.toolStripBtnEditar.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnEditar.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnEditar.Name = "toolStripBtnEditar";
            this.toolStripBtnEditar.Size = new System.Drawing.Size(48, 22);
            this.toolStripBtnEditar.Text = "Editar";
            this.toolStripBtnEditar.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.toolStripBtnEditar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnEditar.Click += new System.EventHandler(this.toolStripBtnEditar_Click);
            //
            // toolStripBtnEliminar
            //
            this.toolStripBtnEliminar.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnEliminar.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.toolStripBtnEliminar.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnEliminar.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnEliminar.Name = "toolStripBtnEliminar";
            this.toolStripBtnEliminar.Size = new System.Drawing.Size(63, 22);
            this.toolStripBtnEliminar.Text = "Eliminar";
            this.toolStripBtnEliminar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnEliminar.Click += new System.EventHandler(this.toolStripBtnEliminar_Click);
            //
            // toolStripBtnSalir
            //
            this.toolStripBtnSalir.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnSalir.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.toolStripBtnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnSalir.Name = "toolStripBtnSalir";
            this.toolStripBtnSalir.Size = new System.Drawing.Size(39, 22);
            this.toolStripBtnSalir.Text = "Salir";
            this.toolStripBtnSalir.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnSalir.Click += new System.EventHandler(this.toolStripBtnSalir_Click);
            //
            // splitContainer1
            //
            this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer1.Location = new System.Drawing.Point(0, 25);
            this.splitContainer1.Name = "splitContainer1";
            //
            // splitContainer1.Panel1
            //
            this.splitContainer1.Panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.splitContainer1.Panel1.Controls.Add(this.lblTipoPoliza);
            this.splitContainer1.Panel1.Controls.Add(this.lblCoberturaAgregadas);
            this.splitContainer1.Panel1.Controls.Add(this.dgvCoberturasAgregadas);
            this.splitContainer1.Panel1.Controls.Add(this.dgvDatos);
            //
            // splitContainer1.Panel2
            //
            this.splitContainer1.Panel2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.splitContainer1.Panel2.Controls.Add(this.panel2);
            this.splitContainer1.Panel2.Controls.Add(this.panel1);
            this.splitContainer1.Panel2.Controls.Add(this.btnCancelar);
            this.splitContainer1.Panel2.Controls.Add(this.btnAceptar);
            this.splitContainer1.Panel2.Paint += new System.Windows.Forms.PaintEventHandler(this.splitContainer1_Panel2_Paint);
            this.splitContainer1.Size = new System.Drawing.Size(1287, 425);
            this.splitContainer1.SplitterDistance = 523;
            this.splitContainer1.TabIndex = 55;
            //
            // lblTipoPoliza
            //
            this.lblTipoPoliza.AutoSize = true;
            this.lblTipoPoliza.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTipoPoliza.ForeColor = System.Drawing.Color.White;
            this.lblTipoPoliza.Location = new System.Drawing.Point(0, 16);
            this.lblTipoPoliza.Name = "lblTipoPoliza";
            this.lblTipoPoliza.Size = new System.Drawing.Size(109, 16);
            this.lblTipoPoliza.TabIndex = 155;
            this.lblTipoPoliza.Text = "Tipos de Polizas";
            this.lblTipoPoliza.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            //
            // lblCoberturaAgregadas
            //
            this.lblCoberturaAgregadas.AutoSize = true;
            this.lblCoberturaAgregadas.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCoberturaAgregadas.ForeColor = System.Drawing.Color.White;
            this.lblCoberturaAgregadas.Location = new System.Drawing.Point(3, 198);
            this.lblCoberturaAgregadas.Name = "lblCoberturaAgregadas";
            this.lblCoberturaAgregadas.Size = new System.Drawing.Size(157, 16);
            this.lblCoberturaAgregadas.TabIndex = 154;
            this.lblCoberturaAgregadas.Text = "Coberturas Agregadas";
            this.lblCoberturaAgregadas.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            //
            // dgvCoberturasAgregadas
            //
            this.dgvCoberturasAgregadas.AllowUserToAddRows = false;
            this.dgvCoberturasAgregadas.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvCoberturasAgregadas.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.dataGridViewTextBoxColumn2,
            this.dataGridViewTextBoxColumn4,
            this.dataGridViewTextBoxColumn3,
            this.Total});
            this.dgvCoberturasAgregadas.Location = new System.Drawing.Point(3, 239);
            this.dgvCoberturasAgregadas.Name = "dgvCoberturasAgregadas";
            this.dgvCoberturasAgregadas.ReadOnly = true;
            this.dgvCoberturasAgregadas.Size = new System.Drawing.Size(498, 159);
            this.dgvCoberturasAgregadas.TabIndex = 153;
            //
            // dataGridViewTextBoxColumn2
            //
            this.dataGridViewTextBoxColumn2.DataPropertyName = "Id";
            this.dataGridViewTextBoxColumn2.HeaderText = "Id";
            this.dataGridViewTextBoxColumn2.Name = "dataGridViewTextBoxColumn2";
            this.dataGridViewTextBoxColumn2.ReadOnly = true;
            //
            // dataGridViewTextBoxColumn4
            //
            this.dataGridViewTextBoxColumn4.DataPropertyName = "Descripcion";
            this.dataGridViewTextBoxColumn4.HeaderText = "Descripcion";
            this.dataGridViewTextBoxColumn4.Name = "dataGridViewTextBoxColumn4";
            this.dataGridViewTextBoxColumn4.ReadOnly = true;
            //
            // dataGridViewTextBoxColumn3
            //
            this.dataGridViewTextBoxColumn3.DataPropertyName = "Precio";
            this.dataGridViewTextBoxColumn3.HeaderText = "Precio";
            this.dataGridViewTextBoxColumn3.Name = "dataGridViewTextBoxColumn3";
            this.dataGridViewTextBoxColumn3.ReadOnly = true;
            //
            // Total
            //
            this.Total.DataPropertyName = "Total";
            this.Total.HeaderText = "Precio+IVA";
            this.Total.Name = "Total";
            this.Total.ReadOnly = true;
            //
            // dgvDatos
            //
            this.dgvDatos.AllowUserToAddRows = false;
            this.dgvDatos.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvDatos.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Id,
            this.DescripcionTipoPlan,
            this.Costo});
            this.dgvDatos.Location = new System.Drawing.Point(0, 35);
            this.dgvDatos.Name = "dgvDatos";
            this.dgvDatos.ReadOnly = true;
            this.dgvDatos.Size = new System.Drawing.Size(501, 141);
            this.dgvDatos.TabIndex = 26;
            this.dgvDatos.CellMouseClick += new System.Windows.Forms.DataGridViewCellMouseEventHandler(this.dgvDatos_CellMouseClick);
            //
            // Id
            //
            this.Id.DataPropertyName = "Id";
            this.Id.HeaderText = "Id";
            this.Id.Name = "Id";
            this.Id.ReadOnly = true;
            //
            // DescripcionTipoPlan
            //
            this.DescripcionTipoPlan.DataPropertyName = "Descripcion";
            this.DescripcionTipoPlan.HeaderText = "DescripcionTipoPlan";
            this.DescripcionTipoPlan.Name = "DescripcionTipoPlan";
            this.DescripcionTipoPlan.ReadOnly = true;
            //
            // Costo
            //
            this.Costo.DataPropertyName = "Costo";
            this.Costo.HeaderText = "Costo";
            this.Costo.Name = "Costo";
            this.Costo.ReadOnly = true;
            //
            // panel2
            //
            this.panel2.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.panel2.Controls.Add(this.txtCosto);
            this.panel2.Controls.Add(this.lblCosto);
            this.panel2.Controls.Add(this.txtDescripcion);
            this.panel2.Controls.Add(this.lblId);
            this.panel2.Controls.Add(this.lblDescripcion);
            this.panel2.Controls.Add(this.txtId);
            this.panel2.Location = new System.Drawing.Point(16, 31);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(350, 254);
            this.panel2.TabIndex = 162;
            //
            // txtCosto
            //
            this.txtCosto.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.txtCosto.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtCosto.Enabled = false;
            this.txtCosto.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCosto.ForeColor = System.Drawing.Color.White;
            this.txtCosto.Location = new System.Drawing.Point(29, 193);
            this.txtCosto.Name = "txtCosto";
            this.txtCosto.Size = new System.Drawing.Size(167, 27);
            this.txtCosto.TabIndex = 163;
            //
            // lblCosto
            //
            this.lblCosto.AutoSize = true;
            this.lblCosto.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCosto.ForeColor = System.Drawing.Color.White;
            this.lblCosto.Location = new System.Drawing.Point(26, 174);
            this.lblCosto.Name = "lblCosto";
            this.lblCosto.Size = new System.Drawing.Size(43, 16);
            this.lblCosto.TabIndex = 162;
            this.lblCosto.Text = "Costo";
            this.lblCosto.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            //
            // txtDescripcion
            //
            this.txtDescripcion.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.txtDescripcion.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtDescripcion.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtDescripcion.ForeColor = System.Drawing.Color.White;
            this.txtDescripcion.Location = new System.Drawing.Point(29, 106);
            this.txtDescripcion.Name = "txtDescripcion";
            this.txtDescripcion.Size = new System.Drawing.Size(167, 27);
            this.txtDescripcion.TabIndex = 152;
            //
            // lblId
            //
            this.lblId.AutoSize = true;
            this.lblId.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblId.ForeColor = System.Drawing.Color.White;
            this.lblId.Location = new System.Drawing.Point(26, -1);
            this.lblId.Name = "lblId";
            this.lblId.Size = new System.Drawing.Size(20, 16);
            this.lblId.TabIndex = 161;
            this.lblId.Text = "Id";
            this.lblId.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            //
            // lblDescripcion
            //
            this.lblDescripcion.AutoSize = true;
            this.lblDescripcion.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblDescripcion.ForeColor = System.Drawing.Color.White;
            this.lblDescripcion.Location = new System.Drawing.Point(26, 87);
            this.lblDescripcion.Name = "lblDescripcion";
            this.lblDescripcion.Size = new System.Drawing.Size(84, 16);
            this.lblDescripcion.TabIndex = 151;
            this.lblDescripcion.Text = "Descripcion";
            this.lblDescripcion.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            //
            // txtId
            //
            this.txtId.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.txtId.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtId.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtId.ForeColor = System.Drawing.Color.White;
            this.txtId.Location = new System.Drawing.Point(29, 18);
            this.txtId.Name = "txtId";
            this.txtId.Size = new System.Drawing.Size(167, 27);
            this.txtId.TabIndex = 155;
            //
            // panel1
            //
            this.panel1.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.panel1.Controls.Add(this.btnEliminarCobAgregada);
            this.panel1.Controls.Add(this.dgvDatosCobertura);
            this.panel1.Controls.Add(this.lblCobertura);
            this.panel1.Controls.Add(this.cmbCobertura);
            this.panel1.Controls.Add(this.btnAgregarCobertura);
            this.panel1.Location = new System.Drawing.Point(389, 30);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(350, 254);
            this.panel1.TabIndex = 160;
            //
            // btnEliminarCobAgregada
            //
            this.btnEliminarCobAgregada.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.btnEliminarCobAgregada.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnEliminarCobAgregada.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnEliminarCobAgregada.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEliminarCobAgregada.ForeColor = System.Drawing.Color.White;
            this.btnEliminarCobAgregada.Location = new System.Drawing.Point(235, 32);
            this.btnEliminarCobAgregada.Name = "btnEliminarCobAgregada";
            this.btnEliminarCobAgregada.Size = new System.Drawing.Size(69, 29);
            this.btnEliminarCobAgregada.TabIndex = 160;
            this.btnEliminarCobAgregada.Text = "Eliminar";
            this.btnEliminarCobAgregada.UseVisualStyleBackColor = false;
            this.btnEliminarCobAgregada.Click += new System.EventHandler(this.btnEliminarCobAgregada_Click);
            //
            // dgvDatosCobertura
            //
            this.dgvDatosCobertura.AllowUserToAddRows = false;
            this.dgvDatosCobertura.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvDatosCobertura.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.dataGridViewTextBoxColumn1,
            this.Descripcion,
            this.Precio,
            this.Totall});
            this.dgvDatosCobertura.Location = new System.Drawing.Point(6, 104);
            this.dgvDatosCobertura.Name = "dgvDatosCobertura";
            this.dgvDatosCobertura.ReadOnly = true;
            this.dgvDatosCobertura.Size = new System.Drawing.Size(337, 139);
            this.dgvDatosCobertura.TabIndex = 159;
            //
            // dataGridViewTextBoxColumn1
            //
            this.dataGridViewTextBoxColumn1.DataPropertyName = "Id";
            this.dataGridViewTextBoxColumn1.HeaderText = "Id";
            this.dataGridViewTextBoxColumn1.Name = "dataGridViewTextBoxColumn1";
            this.dataGridViewTextBoxColumn1.ReadOnly = true;
            //
            // Descripcion
            //
            this.Descripcion.DataPropertyName = "Descripcion";
            this.Descripcion.HeaderText = "Descripcion";
            this.Descripcion.Name = "Descripcion";
            this.Descripcion.ReadOnly = true;
            //
            // Precio
            //
            this.Precio.DataPropertyName = "Precio";
            this.Precio.HeaderText = "Precio";
            this.Precio.Name = "Precio";
            this.Precio.ReadOnly = true;
            //
            // Totall
            //
            this.Totall.DataPropertyName = "Total";
            this.Totall.HeaderText = "Precio+IVA";
            this.Totall.Name = "Totall";
            this.Totall.ReadOnly = true;
            //
            // lblCobertura
            //
            this.lblCobertura.AutoSize = true;
            this.lblCobertura.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCobertura.ForeColor = System.Drawing.Color.White;
            this.lblCobertura.Location = new System.Drawing.Point(3, 12);
            this.lblCobertura.Name = "lblCobertura";
            this.lblCobertura.Size = new System.Drawing.Size(132, 16);
            this.lblCobertura.TabIndex = 157;
            this.lblCobertura.Text = "Agregar Cobertura";
            this.lblCobertura.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            //
            // cmbCobertura
            //
            this.cmbCobertura.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.cmbCobertura.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCobertura.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbCobertura.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbCobertura.ForeColor = System.Drawing.Color.White;
            this.cmbCobertura.FormattingEnabled = true;
            this.cmbCobertura.Location = new System.Drawing.Point(6, 32);
            this.cmbCobertura.Name = "cmbCobertura";
            this.cmbCobertura.Size = new System.Drawing.Size(129, 29);
            this.cmbCobertura.TabIndex = 156;
            //
            // btnAgregarCobertura
            //
            this.btnAgregarCobertura.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.btnAgregarCobertura.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnAgregarCobertura.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAgregarCobertura.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAgregarCobertura.ForeColor = System.Drawing.Color.White;
            this.btnAgregarCobertura.Location = new System.Drawing.Point(150, 32);
            this.btnAgregarCobertura.Name = "btnAgregarCobertura";
            this.btnAgregarCobertura.Size = new System.Drawing.Size(69, 29);
            this.btnAgregarCobertura.TabIndex = 158;
            this.btnAgregarCobertura.Text = "Agregar";
            this.btnAgregarCobertura.UseVisualStyleBackColor = false;
            this.btnAgregarCobertura.Click += new System.EventHandler(this.btnAgregarCobertura_Click);
            //
            // btnCancelar
            //
            this.btnCancelar.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.btnCancelar.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnCancelar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCancelar.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancelar.ForeColor = System.Drawing.Color.White;
            this.btnCancelar.Location = new System.Drawing.Point(477, 353);
            this.btnCancelar.Name = "btnCancelar";
            this.btnCancelar.Size = new System.Drawing.Size(167, 45);
            this.btnCancelar.TabIndex = 154;
            this.btnCancelar.Text = "Cancelar";
            this.btnCancelar.UseVisualStyleBackColor = false;
            this.btnCancelar.Click += new System.EventHandler(this.btnCancelar_Click);
            //
            // btnAceptar
            //
            this.btnAceptar.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.btnAceptar.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnAceptar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAceptar.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAceptar.ForeColor = System.Drawing.Color.White;
            this.btnAceptar.Location = new System.Drawing.Point(117, 353);
            this.btnAceptar.Name = "btnAceptar";
            this.btnAceptar.Size = new System.Drawing.Size(167, 45);
            this.btnAceptar.TabIndex = 153;
            this.btnAceptar.Text = "Aceptar";
            this.btnAceptar.UseVisualStyleBackColor = false;
            this.btnAceptar.Click += new System.EventHandler(this.btnAceptar_Click);
            //
            // frmMantenimientoTipoPoliza
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.ClientSize = new System.Drawing.Size(1287, 450);
            this.Controls.Add(this.splitContainer1);
            this.Controls.Add(this.tspMantenimientos);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmMantenimientoTipoPoliza";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmMantenimientoTipoPoliza";
            this.Load += new System.EventHandler(this.frmMantenimientoTipoPoliza_Load);
            this.tspMantenimientos.ResumeLayout(false);
            this.tspMantenimientos.PerformLayout();
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel1.PerformLayout();
            this.splitContainer1.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvCoberturasAgregadas)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDatos)).EndInit();
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDatosCobertura)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAceptar, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAgregarCobertura, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAgregarCobertura_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnCancelar, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnCancelar_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnEliminarCobAgregada, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnEliminarCobAgregada_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.cmbCobertura, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.Costo, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dataGridViewTextBoxColumn1, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dataGridViewTextBoxColumn2, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dataGridViewTextBoxColumn3, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dataGridViewTextBoxColumn4, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.Descripcion, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.DescripcionTipoPlan, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvCoberturasAgregadas, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvDatos, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvDatos_CellMouseClick(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvDatosCobertura, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.frmMantenimientoTipoPoliza_Load(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.Id, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.lblCobertura, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.lblCoberturaAgregadas, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.lblCosto, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.lblDescripcion, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.lblId, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.lblTipoPoliza, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.panel1, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.panel2, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.Precio, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.splitContainer1, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.splitContainer1_Panel2_Paint(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEditar, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEditar_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEliminar, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEliminar_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnNuevo, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnNuevo_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnSalir, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnSalir_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.Total, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.Totall, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.tspMantenimientos, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.txtCosto, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.txtDescripcion, and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.txtId.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.frmMantenimientoTipoPoliza().
splitContainer1_Panel2_Paint()
void Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.splitContainer1_Panel2_Paint (object sender, PaintEventArgs e) private
Definition at line 106 of file frmMantenimientoTipoPoliza.cs.
        {
        }
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
toolStripBtnEditar_Click()
void Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEditar_Click (object sender, EventArgs e) private
Selecciona el tipo de poliza y lo elimina
Parameters
sender
e
Definition at line 225 of file frmMantenimientoTipoPoliza.cs.
        {
            TipoPoliza tipoPoliza = null;
            try
            {
                if (this.dgvDatos.SelectedRows.Count > 0)
                {
                    // Cambiar de estado
                    this.CambiarEstadoMantenimiento(EstadoMantenimiento.Editar);
                    //Extraer el DTO seleccionado
                    tipoPoliza = this.dgvDatos.SelectedRows[0].DataBoundItem as TipoPoliza;
                    this.txtId.Text = tipoPoliza.Id.ToString();
                    this.txtDescripcion.Text = tipoPoliza.Descripcion.ToString();
                    this.txtCosto.Text = tipoPoliza.Costo.ToString();
                    ICoberturaBLL logicaCobertura = new CoberturaBLL();
                    listaCobertura = logicaCobertura.CoberturasAgregadas(tipoPoliza.Id);
                    dgvDatosCobertura.DataSource = listaCobertura;
                }
                else
                {
                    MessageBox.Show("Seleccione el registro !", "", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza._MyLogControlEventos, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CambiarEstadoMantenimiento(), Interfaces.ICoberturaBLL.CoberturasAgregadas(), Entities.TipoPoliza.Costo, Entities.TipoPoliza.Descripcion, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvDatos, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvDatosCobertura, Entities.TipoPoliza.Id, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.listaCobertura, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.txtCosto, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.txtDescripcion, and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.txtId.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
toolStripBtnEliminar_Click()
void Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEliminar_Click (object sender, EventArgs e) private
Elimina el tipo de poliza seleccionado
Parameters
sender
e
Definition at line 317 of file frmMantenimientoTipoPoliza.cs.
        {
            IDetallePolizaBLL detallePolizaBLL = new DetallePolizaBLL();
            ITipoPolizaBLL logicaTipoPoliza = new TipoPolizaBLL();
            try
            {
                if (this.dgvDatos.SelectedRows.Count > 0)
                {
                    TipoPoliza tipoPoliza = this.dgvDatos.SelectedRows[0].DataBoundItem as TipoPoliza;
                    if (MessageBox.Show($"¿Seguro que desea borrar el registro {tipoPoliza.Id} {tipoPoliza.Descripcion}?", "Confirmación", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
                    {
                        if (dgvCoberturasAgregadas.Rows.Count != 0)
{
                            detallePolizaBLL.EliminarByIdTipoPoliza(tipoPoliza.Id);
                        }
                        logicaTipoPoliza.Eliminar(tipoPoliza.Id);
                        this.CargarDatos();
                        this.CambiarEstadoMantenimiento(EstadoMantenimiento.Nuevo);
                    }
                }
                else
                {
                    MessageBox.Show("Seleccione el registro !", "Atención", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza._MyLogControlEventos, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CambiarEstadoMantenimiento(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CargarDatos(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvCoberturasAgregadas, Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvDatos, Interfaces.ITipoPolizaBLL.Eliminar(), Interfaces.IDetallePolizaBLL.EliminarByIdTipoPoliza(), and Entities.TipoPoliza.Id.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
toolStripBtnNuevo_Click()
void Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnNuevo_Click (object sender, EventArgs e) private
Definition at line 278 of file frmMantenimientoTipoPoliza.cs.
        {
            CambiarEstadoMantenimiento(EstadoMantenimiento.Nuevo);
        }
References Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CambiarEstadoMantenimiento().
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
toolStripBtnSalir_Click()
void Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnSalir_Click (object sender, EventArgs e) private
Sale del form
Parameters
sender
e
Definition at line 358 of file frmMantenimientoTipoPoliza.cs.
        {
            this.Close();
        }
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
Member Data Documentation
_MyLogControlEventos
readonly ILog Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 22 of file frmMantenimientoTipoPoliza.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CargarDatos(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEditar_Click(), and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEliminar_Click().
btnAceptar
System.Windows.Forms.Button Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAceptar private
Definition at line 539 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
btnAgregarCobertura
System.Windows.Forms.Button Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAgregarCobertura private
Definition at line 545 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
btnCancelar
System.Windows.Forms.Button Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnCancelar private
Definition at line 538 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
btnEliminarCobAgregada
System.Windows.Forms.Button Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnEliminarCobAgregada private
Definition at line 551 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
cmbCobertura
System.Windows.Forms.ComboBox Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.cmbCobertura private
Definition at line 544 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAgregarCobertura_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CambiarEstadoMantenimiento(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CargarDatos(), and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
components
System.ComponentModel.IContainer Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.components = null private
Required designer variable.
Definition at line 8 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.Dispose().
Costo
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.Costo private
Definition at line 563 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
dataGridViewTextBoxColumn1
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dataGridViewTextBoxColumn1 private
Definition at line 557 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
dataGridViewTextBoxColumn2
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dataGridViewTextBoxColumn2 private
Definition at line 553 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
dataGridViewTextBoxColumn3
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dataGridViewTextBoxColumn3 private
Definition at line 555 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
dataGridViewTextBoxColumn4
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dataGridViewTextBoxColumn4 private
Definition at line 554 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
Descripcion
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.Descripcion private
Definition at line 558 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
DescripcionTipoPlan
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.DescripcionTipoPlan private
Definition at line 562 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
dgvCoberturasAgregadas
System.Windows.Forms.DataGridView Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvCoberturasAgregadas private
Definition at line 549 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CambiarEstadoMantenimiento(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvDatos_CellMouseClick(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent(), and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEliminar_Click().
dgvDatos
System.Windows.Forms.DataGridView Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvDatos private
Definition at line 536 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CargarDatos(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvDatos_CellMouseClick(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEditar_Click(), and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEliminar_Click().
dgvDatosCobertura
System.Windows.Forms.DataGridView Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvDatosCobertura private
Definition at line 546 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAgregarCobertura_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnEliminarCobAgregada_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CambiarEstadoMantenimiento(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent(), and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEditar_Click().
estadoMantenimiento
EstadoMantenimiento Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.estadoMantenimiento private
Definition at line 20 of file frmMantenimientoTipoPoliza.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CambiarEstadoMantenimiento().
Id
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.Id private
Definition at line 561 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
lblCobertura
System.Windows.Forms.Label Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.lblCobertura private
Definition at line 543 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
lblCoberturaAgregadas
System.Windows.Forms.Label Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.lblCoberturaAgregadas private
Definition at line 548 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
lblCosto
System.Windows.Forms.Label Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.lblCosto private
Definition at line 565 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
lblDescripcion
System.Windows.Forms.Label Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.lblDescripcion private
Definition at line 540 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
lblId
System.Windows.Forms.Label Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.lblId private
Definition at line 547 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
lblTipoPoliza
System.Windows.Forms.Label Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.lblTipoPoliza private
Definition at line 550 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
listaCobertura
List<Cobertura> Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.listaCobertura private
Definition at line 21 of file frmMantenimientoTipoPoliza.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAgregarCobertura_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnEliminarCobAgregada_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CambiarEstadoMantenimiento(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.frmMantenimientoTipoPoliza(), and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEditar_Click().
panel1
System.Windows.Forms.Panel Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.panel1 private
Definition at line 542 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
panel2
System.Windows.Forms.Panel Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.panel2 private
Definition at line 552 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
Precio
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.Precio private
Definition at line 559 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
splitContainer1
System.Windows.Forms.SplitContainer Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.splitContainer1 private
Definition at line 535 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
toolStripBtnEditar
System.Windows.Forms.ToolStripButton Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEditar private
Definition at line 532 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
toolStripBtnEliminar
System.Windows.Forms.ToolStripButton Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEliminar private
Definition at line 533 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
toolStripBtnNuevo
System.Windows.Forms.ToolStripButton Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnNuevo private
Definition at line 531 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
toolStripBtnSalir
System.Windows.Forms.ToolStripButton Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnSalir private
Definition at line 534 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
Total
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.Total private
Definition at line 556 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
Totall
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.Totall private
Definition at line 560 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
tspMantenimientos
System.Windows.Forms.ToolStrip Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.tspMantenimientos private
Definition at line 530 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent().
txtCosto
System.Windows.Forms.TextBox Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.txtCosto private
Definition at line 564 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAgregarCobertura_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CambiarEstadoMantenimiento(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent(), and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEditar_Click().
txtDescripcion
System.Windows.Forms.TextBox Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.txtDescripcion private
Definition at line 541 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CambiarEstadoMantenimiento(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent(), and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEditar_Click().
txtId
System.Windows.Forms.TextBox Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.txtId private
Definition at line 537 of file frmMantenimientoTipoPoliza.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnEliminarCobAgregada_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CambiarEstadoMantenimiento(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.InitializeComponent(), and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEditar_Click().
The documentation for this class was generated from the following files:
Capa.UI/Mantenimientos/frmMantenimientoTipoPoliza.cs
Capa.UI/Mantenimientos/frmMantenimientoTipoPoliza.Designer.cs