Proyecto Autos Seguros: Capa.UI.Login.frmIniciarSesion Class Reference
Capa.UI.Login.frmIniciarSesion Class Reference
Public Member Functions
frmIniciarSesion ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
static void ReleaseCapure ()
Usado para la movilidad por pantalla
static void SendMessage (System.IntPtr hwnd, int wmsg, int wparam, int lparam)
void btnCerrar_Click (object sender, EventArgs e)
void btnMinimizar_Click (object sender, EventArgs e)
Minimiza el login
void pbVisible_Click (object sender, EventArgs e)
este método trae el picture box de ocultar para el frente
void pbOcultar_Click (object sender, EventArgs e)
este método trae el picture box de mostrar para el frente
void btnIngresar_Click (object sender, EventArgs e)
Este método valida que los campos de correo y clave estén con datos, si es así, llama al bll y el bll llamar al dal para consultar en la base de datos la existencia de ese usuario, si la respuesta es positiva, entonces carga el frame principal
void frmIniciarSesion_MouseDown (object sender, MouseEventArgs e)
void VolverInicioDeSesion (Object sender, FormClosedEventArgs e)
Este método se ejecuta cada vez que se vuelve al presente frame
void pnl1_MouseDown (object sender, MouseEventArgs e)
void frmIniciarSesion_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.PictureBox pbLogo
System.Windows.Forms.PictureBox btnCerrar
System.Windows.Forms.Button btnIngresar
System.Windows.Forms.PictureBox btnMinimizar
System.Windows.Forms.Label lblTitulo
System.Windows.Forms.TextBox txtPassword
System.Windows.Forms.TextBox txtCorreo
System.Windows.Forms.PictureBox pbVisible
System.Windows.Forms.PictureBox pbOcultar
System.Windows.Forms.Label label1
System.Windows.Forms.Label label2
System.Windows.Forms.Panel pnl1
Detailed Description
Definition at line 16 of file frmIniciarSesion.cs.
Constructor & Destructor Documentation
frmIniciarSesion()
Capa.UI.Login.frmIniciarSesion.frmIniciarSesion ()
Definition at line 18 of file frmIniciarSesion.cs.
        {
            InitializeComponent();
        }
References Capa.UI.Login.frmIniciarSesion.InitializeComponent().
Member Function Documentation
btnCerrar_Click()
void Capa.UI.Login.frmIniciarSesion.btnCerrar_Click (object sender, EventArgs e) private
Definition at line 33 of file frmIniciarSesion.cs.
        {
                    System.Windows.Forms.Application.Exit();
    }
Referenced by Capa.UI.Login.frmIniciarSesion.InitializeComponent().
btnIngresar_Click()
void Capa.UI.Login.frmIniciarSesion.btnIngresar_Click (object sender, EventArgs e) private
Este método valida que los campos de correo y clave estén con datos, si es así, llama al bll y el bll llamar al dal para consultar en la base de datos la existencia de ese usuario, si la respuesta es positiva, entonces carga el frame principal
Parameters
sender
e
Definition at line 80 of file frmIniciarSesion.cs.
        {
            try
            {
                IUsuarioBLL logica = new UsuarioBLL();
                if (txtCorreo.Text == "CORREO" || txtCorreo.Text == "")
                {
                    MessageBox.Show("Debe de ingresar su correo");
                    txtCorreo.Clear();
                    txtCorreo.Focus(); ;
                    return;
                }
                if (txtPassword.Text == "CLAVE" || txtPassword.Text == "")
                {
                    MessageBox.Show("Debe de ingresar una clave");
                    txtPassword.Clear();
                    txtPassword.Focus();
                    return;
                }
                if (logica.VerificarAcceso(txtCorreo.Text, txtPassword.Text))
                {
                    frmPrincipal frm = new frmPrincipal();
                    frm.Show();
                    this.Hide();
                    frm.FormClosed += VolverInicioDeSesion;
                }
                else
                {
                    MessageBox.Show("Email o contraseña incorrectos");
                    return;
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
              //  _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Login.frmIniciarSesion.txtCorreo, Capa.UI.Login.frmIniciarSesion.txtPassword, Interfaces.IUsuarioBLL.VerificarAcceso(), and Capa.UI.Login.frmIniciarSesion.VolverInicioDeSesion().
Referenced by Capa.UI.Login.frmIniciarSesion.InitializeComponent().
btnMinimizar_Click()
void Capa.UI.Login.frmIniciarSesion.btnMinimizar_Click (object sender, EventArgs e) private
Minimiza el login
Parameters
sender
e
Definition at line 42 of file frmIniciarSesion.cs.
        {
            this.WindowState = FormWindowState.Minimized;
        }
Referenced by Capa.UI.Login.frmIniciarSesion.InitializeComponent().
Dispose()
override void Capa.UI.Login.frmIniciarSesion.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file frmIniciarSesion.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References Capa.UI.Login.frmIniciarSesion.components.
frmIniciarSesion_Load()
void Capa.UI.Login.frmIniciarSesion.frmIniciarSesion_Load (object sender, EventArgs e) private
Definition at line 148 of file frmIniciarSesion.cs.
        {
            txtPassword.UseSystemPasswordChar = true;
        }
References Capa.UI.Login.frmIniciarSesion.txtPassword.
Referenced by Capa.UI.Login.frmIniciarSesion.InitializeComponent().
frmIniciarSesion_MouseDown()
void Capa.UI.Login.frmIniciarSesion.frmIniciarSesion_MouseDown (object sender, MouseEventArgs e) private
Definition at line 123 of file frmIniciarSesion.cs.
        {
            ReleaseCapure();
            SendMessage(this.Handle, 0x112, 0xf012, 0);
        }
References Capa.UI.Login.frmIniciarSesion.ReleaseCapure(), and Capa.UI.Login.frmIniciarSesion.SendMessage().
Referenced by Capa.UI.Login.frmIniciarSesion.InitializeComponent().
InitializeComponent()
void Capa.UI.Login.frmIniciarSesion.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file frmIniciarSesion.Designer.cs.
        {
            this.btnIngresar = new System.Windows.Forms.Button();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.txtPassword = new System.Windows.Forms.TextBox();
            this.txtCorreo = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.pbVisible = new System.Windows.Forms.PictureBox();
            this.pbOcultar = new System.Windows.Forms.PictureBox();
            this.btnCerrar = new System.Windows.Forms.PictureBox();
            this.btnMinimizar = new System.Windows.Forms.PictureBox();
            this.pbLogo = new System.Windows.Forms.PictureBox();
            this.pnl1 = new System.Windows.Forms.Panel();
            ((System.ComponentModel.ISupportInitialize)(this.pbVisible)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbOcultar)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnCerrar)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnMinimizar)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbLogo)).BeginInit();
            this.pnl1.SuspendLayout();
            this.SuspendLayout();
            //
            // btnIngresar
            //
            this.btnIngresar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(138)))), ((int)(((byte)(181)))));
            this.btnIngresar.FlatAppearance.BorderSize = 0;
            this.btnIngresar.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnIngresar.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnIngresar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnIngresar.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnIngresar.ForeColor = System.Drawing.Color.White;
            this.btnIngresar.Location = new System.Drawing.Point(257, 259);
            this.btnIngresar.Name = "btnIngresar";
            this.btnIngresar.Size = new System.Drawing.Size(408, 40);
            this.btnIngresar.TabIndex = 19;
            this.btnIngresar.Text = "Iniciar Sesión";
            this.btnIngresar.UseVisualStyleBackColor = false;
            this.btnIngresar.Click += new System.EventHandler(this.btnIngresar_Click);
            //
            // lblTitulo
            //
            this.lblTitulo.AutoSize = true;
            this.lblTitulo.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.lblTitulo.Font = new System.Drawing.Font("Century Gothic", 21.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitulo.ForeColor = System.Drawing.Color.White;
            this.lblTitulo.Location = new System.Drawing.Point(372, 9);
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.Size = new System.Drawing.Size(240, 36);
            this.lblTitulo.TabIndex = 16;
            this.lblTitulo.Text = "Seguros Pipitica";
            //
            // txtPassword
            //
            this.txtPassword.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(138)))), ((int)(((byte)(181)))));
            this.txtPassword.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.txtPassword.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPassword.ForeColor = System.Drawing.Color.Gainsboro;
            this.txtPassword.Location = new System.Drawing.Point(257, 191);
            this.txtPassword.Name = "txtPassword";
            this.txtPassword.Size = new System.Drawing.Size(408, 20);
            this.txtPassword.TabIndex = 18;
            //
            // txtCorreo
            //
            this.txtCorreo.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(138)))), ((int)(((byte)(181)))));
            this.txtCorreo.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.txtCorreo.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCorreo.ForeColor = System.Drawing.Color.Gainsboro;
            this.txtCorreo.Location = new System.Drawing.Point(257, 123);
            this.txtCorreo.Name = "txtCorreo";
            this.txtCorreo.Size = new System.Drawing.Size(408, 20);
            this.txtCorreo.TabIndex = 17;
            //
            // label1
            //
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.label1.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(257, 98);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(63, 21);
            this.label1.TabIndex = 24;
            this.label1.Text = "Correo";
            //
            // label2
            //
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.label2.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(257, 166);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(57, 21);
            this.label2.TabIndex = 25;
            this.label2.Text = "Clave";
            //
            // pbVisible
            //
            this.pbVisible.Image = global::Capa.UI.Properties.Resources.visible;
            this.pbVisible.Location = new System.Drawing.Point(673, 184);
            this.pbVisible.Name = "pbVisible";
            this.pbVisible.Size = new System.Drawing.Size(43, 27);
            this.pbVisible.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbVisible.TabIndex = 22;
            this.pbVisible.TabStop = false;
            this.pbVisible.Click += new System.EventHandler(this.pbVisible_Click);
            //
            // pbOcultar
            //
            this.pbOcultar.Image = global::Capa.UI.Properties.Resources.oculta;
            this.pbOcultar.Location = new System.Drawing.Point(673, 184);
            this.pbOcultar.Name = "pbOcultar";
            this.pbOcultar.Size = new System.Drawing.Size(43, 27);
            this.pbOcultar.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbOcultar.TabIndex = 23;
            this.pbOcultar.TabStop = false;
            this.pbOcultar.Click += new System.EventHandler(this.pbOcultar_Click);
            //
            // btnCerrar
            //
            this.btnCerrar.ErrorImage = null;
            this.btnCerrar.Image = global::Capa.UI.Properties.Resources.cerrar;
            this.btnCerrar.Location = new System.Drawing.Point(711, 0);
            this.btnCerrar.Name = "btnCerrar";
            this.btnCerrar.Size = new System.Drawing.Size(17, 20);
            this.btnCerrar.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.btnCerrar.TabIndex = 20;
            this.btnCerrar.TabStop = false;
            this.btnCerrar.Click += new System.EventHandler(this.btnCerrar_Click);
            //
            // btnMinimizar
            //
            this.btnMinimizar.ErrorImage = null;
            this.btnMinimizar.Image = global::Capa.UI.Properties.Resources.minimizar;
            this.btnMinimizar.Location = new System.Drawing.Point(690, 0);
            this.btnMinimizar.Name = "btnMinimizar";
            this.btnMinimizar.Size = new System.Drawing.Size(20, 20);
            this.btnMinimizar.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.btnMinimizar.TabIndex = 21;
            this.btnMinimizar.TabStop = false;
            this.btnMinimizar.Click += new System.EventHandler(this.btnMinimizar_Click);
            //
            // pbLogo
            //
            this.pbLogo.Image = global::Capa.UI.Properties.Resources.icons8_car_seat_120px;
            this.pbLogo.Location = new System.Drawing.Point(59, 87);
            this.pbLogo.Name = "pbLogo";
            this.pbLogo.Size = new System.Drawing.Size(120, 124);
            this.pbLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbLogo.TabIndex = 0;
            this.pbLogo.TabStop = false;
            //
            // pnl1
            //
            this.pnl1.BackColor = System.Drawing.Color.WhiteSmoke;
            this.pnl1.Controls.Add(this.pbLogo);
            this.pnl1.Location = new System.Drawing.Point(1, 0);
            this.pnl1.Name = "pnl1";
            this.pnl1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.pnl1.Size = new System.Drawing.Size(236, 330);
            this.pnl1.TabIndex = 26;
            //
            // frmIniciarSesion
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.ClientSize = new System.Drawing.Size(728, 331);
            this.Controls.Add(this.pnl1);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.pbVisible);
            this.Controls.Add(this.pbOcultar);
            this.Controls.Add(this.btnCerrar);
            this.Controls.Add(this.btnIngresar);
            this.Controls.Add(this.btnMinimizar);
            this.Controls.Add(this.lblTitulo);
            this.Controls.Add(this.txtPassword);
            this.Controls.Add(this.txtCorreo);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmIniciarSesion";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmIniciarSesion";
            this.Load += new System.EventHandler(this.frmIniciarSesion_Load);
            this.MouseDown += new System.Windows.Forms.MouseEventHandler(this.frmIniciarSesion_MouseDown);
            ((System.ComponentModel.ISupportInitialize)(this.pbVisible)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbOcultar)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnCerrar)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnMinimizar)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbLogo)).EndInit();
            this.pnl1.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References Capa.UI.Login.frmIniciarSesion.btnCerrar, Capa.UI.Login.frmIniciarSesion.btnCerrar_Click(), Capa.UI.Login.frmIniciarSesion.btnIngresar, Capa.UI.Login.frmIniciarSesion.btnIngresar_Click(), Capa.UI.Login.frmIniciarSesion.btnMinimizar, Capa.UI.Login.frmIniciarSesion.btnMinimizar_Click(), Capa.UI.Login.frmIniciarSesion.frmIniciarSesion_Load(), Capa.UI.Login.frmIniciarSesion.frmIniciarSesion_MouseDown(), Capa.UI.Login.frmIniciarSesion.label1, Capa.UI.Login.frmIniciarSesion.label2, Capa.UI.Login.frmIniciarSesion.lblTitulo, Capa.UI.Login.frmIniciarSesion.pbLogo, Capa.UI.Login.frmIniciarSesion.pbOcultar, Capa.UI.Login.frmIniciarSesion.pbOcultar_Click(), Capa.UI.Login.frmIniciarSesion.pbVisible, Capa.UI.Login.frmIniciarSesion.pbVisible_Click(), Capa.UI.Login.frmIniciarSesion.pnl1, Capa.UI.Login.frmIniciarSesion.txtCorreo, and Capa.UI.Login.frmIniciarSesion.txtPassword.
Referenced by Capa.UI.Login.frmIniciarSesion.frmIniciarSesion().
pbOcultar_Click()
void Capa.UI.Login.frmIniciarSesion.pbOcultar_Click (object sender, EventArgs e) private
este método trae el picture box de mostrar para el frente
Parameters
sender
e
Definition at line 65 of file frmIniciarSesion.cs.
        {
                txtPassword.UseSystemPasswordChar = true;
                pbVisible.BringToFront();
        }
References Capa.UI.Login.frmIniciarSesion.pbVisible, and Capa.UI.Login.frmIniciarSesion.txtPassword.
Referenced by Capa.UI.Login.frmIniciarSesion.InitializeComponent().
pbVisible_Click()
void Capa.UI.Login.frmIniciarSesion.pbVisible_Click (object sender, EventArgs e) private
este método trae el picture box de ocultar para el frente
Parameters
sender
e
Definition at line 53 of file frmIniciarSesion.cs.
        {
                txtPassword.UseSystemPasswordChar = false;
                pbOcultar.BringToFront();
        }
References Capa.UI.Login.frmIniciarSesion.pbOcultar, and Capa.UI.Login.frmIniciarSesion.txtPassword.
Referenced by Capa.UI.Login.frmIniciarSesion.InitializeComponent().
pnl1_MouseDown()
void Capa.UI.Login.frmIniciarSesion.pnl1_MouseDown (object sender, MouseEventArgs e) private
Definition at line 143 of file frmIniciarSesion.cs.
        {
        }
ReleaseCapure()
static void Capa.UI.Login.frmIniciarSesion.ReleaseCapure () private
Usado para la movilidad por pantalla
Referenced by Capa.UI.Login.frmIniciarSesion.frmIniciarSesion_MouseDown().
SendMessage()
static void Capa.UI.Login.frmIniciarSesion.SendMessage (System.IntPtr hwnd, int wmsg, int wparam, int lparam) private
Referenced by Capa.UI.Login.frmIniciarSesion.frmIniciarSesion_MouseDown().
VolverInicioDeSesion()
void Capa.UI.Login.frmIniciarSesion.VolverInicioDeSesion (Object sender, FormClosedEventArgs e) private
Este método se ejecuta cada vez que se vuelve al presente frame
Parameters
sender
e
Definition at line 135 of file frmIniciarSesion.cs.
        {
            txtCorreo.Clear();
            txtPassword.Clear();
            txtPassword.UseSystemPasswordChar = false;
            this.Show();
        }
References Capa.UI.Login.frmIniciarSesion.txtCorreo, and Capa.UI.Login.frmIniciarSesion.txtPassword.
Referenced by Capa.UI.Login.frmIniciarSesion.btnIngresar_Click().
Member Data Documentation
btnCerrar
System.Windows.Forms.PictureBox Capa.UI.Login.frmIniciarSesion.btnCerrar private
Definition at line 228 of file frmIniciarSesion.Designer.cs.
Referenced by Capa.UI.Login.frmIniciarSesion.InitializeComponent().
btnIngresar
System.Windows.Forms.Button Capa.UI.Login.frmIniciarSesion.btnIngresar private
Definition at line 229 of file frmIniciarSesion.Designer.cs.
Referenced by Capa.UI.Login.frmIniciarSesion.InitializeComponent().
btnMinimizar
System.Windows.Forms.PictureBox Capa.UI.Login.frmIniciarSesion.btnMinimizar private
Definition at line 230 of file frmIniciarSesion.Designer.cs.
Referenced by Capa.UI.Login.frmIniciarSesion.InitializeComponent().
components
System.ComponentModel.IContainer Capa.UI.Login.frmIniciarSesion.components = null private
Required designer variable.
Definition at line 8 of file frmIniciarSesion.Designer.cs.
Referenced by Capa.UI.Login.frmIniciarSesion.Dispose().
label1
System.Windows.Forms.Label Capa.UI.Login.frmIniciarSesion.label1 private
Definition at line 236 of file frmIniciarSesion.Designer.cs.
Referenced by Capa.UI.Login.frmIniciarSesion.InitializeComponent().
label2
System.Windows.Forms.Label Capa.UI.Login.frmIniciarSesion.label2 private
Definition at line 237 of file frmIniciarSesion.Designer.cs.
Referenced by Capa.UI.Login.frmIniciarSesion.InitializeComponent().
lblTitulo
System.Windows.Forms.Label Capa.UI.Login.frmIniciarSesion.lblTitulo private
Definition at line 231 of file frmIniciarSesion.Designer.cs.
Referenced by Capa.UI.Login.frmIniciarSesion.InitializeComponent().
pbLogo
System.Windows.Forms.PictureBox Capa.UI.Login.frmIniciarSesion.pbLogo private
Definition at line 227 of file frmIniciarSesion.Designer.cs.
Referenced by Capa.UI.Login.frmIniciarSesion.InitializeComponent().
pbOcultar
System.Windows.Forms.PictureBox Capa.UI.Login.frmIniciarSesion.pbOcultar private
Definition at line 235 of file frmIniciarSesion.Designer.cs.
Referenced by Capa.UI.Login.frmIniciarSesion.InitializeComponent(), and Capa.UI.Login.frmIniciarSesion.pbVisible_Click().
pbVisible
System.Windows.Forms.PictureBox Capa.UI.Login.frmIniciarSesion.pbVisible private
Definition at line 234 of file frmIniciarSesion.Designer.cs.
Referenced by Capa.UI.Login.frmIniciarSesion.InitializeComponent(), and Capa.UI.Login.frmIniciarSesion.pbOcultar_Click().
pnl1
System.Windows.Forms.Panel Capa.UI.Login.frmIniciarSesion.pnl1 private
Definition at line 238 of file frmIniciarSesion.Designer.cs.
Referenced by Capa.UI.Login.frmIniciarSesion.InitializeComponent().
txtCorreo
System.Windows.Forms.TextBox Capa.UI.Login.frmIniciarSesion.txtCorreo private
Definition at line 233 of file frmIniciarSesion.Designer.cs.
Referenced by Capa.UI.Login.frmIniciarSesion.btnIngresar_Click(), Capa.UI.Login.frmIniciarSesion.InitializeComponent(), and Capa.UI.Login.frmIniciarSesion.VolverInicioDeSesion().
txtPassword
System.Windows.Forms.TextBox Capa.UI.Login.frmIniciarSesion.txtPassword private
Definition at line 232 of file frmIniciarSesion.Designer.cs.
Referenced by Capa.UI.Login.frmIniciarSesion.btnIngresar_Click(), Capa.UI.Login.frmIniciarSesion.frmIniciarSesion_Load(), Capa.UI.Login.frmIniciarSesion.InitializeComponent(), Capa.UI.Login.frmIniciarSesion.pbOcultar_Click(), Capa.UI.Login.frmIniciarSesion.pbVisible_Click(), and Capa.UI.Login.frmIniciarSesion.VolverInicioDeSesion().
The documentation for this class was generated from the following files:
Capa.UI/Login/frmIniciarSesion.cs
Capa.UI/Login/frmIniciarSesion.Designer.cs