Proyecto Autos Seguros: Capa.UI.Mantenimientos.frmMantenimientoIVA Class Reference
Capa.UI.Mantenimientos.frmMantenimientoIVA Class Reference
Public Member Functions
frmMantenimientoIVA ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void CargarDatos ()
Llena los datos
void CambiarEstadoMantenimiento (EstadoMantenimiento estado)
Cambia el estado de mantenimiento según el enum
void btnAceptar_Click (object sender, EventArgs e)
guarda el registro en la base de datos
void toolStripBtnNuevo_Click (object sender, EventArgs e)
Limpia los campos por medio del método cambiar estado mantenimiento
void toolStripBtnEditar_Click (object sender, EventArgs e)
Selecciona el registro de la tabla para editarlo
void toolStripBtnEliminar_Click (object sender, EventArgs e)
void toolStripBtnSalir_Click (object sender, EventArgs e)
void frmMantenimientoIVA_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
EstadoMantenimiento estadoMantenimiento
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.ToolStrip tspMantenimientos
System.Windows.Forms.ToolStripButton toolStripBtnNuevo
System.Windows.Forms.ToolStripButton toolStripBtnEditar
System.Windows.Forms.ToolStripButton toolStripBtnEliminar
System.Windows.Forms.ToolStripButton toolStripBtnSalir
System.Windows.Forms.SplitContainer splitContainer1
System.Windows.Forms.DataGridView dgvDatos
System.Windows.Forms.DataGridViewTextBoxColumn Id
System.Windows.Forms.DataGridViewTextBoxColumn Porcentaje
System.Windows.Forms.DataGridViewTextBoxColumn Fecha
System.Windows.Forms.TextBox txtId
System.Windows.Forms.Button btnCancelar
System.Windows.Forms.Button btnAceptar
System.Windows.Forms.Label lblPorcentaje
System.Windows.Forms.TextBox txtPorcentaje
Static Private Attributes
static readonly ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 18 of file frmMantenimientoIVA.cs.
Constructor & Destructor Documentation
frmMantenimientoIVA()
Capa.UI.Mantenimientos.frmMantenimientoIVA.frmMantenimientoIVA ()
Definition at line 22 of file frmMantenimientoIVA.cs.
        {
            InitializeComponent();
        }
References Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent().
Member Function Documentation
btnAceptar_Click()
void Capa.UI.Mantenimientos.frmMantenimientoIVA.btnAceptar_Click (object sender, EventArgs e) private
guarda el registro en la base de datos
Parameters
sender
e
Definition at line 97 of file frmMantenimientoIVA.cs.
        {
            ErrorProvider oErrorProvider = new ErrorProvider();
            if (txtPorcentaje.Text == "")
            {
                oErrorProvider.SetError(txtPorcentaje, "Digite un porcentaje");
                return;
            }
            try
            {
                IVA iva = new IVA();
                if (estadoMantenimiento == EstadoMantenimiento.Editar)
                {
                    iva.Id = Int32.Parse(txtId.Text);
                }
                iva.Porcentaje =Decimal.Parse( txtPorcentaje.Text);
                iva.Fecha = DateTime.Now;
                I_IVA_BLL logica = new IVABLL();
                logica.Insertar(iva);
                CargarDatos();
                CambiarEstadoMantenimiento(EstadoMantenimiento.Ninguno);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Mantenimientos.frmMantenimientoIVA._MyLogControlEventos, Capa.UI.Mantenimientos.frmMantenimientoIVA.CambiarEstadoMantenimiento(), Capa.UI.Mantenimientos.frmMantenimientoIVA.CargarDatos(), Capa.UI.Mantenimientos.frmMantenimientoIVA.estadoMantenimiento, Entities.IVA.Fecha, Entities.IVA.Id, Interfaces.I_IVA_BLL.Insertar(), Entities.IVA.Porcentaje, Capa.UI.Mantenimientos.frmMantenimientoIVA.txtId, and Capa.UI.Mantenimientos.frmMantenimientoIVA.txtPorcentaje.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent().
CambiarEstadoMantenimiento()
void Capa.UI.Mantenimientos.frmMantenimientoIVA.CambiarEstadoMantenimiento (EstadoMantenimiento estado) private
Cambia el estado de mantenimiento según el enum
Parameters
estado
Definition at line 54 of file frmMantenimientoIVA.cs.
        {
            txtPorcentaje.Clear();
            txtId.Clear();
            txtPorcentaje.Enabled = false;
            txtId.Enabled = false;
            switch (estado)
            {
                case EstadoMantenimiento.Nuevo:
                    txtPorcentaje.Enabled = true;
                    txtId.Enabled = true;
                    estadoMantenimiento = EstadoMantenimiento.Nuevo;
                    break;
                case EstadoMantenimiento.Editar:
                    txtPorcentaje.Enabled = true;
                    txtId.Enabled = true;
                    estadoMantenimiento = EstadoMantenimiento.Editar;
                    break;
                case EstadoMantenimiento.Borrar:
                    estadoMantenimiento = EstadoMantenimiento.Borrar;
                    break;
                case EstadoMantenimiento.Ninguno:
                    estadoMantenimiento = EstadoMantenimiento.Ninguno;
                    break;
            }
        }
References Capa.UI.Mantenimientos.frmMantenimientoIVA.estadoMantenimiento, Capa.UI.Mantenimientos.frmMantenimientoIVA.txtId, and Capa.UI.Mantenimientos.frmMantenimientoIVA.txtPorcentaje.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnEditar_Click(), Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnEliminar_Click(), and Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnNuevo_Click().
CargarDatos()
void Capa.UI.Mantenimientos.frmMantenimientoIVA.CargarDatos () private
Llena los datos
Definition at line 30 of file frmMantenimientoIVA.cs.
        {
            try
            {
                dgvDatos.AutoGenerateColumns = false;
                dgvDatos.RowTemplate.Height = 100;
                dgvDatos.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
                I_IVA_BLL logica = new IVABLL();
                dgvDatos.DataSource = logica.SeleccionarTodas();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Mantenimientos.frmMantenimientoIVA._MyLogControlEventos, Capa.UI.Mantenimientos.frmMantenimientoIVA.dgvDatos, and Interfaces.I_IVA_BLL.SeleccionarTodas().
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoIVA.frmMantenimientoIVA_Load(), and Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnEliminar_Click().
Dispose()
override void Capa.UI.Mantenimientos.frmMantenimientoIVA.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file frmMantenimientoIVA.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References Capa.UI.Mantenimientos.frmMantenimientoIVA.components.
frmMantenimientoIVA_Load()
void Capa.UI.Mantenimientos.frmMantenimientoIVA.frmMantenimientoIVA_Load (object sender, EventArgs e) private
Definition at line 219 of file frmMantenimientoIVA.cs.
        {
            CargarDatos();
        }
References Capa.UI.Mantenimientos.frmMantenimientoIVA.CargarDatos().
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent().
InitializeComponent()
void Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file frmMantenimientoIVA.Designer.cs.
        {
            this.tspMantenimientos = new System.Windows.Forms.ToolStrip();
            this.toolStripBtnNuevo = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnEditar = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnEliminar = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnSalir = new System.Windows.Forms.ToolStripButton();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.dgvDatos = new System.Windows.Forms.DataGridView();
            this.Id = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Porcentaje = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Fecha = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.txtId = new System.Windows.Forms.TextBox();
            this.btnCancelar = new System.Windows.Forms.Button();
            this.btnAceptar = new System.Windows.Forms.Button();
            this.lblPorcentaje = new System.Windows.Forms.Label();
            this.txtPorcentaje = new System.Windows.Forms.TextBox();
            this.tspMantenimientos.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDatos)).BeginInit();
            this.SuspendLayout();
            //
            // tspMantenimientos
            //
            this.tspMantenimientos.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.tspMantenimientos.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripBtnNuevo,
            this.toolStripBtnEditar,
            this.toolStripBtnEliminar,
            this.toolStripBtnSalir});
            this.tspMantenimientos.Location = new System.Drawing.Point(0, 0);
            this.tspMantenimientos.Name = "tspMantenimientos";
            this.tspMantenimientos.Size = new System.Drawing.Size(792, 25);
            this.tspMantenimientos.TabIndex = 53;
            this.tspMantenimientos.Text = "toolStrip1";
            //
            // toolStripBtnNuevo
            //
            this.toolStripBtnNuevo.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.toolStripBtnNuevo.ForeColor = System.Drawing.Color.White;
            this.toolStripBtnNuevo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnNuevo.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnNuevo.Name = "toolStripBtnNuevo";
            this.toolStripBtnNuevo.Size = new System.Drawing.Size(52, 22);
            this.toolStripBtnNuevo.Text = "Nuevo";
            this.toolStripBtnNuevo.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnNuevo.Click += new System.EventHandler(this.toolStripBtnNuevo_Click);
            //
            // toolStripBtnEditar
            //
            this.toolStripBtnEditar.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnEditar.ForeColor = System.Drawing.Color.White;
            this.toolStripBtnEditar.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnEditar.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnEditar.Name = "toolStripBtnEditar";
            this.toolStripBtnEditar.Size = new System.Drawing.Size(48, 22);
            this.toolStripBtnEditar.Text = "Editar";
            this.toolStripBtnEditar.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.toolStripBtnEditar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnEditar.Click += new System.EventHandler(this.toolStripBtnEditar_Click);
            //
            // toolStripBtnEliminar
            //
            this.toolStripBtnEliminar.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnEliminar.ForeColor = System.Drawing.Color.White;
            this.toolStripBtnEliminar.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnEliminar.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnEliminar.Name = "toolStripBtnEliminar";
            this.toolStripBtnEliminar.Size = new System.Drawing.Size(63, 22);
            this.toolStripBtnEliminar.Text = "Eliminar";
            this.toolStripBtnEliminar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnEliminar.Click += new System.EventHandler(this.toolStripBtnEliminar_Click);
            //
            // toolStripBtnSalir
            //
            this.toolStripBtnSalir.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnSalir.ForeColor = System.Drawing.Color.White;
            this.toolStripBtnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnSalir.Name = "toolStripBtnSalir";
            this.toolStripBtnSalir.Size = new System.Drawing.Size(39, 22);
            this.toolStripBtnSalir.Text = "Salir";
            this.toolStripBtnSalir.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnSalir.Click += new System.EventHandler(this.toolStripBtnSalir_Click);
            //
            // splitContainer1
            //
            this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer1.Location = new System.Drawing.Point(0, 25);
            this.splitContainer1.Name = "splitContainer1";
            //
            // splitContainer1.Panel1
            //
            this.splitContainer1.Panel1.Controls.Add(this.dgvDatos);
            //
            // splitContainer1.Panel2
            //
            this.splitContainer1.Panel2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.splitContainer1.Panel2.Controls.Add(this.txtId);
            this.splitContainer1.Panel2.Controls.Add(this.btnCancelar);
            this.splitContainer1.Panel2.Controls.Add(this.btnAceptar);
            this.splitContainer1.Panel2.Controls.Add(this.lblPorcentaje);
            this.splitContainer1.Panel2.Controls.Add(this.txtPorcentaje);
            this.splitContainer1.Size = new System.Drawing.Size(792, 516);
            this.splitContainer1.SplitterDistance = 380;
            this.splitContainer1.TabIndex = 54;
            //
            // dgvDatos
            //
            this.dgvDatos.AllowUserToAddRows = false;
            this.dgvDatos.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvDatos.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Id,
            this.Porcentaje,
            this.Fecha});
            this.dgvDatos.Location = new System.Drawing.Point(0, 3);
            this.dgvDatos.Name = "dgvDatos";
            this.dgvDatos.ReadOnly = true;
            this.dgvDatos.Size = new System.Drawing.Size(548, 487);
            this.dgvDatos.TabIndex = 25;
            //
            // Id
            //
            this.Id.DataPropertyName = "Id";
            this.Id.HeaderText = "Id";
            this.Id.Name = "Id";
            this.Id.ReadOnly = true;
            //
            // Porcentaje
            //
            this.Porcentaje.DataPropertyName = "Porcentaje";
            this.Porcentaje.HeaderText = "Porcentaje";
            this.Porcentaje.Name = "Porcentaje";
            this.Porcentaje.ReadOnly = true;
            //
            // Fecha
            //
            this.Fecha.DataPropertyName = "Fecha";
            this.Fecha.HeaderText = "Fecha";
            this.Fecha.Name = "Fecha";
            this.Fecha.ReadOnly = true;
            //
            // txtId
            //
            this.txtId.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(138)))), ((int)(((byte)(181)))));
            this.txtId.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtId.Enabled = false;
            this.txtId.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtId.ForeColor = System.Drawing.Color.White;
            this.txtId.Location = new System.Drawing.Point(125, 28);
            this.txtId.Name = "txtId";
            this.txtId.Size = new System.Drawing.Size(167, 27);
            this.txtId.TabIndex = 150;
            this.txtId.Visible = false;
            //
            // btnCancelar
            //
            this.btnCancelar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(138)))), ((int)(((byte)(181)))));
            this.btnCancelar.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnCancelar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCancelar.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancelar.ForeColor = System.Drawing.Color.White;
            this.btnCancelar.Location = new System.Drawing.Point(275, 405);
            this.btnCancelar.Name = "btnCancelar";
            this.btnCancelar.Size = new System.Drawing.Size(99, 45);
            this.btnCancelar.TabIndex = 149;
            this.btnCancelar.Text = "Cancelar";
            this.btnCancelar.UseVisualStyleBackColor = false;
            //
            // btnAceptar
            //
            this.btnAceptar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(138)))), ((int)(((byte)(181)))));
            this.btnAceptar.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnAceptar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAceptar.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAceptar.ForeColor = System.Drawing.Color.White;
            this.btnAceptar.Location = new System.Drawing.Point(35, 405);
            this.btnAceptar.Name = "btnAceptar";
            this.btnAceptar.Size = new System.Drawing.Size(99, 45);
            this.btnAceptar.TabIndex = 148;
            this.btnAceptar.Text = "Aceptar";
            this.btnAceptar.UseVisualStyleBackColor = false;
            this.btnAceptar.Click += new System.EventHandler(this.btnAceptar_Click);
            //
            // lblPorcentaje
            //
            this.lblPorcentaje.AutoSize = true;
            this.lblPorcentaje.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPorcentaje.ForeColor = System.Drawing.Color.White;
            this.lblPorcentaje.Location = new System.Drawing.Point(122, 97);
            this.lblPorcentaje.Name = "lblPorcentaje";
            this.lblPorcentaje.Size = new System.Drawing.Size(97, 16);
            this.lblPorcentaje.TabIndex = 146;
            this.lblPorcentaje.Text = "Porcentaje(%)";
            this.lblPorcentaje.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            //
            // txtPorcentaje
            //
            this.txtPorcentaje.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(138)))), ((int)(((byte)(181)))));
            this.txtPorcentaje.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtPorcentaje.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPorcentaje.ForeColor = System.Drawing.Color.White;
            this.txtPorcentaje.Location = new System.Drawing.Point(125, 116);
            this.txtPorcentaje.Name = "txtPorcentaje";
            this.txtPorcentaje.Size = new System.Drawing.Size(167, 27);
            this.txtPorcentaje.TabIndex = 147;
            //
            // frmMantenimientoIVA
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.ClientSize = new System.Drawing.Size(792, 541);
            this.Controls.Add(this.splitContainer1);
            this.Controls.Add(this.tspMantenimientos);
            this.Cursor = System.Windows.Forms.Cursors.Cross;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmMantenimientoIVA";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmMantenimientoIVA";
            this.Load += new System.EventHandler(this.frmMantenimientoIVA_Load);
            this.tspMantenimientos.ResumeLayout(false);
            this.tspMantenimientos.PerformLayout();
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            this.splitContainer1.Panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvDatos)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References Capa.UI.Mantenimientos.frmMantenimientoIVA.btnAceptar, Capa.UI.Mantenimientos.frmMantenimientoIVA.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoIVA.btnCancelar, Capa.UI.Mantenimientos.frmMantenimientoIVA.dgvDatos, Capa.UI.Mantenimientos.frmMantenimientoIVA.Fecha, Capa.UI.Mantenimientos.frmMantenimientoIVA.frmMantenimientoIVA_Load(), Capa.UI.Mantenimientos.frmMantenimientoIVA.Id, Capa.UI.Mantenimientos.frmMantenimientoIVA.lblPorcentaje, Capa.UI.Mantenimientos.frmMantenimientoIVA.Porcentaje, Capa.UI.Mantenimientos.frmMantenimientoIVA.splitContainer1, Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnEditar, Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnEditar_Click(), Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnEliminar, Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnEliminar_Click(), Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnNuevo, Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnNuevo_Click(), Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnSalir, Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnSalir_Click(), Capa.UI.Mantenimientos.frmMantenimientoIVA.tspMantenimientos, Capa.UI.Mantenimientos.frmMantenimientoIVA.txtId, and Capa.UI.Mantenimientos.frmMantenimientoIVA.txtPorcentaje.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.frmMantenimientoIVA().
toolStripBtnEditar_Click()
void Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnEditar_Click (object sender, EventArgs e) private
Selecciona el registro de la tabla para editarlo
Parameters
sender
e
Definition at line 157 of file frmMantenimientoIVA.cs.
        {
            IVA oIVA = null;
            try
            {
                if (this.dgvDatos.SelectedRows.Count > 0)
                {
                    // Cambiar de estado
                    this.CambiarEstadoMantenimiento(EstadoMantenimiento.Editar);
                    //Extraer el DTO seleccionado
                    oIVA = this.dgvDatos.SelectedRows[0].DataBoundItem as IVA;
                    this.txtId.Text = oIVA.Id.ToString();
                    this.txtPorcentaje.Text = oIVA.Porcentaje.ToString();
                }
                else
                {
                    MessageBox.Show("Seleccione el registro !", "", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Mantenimientos.frmMantenimientoIVA._MyLogControlEventos, Capa.UI.Mantenimientos.frmMantenimientoIVA.CambiarEstadoMantenimiento(), Capa.UI.Mantenimientos.frmMantenimientoIVA.dgvDatos, Entities.IVA.Id, Entities.IVA.Porcentaje, Capa.UI.Mantenimientos.frmMantenimientoIVA.txtId, and Capa.UI.Mantenimientos.frmMantenimientoIVA.txtPorcentaje.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent().
toolStripBtnEliminar_Click()
void Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnEliminar_Click (object sender, EventArgs e) private
Definition at line 185 of file frmMantenimientoIVA.cs.
        {
            I_IVA_BLL logica = new IVABLL();
            try
            {
                if (this.dgvDatos.SelectedRows.Count > 0)
                {
                    this.CambiarEstadoMantenimiento(EstadoMantenimiento.Borrar);
                    IVA oIva = this.dgvDatos.SelectedRows[0].DataBoundItem as IVA;
                    if (MessageBox.Show($"¿Seguro que desea borrar el registro {oIva.Id} {oIva.Porcentaje}?", "Confirmación", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
                    {
                        logica.Eliminar(oIva.Id);
                        this.CargarDatos();
                    }
                }
                else
                {
                    MessageBox.Show("Seleccione el registro !", "Atención", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Mantenimientos.frmMantenimientoIVA._MyLogControlEventos, Capa.UI.Mantenimientos.frmMantenimientoIVA.CambiarEstadoMantenimiento(), Capa.UI.Mantenimientos.frmMantenimientoIVA.CargarDatos(), Capa.UI.Mantenimientos.frmMantenimientoIVA.dgvDatos, Interfaces.I_IVA_BLL.Eliminar(), and Entities.IVA.Id.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent().
toolStripBtnNuevo_Click()
void Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnNuevo_Click (object sender, EventArgs e) private
Limpia los campos por medio del método cambiar estado mantenimiento
Parameters
sender
e
Definition at line 139 of file frmMantenimientoIVA.cs.
        {
            try
            {
                this.CambiarEstadoMantenimiento(EstadoMantenimiento.Nuevo);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Mantenimientos.frmMantenimientoIVA._MyLogControlEventos, and Capa.UI.Mantenimientos.frmMantenimientoIVA.CambiarEstadoMantenimiento().
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent().
toolStripBtnSalir_Click()
void Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnSalir_Click (object sender, EventArgs e) private
Definition at line 214 of file frmMantenimientoIVA.cs.
        {
            this.Close();
        }
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent().
Member Data Documentation
_MyLogControlEventos
readonly ILog Capa.UI.Mantenimientos.frmMantenimientoIVA._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 21 of file frmMantenimientoIVA.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoIVA.CargarDatos(), Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnEditar_Click(), Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnEliminar_Click(), and Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnNuevo_Click().
btnAceptar
System.Windows.Forms.Button Capa.UI.Mantenimientos.frmMantenimientoIVA.btnAceptar private
Definition at line 280 of file frmMantenimientoIVA.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent().
btnCancelar
System.Windows.Forms.Button Capa.UI.Mantenimientos.frmMantenimientoIVA.btnCancelar private
Definition at line 279 of file frmMantenimientoIVA.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent().
components
System.ComponentModel.IContainer Capa.UI.Mantenimientos.frmMantenimientoIVA.components = null private
Required designer variable.
Definition at line 8 of file frmMantenimientoIVA.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.Dispose().
dgvDatos
System.Windows.Forms.DataGridView Capa.UI.Mantenimientos.frmMantenimientoIVA.dgvDatos private
Definition at line 274 of file frmMantenimientoIVA.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.CargarDatos(), Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent(), Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnEditar_Click(), and Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnEliminar_Click().
estadoMantenimiento
EstadoMantenimiento Capa.UI.Mantenimientos.frmMantenimientoIVA.estadoMantenimiento private
Definition at line 20 of file frmMantenimientoIVA.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.btnAceptar_Click(), and Capa.UI.Mantenimientos.frmMantenimientoIVA.CambiarEstadoMantenimiento().
Fecha
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoIVA.Fecha private
Definition at line 277 of file frmMantenimientoIVA.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent().
Id
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoIVA.Id private
Definition at line 275 of file frmMantenimientoIVA.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent().
lblPorcentaje
System.Windows.Forms.Label Capa.UI.Mantenimientos.frmMantenimientoIVA.lblPorcentaje private
Definition at line 281 of file frmMantenimientoIVA.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent().
Porcentaje
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Mantenimientos.frmMantenimientoIVA.Porcentaje private
Definition at line 276 of file frmMantenimientoIVA.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent().
splitContainer1
System.Windows.Forms.SplitContainer Capa.UI.Mantenimientos.frmMantenimientoIVA.splitContainer1 private
Definition at line 273 of file frmMantenimientoIVA.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent().
toolStripBtnEditar
System.Windows.Forms.ToolStripButton Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnEditar private
Definition at line 270 of file frmMantenimientoIVA.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent().
toolStripBtnEliminar
System.Windows.Forms.ToolStripButton Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnEliminar private
Definition at line 271 of file frmMantenimientoIVA.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent().
toolStripBtnNuevo
System.Windows.Forms.ToolStripButton Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnNuevo private
Definition at line 269 of file frmMantenimientoIVA.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent().
toolStripBtnSalir
System.Windows.Forms.ToolStripButton Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnSalir private
Definition at line 272 of file frmMantenimientoIVA.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent().
tspMantenimientos
System.Windows.Forms.ToolStrip Capa.UI.Mantenimientos.frmMantenimientoIVA.tspMantenimientos private
Definition at line 268 of file frmMantenimientoIVA.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent().
txtId
System.Windows.Forms.TextBox Capa.UI.Mantenimientos.frmMantenimientoIVA.txtId private
Definition at line 278 of file frmMantenimientoIVA.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoIVA.CambiarEstadoMantenimiento(), Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent(), and Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnEditar_Click().
txtPorcentaje
System.Windows.Forms.TextBox Capa.UI.Mantenimientos.frmMantenimientoIVA.txtPorcentaje private
Definition at line 282 of file frmMantenimientoIVA.Designer.cs.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.btnAceptar_Click(), Capa.UI.Mantenimientos.frmMantenimientoIVA.CambiarEstadoMantenimiento(), Capa.UI.Mantenimientos.frmMantenimientoIVA.InitializeComponent(), and Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnEditar_Click().
The documentation for this class was generated from the following files:
Capa.UI/Mantenimientos/frmMantenimientoIVA.cs
Capa.UI/Mantenimientos/frmMantenimientoIVA.Designer.cs