Proyecto Autos Seguros: Capa.UI.Facturacion.frmFacturacion Class Reference
Capa.UI.Facturacion.frmFacturacion Class Reference
Public Member Functions
frmFacturacion ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void CargarDatos ()
Este métodoc carga los datos que son llamados desde la base de datos y los coloca en sus respectivos combobox y datagrid views
void toolStripBtnSalir_Click (object sender, EventArgs e)
Cierra el form
void frmFacturacion_Load (object sender, EventArgs e)
Carga el culture info para Costa Rica y invoca al método que carga los datos
void btnBuscar_Click (object sender, EventArgs e)
Este método verifica que hayan datos en la parte de tarjetas y si es así, invoca al dialog de filtro usuarios para poder escoger al usuario por facturar una vez hecho esto, vuelve al presente form con los campos de id y nombre cargados
void btnMostrarCoberturas_Click (object sender, EventArgs e)
Este método invoca al frame que muestra las coberturas del tipo de plan seleccionado
void cmbTipoPago_SelectionChangeCommitted (object sender, EventArgs e)
Este método invoca al método calcula costo que trae el precio a pagar según el tipo de pago seleccionado
void toolStripBtnNuevo_Click (object sender, EventArgs e)
Este ,método limpia todos los campos del frame para poder facturar nuevamente
void toolStripBtnFacturar_Click (object sender, EventArgs e)
Este método termina de llenar la factura con los datos para poder ser enviado a la capa lógica y de ahí ser enviado a la base de datos por medio de la DAL
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Factura _Factura = new Factura()
double valorDolar = 0
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.ToolStrip tspBarraSuperior
System.Windows.Forms.ToolStripButton toolStripBtnNuevo
System.Windows.Forms.ToolStripButton toolStripBtnFacturar
System.Windows.Forms.ToolStripButton toolStripBtnSalir
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.TextBox txtNumTarjeta
System.Windows.Forms.Label lblTarjeta
System.Windows.Forms.Label lblNumTarjeta
System.Windows.Forms.ComboBox cmbTarjetas
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.Button btnBuscar
System.Windows.Forms.TextBox txtNombre
System.Windows.Forms.Label lblNombre
System.Windows.Forms.Label lblId
System.Windows.Forms.TextBox txtId
System.Windows.Forms.DataGridView dgvDatosTipoPlan
System.Windows.Forms.DataGridViewTextBoxColumn Id
System.Windows.Forms.DataGridViewTextBoxColumn DescripcionTipoPlan
System.Windows.Forms.GroupBox groupBox3
System.Windows.Forms.Button btnMostrarCoberturas
System.ComponentModel.BackgroundWorker backgroundWorker1
System.Windows.Forms.ComboBox cmbTipoPago
System.Windows.Forms.Label lblTotalColones
System.Windows.Forms.TextBox txtTotalColones
System.Windows.Forms.Label lblTotal
System.Windows.Forms.TextBox txtTotal
System.Windows.Forms.ErrorProvider erpError
System.Windows.Forms.Label lblTipoPago
Static Private Attributes
static readonly ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 24 of file frmFacturacion.cs.
Constructor & Destructor Documentation
frmFacturacion()
Capa.UI.Facturacion.frmFacturacion.frmFacturacion ()
Definition at line 29 of file frmFacturacion.cs.
        {
            InitializeComponent();
        }
References Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
Member Function Documentation
btnBuscar_Click()
void Capa.UI.Facturacion.frmFacturacion.btnBuscar_Click (object sender, EventArgs e) private
Este método verifica que hayan datos en la parte de tarjetas y si es así, invoca al dialog de filtro usuarios para poder escoger al usuario por facturar una vez hecho esto, vuelve al presente form con los campos de id y nombre cargados
Parameters
sender
e
Definition at line 94 of file frmFacturacion.cs.
        {
            Usuario user = null;
           frmFiltroUsuario frm = new frmFiltroUsuario();
            try
            {
                erpError.Clear();
                if (cmbTarjetas.SelectedIndex == -1)
                {
                    erpError.SetError(cmbTarjetas, "Debe indicar el tipo de tarjeta");
                    return;
                }
                if (string.IsNullOrEmpty(this.txtNumTarjeta.Text))
                {
                    erpError.SetError(txtNumTarjeta, "Debe digitar su número de tarjeta");
                    return;
                }
                frm.ShowDialog();
                if (frm.DialogResult == DialogResult.OK)
                {
                    user = frm._User;
                    txtId.Text = user.Id.ToString();
                    txtNombre.Text = user.Nombre;
                    _Factura.IdUsuario = user.Id;
                }
                _Factura.IdTarjeta = (int)cmbTarjetas.SelectedValue;
                _Factura.NumeroTarjeta = int.Parse(txtNumTarjeta.Text);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Facturacion.frmFacturacion._Factura, Capa.UI.Facturacion.frmFacturacion._MyLogControlEventos, Capa.UI.Filtro.frmFiltroUsuario._User, Capa.UI.Facturacion.frmFacturacion.cmbTarjetas, Capa.UI.Facturacion.frmFacturacion.erpError, Entities.Usuario.Id, capa.Entidades.Factura.IdTarjeta, capa.Entidades.Factura.IdUsuario, Entities.Usuario.Nombre, capa.Entidades.Factura.NumeroTarjeta, Capa.UI.Facturacion.frmFacturacion.txtId, Capa.UI.Facturacion.frmFacturacion.txtNombre, and Capa.UI.Facturacion.frmFacturacion.txtNumTarjeta.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
btnMostrarCoberturas_Click()
void Capa.UI.Facturacion.frmFacturacion.btnMostrarCoberturas_Click (object sender, EventArgs e) private
Este método invoca al frame que muestra las coberturas del tipo de plan seleccionado
Parameters
sender
e
Definition at line 137 of file frmFacturacion.cs.
        {
            frmCoberturasAgregadas frm;
            TipoPoliza tipoPoliza = null;
            try
            {
                if (this.dgvDatosTipoPlan.SelectedRows.Count > 0)
                {
                    tipoPoliza = this.dgvDatosTipoPlan.SelectedRows[0].DataBoundItem as TipoPoliza;
                    frm = new frmCoberturasAgregadas(tipoPoliza.Id);
                    frm.ShowDialog();
                }
                else
                {
                    MessageBox.Show("Seleccione el registro !", "Atención", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Facturacion.frmFacturacion._MyLogControlEventos, Capa.UI.Facturacion.frmFacturacion.dgvDatosTipoPlan, and Entities.TipoPoliza.Id.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
CargarDatos()
void Capa.UI.Facturacion.frmFacturacion.CargarDatos () private
Este métodoc carga los datos que son llamados desde la base de datos y los coloca en sus respectivos combobox y datagrid views
Definition at line 37 of file frmFacturacion.cs.
        {
            ITipoPagoBLL logicaTipoPago = new TipoPagoBLL();
            ITarjetaBLL logicaTarjeta = new TarjetaBLL();
            ITipoPolizaBLL logicaTipoPlan = new TipoPolizaBLL();
            try
            {
                cmbTarjetas.DataSource = logicaTarjeta.ObtenerTarjeta();
                cmbTarjetas.DisplayMember = "Nombre";
                cmbTarjetas.ValueMember = "Id";
                cmbTarjetas.SelectedIndex = -1;
                cmbTipoPago.DataSource = logicaTipoPago.ObtenerTipoPago();
                cmbTipoPago.DisplayMember = "Descripcion";
                cmbTipoPago.ValueMember = "Id";
                cmbTipoPago.SelectedIndex = -1;
                dgvDatosTipoPlan.DataSource = logicaTipoPlan.ObtenerTipoPolizas();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Facturacion.frmFacturacion._MyLogControlEventos, Capa.UI.Facturacion.frmFacturacion.cmbTarjetas, Capa.UI.Facturacion.frmFacturacion.cmbTipoPago, Capa.UI.Facturacion.frmFacturacion.dgvDatosTipoPlan, Interfaces.ITarjetaBLL.ObtenerTarjeta(), Interfaces.ITipoPagoBLL.ObtenerTipoPago(), and Interfaces.ITipoPolizaBLL.ObtenerTipoPolizas().
Referenced by Capa.UI.Facturacion.frmFacturacion.frmFacturacion_Load().
cmbTipoPago_SelectionChangeCommitted()
void Capa.UI.Facturacion.frmFacturacion.cmbTipoPago_SelectionChangeCommitted (object sender, EventArgs e) private
Este método invoca al método calcula costo que trae el precio a pagar según el tipo de pago seleccionado
Parameters
sender
e
Definition at line 169 of file frmFacturacion.cs.
        {
            ITipoPagoBLL logicaTipoPago = new TipoPagoBLL();
            TipoPoliza tipoPoliza = null;
            try
            {
                if (this.dgvDatosTipoPlan.SelectedRows.Count > 0)
                {
                    if (cmbTipoPago.SelectedIndex == -1)
                    {
                        erpError.SetError(cmbTipoPago, "Debe seleccionar un tipo de pago");
                        return;
                    }
                    TipoPago tipoPago = logicaTipoPago.ObtenerPorId((int)cmbTipoPago.SelectedValue);
                    tipoPoliza = this.dgvDatosTipoPlan.SelectedRows[0].DataBoundItem as TipoPoliza;
                    _Factura.CalculaCosto(tipoPago.Porcentaje, tipoPoliza.Costo, tipoPago.Descripcion);
                    txtTotal.Text = _Factura.TotalDolares.ToString("N2");
                    txtTotalColones.Text = Utilitarios.ConsumoDolar(_Factura.TotalDolares).ToString("N2");
                }
                else
                {
                    MessageBox.Show("Seleccione el registro !", "Atención", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Facturacion.frmFacturacion._Factura, Capa.UI.Facturacion.frmFacturacion._MyLogControlEventos, capa.Entidades.Factura.CalculaCosto(), Capa.UI.Facturacion.frmFacturacion.cmbTipoPago, Capa.UI.Util.Utilitarios.ConsumoDolar(), Entities.TipoPoliza.Costo, Entities.TipoPago.Descripcion, Capa.UI.Facturacion.frmFacturacion.dgvDatosTipoPlan, Capa.UI.Facturacion.frmFacturacion.erpError, Interfaces.ITipoPagoBLL.ObtenerPorId(), Entities.TipoPago.Porcentaje, capa.Entidades.Factura.TotalDolares, Capa.UI.Facturacion.frmFacturacion.txtTotal, and Capa.UI.Facturacion.frmFacturacion.txtTotalColones.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
Dispose()
override void Capa.UI.Facturacion.frmFacturacion.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file frmFacturacion.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References Capa.UI.Facturacion.frmFacturacion.components.
frmFacturacion_Load()
void Capa.UI.Facturacion.frmFacturacion.frmFacturacion_Load (object sender, EventArgs e) private
Carga el culture info para Costa Rica y invoca al método que carga los datos
Parameters
sender
e
Definition at line 80 of file frmFacturacion.cs.
        {
            Utilitarios.CultureInfo();
            CargarDatos();
        }
References Capa.UI.Facturacion.frmFacturacion.CargarDatos(), and Capa.UI.Util.Utilitarios.CultureInfo().
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
InitializeComponent()
void Capa.UI.Facturacion.frmFacturacion.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file frmFacturacion.Designer.cs.
        {
            this.components = new System.ComponentModel.Container();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            this.tspBarraSuperior = new System.Windows.Forms.ToolStrip();
            this.toolStripBtnNuevo = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnFacturar = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnSalir = new System.Windows.Forms.ToolStripButton();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.txtNumTarjeta = new System.Windows.Forms.TextBox();
            this.lblTarjeta = new System.Windows.Forms.Label();
            this.lblNumTarjeta = new System.Windows.Forms.Label();
            this.cmbTarjetas = new System.Windows.Forms.ComboBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.btnBuscar = new System.Windows.Forms.Button();
            this.txtNombre = new System.Windows.Forms.TextBox();
            this.lblNombre = new System.Windows.Forms.Label();
            this.lblId = new System.Windows.Forms.Label();
            this.txtId = new System.Windows.Forms.TextBox();
            this.dgvDatosTipoPlan = new System.Windows.Forms.DataGridView();
            this.Id = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.DescripcionTipoPlan = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.lblTipoPago = new System.Windows.Forms.Label();
            this.cmbTipoPago = new System.Windows.Forms.ComboBox();
            this.btnMostrarCoberturas = new System.Windows.Forms.Button();
            this.backgroundWorker1 = new System.ComponentModel.BackgroundWorker();
            this.lblTotalColones = new System.Windows.Forms.Label();
            this.txtTotalColones = new System.Windows.Forms.TextBox();
            this.lblTotal = new System.Windows.Forms.Label();
            this.txtTotal = new System.Windows.Forms.TextBox();
            this.erpError = new System.Windows.Forms.ErrorProvider(this.components);
            this.tspBarraSuperior.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDatosTipoPlan)).BeginInit();
            this.groupBox3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.erpError)).BeginInit();
            this.SuspendLayout();
            //
            // tspBarraSuperior
            //
            this.tspBarraSuperior.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.tspBarraSuperior.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripBtnNuevo,
            this.toolStripBtnFacturar,
            this.toolStripBtnSalir});
            this.tspBarraSuperior.Location = new System.Drawing.Point(0, 0);
            this.tspBarraSuperior.Name = "tspBarraSuperior";
            this.tspBarraSuperior.Size = new System.Drawing.Size(792, 25);
            this.tspBarraSuperior.TabIndex = 103;
            this.tspBarraSuperior.Text = "toolStrip1";
            //
            // toolStripBtnNuevo
            //
            this.toolStripBtnNuevo.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnNuevo.ForeColor = System.Drawing.Color.White;
            this.toolStripBtnNuevo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnNuevo.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnNuevo.Name = "toolStripBtnNuevo";
            this.toolStripBtnNuevo.Size = new System.Drawing.Size(52, 22);
            this.toolStripBtnNuevo.Text = "Nuevo";
            this.toolStripBtnNuevo.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnNuevo.Click += new System.EventHandler(this.toolStripBtnNuevo_Click);
            //
            // toolStripBtnFacturar
            //
            this.toolStripBtnFacturar.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnFacturar.ForeColor = System.Drawing.Color.White;
            this.toolStripBtnFacturar.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnFacturar.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnFacturar.Name = "toolStripBtnFacturar";
            this.toolStripBtnFacturar.Size = new System.Drawing.Size(62, 22);
            this.toolStripBtnFacturar.Text = "Facturar";
            this.toolStripBtnFacturar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnFacturar.Click += new System.EventHandler(this.toolStripBtnFacturar_Click);
            //
            // toolStripBtnSalir
            //
            this.toolStripBtnSalir.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.toolStripBtnSalir.ForeColor = System.Drawing.Color.White;
            this.toolStripBtnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnSalir.Name = "toolStripBtnSalir";
            this.toolStripBtnSalir.Size = new System.Drawing.Size(39, 22);
            this.toolStripBtnSalir.Text = "Salir";
            this.toolStripBtnSalir.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.toolStripBtnSalir.Click += new System.EventHandler(this.toolStripBtnSalir_Click);
            //
            // groupBox1
            //
            this.groupBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.groupBox1.Controls.Add(this.txtNumTarjeta);
            this.groupBox1.Controls.Add(this.lblTarjeta);
            this.groupBox1.Controls.Add(this.lblNumTarjeta);
            this.groupBox1.Controls.Add(this.cmbTarjetas);
            this.groupBox1.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox1.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.groupBox1.Location = new System.Drawing.Point(33, 38);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(200, 229);
            this.groupBox1.TabIndex = 104;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Facturación";
            //
            // txtNumTarjeta
            //
            this.txtNumTarjeta.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(138)))), ((int)(((byte)(181)))));
            this.txtNumTarjeta.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtNumTarjeta.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNumTarjeta.ForeColor = System.Drawing.Color.White;
            this.txtNumTarjeta.Location = new System.Drawing.Point(15, 118);
            this.txtNumTarjeta.Name = "txtNumTarjeta";
            this.txtNumTarjeta.Size = new System.Drawing.Size(167, 27);
            this.txtNumTarjeta.TabIndex = 75;
            //
            // lblTarjeta
            //
            this.lblTarjeta.AutoSize = true;
            this.lblTarjeta.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTarjeta.ForeColor = System.Drawing.Color.White;
            this.lblTarjeta.Location = new System.Drawing.Point(12, 32);
            this.lblTarjeta.Name = "lblTarjeta";
            this.lblTarjeta.Size = new System.Drawing.Size(52, 16);
            this.lblTarjeta.TabIndex = 74;
            this.lblTarjeta.Text = "Tarjeta";
            this.lblTarjeta.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            //
            // lblNumTarjeta
            //
            this.lblNumTarjeta.AutoSize = true;
            this.lblNumTarjeta.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblNumTarjeta.ForeColor = System.Drawing.Color.White;
            this.lblNumTarjeta.Location = new System.Drawing.Point(15, 99);
            this.lblNumTarjeta.Name = "lblNumTarjeta";
            this.lblNumTarjeta.Size = new System.Drawing.Size(128, 16);
            this.lblNumTarjeta.TabIndex = 76;
            this.lblNumTarjeta.Text = "Número de Tarjeta";
            this.lblNumTarjeta.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            //
            // cmbTarjetas
            //
            this.cmbTarjetas.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(138)))), ((int)(((byte)(181)))));
            this.cmbTarjetas.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbTarjetas.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbTarjetas.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbTarjetas.ForeColor = System.Drawing.Color.White;
            this.cmbTarjetas.FormattingEnabled = true;
            this.cmbTarjetas.Location = new System.Drawing.Point(15, 51);
            this.cmbTarjetas.Name = "cmbTarjetas";
            this.cmbTarjetas.Size = new System.Drawing.Size(164, 29);
            this.cmbTarjetas.TabIndex = 77;
            //
            // groupBox2
            //
            this.groupBox2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.groupBox2.Controls.Add(this.btnBuscar);
            this.groupBox2.Controls.Add(this.txtNombre);
            this.groupBox2.Controls.Add(this.lblNombre);
            this.groupBox2.Controls.Add(this.lblId);
            this.groupBox2.Controls.Add(this.txtId);
            this.groupBox2.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox2.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.groupBox2.Location = new System.Drawing.Point(284, 38);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(200, 229);
            this.groupBox2.TabIndex = 105;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Cliente";
            //
            // btnBuscar
            //
            this.btnBuscar.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.btnBuscar.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnBuscar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnBuscar.Font = new System.Drawing.Font("Century Gothic", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnBuscar.ForeColor = System.Drawing.Color.White;
            this.btnBuscar.Location = new System.Drawing.Point(52, 167);
            this.btnBuscar.Name = "btnBuscar";
            this.btnBuscar.Size = new System.Drawing.Size(87, 38);
            this.btnBuscar.TabIndex = 127;
            this.btnBuscar.Text = "Buscar";
            this.btnBuscar.UseVisualStyleBackColor = false;
            this.btnBuscar.Click += new System.EventHandler(this.btnBuscar_Click);
            //
            // txtNombre
            //
            this.txtNombre.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(138)))), ((int)(((byte)(181)))));
            this.txtNombre.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtNombre.Enabled = false;
            this.txtNombre.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNombre.ForeColor = System.Drawing.Color.White;
            this.txtNombre.Location = new System.Drawing.Point(13, 105);
            this.txtNombre.Name = "txtNombre";
            this.txtNombre.Size = new System.Drawing.Size(166, 27);
            this.txtNombre.TabIndex = 119;
            //
            // lblNombre
            //
            this.lblNombre.AutoSize = true;
            this.lblNombre.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblNombre.ForeColor = System.Drawing.Color.White;
            this.lblNombre.Location = new System.Drawing.Point(6, 86);
            this.lblNombre.Name = "lblNombre";
            this.lblNombre.Size = new System.Drawing.Size(59, 16);
            this.lblNombre.TabIndex = 118;
            this.lblNombre.Text = "Nombre";
            this.lblNombre.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            //
            // lblId
            //
            this.lblId.AutoSize = true;
            this.lblId.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblId.ForeColor = System.Drawing.Color.White;
            this.lblId.Location = new System.Drawing.Point(7, 19);
            this.lblId.Name = "lblId";
            this.lblId.Size = new System.Drawing.Size(20, 16);
            this.lblId.TabIndex = 116;
            this.lblId.Text = "Id";
            this.lblId.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            //
            // txtId
            //
            this.txtId.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(138)))), ((int)(((byte)(181)))));
            this.txtId.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtId.Enabled = false;
            this.txtId.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtId.ForeColor = System.Drawing.Color.White;
            this.txtId.Location = new System.Drawing.Point(15, 47);
            this.txtId.Name = "txtId";
            this.txtId.Size = new System.Drawing.Size(164, 27);
            this.txtId.TabIndex = 117;
            //
            // dgvDatosTipoPlan
            //
            this.dgvDatosTipoPlan.AllowUserToAddRows = false;
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle1.BackColor = System.Drawing.SystemColors.ActiveBorder;
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvDatosTipoPlan.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvDatosTipoPlan.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvDatosTipoPlan.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Id,
            this.DescripcionTipoPlan});
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.Gray;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvDatosTipoPlan.DefaultCellStyle = dataGridViewCellStyle2;
            this.dgvDatosTipoPlan.Location = new System.Drawing.Point(18, 38);
            this.dgvDatosTipoPlan.Name = "dgvDatosTipoPlan";
            this.dgvDatosTipoPlan.ReadOnly = true;
            this.dgvDatosTipoPlan.Size = new System.Drawing.Size(254, 141);
            this.dgvDatosTipoPlan.TabIndex = 156;
            //
            // Id
            //
            this.Id.DataPropertyName = "Id";
            this.Id.HeaderText = "Id";
            this.Id.Name = "Id";
            this.Id.ReadOnly = true;
            //
            // DescripcionTipoPlan
            //
            this.DescripcionTipoPlan.DataPropertyName = "Descripcion";
            this.DescripcionTipoPlan.HeaderText = "DescripcionTipoPlan";
            this.DescripcionTipoPlan.Name = "DescripcionTipoPlan";
            this.DescripcionTipoPlan.ReadOnly = true;
            //
            // groupBox3
            //
            this.groupBox3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.groupBox3.Controls.Add(this.lblTipoPago);
            this.groupBox3.Controls.Add(this.cmbTipoPago);
            this.groupBox3.Controls.Add(this.btnMostrarCoberturas);
            this.groupBox3.Controls.Add(this.dgvDatosTipoPlan);
            this.groupBox3.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox3.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.groupBox3.Location = new System.Drawing.Point(33, 306);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(451, 209);
            this.groupBox3.TabIndex = 105;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Tipos de planes";
            //
            // lblTipoPago
            //
            this.lblTipoPago.AutoSize = true;
            this.lblTipoPago.Font = new System.Drawing.Font("Century Gothic", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTipoPago.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.lblTipoPago.Location = new System.Drawing.Point(281, 132);
            this.lblTipoPago.Name = "lblTipoPago";
            this.lblTipoPago.Size = new System.Drawing.Size(77, 15);
            this.lblTipoPago.TabIndex = 159;
            this.lblTipoPago.Text = "Tipo de Pago";
            this.lblTipoPago.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            //
            // cmbTipoPago
            //
            this.cmbTipoPago.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(138)))), ((int)(((byte)(181)))));
            this.cmbTipoPago.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbTipoPago.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbTipoPago.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbTipoPago.ForeColor = System.Drawing.Color.White;
            this.cmbTipoPago.FormattingEnabled = true;
            this.cmbTipoPago.Location = new System.Drawing.Point(284, 150);
            this.cmbTipoPago.Name = "cmbTipoPago";
            this.cmbTipoPago.Size = new System.Drawing.Size(146, 29);
            this.cmbTipoPago.TabIndex = 158;
            this.cmbTipoPago.SelectionChangeCommitted += new System.EventHandler(this.cmbTipoPago_SelectionChangeCommitted);
            //
            // btnMostrarCoberturas
            //
            this.btnMostrarCoberturas.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.btnMostrarCoberturas.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnMostrarCoberturas.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnMostrarCoberturas.Font = new System.Drawing.Font("Century Gothic", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnMostrarCoberturas.ForeColor = System.Drawing.Color.White;
            this.btnMostrarCoberturas.Location = new System.Drawing.Point(284, 38);
            this.btnMostrarCoberturas.Name = "btnMostrarCoberturas";
            this.btnMostrarCoberturas.Size = new System.Drawing.Size(146, 36);
            this.btnMostrarCoberturas.TabIndex = 128;
            this.btnMostrarCoberturas.Text = "Desglose de Coberturas";
            this.btnMostrarCoberturas.UseVisualStyleBackColor = false;
            this.btnMostrarCoberturas.Click += new System.EventHandler(this.btnMostrarCoberturas_Click);
            //
            // lblTotalColones
            //
            this.lblTotalColones.AutoSize = true;
            this.lblTotalColones.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTotalColones.ForeColor = System.Drawing.Color.White;
            this.lblTotalColones.Location = new System.Drawing.Point(555, 283);
            this.lblTotalColones.Name = "lblTotalColones";
            this.lblTotalColones.Size = new System.Drawing.Size(114, 16);
            this.lblTotalColones.TabIndex = 161;
            this.lblTotalColones.Text = "Total en Colones";
            this.lblTotalColones.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            //
            // txtTotalColones
            //
            this.txtTotalColones.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(138)))), ((int)(((byte)(181)))));
            this.txtTotalColones.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtTotalColones.Enabled = false;
            this.txtTotalColones.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTotalColones.ForeColor = System.Drawing.Color.White;
            this.txtTotalColones.Location = new System.Drawing.Point(558, 306);
            this.txtTotalColones.Name = "txtTotalColones";
            this.txtTotalColones.Size = new System.Drawing.Size(167, 27);
            this.txtTotalColones.TabIndex = 160;
            //
            // lblTotal
            //
            this.lblTotal.AutoSize = true;
            this.lblTotal.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTotal.ForeColor = System.Drawing.Color.White;
            this.lblTotal.Location = new System.Drawing.Point(555, 224);
            this.lblTotal.Name = "lblTotal";
            this.lblTotal.Size = new System.Drawing.Size(38, 16);
            this.lblTotal.TabIndex = 159;
            this.lblTotal.Text = "Total";
            this.lblTotal.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            //
            // txtTotal
            //
            this.txtTotal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(138)))), ((int)(((byte)(181)))));
            this.txtTotal.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtTotal.Enabled = false;
            this.txtTotal.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTotal.ForeColor = System.Drawing.Color.White;
            this.txtTotal.Location = new System.Drawing.Point(558, 247);
            this.txtTotal.Name = "txtTotal";
            this.txtTotal.Size = new System.Drawing.Size(167, 27);
            this.txtTotal.TabIndex = 158;
            //
            // erpError
            //
            this.erpError.ContainerControl = this;
            //
            // frmFacturacion
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(165)))), ((int)(((byte)(209)))));
            this.ClientSize = new System.Drawing.Size(792, 541);
            this.Controls.Add(this.lblTotalColones);
            this.Controls.Add(this.txtTotalColones);
            this.Controls.Add(this.lblTotal);
            this.Controls.Add(this.txtTotal);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.tspBarraSuperior);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmFacturacion";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmFacturacion";
            this.Load += new System.EventHandler(this.frmFacturacion_Load);
            this.tspBarraSuperior.ResumeLayout(false);
            this.tspBarraSuperior.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDatosTipoPlan)).EndInit();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.erpError)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References Capa.UI.Facturacion.frmFacturacion.backgroundWorker1, Capa.UI.Facturacion.frmFacturacion.btnBuscar, Capa.UI.Facturacion.frmFacturacion.btnBuscar_Click(), Capa.UI.Facturacion.frmFacturacion.btnMostrarCoberturas, Capa.UI.Facturacion.frmFacturacion.btnMostrarCoberturas_Click(), Capa.UI.Facturacion.frmFacturacion.cmbTarjetas, Capa.UI.Facturacion.frmFacturacion.cmbTipoPago, Capa.UI.Facturacion.frmFacturacion.cmbTipoPago_SelectionChangeCommitted(), Capa.UI.Facturacion.frmFacturacion.components, Capa.UI.Facturacion.frmFacturacion.DescripcionTipoPlan, Capa.UI.Facturacion.frmFacturacion.dgvDatosTipoPlan, Capa.UI.Facturacion.frmFacturacion.erpError, Capa.UI.Facturacion.frmFacturacion.frmFacturacion_Load(), Capa.UI.Facturacion.frmFacturacion.groupBox1, Capa.UI.Facturacion.frmFacturacion.groupBox2, Capa.UI.Facturacion.frmFacturacion.groupBox3, Capa.UI.Facturacion.frmFacturacion.Id, Capa.UI.Facturacion.frmFacturacion.lblId, Capa.UI.Facturacion.frmFacturacion.lblNombre, Capa.UI.Facturacion.frmFacturacion.lblNumTarjeta, Capa.UI.Facturacion.frmFacturacion.lblTarjeta, Capa.UI.Facturacion.frmFacturacion.lblTipoPago, Capa.UI.Facturacion.frmFacturacion.lblTotal, Capa.UI.Facturacion.frmFacturacion.lblTotalColones, Capa.UI.Facturacion.frmFacturacion.toolStripBtnFacturar, Capa.UI.Facturacion.frmFacturacion.toolStripBtnFacturar_Click(), Capa.UI.Facturacion.frmFacturacion.toolStripBtnNuevo, Capa.UI.Facturacion.frmFacturacion.toolStripBtnNuevo_Click(), Capa.UI.Facturacion.frmFacturacion.toolStripBtnSalir, Capa.UI.Facturacion.frmFacturacion.toolStripBtnSalir_Click(), Capa.UI.Facturacion.frmFacturacion.tspBarraSuperior, Capa.UI.Facturacion.frmFacturacion.txtId, Capa.UI.Facturacion.frmFacturacion.txtNombre, Capa.UI.Facturacion.frmFacturacion.txtNumTarjeta, Capa.UI.Facturacion.frmFacturacion.txtTotal, and Capa.UI.Facturacion.frmFacturacion.txtTotalColones.
Referenced by Capa.UI.Facturacion.frmFacturacion.frmFacturacion().
toolStripBtnFacturar_Click()
void Capa.UI.Facturacion.frmFacturacion.toolStripBtnFacturar_Click (object sender, EventArgs e) private
Este método termina de llenar la factura con los datos para poder ser enviado a la capa lógica y de ahí ser enviado a la base de datos por medio de la DAL
Parameters
sender
e
Definition at line 239 of file frmFacturacion.cs.
        {
            IPolizaBLL logicaPoliza = new PolizaBLL();
            IFacturaBLL logicaFactura = new FacturaBLL();
            //IFacturaBLL logica = new FacturaLN();
            string rutaImagen = @"c:\temp\qr.png";
            int numeroFactura = 0;
            try
            {
                if (_Factura == null)
                {
                    MessageBox.Show("No hay datos por facturar", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    return;
                }
                _Factura.FechaFacturacion = DateTime.Now;
                _Factura._Poliza = new Poliza();
                _Factura._Poliza.Id = logicaPoliza.GetNextNumeroPoliza();
                _Factura._Poliza.Descripcion = "Poliza";
                _Factura._Poliza.IdTipoPoliza = (int)this.dgvDatosTipoPlan.SelectedRows[0].Cells[0].Value;
                _Factura._Poliza.FechaVencimiento = new DateTime((DateTime.Now.Year + 1), DateTime.Now.Month, DateTime.Now.Day);
                _Factura._Poliza.IdUsuario =int.Parse(txtId.Text);
                _Factura._Poliza.IdFactura = _Factura._Poliza.Id;
                _Factura.IdPoliza = _Factura._Poliza.Id;
                _Factura.IdFactura = _Factura._Poliza.IdFactura;
                _Factura.IdTipoPago = (int)cmbTipoPago.SelectedValue;
                _Factura.TotalColones = decimal.Parse(txtTotalColones.Text);
                logicaFactura.Insertar(_Factura);
                numeroFactura = _Factura.IdFactura;
                if (_Factura == null)
                    MessageBox.Show("Error al crear factura!", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                else
                    toolStripBtnNuevo_Click(null, null);
                //Si existe borrelo
                if (File.Exists(rutaImagen))
                    File.Delete(rutaImagen);
                // Crear imagen quickresponse
                Image quickResponseImage = QuickResponse.QuickResponseGenerador(numeroFactura.ToString(), 53);
                // Salvarla en c:\temp para luego ser leida
                quickResponseImage.Save(rutaImagen, ImageFormat.Png);
                frmRptFactura ofrmReporteFactura = new frmRptFactura(numeroFactura);
                ofrmReporteFactura.ShowDialog();
                _Factura = new Factura();
            }
            catch (Exception er)
            {
                MessageBox.Show("Se ha producido el siguiente error: " + er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error(er.Message);
            }
        }
References Capa.UI.Facturacion.frmFacturacion._Factura, Capa.UI.Facturacion.frmFacturacion._MyLogControlEventos, capa.Entidades.Factura._Poliza, Capa.UI.Facturacion.frmFacturacion.cmbTipoPago, Entities.Poliza.Descripcion, Capa.UI.Facturacion.frmFacturacion.dgvDatosTipoPlan, capa.Entidades.Factura.FechaFacturacion, Entities.Poliza.FechaVencimiento, Interfaces.IPolizaBLL.GetNextNumeroPoliza(), Entities.Poliza.Id, capa.Entidades.Factura.IdFactura, Entities.Poliza.IdFactura, capa.Entidades.Factura.IdPoliza, capa.Entidades.Factura.IdTipoPago, Entities.Poliza.IdTipoPoliza, Entities.Poliza.IdUsuario, Interfaces.IFacturaBLL.Insertar(), QuickResponse.QuickResponseGenerador(), Capa.UI.Facturacion.frmFacturacion.toolStripBtnNuevo_Click(), capa.Entidades.Factura.TotalColones, Capa.UI.Facturacion.frmFacturacion.txtId, and Capa.UI.Facturacion.frmFacturacion.txtTotalColones.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
toolStripBtnNuevo_Click()
void Capa.UI.Facturacion.frmFacturacion.toolStripBtnNuevo_Click (object sender, EventArgs e) private
Este ,método limpia todos los campos del frame para poder facturar nuevamente
Parameters
sender
e
Definition at line 213 of file frmFacturacion.cs.
        {
            try
            {
                txtNumTarjeta.Clear();
                cmbTarjetas.SelectedIndex = -1;
                txtId.Clear();
                txtNombre.Clear();
                txtTotal.Clear();
                txtTotalColones.Clear();
                _Factura = new Factura();
                cmbTipoPago.SelectedIndex = 0;
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                _MyLogControlEventos.Error(ex.Message);
            }
        }
References Capa.UI.Facturacion.frmFacturacion._Factura, Capa.UI.Facturacion.frmFacturacion._MyLogControlEventos, Capa.UI.Facturacion.frmFacturacion.cmbTarjetas, Capa.UI.Facturacion.frmFacturacion.cmbTipoPago, Capa.UI.Facturacion.frmFacturacion.txtId, Capa.UI.Facturacion.frmFacturacion.txtNombre, Capa.UI.Facturacion.frmFacturacion.txtNumTarjeta, Capa.UI.Facturacion.frmFacturacion.txtTotal, and Capa.UI.Facturacion.frmFacturacion.txtTotalColones.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent(), and Capa.UI.Facturacion.frmFacturacion.toolStripBtnFacturar_Click().
toolStripBtnSalir_Click()
void Capa.UI.Facturacion.frmFacturacion.toolStripBtnSalir_Click (object sender, EventArgs e) private
Cierra el form
Parameters
sender
e
Definition at line 71 of file frmFacturacion.cs.
        {
            this.Close();
        }
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
Member Data Documentation
_Factura
Factura Capa.UI.Facturacion.frmFacturacion._Factura = new Factura() private
Definition at line 27 of file frmFacturacion.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.btnBuscar_Click(), Capa.UI.Facturacion.frmFacturacion.cmbTipoPago_SelectionChangeCommitted(), Capa.UI.Facturacion.frmFacturacion.toolStripBtnFacturar_Click(), and Capa.UI.Facturacion.frmFacturacion.toolStripBtnNuevo_Click().
_MyLogControlEventos
readonly ILog Capa.UI.Facturacion.frmFacturacion._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 26 of file frmFacturacion.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.btnBuscar_Click(), Capa.UI.Facturacion.frmFacturacion.btnMostrarCoberturas_Click(), Capa.UI.Facturacion.frmFacturacion.CargarDatos(), Capa.UI.Facturacion.frmFacturacion.cmbTipoPago_SelectionChangeCommitted(), Capa.UI.Facturacion.frmFacturacion.toolStripBtnFacturar_Click(), and Capa.UI.Facturacion.frmFacturacion.toolStripBtnNuevo_Click().
backgroundWorker1
System.ComponentModel.BackgroundWorker Capa.UI.Facturacion.frmFacturacion.backgroundWorker1 private
Definition at line 471 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
btnBuscar
System.Windows.Forms.Button Capa.UI.Facturacion.frmFacturacion.btnBuscar private
Definition at line 461 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
btnMostrarCoberturas
System.Windows.Forms.Button Capa.UI.Facturacion.frmFacturacion.btnMostrarCoberturas private
Definition at line 470 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
cmbTarjetas
System.Windows.Forms.ComboBox Capa.UI.Facturacion.frmFacturacion.cmbTarjetas private
Definition at line 459 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.btnBuscar_Click(), Capa.UI.Facturacion.frmFacturacion.CargarDatos(), Capa.UI.Facturacion.frmFacturacion.InitializeComponent(), and Capa.UI.Facturacion.frmFacturacion.toolStripBtnNuevo_Click().
cmbTipoPago
System.Windows.Forms.ComboBox Capa.UI.Facturacion.frmFacturacion.cmbTipoPago private
Definition at line 472 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.CargarDatos(), Capa.UI.Facturacion.frmFacturacion.cmbTipoPago_SelectionChangeCommitted(), Capa.UI.Facturacion.frmFacturacion.InitializeComponent(), Capa.UI.Facturacion.frmFacturacion.toolStripBtnFacturar_Click(), and Capa.UI.Facturacion.frmFacturacion.toolStripBtnNuevo_Click().
components
System.ComponentModel.IContainer Capa.UI.Facturacion.frmFacturacion.components = null private
Required designer variable.
Definition at line 8 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.Dispose(), and Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
DescripcionTipoPlan
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Facturacion.frmFacturacion.DescripcionTipoPlan private
Definition at line 468 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
dgvDatosTipoPlan
System.Windows.Forms.DataGridView Capa.UI.Facturacion.frmFacturacion.dgvDatosTipoPlan private
Definition at line 466 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.btnMostrarCoberturas_Click(), Capa.UI.Facturacion.frmFacturacion.CargarDatos(), Capa.UI.Facturacion.frmFacturacion.cmbTipoPago_SelectionChangeCommitted(), Capa.UI.Facturacion.frmFacturacion.InitializeComponent(), and Capa.UI.Facturacion.frmFacturacion.toolStripBtnFacturar_Click().
erpError
System.Windows.Forms.ErrorProvider Capa.UI.Facturacion.frmFacturacion.erpError private
Definition at line 477 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.btnBuscar_Click(), Capa.UI.Facturacion.frmFacturacion.cmbTipoPago_SelectionChangeCommitted(), and Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
groupBox1
System.Windows.Forms.GroupBox Capa.UI.Facturacion.frmFacturacion.groupBox1 private
Definition at line 455 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
groupBox2
System.Windows.Forms.GroupBox Capa.UI.Facturacion.frmFacturacion.groupBox2 private
Definition at line 460 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
groupBox3
System.Windows.Forms.GroupBox Capa.UI.Facturacion.frmFacturacion.groupBox3 private
Definition at line 469 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
Id
System.Windows.Forms.DataGridViewTextBoxColumn Capa.UI.Facturacion.frmFacturacion.Id private
Definition at line 467 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
lblId
System.Windows.Forms.Label Capa.UI.Facturacion.frmFacturacion.lblId private
Definition at line 464 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
lblNombre
System.Windows.Forms.Label Capa.UI.Facturacion.frmFacturacion.lblNombre private
Definition at line 463 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
lblNumTarjeta
System.Windows.Forms.Label Capa.UI.Facturacion.frmFacturacion.lblNumTarjeta private
Definition at line 458 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
lblTarjeta
System.Windows.Forms.Label Capa.UI.Facturacion.frmFacturacion.lblTarjeta private
Definition at line 457 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
lblTipoPago
System.Windows.Forms.Label Capa.UI.Facturacion.frmFacturacion.lblTipoPago private
Definition at line 478 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
lblTotal
System.Windows.Forms.Label Capa.UI.Facturacion.frmFacturacion.lblTotal private
Definition at line 475 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
lblTotalColones
System.Windows.Forms.Label Capa.UI.Facturacion.frmFacturacion.lblTotalColones private
Definition at line 473 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
toolStripBtnFacturar
System.Windows.Forms.ToolStripButton Capa.UI.Facturacion.frmFacturacion.toolStripBtnFacturar private
Definition at line 453 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
toolStripBtnNuevo
System.Windows.Forms.ToolStripButton Capa.UI.Facturacion.frmFacturacion.toolStripBtnNuevo private
Definition at line 452 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
toolStripBtnSalir
System.Windows.Forms.ToolStripButton Capa.UI.Facturacion.frmFacturacion.toolStripBtnSalir private
Definition at line 454 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
tspBarraSuperior
System.Windows.Forms.ToolStrip Capa.UI.Facturacion.frmFacturacion.tspBarraSuperior private
Definition at line 451 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.InitializeComponent().
txtId
System.Windows.Forms.TextBox Capa.UI.Facturacion.frmFacturacion.txtId private
Definition at line 465 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.btnBuscar_Click(), Capa.UI.Facturacion.frmFacturacion.InitializeComponent(), Capa.UI.Facturacion.frmFacturacion.toolStripBtnFacturar_Click(), and Capa.UI.Facturacion.frmFacturacion.toolStripBtnNuevo_Click().
txtNombre
System.Windows.Forms.TextBox Capa.UI.Facturacion.frmFacturacion.txtNombre private
Definition at line 462 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.btnBuscar_Click(), Capa.UI.Facturacion.frmFacturacion.InitializeComponent(), and Capa.UI.Facturacion.frmFacturacion.toolStripBtnNuevo_Click().
txtNumTarjeta
System.Windows.Forms.TextBox Capa.UI.Facturacion.frmFacturacion.txtNumTarjeta private
Definition at line 456 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.btnBuscar_Click(), Capa.UI.Facturacion.frmFacturacion.InitializeComponent(), and Capa.UI.Facturacion.frmFacturacion.toolStripBtnNuevo_Click().
txtTotal
System.Windows.Forms.TextBox Capa.UI.Facturacion.frmFacturacion.txtTotal private
Definition at line 476 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.cmbTipoPago_SelectionChangeCommitted(), Capa.UI.Facturacion.frmFacturacion.InitializeComponent(), and Capa.UI.Facturacion.frmFacturacion.toolStripBtnNuevo_Click().
txtTotalColones
System.Windows.Forms.TextBox Capa.UI.Facturacion.frmFacturacion.txtTotalColones private
Definition at line 474 of file frmFacturacion.Designer.cs.
Referenced by Capa.UI.Facturacion.frmFacturacion.cmbTipoPago_SelectionChangeCommitted(), Capa.UI.Facturacion.frmFacturacion.InitializeComponent(), Capa.UI.Facturacion.frmFacturacion.toolStripBtnFacturar_Click(), and Capa.UI.Facturacion.frmFacturacion.toolStripBtnNuevo_Click().
valorDolar
double Capa.UI.Facturacion.frmFacturacion.valorDolar = 0 private
Definition at line 28 of file frmFacturacion.cs.
The documentation for this class was generated from the following files:
Capa.UI/Facturacion/frmFacturacion.cs
Capa.UI/Facturacion/frmFacturacion.Designer.cs