Proyecto Autos Seguros: Interfaces.IFacturaBLL Interface Reference
Interfaces.IFacturaBLL Interface Reference
Public Member Functions
void Insertar (Factura encFactura)
void Eliminar (int idFactura)
List< Factura > SeleccionarTodas ()
Factura SeleccionarPorId (int idFactura)
List< Factura > SeleccionarFacturaHoy ()
void AnularFactura (int idFactura)
List< Factura > SeleccionarFacturasAnuladas ()
Detailed Description
Definition at line 10 of file IFacturaBLL.cs.
Member Function Documentation
AnularFactura()
void Interfaces.IFacturaBLL.AnularFactura (int idFactura)
Implemented in BLL.FacturaBLL.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.toolStripBtnEliminar_Click().
Eliminar()
void Interfaces.IFacturaBLL.Eliminar (int idFactura)
Implemented in BLL.FacturaBLL.
Insertar()
void Interfaces.IFacturaBLL.Insertar (Factura encFactura)
Implemented in BLL.FacturaBLL.
Referenced by Capa.UI.Facturacion.frmFacturacion.toolStripBtnFacturar_Click().
SeleccionarFacturaHoy()
List< Factura > Interfaces.IFacturaBLL.SeleccionarFacturaHoy ()
Implemented in BLL.FacturaBLL.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.CargarDatos().
SeleccionarFacturasAnuladas()
List< Factura > Interfaces.IFacturaBLL.SeleccionarFacturasAnuladas ()
Implemented in BLL.FacturaBLL.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoAnulaFac.CargarDatos().
SeleccionarPorId()
Factura Interfaces.IFacturaBLL.SeleccionarPorId (int idFactura)
Implemented in BLL.FacturaBLL.
SeleccionarTodas()
List< Factura > Interfaces.IFacturaBLL.SeleccionarTodas ()
Implemented in BLL.FacturaBLL.
The documentation for this interface was generated from the following file:
Interfaces/IFacturaBLL.cs