Proyecto Autos Seguros: Interfaces.I_IVA_DAL Interface Reference
Interfaces.I_IVA_DAL Interface Reference
Public Member Functions
void Actualizar (IVA iva)
void Eliminar (int id)
void Insertar (IVA iva)
List< IVA > SeleccionarTodas ()
IVA SeleccionarPorId (int id)
IVA SeleccionarReciente ()
Detailed Description
Definition at line 10 of file I_IVA_DAL.cs.
Member Function Documentation
Actualizar()
void Interfaces.I_IVA_DAL.Actualizar (IVA iva)
Implemented in DAL.IVADAL.
Referenced by BLL.IVABLL.Actualizar(), and BLL.IVABLL.Insertar().
Eliminar()
void Interfaces.I_IVA_DAL.Eliminar (int id)
Implemented in DAL.IVADAL.
Referenced by BLL.IVABLL.Eliminar().
Insertar()
void Interfaces.I_IVA_DAL.Insertar (IVA iva)
Implemented in DAL.IVADAL.
Referenced by BLL.IVABLL.Insertar().
SeleccionarPorId()
IVA Interfaces.I_IVA_DAL.SeleccionarPorId (int id)
Implemented in DAL.IVADAL.
Referenced by BLL.IVABLL.Insertar(), and BLL.IVABLL.SeleccionarPorId().
SeleccionarReciente()
IVA Interfaces.I_IVA_DAL.SeleccionarReciente ()
Implemented in DAL.IVADAL.
Referenced by BLL.IVABLL.SeleccionarReciente().
SeleccionarTodas()
List< IVA > Interfaces.I_IVA_DAL.SeleccionarTodas ()
Implemented in DAL.IVADAL.
Referenced by BLL.IVABLL.SeleccionarTodas().
The documentation for this interface was generated from the following file:
Interfaces/I_IVA_DAL.cs