Proyecto Autos Seguros: Interfaces.IPaisDAL Interface Reference
Interfaces.IPaisDAL Interface Reference
Public Member Functions
Pais ObtenerPorId (int id)
List< Pais > ObtenerPaises ()
Detailed Description
Definition at line 10 of file IPaisDAL.cs.
Member Function Documentation
ObtenerPaises()
List< Pais > Interfaces.IPaisDAL.ObtenerPaises ()
Implemented in DAL.PaisDAL.
Referenced by BLL.PaisBLL.ObtenerPaises().
ObtenerPorId()
Pais Interfaces.IPaisDAL.ObtenerPorId (int id)
Implemented in DAL.PaisDAL.
Referenced by DAL.UsuarioDAL.GetUsuarioByFiltro(), BLL.PaisBLL.ObtenerPorId(), DAL.UsuarioDAL.SeleccionarPorId(), and DAL.UsuarioDAL.SeleccionarTodas().
The documentation for this interface was generated from the following file:
Interfaces/IPaisDAL.cs