Proyecto Autos Seguros: Interfaces.IPolizaDAL Interface Reference
Interfaces.IPolizaDAL Interface Reference
Public Member Functions
void Insertar (Poliza poliza)
void Actualizar (Poliza poliza)
void Eliminar (int id)
List< Poliza > SeleccionarTodas ()
Poliza SeleccionarPorId (int id)
int GetNextNumeroPoliza ()
int GetCurrentNumeroPoliza ()
Detailed Description
Definition at line 10 of file IPolizaDAL.cs.
Member Function Documentation
Actualizar()
void Interfaces.IPolizaDAL.Actualizar (Poliza poliza)
Implemented in DAL.PolizaDAL.
Referenced by BLL.PolizaBLL.Actualizar(), and BLL.PolizaBLL.Insertar().
Eliminar()
void Interfaces.IPolizaDAL.Eliminar (int id)
Implemented in DAL.PolizaDAL.
Referenced by BLL.PolizaBLL.Eliminar().
GetCurrentNumeroPoliza()
int Interfaces.IPolizaDAL.GetCurrentNumeroPoliza ()
Implemented in DAL.PolizaDAL.
Referenced by BLL.PolizaBLL.GetCurrentNumeroPoliza().
GetNextNumeroPoliza()
int Interfaces.IPolizaDAL.GetNextNumeroPoliza ()
Implemented in DAL.PolizaDAL.
Referenced by BLL.PolizaBLL.GetNextNumeroPoliza().
Insertar()
void Interfaces.IPolizaDAL.Insertar (Poliza poliza)
Implemented in DAL.PolizaDAL.
Referenced by BLL.PolizaBLL.Insertar().
SeleccionarPorId()
Poliza Interfaces.IPolizaDAL.SeleccionarPorId (int id)
Implemented in DAL.PolizaDAL.
Referenced by BLL.PolizaBLL.Insertar(), and BLL.PolizaBLL.SeleccionarPorId().
SeleccionarTodas()
List< Poliza > Interfaces.IPolizaDAL.SeleccionarTodas ()
Implemented in DAL.PolizaDAL.
Referenced by BLL.PolizaBLL.SeleccionarTodas().
The documentation for this interface was generated from the following file:
Interfaces/IPolizaDAL.cs