Proyecto Autos Seguros: Interfaces.ITipoPolizaBLL Interface Reference
Interfaces.ITipoPolizaBLL Interface Reference
Public Member Functions
void Insertar (TipoPoliza tipoPoliza)
void Eliminar (int id)
List< TipoPoliza > ObtenerTipoPolizas ()
TipoPoliza ObtenerPorId (int id)
Detailed Description
Definition at line 10 of file ITipoPolizaBLL.cs.
Member Function Documentation
Eliminar()
void Interfaces.ITipoPolizaBLL.Eliminar (int id)
Implemented in BLL.TipoPolizaBLL.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEliminar_Click().
Insertar()
void Interfaces.ITipoPolizaBLL.Insertar (TipoPoliza tipoPoliza)
Implemented in BLL.TipoPolizaBLL.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAceptar_Click().
ObtenerPorId()
TipoPoliza Interfaces.ITipoPolizaBLL.ObtenerPorId (int id)
Implemented in BLL.TipoPolizaBLL.
ObtenerTipoPolizas()
List< TipoPoliza > Interfaces.ITipoPolizaBLL.ObtenerTipoPolizas ()
Implemented in BLL.TipoPolizaBLL.
Referenced by Capa.UI.Facturacion.frmFacturacion.CargarDatos(), and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CargarDatos().
The documentation for this interface was generated from the following file:
Interfaces/ITipoPolizaBLL.cs