Proyecto Autos Seguros: Interfaces.IUsuarioBLL Interface Reference
Interfaces.IUsuarioBLL Interface Reference
Public Member Functions
void Guardar (Usuario user)
void Eliminar (string id)
List< Usuario > ObtenerUsuarios ()
bool VerificarAcceso (string correo, string clave)
Usuario GetUsuarioById (string id)
List< Usuario > GetUsuarioByFiltro (string filtro)
string ObtenerUsuarioIdByIdFac (int idFactura)
Detailed Description
Definition at line 10 of file IUsuarioBLL.cs.
Member Function Documentation
Eliminar()
void Interfaces.IUsuarioBLL.Eliminar (string id)
Implemented in BLL.UsuarioBLL.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoUsuarios.toolStripBtnEliminar_Click().
GetUsuarioByFiltro()
List< Usuario > Interfaces.IUsuarioBLL.GetUsuarioByFiltro (string filtro)
Implemented in BLL.UsuarioBLL.
Referenced by Capa.UI.Filtro.frmFiltroUsuario.toolStripBtnBuscar_Click().
GetUsuarioById()
Usuario Interfaces.IUsuarioBLL.GetUsuarioById (string id)
Implemented in BLL.UsuarioBLL.
Referenced by Capa.UI.Reporte.frmRptFactura.EnviarFacturaAsync(), and BLL.FacturaBLL.Insertar().
Guardar()
void Interfaces.IUsuarioBLL.Guardar (Usuario user)
Implemented in BLL.UsuarioBLL.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoUsuarios.btnAceptar_Click().
ObtenerUsuarioIdByIdFac()
string Interfaces.IUsuarioBLL.ObtenerUsuarioIdByIdFac (int idFactura)
Implemented in BLL.UsuarioBLL.
Referenced by Capa.UI.Reporte.frmRptFactura.EnviarFacturaAsync().
ObtenerUsuarios()
List< Usuario > Interfaces.IUsuarioBLL.ObtenerUsuarios ()
Implemented in BLL.UsuarioBLL.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoUsuarios.CargarCombos().
VerificarAcceso()
bool Interfaces.IUsuarioBLL.VerificarAcceso (string correo, string clave)
Implemented in BLL.UsuarioBLL.
Referenced by Capa.UI.Login.frmIniciarSesion.btnIngresar_Click().
The documentation for this interface was generated from the following file:
Interfaces/IUsuarioBLL.cs