Proyecto Autos Seguros: Interfaces.ICoberturaBLL Interface Reference
Interfaces.ICoberturaBLL Interface Reference
Public Member Functions
void Insertar (Cobertura cobertura)
void Actualizar (Cobertura cobertur)
void Eliminar (int id)
List< Cobertura > SeleccionarTodas ()
Cobertura SeleccionarPorId (int id)
List< Cobertura > CoberturasAgregadas (int idTipoPoliza)
Detailed Description
Definition at line 10 of file ICoberturaBLL.cs.
Member Function Documentation
Actualizar()
void Interfaces.ICoberturaBLL.Actualizar (Cobertura cobertur)
Implemented in BLL.CoberturaBLL.
CoberturasAgregadas()
List< Cobertura > Interfaces.ICoberturaBLL.CoberturasAgregadas (int idTipoPoliza)
Implemented in BLL.CoberturaBLL.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnEliminarCobAgregada_Click(), Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.dgvDatos_CellMouseClick(), Capa.UI.Filtro.frmCoberturasAgregadas.frmCoberturasAgregadas_Load(), and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.toolStripBtnEditar_Click().
Eliminar()
void Interfaces.ICoberturaBLL.Eliminar (int id)
Implemented in BLL.CoberturaBLL.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.toolStripBtnEliminar_Click().
Insertar()
void Interfaces.ICoberturaBLL.Insertar (Cobertura cobertura)
Implemented in BLL.CoberturaBLL.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.btnAceptar_Click().
SeleccionarPorId()
Cobertura Interfaces.ICoberturaBLL.SeleccionarPorId (int id)
Implemented in BLL.CoberturaBLL.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.btnAgregarCobertura_Click().
SeleccionarTodas()
List< Cobertura > Interfaces.ICoberturaBLL.SeleccionarTodas ()
Implemented in BLL.CoberturaBLL.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoCoberturas.CargarDatos(), and Capa.UI.Mantenimientos.frmMantenimientoTipoPoliza.CargarDatos().
The documentation for this interface was generated from the following file:
Interfaces/ICoberturaBLL.cs