Proyecto Autos Seguros: IDataBase Interface Reference
IDataBase Interface Reference
Public Member Functions
double ExecuteNonQuery (IDbCommand pCommand, IsolationLevel pIsolationLevel)
void ExecuteNonQuery (ref IDbCommand pCommand, IsolationLevel pIsolationLevel)
void ExecuteNonQuery (List< IDbCommand > pCommands, IsolationLevel pIsolationLevel)
int ExecuteNonQuery (IDbCommand pCommand)
IDataReader ExecuteReader (IDbCommand pSqlCommand)
DataSet ExecuteDataSet (IDbCommand pSqlCommand, string pTabla)
DataSet ExecuteDataSet (IDbCommand pCommand)
object ExecuteScalar (IDbCommand pSQLCommand)
Properties
IDbConnection _Conexion [get, set]
Detailed Description
Definition at line 5 of file IDataBase.cs.
Member Function Documentation
ExecuteDataSet() [1/2]
DataSet IDataBase.ExecuteDataSet (IDbCommand pCommand)
Implemented in DataBase.
ExecuteDataSet() [2/2]
DataSet IDataBase.ExecuteDataSet (IDbCommand pSqlCommand, string pTabla)
Referenced by DAL.CoberturaDAL.CoberturasAgregadas(), DAL.PolizaDAL.GetCurrentNumeroPoliza(), DAL.PolizaDAL.GetNextNumeroPoliza(), DAL.UsuarioDAL.GetUsuarioByFiltro(), DAL.GeneroDAL.ObtenerGenero(), DAL.TarjetaDAL.ObtenerTarjeta(), DAL.TipoPagoDAL.ObtenerTipoPago(), DAL.TipoPolizaDAL.ObtenerTipoPolizas(), DAL.FacturaDAL.SeleccionarFacturaHoy(), DAL.FacturaDAL.SeleccionarFacturasAnuladas(), DAL.FacturaDAL.SeleccionarPorId(), DAL.CoberturaDAL.SeleccionarTodas(), DAL.DetallePolizaDAL.SeleccionarTodas(), DAL.FacturaDAL.SeleccionarTodas(), DAL.IVADAL.SeleccionarTodas(), DAL.PolizaDAL.SeleccionarTodas(), and DAL.UsuarioDAL.SeleccionarTodas().
ExecuteNonQuery() [1/4]
int IDataBase.ExecuteNonQuery (IDbCommand pCommand)
Implemented in DataBase.
ExecuteNonQuery() [2/4]
double IDataBase.ExecuteNonQuery (IDbCommand pCommand, IsolationLevel pIsolationLevel)
Implemented in DataBase.
Referenced by DAL.CoberturaDAL.Actualizar(), DAL.DetallePolizaDAL.Actualizar(), DAL.IVADAL.Actualizar(), DAL.PolizaDAL.Actualizar(), DAL.TipoPolizaDAL.Actualizar(), DAL.UsuarioDAL.Actualizar(), DAL.FacturaDAL.AnularFactura(), DAL.CoberturaDAL.Eliminar(), DAL.IVADAL.Eliminar(), DAL.PolizaDAL.Eliminar(), DAL.TipoPolizaDAL.Eliminar(), DAL.FacturaDAL.Eliminar(), DAL.DetallePolizaDAL.Eliminar(), DAL.UsuarioDAL.Eliminar(), DAL.DetallePolizaDAL.EliminarByPolCob(), DAL.CoberturaDAL.Insertar(), DAL.DetallePolizaDAL.Insertar(), DAL.FacturaDAL.Insertar(), DAL.IVADAL.Insertar(), DAL.PolizaDAL.Insertar(), DAL.TipoPolizaDAL.Insertar(), and DAL.UsuarioDAL.Insertar().
ExecuteNonQuery() [3/4]
void IDataBase.ExecuteNonQuery (List< IDbCommand > pCommands, IsolationLevel pIsolationLevel)
Implemented in DataBase.
ExecuteNonQuery() [4/4]
void IDataBase.ExecuteNonQuery (ref IDbCommand pCommand, IsolationLevel pIsolationLevel)
Implemented in DataBase.
ExecuteReader()
IDataReader IDataBase.ExecuteReader (IDbCommand pSqlCommand)
Implemented in DataBase.
Referenced by DAL.PaisDAL.ObtenerPaises(), DAL.GeneroDAL.ObtenerPorId(), DAL.PaisDAL.ObtenerPorId(), DAL.TarjetaDAL.ObtenerPorId(), DAL.TipoPagoDAL.ObtenerPorId(), DAL.TipoPolizaDAL.ObtenerPorId(), DAL.TipoUsuarioDAL.ObtenerPorId(), DAL.TipoUsuarioDAL.ObtenerTiposUsuarios(), DAL.UsuarioDAL.ObtenerUsuarioIdByIdFac(), DAL.CoberturaDAL.SeleccionarPorId(), DAL.IVADAL.SeleccionarPorId(), DAL.PolizaDAL.SeleccionarPorId(), DAL.DetallePolizaDAL.SeleccionarPorId(), DAL.UsuarioDAL.SeleccionarPorId(), DAL.IVADAL.SeleccionarReciente(), and DAL.UsuarioDAL.VerificarLogin().
ExecuteScalar()
object IDataBase.ExecuteScalar (IDbCommand pSQLCommand)
Implemented in DataBase.
Property Documentation
_Conexion
IDbConnection IDataBase._Conexion get set
Implemented in DataBase.
Definition at line 7 of file IDataBase.cs.
{ get; set; }
Referenced by FactoryDatabase.CreateDataBase(), and FactoryDatabase.CreateDefaultDataBase().
The documentation for this interface was generated from the following file:
DAL/Persistencia/IDataBase.cs