Proyecto Autos Seguros: Interfaces.ITipoPolizaDAL Interface Reference
Interfaces.ITipoPolizaDAL Interface Reference
Public Member Functions
void Insertar (TipoPoliza tipoPoliza)
void Actualizar (TipoPoliza tipoPoliza)
void Eliminar (int id)
List< TipoPoliza > ObtenerTipoPolizas ()
TipoPoliza ObtenerPorId (int id)
Detailed Description
Definition at line 10 of file ITipoPolizaDAL.cs.
Member Function Documentation
Actualizar()
void Interfaces.ITipoPolizaDAL.Actualizar (TipoPoliza tipoPoliza)
Implemented in DAL.TipoPolizaDAL.
Referenced by BLL.TipoPolizaBLL.Insertar().
Eliminar()
void Interfaces.ITipoPolizaDAL.Eliminar (int id)
Implemented in DAL.TipoPolizaDAL.
Referenced by BLL.TipoPolizaBLL.Eliminar().
Insertar()
void Interfaces.ITipoPolizaDAL.Insertar (TipoPoliza tipoPoliza)
Implemented in DAL.TipoPolizaDAL.
Referenced by BLL.TipoPolizaBLL.Insertar().
ObtenerPorId()
TipoPoliza Interfaces.ITipoPolizaDAL.ObtenerPorId (int id)
Implemented in DAL.TipoPolizaDAL.
Referenced by BLL.TipoPolizaBLL.Insertar(), BLL.TipoPolizaBLL.ObtenerPorId(), and DAL.PolizaDAL.SeleccionarPorId().
ObtenerTipoPolizas()
List< TipoPoliza > Interfaces.ITipoPolizaDAL.ObtenerTipoPolizas ()
Implemented in DAL.TipoPolizaDAL.
Referenced by BLL.TipoPolizaBLL.ObtenerTipoPolizas().
The documentation for this interface was generated from the following file:
Interfaces/ITipoPolizaDAL.cs