Proyecto Autos Seguros: Interfaces.I_IVA_BLL Interface Reference
Interfaces.I_IVA_BLL Interface Reference
Public Member Functions
void Actualizar (IVA iva)
void Eliminar (int id)
void Insertar (IVA iva)
List< IVA > SeleccionarTodas ()
IVA SeleccionarPorId (int id)
IVA SeleccionarReciente ()
Detailed Description
Definition at line 10 of file I_IVA_BLL.cs.
Member Function Documentation
Actualizar()
void Interfaces.I_IVA_BLL.Actualizar (IVA iva)
Implemented in BLL.IVABLL.
Eliminar()
void Interfaces.I_IVA_BLL.Eliminar (int id)
Implemented in BLL.IVABLL.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.toolStripBtnEliminar_Click().
Insertar()
void Interfaces.I_IVA_BLL.Insertar (IVA iva)
Implemented in BLL.IVABLL.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.btnAceptar_Click().
SeleccionarPorId()
IVA Interfaces.I_IVA_BLL.SeleccionarPorId (int id)
Implemented in BLL.IVABLL.
SeleccionarReciente()
IVA Interfaces.I_IVA_BLL.SeleccionarReciente ()
Implemented in BLL.IVABLL.
Referenced by BLL.CoberturaBLL.Insertar().
SeleccionarTodas()
List< IVA > Interfaces.I_IVA_BLL.SeleccionarTodas ()
Implemented in BLL.IVABLL.
Referenced by Capa.UI.Mantenimientos.frmMantenimientoIVA.CargarDatos().
The documentation for this interface was generated from the following file:
Interfaces/I_IVA_BLL.cs