Proyecto Autos Seguros: Interfaces.ICoberturaDAL Interface Reference
Interfaces.ICoberturaDAL Interface Reference
Public Member Functions
void Insertar (Cobertura cobertura)
void Actualizar (Cobertura cobertura)
void Eliminar (int id)
List< Cobertura > SeleccionarTodas ()
Cobertura SeleccionarPorId (int id)
List< Cobertura > CoberturasAgregadas (int idTipoPoliza)
Detailed Description
Definition at line 10 of file ICoberturaDAL.cs.
Member Function Documentation
Actualizar()
void Interfaces.ICoberturaDAL.Actualizar (Cobertura cobertura)
Implemented in DAL.CoberturaDAL.
Referenced by BLL.CoberturaBLL.Actualizar(), and BLL.CoberturaBLL.Insertar().
CoberturasAgregadas()
List< Cobertura > Interfaces.ICoberturaDAL.CoberturasAgregadas (int idTipoPoliza)
Implemented in DAL.CoberturaDAL.
Referenced by BLL.CoberturaBLL.CoberturasAgregadas().
Eliminar()
void Interfaces.ICoberturaDAL.Eliminar (int id)
Implemented in DAL.CoberturaDAL.
Referenced by BLL.CoberturaBLL.Eliminar().
Insertar()
void Interfaces.ICoberturaDAL.Insertar (Cobertura cobertura)
Implemented in DAL.CoberturaDAL.
Referenced by BLL.CoberturaBLL.Insertar().
SeleccionarPorId()
Cobertura Interfaces.ICoberturaDAL.SeleccionarPorId (int id)
Implemented in DAL.CoberturaDAL.
Referenced by BLL.CoberturaBLL.Insertar(), and BLL.CoberturaBLL.SeleccionarPorId().
SeleccionarTodas()
List< Cobertura > Interfaces.ICoberturaDAL.SeleccionarTodas ()
Implemented in DAL.CoberturaDAL.
Referenced by BLL.CoberturaBLL.SeleccionarTodas().
The documentation for this interface was generated from the following file:
Interfaces/ICoberturaDAL.cs