Proyecto Autos Seguros: Interfaces.IUsuarioDAL Interface Reference
Interfaces.IUsuarioDAL Interface Reference
Public Member Functions
void Insertar (Usuario user)
void Actualizar (Usuario user)
void Eliminar (string id)
List< Usuario > SeleccionarTodas ()
Usuario SeleccionarPorId (string id)
bool VerificarLogin (string correo, string clave)
List< Usuario > GetUsuarioByFiltro (string filtro)
string ObtenerUsuarioIdByIdFac (int idFactura)
Detailed Description
Definition at line 10 of file IUsuarioDAL.cs.
Member Function Documentation
Actualizar()
void Interfaces.IUsuarioDAL.Actualizar (Usuario user)
Implemented in DAL.UsuarioDAL.
Referenced by BLL.UsuarioBLL.Guardar().
Eliminar()
void Interfaces.IUsuarioDAL.Eliminar (string id)
Implemented in DAL.UsuarioDAL.
Referenced by BLL.UsuarioBLL.Eliminar().
GetUsuarioByFiltro()
List< Usuario > Interfaces.IUsuarioDAL.GetUsuarioByFiltro (string filtro)
Implemented in DAL.UsuarioDAL.
Referenced by BLL.UsuarioBLL.GetUsuarioByFiltro().
Insertar()
void Interfaces.IUsuarioDAL.Insertar (Usuario user)
Implemented in DAL.UsuarioDAL.
Referenced by BLL.UsuarioBLL.Guardar().
ObtenerUsuarioIdByIdFac()
string Interfaces.IUsuarioDAL.ObtenerUsuarioIdByIdFac (int idFactura)
Implemented in DAL.UsuarioDAL.
Referenced by BLL.UsuarioBLL.ObtenerUsuarioIdByIdFac().
SeleccionarPorId()
Usuario Interfaces.IUsuarioDAL.SeleccionarPorId (string id)
Implemented in DAL.UsuarioDAL.
Referenced by BLL.UsuarioBLL.Eliminar(), BLL.UsuarioBLL.GetUsuarioById(), BLL.UsuarioBLL.Guardar(), and DAL.FacturaDAL.SeleccionarPorId().
SeleccionarTodas()
List< Usuario > Interfaces.IUsuarioDAL.SeleccionarTodas ()
Implemented in DAL.UsuarioDAL.
Referenced by BLL.UsuarioBLL.ObtenerUsuarios().
VerificarLogin()
bool Interfaces.IUsuarioDAL.VerificarLogin (string correo, string clave)
Implemented in DAL.UsuarioDAL.
Referenced by BLL.UsuarioBLL.VerificarAcceso().
The documentation for this interface was generated from the following file:
Interfaces/IUsuarioDAL.cs