Proyecto Autos Seguros: Interfaces.IFacturaDAL Interface Reference
Interfaces.IFacturaDAL Interface Reference
Public Member Functions
void Insertar (Factura factura)
void Eliminar (int idFactura)
List< Factura > SeleccionarTodas ()
Factura SeleccionarPorId (int idFactura)
List< Factura > SeleccionarFacturaHoy ()
void AnularFactura (int idFactura)
List< Factura > SeleccionarFacturasAnuladas ()
Detailed Description
Definition at line 10 of file IFacturaDAL.cs.
Member Function Documentation
AnularFactura()
void Interfaces.IFacturaDAL.AnularFactura (int idFactura)
Implemented in DAL.FacturaDAL.
Referenced by BLL.FacturaBLL.AnularFactura().
Eliminar()
void Interfaces.IFacturaDAL.Eliminar (int idFactura)
Implemented in DAL.FacturaDAL.
Referenced by BLL.FacturaBLL.Eliminar().
Insertar()
void Interfaces.IFacturaDAL.Insertar (Factura factura)
Implemented in DAL.FacturaDAL.
Referenced by BLL.FacturaBLL.Insertar().
SeleccionarFacturaHoy()
List< Factura > Interfaces.IFacturaDAL.SeleccionarFacturaHoy ()
Implemented in DAL.FacturaDAL.
Referenced by BLL.FacturaBLL.SeleccionarFacturaHoy().
SeleccionarFacturasAnuladas()
List< Factura > Interfaces.IFacturaDAL.SeleccionarFacturasAnuladas ()
Implemented in DAL.FacturaDAL.
Referenced by BLL.FacturaBLL.SeleccionarFacturasAnuladas().
SeleccionarPorId()
Factura Interfaces.IFacturaDAL.SeleccionarPorId (int idFactura)
Implemented in DAL.FacturaDAL.
Referenced by BLL.FacturaBLL.SeleccionarPorId().
SeleccionarTodas()
List< Factura > Interfaces.IFacturaDAL.SeleccionarTodas ()
Implemented in DAL.FacturaDAL.
Referenced by BLL.FacturaBLL.SeleccionarTodas().
The documentation for this interface was generated from the following file:
Interfaces/IFacturaDAL.cs