Proyecto Autos Seguros: Interfaces.IDetallePolizaDAL Interface Reference
Interfaces.IDetallePolizaDAL Interface Reference
Public Member Functions
void Insertar (DetallePoliza detallePoliza)
void Actualizar (DetallePoliza detallePoliza)
void Eliminar (int idTipoPoliza)
void EliminarByPolCob (int idTipoPoliza, int idCobertura)
List< DetallePoliza > SeleccionarTodas ()
DetallePoliza SeleccionarPorId (int idTipoPoliza, int idCobertura)
Detailed Description
Definition at line 10 of file IDetallePolizaDAL.cs.
Member Function Documentation
Actualizar()
void Interfaces.IDetallePolizaDAL.Actualizar (DetallePoliza detallePoliza)
Implemented in DAL.DetallePolizaDAL.
Referenced by BLL.DetallePolizaBLL.Actualizar().
Eliminar()
void Interfaces.IDetallePolizaDAL.Eliminar (int idTipoPoliza)
Implemented in DAL.DetallePolizaDAL.
Referenced by BLL.DetallePolizaBLL.EliminarByIdTipoPoliza().
EliminarByPolCob()
void Interfaces.IDetallePolizaDAL.EliminarByPolCob (int idTipoPoliza, int idCobertura)
Implemented in DAL.DetallePolizaDAL.
Referenced by BLL.DetallePolizaBLL.EliminarByPolCob().
Insertar()
void Interfaces.IDetallePolizaDAL.Insertar (DetallePoliza detallePoliza)
Implemented in DAL.DetallePolizaDAL.
Referenced by BLL.DetallePolizaBLL.Insertar().
SeleccionarPorId()
DetallePoliza Interfaces.IDetallePolizaDAL.SeleccionarPorId (int idTipoPoliza, int idCobertura)
Implemented in DAL.DetallePolizaDAL.
Referenced by BLL.DetallePolizaBLL.SeleccionarPorId().
SeleccionarTodas()
List< DetallePoliza > Interfaces.IDetallePolizaDAL.SeleccionarTodas ()
Implemented in DAL.DetallePolizaDAL.
Referenced by BLL.DetallePolizaBLL.SeleccionarTodas().
The documentation for this interface was generated from the following file:
Interfaces/IDetallePolizaDAL.cs