Proyecto Autos Seguros: Interfaces.ITipoUsuarioDAL Interface Reference
Interfaces.ITipoUsuarioDAL Interface Reference
Public Member Functions
TipoUsuario ObtenerPorId (int id)
List< TipoUsuario > ObtenerTiposUsuarios ()
Detailed Description
Definition at line 10 of file ITipoUsuarioDAL.cs.
Member Function Documentation
ObtenerPorId()
TipoUsuario Interfaces.ITipoUsuarioDAL.ObtenerPorId (int id)
Implemented in DAL.TipoUsuarioDAL.
Referenced by DAL.UsuarioDAL.GetUsuarioByFiltro(), BLL.TipoUsuarioBLL.ObtenerPorId(), DAL.UsuarioDAL.SeleccionarPorId(), and DAL.UsuarioDAL.SeleccionarTodas().
ObtenerTiposUsuarios()
List< TipoUsuario > Interfaces.ITipoUsuarioDAL.ObtenerTiposUsuarios ()
Implemented in DAL.TipoUsuarioDAL.
Referenced by BLL.TipoUsuarioBLL.ObtenerTiposUsuarios().
The documentation for this interface was generated from the following file:
Interfaces/ITipoUsuarioDAL.cs